@DATABASE gedicht.inc
@NODE "gedicht"

Boba Fett
---------------------
By Beate Richter

Boba Fett war ein großer Held,
er jagte Köpfe für Geld.
Jabba, der sein Auftraggeber war,
war plötzlich nicht mehr da,
na gucke an.
Was macht man da?
Man jage fröhliche weiter,
nach der alten Leier.
Han Solo hat er auch gekriegt,
doch diesem ist die Flucht geglückt,
auf Nal Hutta war er plötzlich wieder da,
Boba seine Chance gekommen sa,
die andren in die Quere kam,
und Solo wieder entkam.
Und so jagt er weier
fröhlich nach der alten Leier.

  
  "The Boba Fett-Experience" is a fan-produced programm.  
  We do not want intend to infringe upon rights
  of any other copyright holder. All rights revert to the
  contributor upon publication.


@ENDNODE

