@DATABASE PGS.MAN
@(C) 1995 Soft-Logik Publishing Corporation
@INDEX PageStream3:Help/PGS.INA/MAIN



@remark *** MANUAL ERRATA ***

@node MAIN "Manual Errata"

@{FG Highlight}Manual Errata@{FG Text}

While we strive to make our manuals as error-free as possible, there are
always some errors and changes after a manual has gone to press.

@{FG Highlight}Page Explanation@{FG Text}
@{CODE}
 14: Para 1: PageStream format bitmap screen fonts are no longer used. The
     Compugraphic font engine is now faster and better so bitmap screen
     fonts are no longer required.
 16: Triumvirate Oblique and Bold Oblique will show up in the fontlist
when
     the Normal and Bold versions are installed.
 49: Step 7: You do not have to position the mouse pointer at the precise
     coordinates because drawing objects with the grid on will snap the
     start point to the closest grid point.
 51: Step 9: It is no longer true that 117% is the optimum view
magnification
     for 12pt body text. (That was true in v2.2, but not v3.0.) The higher
     the magnification, the more readable the text, but 12pt type is quite
     readable even at Actual Size in PageStream 3.0.
 58: Step 3: Note that the text will remain highlighted after importing.
     Click in the text to deselect it.
 68: The grid commands are in the View menu, not Layout.
 73: Last sentence: `anwhere' should be `anywhere'.
 94  Step 1: You must create a new document (the size is unimportant)
     before starting this lesson.
 94: Step 3: The text column frame will already be opaque, so you do not
     need to change this option.
 95: Your macro will record two additional `FILLED ON' lines not shown in
     the screenshots.
 97: Step 2. The point for selecting text can be the same as the text
     column frame's top left corner, so you do not need to add 0.25i to
each
     coordinate as explained in the text.
100: Same as page 97. Just type: 'selecttext at 'p2d(click.x) p2d(click.y)
120: The description for gadget A refers to gadget E; it should refer to
D.
162: The frameless text examples have an overset indicator which should
not
     be there.
171: The filter list omits ProWrite.tfilter which is used to import text
     from New Horizons' ProWrite.
219: The Illustrator filter will not ignore charts and graphs as stated in
     the list; they will be imported as drawings.
246: Para 1: Change `Edit tool' to `Object tool'.
262: The first Flash Macro sidebar is incorrect. Change `DuplicateTo-
     Page.rexx' to `RotateAboutPoint.rexx'. The last word of the sidebar,
     `PageStream', was cut off.
301: Canon: For some Canon printers, including the BJC-600, you must
choose
     the Epson driver. Choose Epson from the Type popup and see if your
     printer is listed before choosing Canon.
301: Primera: This driver can be used with or without the dye sublimation
     option. The driver name (as listed in the Type popup gadget) is
Fargo,
     not Primera. Choose Primera or Primera Pro from the Model popup. This
     driver has extra options specific to these printers.
303: Step 3: Change `page 105' to `page 305'.
383: Last para: PageLiner copies text to the clipboard in IFF FTXT format
     only, not IFF FTXT and IFF DTXT.
387: Show Invisibles para: Change `Settings/Options' to
`Settings/General'.
388: Path Preferences requester: The screenshot is wrong. There is just
     one path for dictionaries, instead of path and filenames for the
     individual dictionaries.
404: Conditional Break, Para 2: Choosing the Conditional Break command
will
     toggle conditional break, not automatic kerning.
419-421: All occurrences of Frame Lock. The first sentence of each
     description should be `When the frame lock option is on...'
482: The Save command does not open a file overwrite alert requester; only
     Save As does.
484: Para 1: Change `75x75 dpi' to `65x70 dpi' for PAL.
485: Set Grid: This command is in the View menu, not the Layout menu.
486: Set Guides: This command is in the View menu, not the Layout menu.
487: Note that outlines are only shown for text frames, not frameless text
     objects.
495: Style Palette, Para 1: Change `Macro palette' to `Style palette'.

@{FG Highlight}Appendix A: Special Characters@{FG Text}
00173: Macron          should be 00175
00222: thorn           should be Thorn
00254: Thorn           should be thorn
00254: y dieresis (ÿ)  should be 00255 (Two 00254 entries were listed.)
00255: z caron         should be 00382
00337: oe ligature     should be 00339
00352: S caron         Ctrl C code is SV
08224: dagger          Ctrl C code is |- (not l-)
08225: dagger double   Ctrl C code is |= (not l=)

@{FG Highlight}Appendix B: Text Codes@{FG Text}
522: Track amount is duplicated by Track. Ignore the second one.
522: Leading amount and type are combined: <lx,#>  Example: <lf,18pt>
523: Tab: should be <*t(#,a,"c")> Repeat the code in parentheses for
     multiple tabs.
523: Paragraph spacing amount and type are combined: <*sb,#,a,#> where `b'
     is the spacing type before, and `a' is the spacing type after (`n'
     for none, `r' for relative, or `f' for fixed). Example <*sn,0,f,3pt>
523: Paragraph type: has been changed from *t to *p so as not to conflict
     with tabs.
523: Window/Orphan: has been changed from *k to *w so as not to conflict
     with auto kerning.
524: Define character style tag: should be @Cname=[def]

@{FG Highlight}Appendix D: Keyboard Shortcuts@{FG Text}
527: The shortcuts for Send to Back and Send Backward are reversed.
@{BODY}
@toc PageStream3:Help/PGS.HEL/MAIN
@endnode

