@DATABASE Katalog.inc
@NODE "Katalog"


Science Fiction-Themes 
by the
Faces of Mars


1 ) FOM210
-Battlestar Galactica
-Blade Runner
-The Faces of Mars
-Star Wars
-Terminator

2 ) FOM241
-Ghostbusters
-Odyssey
-Star Wars
-Terminator II

3 ) FOM273
-Star Trek
-The Black Hole
-Robocop
-Rambo

4 ) FOM299
-Airwolf
-Bat Man
-Future World
-Spacepatrol Orion

5 ) FOM349
-Dune (3 modules)

6 ) FOM361
-Airwolf II
-Alf (2 modules)
-Blade Runner
-Super Mario Bros.

7 ) FOM392
-A Journey to Mars
-Star Trek
-Star Wars

8 ) FOM403
-Flashdance
-Max Headroom / Space Balls
-Spaceman
-Magnun
-Top Gun

9 ) FOM425
-Airwolf
-Bat Man
-Doctor Who

10) FOM474
-Max Headroom
-Star Trek
-Ghostbusters II
-Defender of the Crown
-Miami Vice

11)FOM491
-Forrest Gump
-Kuffs
-Predator 2
-dsv seaQuest
-Thunderbirds
-Tron


All disks are freeware.

@endnode

                




