@DATABASE Modul3.inc
@NODE Modul3

Die Blobrennen von Umgul
**************************************************
                         Copyright by Patrick Henz


Einleitung
==========
Auf dem Planeten Umgul finden die in der ganzen Galaxis 
bekannten Blobrennen statt. Bei diesen einmaligen Rennen hat 
der Spieler die Chance entweder reich oder arm zu werden. Um 
die Möglichkeiten vom Umgul ausnutzen zu können, muß man vorher 
mit einem Schiff einen Abgesandten zu diesem Planeten 
schicken. Jeder Spieler kann nur einen Abgesandten auf dem 
Planeten haben.


Der Abgesandte
==============
Vor dem Abflug nach Umgul muß noch der Abgesandte festgelegt 
werden, d.h., daß Name, Aussehen, Rasse, vielleicht noch 
Kleidung, Akzent, Charakter, etc. entworfen wird. Danach 
schickt man ihn mit einem Schiff nach Umgul.


Befehle
=======
Um die Möglichkeiten Umguls auszunutzen zu können muß sich 
mindestens ein Schiff des Spielers bei dem Planeten befinden! 
Dem Befehl sollte zur besseren Kenntnismachung des Masters 
"Umgul:" vorausgehen.


Wetten
------
Pro Lauf treten 10 Blobs auf einer Hindernisbahn gegeneinander 
an. Aus traditionellen Gründen gibt es auf Umgul nur die 
Möglichkeit auf den Sieger zu Wetten. Siegt der Blob dann, 
gewinnt man das zehnfache seines Einsatzes.

Befehl: "Umgul: Setzte 30CR auf Blob5."


Doping
------
In der Nacht vor dem Rennen kann man sich in die Ställe der 
Rennblobs schleichen und sie mit einer Dopingsubstanz 
spritzen, dadurch steigt ihre Chance, beim Rennen ganz vorne 
zu sein. Aber Achtung: Auf Doping steht die Todesstrafe auf 
Umgul! Wird ein Abgesandter dabei erwischt, wird er exekutiert 
und das Schiff wird einbehalten.

Befehl:"Umgul:Dope Blob2."


Blobüberwachung
---------------
Hat man den Verdacht, daß bei den Rennen nicht alles mit 
rechten Mitteln zugeht, kann man auch die Ställe überwachen. 
Man sieht hier dann, ob andere Spieler zum Doping greifen 
oder nicht. Man kann in einer Runder entweder nur überwachen 
oder nur dopen!

Befehl:"Umgul: Überwache Blobs."


Abgesandten anzeigen
--------------------
Hat man die leidige Konkurenz beim Doping erwischt besteht 
die Möglichkeit, diese dann anzuzeigen. 

Befehl:"Umgul:Zeige Vigan wg. Doping an."


Gebühren
--------
Der Raumhafen verlangt 10CR Landegebühren, danach werden pro 
Runde 2CR Liegegebühren fällig.


Zugbeispiel:

Umgul: -Dope Blob 3.
       -Setze 45CR auf Blob 3.
       
Zugauswertungsbeispiel:
       
Blob 3 hat das Rennen gewonnen. Dir werden 450CR gutgeschrieben.


Diese Befehle sollten für die Rennen reichen, falls Du aber 
noch anderes probieren willst, kannst Du dies ja so an den 
Spielleiter schreiben.

Anmerkung:Dieses Zusatzmodul geht auf das Buch "Flucht ins 
Ungewisse" von Kevin J.Anderson zurück. Da jeder Star Wars-Fan 
dieses Buch gelesen haben sollte, wird an dieser Stelle die 
ganzen Hintergründe und Beschreibungen der Blobs weggelassen.

  




The Faces of Mars
*****************
"Star Wars - your own Chapter" is a fan-produced game.
"The Faces of Mars"  do not want intend to infringe 
upon rights of any other copyright holder. All 
rights revert to the contributor upon publication.


FOM-Adresse:          Patrick Henz
                      Martinstr.15
                      52062 Aachen
                      Germany


@ENDNODE

