@DATABASE missions.inc
@NODE "missions"


                           Mission Log by Lord Kur:

                           ~~~~~~~~~~~~~~~~~~~~~~~~

                          -=ð Star Trek: Voyager ð=-



  "Star Trek: Voyager" created by Rick Berman & Michael Piller & Jeri Taylor

              based upon "Star Trek" created by Gene Roddenberry





                               Season One: 1995



01/02  "Caretaker"                                                     16/01/95



       Story by: Rick Berman & Michael Piller & Jeri Taylor

       Teleplay by: Michael Piller & Jeri Taylor

       Directed by: Winrich Kolbe

   The excitement and adventure begin when the Starship U.S.S. Voyager is

   dispatched in search of a Maquis ship which has disappeared in an unusual

   region of space known as the "Badlands." The Voyager finds the Maquis ship

   but not before being swept up in a strange and terrifying phenomenon which

   sends Voyager into the far reaches of the galaxy -- so far away that, even

   at warp speeds, it would take nearly seventy years to return. Two diverse

   crews must band together to explore this distant part of space and to find

   a way home.

 Season One Regular Cast2àKate Mulgrew (Captain Kathryn Janeway), Robert

   Beltran (Chakotay), Roxann Biggs-Dawson (B'Elanna Torres), Jennifer Lien

   (Kes), Robert Duncan McNeill (Lt. Tom Paris), Robert Picardo (the Doctor),

   Ethan Phillips (Neelix), Tim Russ (Tuvok), Garrett Wang (Harry Kim)



03     "Parallax"                                                      23/01/95



       Story by: Jim Trombetta

       Teleplay by: Brannon Braga

       Directed by: Kim Friedman

   The Starship Voyager encounters a quantum singularity and what appears to be

   another ship in jeopardy. In their attempt to rescue the vessel, the crew

   comes to realize that it is they who are trapped, and the race begins to

   free themselves before the ship is destroyed.

 Guest Stars: Josh Clark (Carey), Martha Hackett (Seska), Justin Williams

   (Jarvin)



04     "Time and Again"                                                30/01/95



       Story by: David Kemper

       Teleplay by: Michael Piller and David Kemper

       Directed by: Les Landau

   The Starship Voyager experiences a shock wave in space, a wave set off by a

   huge explosion on a nearby planet. When they beam down to investigate, the

   away team discovers all life has been eradicated. In addition, they discover

   subspace fractures which ultimately transport Captain Janeway and Lt. Paris

   back in time to right before the explosion. They must discover a way to

   avert the catastrophe to save their lives.

 Guest Stars: Brady Bluhm (Latika), Ryan McDonald (Shopkeeper), Joel Polis

   (Terla), Jerry Spicer (Guard), Nicholas Surovy (Makull), Steve Vaught

   (Officer)



05     "Phage"                                                         06/02/95



       Story by: Tim DeHaas

       Teleplay by: Skye Dent and Brannon Braga

       Directed by: Rick Kolbe

   In their continuing search for a source of dilithium crystals that could be

   used to supplement the Voyager's power core, the crew of the Starship come

   upon a planet that seems replete with the substance. Upon closer

   examination, they find that the place is really a base for a strange alien

   culture that must steal bodily organs to fight the "phage," a disease that

   eats away at their bodies and destroys their organs. Neelix falls prey to

   them, and the race is on to save his life.

 Guest Stars: Martha Hackett (Seska), Cully Fredericksen (Alien #1), Stephen

   Rappaport (Alien #2)

 Encounters in this episode: Vidiians



06     "The Cloud"                                                     13/02/95



       Story by: Brannon Braga

       Written by: Michael Piller

       Directed by: David Livingston

   While investigating what they believe to be a nebula in search of fuel, the

   crew of Voyager discovers that they have in fact entered and injured a new

   life form, which they must help heal as they try to escape.

 Guest Stars: Larry Hankin (Gaunt Gary), Angela Dohrmann (Ricky), Judy Geeson

   (Sandrine), Luigi Amodeo (The Gigolo)



07     "Eye of the Needle"                                             20/02/95



       Story by: Hilary Bader

       Teleplay by: Jeri Taylor

       Directed by: Rick Kolbe

   The Voyager crew becomes hopeful when they encounter a small wormhole 

   through which they communicate with a cargo vessel on the other side... 

   in the Alpha Quadrant.

 Guest Stars: Michael Cumpsty (Lord Burleigh), Carolyn Seymour (Mrs.

   Templeton), Vaughn Armstrong (Telek), Tom Virtue (Baxter)

 Encounters in this episode: Romulans



08     "Ex Post Facto"                                                 27/02/95



       Story by: Evan Carlos Somers

       Teleplay by: Evan Carlos Somers & Michael Piller

       Directed by: LeVar Burton

   Upon visiting a world in the midst of a war with a neighboring planet, 

   Lt. Tom Paris finds himself accused of a murder 

   he didn't commit... his sentence -- to relive the crime from the victim's 

   point-of-view every 14 hours for the rest of his life. It is up to Tuvok 

   to prove his innocence by using the Vulcan Mind-Meld before his 

   sentence destroys his sanity.

 Guest Stars: Robin McKee (Lidell), Francis Guinan (Minister Kray), Aaron

   Lustig (Doctor), Ray Reinhardt (Tolen Ren), Henry Brown (Numiri Captain)

 Encounters in this episode: Baneans, Numiri



00à    "Emanations"                                                    13/03/95



       Teleplay by: Brannon Braga

       Directed by: David Livingston

   While exploring an uncharted planet, the crew stumbles on the burial ground

   of the alien race Vhnori. During an investigation of the bodies, Harry Kim

   is caught up in a subspace vacuole and is transported to the alien culture's

   homeworld. His presence there causes many to doubt their traditional belief

   in the afterlife, and Kim soon realizes that the only way he can return home

   is the same way he came... through the Vhnori's death stations. Kim places

   his life in the hands of fate, trusting that the crew of the Voyager will be

   able to revive him upon his return.

 Guest Stars: Jefrey Alan Chandler (Hatil), Jerry Hardin (Dr. Neria), John

   Cirigliano (Alien #1), Martha Hackett (Seska), Robin Groves (Hatil's Wife),

   Cecile Callan (Ptera)

 Encounters in this episode: Vhnori



10     "Prime Factors"                                                 20/03/95



       Story by: David R. George III & Eric Stillwell & Michael Perricone &

                 Greg Elliot

       Teleplay by: Michael Perricone & Greg Elliot & Jeri Taylor

       Directed by: Les Landau

   The crew of Voyager encounters alien beings known as the Sikarians - a race 

   renowned for their incredible hospitality. When it becomes known that the 

   Sikarians have the technology to "fold" space and travel more than 40,000 

   light years in an instant, the Voyager crew think they've found their way

   home. But the hospitality of the Sikarians is not all it seems on the

   surface, and both races' code of ethics is put to the test.

 Guest Stars: Martha Hackett (Seska), Josh Clark (Carey), Andrew Hill Newman

   (Jaret), Ronald Guttman (Gath), Yvonne Suhor (Eudana)

 Encounters in this episode: Sikarians



11     "State of Flux"                                                 10/04/95



       Story by: Paul Coyle

       Teleplay by: Chris Abbott

       Directed by: Robert Scheerer

    While on a routine exploration of a new planet, Voyager responds to the

    distress call of a Kazon warship. Upon investigation, they find the Kazon

    ship hobbled by an accident caused by Federation technology... a clear

    signal that Voyager may be carrying a traitor.

 Guest Stars: Martha Hackett (Seska), Josh Clark (Carey)



12     "Heroes and Demons"                                             24/04/95



       Written by: Naren Sankar

       Directed by: Les Landau

   The ship's holographic Doctor must overcome his computer-programmed

   limitations when the ship's Holodeck is taken over by an alien lifeform that

   transforms living crew members into pure energy. As the only Voyager crew

   member able to face this alien being, the Doctor must explore the limits of

   his programmed behavior and reach beyond them to save the crew from a fate

   worse than death.

 Guest Stars: Marjorie Monaghan (Freya), Christopher Neame (Unferth), Michael

   Keenan (Hrothgar)



13     "Cathexis"                                                      01/05/95



       Story by: Brannon Braga & Joe Menoksy

       Teleplay by: Brannon Braga

       Directed by: Kim Friedman

   Both Tuvok and Chakotay return from a routine expedition injured -- Tuvok

   with minor ailments and Chakotay greviously injured. During an encounter

   with a black nebula, Chakotay's neural energy was depleted; unless it is

   returned, Chakotay will be doomed to a life as a brain-dead host. While

   trying to return to the nebula, the crew of Voyager discovers that an alien

   presence is aboard and able to control their efforts.

 Guest Stars: Brian Markinson (Durst), Michael Dumpsty (Lord Burleigh), Carolyn

   Seymour (Mrs. Templeton)

 Encounters in this episode: Konar



14     "Faces"                                                         08/05/95



       Story by: Jonathan Glassner & Adam Grossman

       Teleplay by: Kenneth Biller

       Directed by: Rick Kolbe

   B'Elanna Torres and Lt. Tom Paris are abducted by the alien race who suffer

   from the Phage. During an experiment, B'Elanna is literally split into two

   separate beings -- one fully Klingon, the other fully human -- by Sulan, a

   Vidiian Soldality scientist in search of a cure for the deadly disease. Her

   two selves must learn to work together in order to escape the alien

   laboratory and rescue Lt. Paris.

 Guest Stars: Brian Markinson (both Sulan and Durst), Rob LaBelle (a Talaxian

   prisoner), Barton Tinapp (Guard #1)



15     "Jetrel"                                                        15/05/95



       Story by: Scott Nimerfro & Jim Thornton

       Teleplay by: Jack Klein & Karen Klein and Kenneth Biller

       Directed by: Kim Friedman

   Neelix is confronted by Haakonian scientist Ma'bor Jetrel, the man

   responsible for creating the Metreon Cascade, a device that was used to

   annihilate a major portion of the Talaxian race, including Neelix' own

   family. Jetrel is allowed to board Voyager when he asserts that Neelix will

   soon fall ill from long-term effects of the Metreon Cascade device. Tempers

   flare between the two, with Neelix instantly distrusting the man who

   murdered his loved ones. Ultimately, Neelix must discover Jetrel's true

   motive for being on board Voyager before it is too late.

 Guest Stars: James Sloyan (Ma'bor Jetrel), Larry Hankin (Gaunt Gary)

 Encounters in this episode: Haakonians



16     "Learning Curve"                                                22/05/95



       Written by: Ronald Wilkerson & Jean Louise Matthias & Jeri Taylor

       Directed by: David Livingston

   When several former Maquis crew members break Federation rules, it is up to

   Tuvok to train them in the finer points of Starfleet protocol and discipline

   in order to reestablish harmony among Voyager's crew. Simultaneously, a

   strange virus invades the ship's bio-neural circuitry, endangering the lives

   of all aboard. As B'Elanna Torres and the Doctor try to discover a cure,

   Tuvok and his unlikely "cadets" become trapped in an unstable part of the

   ship. As one of them lies near death, Starfleet tenets are put to the test.

 Guest Stars: Armand Shultz (Dalby), Derek McGrath (Chell), Kenny Morrison

   (Geron), Catherine MacNeal (Henley), Thomas Alexander Dekker (Henry),

   Lindsey Haun (Beatrice)



17     "Projections"                                                   11/09/95



       Story written by: Brannon Braga

       Directed by: Jonathan Frakes

   The Doctor receives information that Voyager has suffered a massive Kazon

   attack and that most of the crew has abandoned ship, so he ventures from

   Sickbay, via remote holo-projection system, to aid those still on board.

 Guest Stars: Dwight Schultz (Lieutenant Barclay)



18     "Elogium"                                                       18/09/95



       Story written by: Jimmy Diggs & Steve J. Kay

       Teleplay by: Kenneth Biller and Jeri Taylor

       Directed by: Rick Kolbe

   Aggresive space-dwelling lifeforms attach themselves to the Starship,

   creating an electrophoretic field. The occurence increases Kes' metabolic

   activity and accelerates her reproductive process, causing her to

   prematurely enter the elogium - the time of life when Ocampa bodies become

   fertile. However, the elogium occurs only once, so if Kes is ever going to

   have a child, it must be immediately. 

 Guest Stars: Nancy Hower (Ensign Clarke), Gary O'Brien and Terry Correll (Crew

   Members)



19     "Twisted"                                                       02/10/95



       Story by: Arnold Rudnick & Rich Hosek

       Teleplay by: Kenneth Biller

       Directed by: Kim Friedman

   A spatial distortion phenomenon occurs not only in space but inside the ship

   as well, changing Voyager's structural layout and completely disabling it.

   As Voyager is compressed and twisted by this unknown anomaly, the crew must

   work frantically to stop it.

 Guest Stars: Judy Geeson (Sandrine), Larry Hankin (Gaunt Gary), Tom Virtue

   (Baxter), Terry Correll (the crewmen)





                             Season Two: 1995-1996



20     "The 37's"                                                      28/08/95



       Story Written by: Jeri Taylor & Brannon Braga

       Directed by: Jim Conway

   After atmospheric disturbances force the crew to land the Starship Voyager

   on a mysterious planet, Captain Janeway leads an away team in search of the

   source of the centuries-old distress signal detected by the ship's sensors.

   They discover the source of the SOS to be an old Earth aircraft. Upon

   further investigation, the team finds a massive chamber containing eight

   earthlings in cryogenic units, one of which is Amelia Earhart (Sharon

   Lawrence). After releasing them from suspended animation, the U.S.S. Voyager

   crew comes under attack when a group of the planet's inhabitants mistakes

   them for members of the Briori -- an alien race which abducted more than 300

   people from Earth in 1937 and brought them this planet as slaves. It's

   learned that over time, the slaves revolted and killed the aliens. The eight

   surviving "37's" became part of the planet's history and the cryogenic

   chamber was their shrine. Since then, the descendants of the original 300

   cultivated the planet and created a home much like Earth.

   The crew of the U.S.S. Voyager is invited to stay, and Janeway must face her

   greatest challenge as she allows each crewmember the personal choice to stay

   behind and begin a life among these kindred Humans.

 Season Two Regular Cast: Kate Mulgrew (Captain Kathryn Janeway), Robert

   Beltran (Chakotay), Roxann Biggs-Dawson (B'Elanna Torres), Jennifer Lien

   (Kes), Robert Duncan McNeill (Lt. Tom Paris), Robert Picardo (the Doctor),

   Ethan Phillips (Neelix), Tim Russ (Tuvok), Garrett Wang (Harry Kim)

 Guest Stars: Sharon Lawrence (Amelia Earhart), David Graf (Noonan), James

   Saito (The Japanese Soldier), Mel Winkler (Jack Hayes), John Rubenstein

   (John Evansville)



21     "Initiations"                                                   04/00ï95



       Story written by: Kenneth Biller

       Directed by: Rick Kolbe

   When First Officer Chakotay borrows a Shuttlecraft to perform the Pakra,

   a solitary Indian ritual commemorating his father's death, he inadvertently 

   drifts into Kazon-Ogla territory and becomes the target of a Kazon youth 

   attempting to earn his Ogla warrior name by killing the Federation enemy.

 Guest Stars: Aron Eisenberg (Kar), Patrick Killpatrick (Razik), Tim de Zarn

   (Haliz)



22     "Non Sequitur"                                                  25/09/95



       Written by: Brannon Braga

       Directed by: David Livingston

   Ensign Harry Kim is confused when he awakens to find himself on Earth -- in

   24th century San Francisco -- working as a design specialist at Starfleet

   Engineering and engaged to be married to Libby. Accessing Starfleet service

   records, he mysteriously finds that he was never assigned to the U.S.S.

   Voyager.

 Guest Stars: Louis Gimbalvo (Cosimo), Jennifer Gatti (Libby), Jack Shearer

   (Admiral Strickler), Mark Kiely (Lieutenant Lasca)



23     "Parturition"                                                   09/10/95



       Written by: Tom Szollosi

       Directed by: Jonathan Frakes

   When Kes spends free time with a smitten Tom Paris, Neelix is overcome with

   jealousy and instigates a messy fight with the Lieutenant. In the aftermath,

   the Captain sends the sparring pair on a shuttlecraft mission to an M-Class

   planet, to replenish food supplies. When their craft experiences an

   interference pattern, they crash on the planet's surface.



24     "Persistence of Vision"                                         30/10/95



       Written by: Jeri Taylor

       Directed by: James L. Conway

   As they ready for a first encounter with the Bothan alien species, a strange

   psionic field causes the U.S.S. Voyager crew to succumb to a delusional

   state and their most deeply buried thoughts surface. During this ordeal, the

   characters in Janeway's holonovel program become real, and her beloved Mark

   appears; Paris faces off with his disparaging father, the Admiral; Kim is

   finally reunited with his girlfriend, Libby; Tuvok talks to his Vulcan wife,

   T'Pel; and Torres is seduced by Chakotay. The ship is effectively disabled

   and it's up to an unaffected Kes and The Doctor to block the mysterious

   field.

 Guest Stars: Michael Cumpsty (Lord Burleigh), Carolyn Seymour (Mrs.

   Templeton), Stan Ivar (Mark), Warren Munson (Admiral Paris), Lindsey Haun

   (Beatrice), Thomas Alexander Dekker (Henry), Patrick Kerr (the Bothan),

   Marva Hicks (T'Pel)



25     "Tattoo"                                                        06/11/95



       Story by: Larry Brody

       Teleplay by: Michael Piller

       Directed by: Alexander Singer

   While Chakotay leads an Away Team to drill for minerals on a moon's surface,

   they accidentally disturb a village and encounter its defensive inhabitants

   -- a group with Indian origins.  A regreatful Chakotay then experiences

   flashbacks of himself as a defiant 15-year-old who disappoints his father be

   not embracing the traditions of his tribe.

 Guest Stars: Henry Darrow (Kolopak), Richard Fancy (an alien), Douglas Spain

   (Young Chakotay), Nancy Hower (Ensign Wildman), Richard Chaves (the Chief)



26     "Cold Fire"                                                     13/11/95



       Story by: Anthony Williams

       Teleplay by: Brannon Braga

       Directed by: Cliff Bole

   The crew is hailed by Ocampa colonists on an alien space station who, at

   long last, lead them to the female mate of The Caretaker, a mysterious being

   who may have the ability to send them home. As Tuvok tutors Kes in honing

   her rapidly maturing mental abilities, it's concluded that her burgeoning

   powers have been extremely underestimated.

 Guest Stars: Gary Graham (Tanis), Lindsay Ridgeway (the girl), Norman Large

   (an Ocampa man)



27     "Maneuvers"                                                     20/11/95



       Written by: Kenneth Biller

       Directed by: David Livingston

   Kazon intruders board the U.S.S. Voyager and steal a Transporter control

   module. That collateral enables their leader, Culluh, to persuade rival

   sects to join together to conquer the Federation ship. Surprisingly, the

   mastermind behind the Kazon's scheme is an advisor with Cardassian, Maquis,

   and Starfleet tactical experience -- none other than Seska, the despised

   traitor and former intimate of Chakotay.

 Guest Stars: Martha Hackett (Seska), Anthony DeLongis (Culluh), Terry Lester

   (Haron), John Gegenhuber (Kelat)



28     "Resistance"                                                    27/11/95



       Story by: Kevin Ryan & Michael J. Friedman

       Teleplay by: Lisa Klink

       Directed by: Rick Kolbe

   In search of precious tellerium needed to power the ship, Janeway, Tuvok,

   Torres and Neelix transport to an Alsaurian city occupied by the hostile

   Mokra. Tipped off to the U.S.S. Voyager crew's presence, Mokra soldiers

   capture Tuvok and Torres. During the commotion, Janeway is secreted away by

   Caylem, a local eccentric who believes she is his long lost daughter.

 Special Guest Star: Joel Grey (Caylem)

 Guest Stars: Alan Scarfe (Augris), Tom Todoroff (Darod), Glenn Morshower

   (guard #1), John Gegenhuber (Kelat)



29     "Prototype"                                                     15/01/96



       Written by: Nick Correa & Kenneth Biller

       Directed by: Jonathan Frakes

   When the crew finds a deactivated humanoid robot with an unfamiliar power

   source floating in space, Chief Engineer B'Elanna Torres is able to repair

   this mysterious mechanical "man." When it comes to "life," the sentient

   artificial lifeform, Automated Unit 3947, explains that its kind is near

   extinction and asks Torres to build a prototype for the construction of more

   units. In accordance with the Prime Directive, Torres must decline the

   request, but when 3947's Pralor homeship is located, the robot abducts her

   and threatens to destroy Voyager unless she constructs the prototype.

 Guest Stars: Rick Worthy (3947), Hugh Hodgin (6263)



30     "Death Wish"                                                    19/02/96



       Story by: Shawn Piller

       Teleplay by: Michael Piller

       Directed by: James L. Conway

   A rebel Q (Gerrit Graham) escapes imprisonment from inside a comet and

   demands asylum aboard the U.S.S. Voyager. Just as quickly, the well-known

   Q (John de Lancie), arrives to force the escaped Q back to the Continuum.

   Noting the dictates of Starfleet protocol, Captain Janeway holds a hearing

   to consider the request for asylum. A courtroom drama ensues when Q (de

   Lancie) calls himself to the witness stand along with a varied group of

   people, including Commander William T. Riker, to defend the Q Continuum

   against the ever-logical Tuvok. 

 Special Guest Appearance: Jonathan Frakes (Commander William T. Riker)

 Guest Stars: John de Lancie (Q), Gerrit Graham (Q2), Peter Dennis (Isaac

   Newton), Maury Ginsberg (Maury Ginsberg)



31     "Alliances"                                                     22/01/96



       Teleplay by: Jeri Taylor

       Directed by: Les Landau

   After Voyager is severely attacked by Kazon and one of its crewmen killed,

   Chakotay appeals to Janeway to start thinking more like the Maquis. Janeway

   knows she must strengthen Voyager's position in the quadrant and, although

   it's a difficult decision and is against her beliefs and training, she

   agrees to take steps toward a strategic alliance with leaders of several

   Kazon factions. When they come together for a conference, it's eminently

   clear that there are no rules in this region of space.

 Guest Stars: Charles Lucia (Mabus), Anthony De Longis (Culluh), Martha Hackett

   (Seska), Raphael Sbarge (Michael Jonas), Larry Cedar (Tersa), John

   Gegenhuber (Kelat), Simon Billig (Hogan), Mirron E. Willis (Rettik)



32     "Threshold"                                                     29/01/96



       Story by: Michael DeLuca

       Teleplay by: Brannon Braga

       Directed by: Alex Singer

   Lieutenant Paris makes history by becoming the first person to make a

   transwarp flight. But, soon after his shuttle returns from Warp Ten, he

   undergoes startling biochemistry changes. His cell membranes begin to

   degrade and, despite the Doctor's best efforts, Paris dies. Hours after the

   pronouncement of death, Paris is discovered breathing, his body going

   through accelerated mutations which leave him radically transformed into a

   bizarre and terrifying cross between a human and amphibian.

 Guest Stars: Raphael Sbarge (Michael Jonas), Mirron E. Willias (Rettik)



33     "Meld"                                                          05/02/96



       Story by: Michael Sussman

       Teleplay by: Michael Piller

       Directed by: Cliff Bole

   When a crew member is murdered, Tuvok's investigation leads to another

   crewman, Ensign Suder, who finally admits he is the perpetrator. Vulcan

   instincts prohibit Tuvok from determining a logical motive for committing

   such a crime, so he attempts to understand the violent impulses of a

   criminal by performing a mind-meld on Suder -- with deadly results.

 Special Guest Star: Brad Dourif (Suder)

 Guest Stars: Angela Dohrman (Ricky), Simon Billig (Hogan)



34     "Dreadnought"                                                   12/02/96



       Story by: Gary Holland

       Teleplay by: Gary Holland & Lisa Klink

       Directed by: LeVar Burton

   The U.S.S. Voyager crew spots a Cardassian designed, self-guided missile

   carrying a warhead capable of significant destructive force. As it travels

   towards Rakosan, a heavily populated planet, Torres reports that she is

   partly responsible for its virtually unstoppable status. When she was a

   Maquis, she intercepted the missile and changed its program to assult its

   own makers, but it later went astray and now she is the only hope in

   stopping it. So Torres volunteers to transport to the missile's interior and

   reprogram it again. But, before she can detonate the warhead, the onboard

   computer tries to destroy her.

 Guest Stars: Raphael Sbarge (Jonas), Nancy Hower (Ensign Wildman), Michael

   Spound (Lorrum), Dan Kern (Kellan)



35     "Investigations"                                                11/03/96



       Story by: Jeff Schnaufer & Ed Bond

       Teleplay by: Jeri Taylor

       Directed by: Les Landau

   Neelix, a suddenly self-proclaimed journalist, hears a rumor that a fellow

   crew member has expressed displeasure with Starfleet and requested leave.

   Soon, Tom Paris is relieved of duty to become a pilot with a Talaxian convoy

   -- leaving a saddened Voyager crew behind. Almost immediately, the

   Kazon-Nistim and the scheming Seska attack the Talaxian fleet, kidnap Paris

   and attempt to coerce classified information from him. Meanwhile, Neelix

   suspects someone aboard Voyager has been secretly communicating with the

   Kazon and his sleuthing leads him directly to Paris.

 Guest Stars: Raphael Sbarge (Michael Jonas), Jerry Sroka (Laxeth), Simon

   Billig (Hogan)



36     "Lifesigns"                                                     26/02/96



       Written by: Kenneth Biller

       Directed by: Cliff Bole

   The U.S.S. Voyager detects a distress call from a weakened lifeform aboard a

   small spacecraft and quickly beams a deathly ill Viidian female to Sickbay.

   The Doctor starts treating her for advanced stages of the Phage by

   transferring her decaying body into stasis and creating a temporary, healthy

   holographic program of her being. As he becomes acquainted with the alien, a

   hematologist named Danara Pel, the Doctor's adaptive programming allows him

   to experience romantic feelings.

 Guest Stars: Susan Diol (Dr. Danara Pel), Raphael Sbarge (Michael Jonas),

   Martha Hackett (Seska), Michael Spound (Lorum), Rick Gianasi (the Gigolo)



37     "Deadlock"                                                      18/03/96



       Story and Teleplay by: Brannon Braga

       Directed by: David Livingston

   When the U.S.S. Voyager enters plasma cloud, while being pursued by Vidiian

   vessels, a series of astounding consequences occur. Before the ship is able

   to clear the cloud, the engines stall, anti-matter supplies begin to drain,

   and Proton bursts causing significant casualties and a hull breach. Without

   warning, Ensign Kim and Kes disappear into a mysterious void in space and

   Captain Janeway discovers a duplicate U.S.S. Voyager and crew in a parallel

   universe. While the U.S.S. Voyager crew contends with the most significant

   disaster to befall on the vessel, Captain Janeway discovers that a

   divergence field has caused all sensor readings to double and every particle

   on the ship to duplicate but there is still not enough anti-matter to

   sustain both vessels. When the Vidiians begin to close in, the two Janeways

   meet to determine a solution, knowing that only one of the two ships can

   survive.

 Guest Stars: Nancy Hower (Wildman), Simon Billig (Hogan), Bob Clendenin

   (Vidiian Surgeon), Ray Proscia (Vidiian Commander), Keythe Farley

   (Vidiian), Christopher Johnston (Vidiian)



38     "Innocence"                                                     08/04/96



       Story by: Anthony Williams

       Teleplay by: Lisa Klink

       Directed by: James Conway

   Tuvok and Bennet's shuttle crash lands on a sacred haven for the Drayan, an

   alien race which has shunned outside contact for decades. While Bennet lies

   dying from his injuries, three frightened Drayan children venture out from

   hiding. The young ones tell Tuvok that they have been abandoned by their

   people to die on the planet, and beg his help in saving them from the

   imminent arrival of the "morrok" -- the messenger of death.

 Guest Stars: Marnie McPhail (Alicia), Tiffany Taubman (Tressa), Sarah Rayne

   (Elani), Tahj D. Mowry (Corin), Richard Garon (Bennet)



39     "The Thaw"                                                      29/04/96



       Story by: Richard Gadas and Michael Piller

       Teleplay by: Joe Menosky

       Directed by: Marvin Rush

   The U.S.S. Voyager activates an automated message from members of the Kohl

   settlement who, years earlier, survived an environmental catastrophe by

   submitting themselves into artificial hibernation. When the crew transports

   the Kohl's hibernation pods on board, they find humanoids in deep stasis

   with suppressed metabolic activity -- but with active minds and complex

   sensory systems controlled by a computer -- and that is where the nightmare

   begins.  

 Special Guest Star: Michael McKean (the Clown)

 Guest Stars: Thomas Kopache (Viorsa), Carel Struycken (Spectre), Patty Maloney

   (the Little Woman), Tony Carlin (the Physician), Shannon O'Hurley (the

   Programmer)



40     "Symbiogenesis"                                                 06/05/96



       Story by: Andrew Price and Mark Gaberman

       Teleplay by: Kenneth Biller

       Directed by: Cliff Bole

   A bizarre occurrence causes Neelix and Tuvok, who are attempting to

   transport back to the U.S.S. Voyager from an away mission, to arrive aboard

   ship as one. The crew is astonished when a strange but oddly familiar alien

   humanoid with dark speckled skin and pointy ears -- which is neither Tuvok

   nor Neelix -- appears. The Doctor's bio-scanner shows that Neelix and

   Tuvok's patterns have merged, causing the pair to become one entity -- Tuvix

   -- a humor-filled, logic defying fusion of the two crewmen. 

 Guest Stars: Tom Wright (Tuvix), Simon Billig (Hogan), Bahni Turpin (Swinn)



41     "Resolutions"                                                   13/05/96



       Written by: Jeff Taylor

       Directed by: Alex Singer

   When Janeway and Chakotay contract a deadly virus from an insect bite, the

   Doctor cannot find a cure. Unable to perform her duties, Janeway is forced

   to turn over permanent command of the ship to Tuvok and retreat, with

   Chakotay, to a small planet which shields the effects of the fatal disease.

 Guest Stars: Susan Diol (Dr. Denara Pel), Simon Billig (Hogan), Bahni Turpin

   (Powell)



42     "Basics, Part I"                                                13/05/96



       Written by: Michael Piller

       Directed by: Rick Kolbe

   In an emergency message to Chakotay, Seska discloses that their newborn son

   has been banished by Culluh to a servant colony. Chakotay feels conflicted

   about rescuing the baby because he was manipulated into fatherhood by Seska.

   When the crew detects a distress signal from a Kazon shuttle, they transport

   aboard the critically injured Teirna, a former aide to Seska, who delivers

   the news that Culluh has killed Seska. So, with Teirna restricted to secured

   quarters, the U.S.S. Voyager heads on a rescue mission through Kazon-Nistrim

   territory where Kazon raiders viciously attack the ship. Before long, the

   fierce battle is over and the Voyager crew has lost -- outwitted by their

   most bitter foe. Surrounded and defenseless, Captain Janeway must give up

   the ship to the Kazon.

 Special Guest Star: Brad Dourif (Suder)

 Guest Stars: Anthony De Longis (Culluh), John Gegunhuber (Teirna), Martha

  Hackett (Seska), Henry Darrow (Kolopak)



~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~

"Star Trek" and "Star Trek: Voyager" are registered trademarks of Paramount

Pictures registered in the United States Patent and Trademark Office.

ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

Mission Log written by Lord Kur                          Last updated2à06/06/96

@ENDNODE

