@DATABASE Aussehen.inc
@NODE Aussehen

Autor:Solo

@{"Das Aussehen von Außerirdischen" SYSTEM "view pics/alien4"}
Viele Berichte von Außerirdischen beschreiben diese als
humanoid. Diverse Kritiker stoßen sich daran. Es gibt aber auch
Theorien, warum UFOnauten so aussehen könnten oder es auch tuen.

1)Der Mensch ist eine Züchtung der Außerirdischen
   Mit Hilfe hochstehender Genforschung wurden die Menschen
   gezeugt und auf der Erde ausgesetzt. Aus Forschungsgründen
   werden wir immernoch von unseren Vätern überwacht.

2)Gleiche Bedingungen, gleiche Evolution
   Anhand der Evolution auf dem abgeschirmten Australien und den
   anderen Kontinenten konnte man erkennen, daß bei gleichen
   Lebensräumen sich relativ gleiche Arten entwickeln müssen.

3)Kindchen-Effekt
   Viele Beschreiben Außerirdische als kleine Humanoiden mit 
   relativ hoher Stirn und großen Augen. In der Tierwelt ist
   ähnliches bekannt. Mit der Evolution der Schimpansen wurde
   ihr Schädel immer runder und er bekam seine großen Augen.
   Man vermutet, daß durch die schwächer werdenen tierischen
   Instinkte und Agressionen sich Lebewesen zu "kindlicheren"
   Individuen entwickeln.

Buchtip: Gene Bylinski, Evolution im Weltall

@ENDNODE

  


