@DATABASE Bildergalerie.inc
@NODE Bildergalerie

Autor:Starman


Das Projekt ´Blue Book´

Von den Jahren 1948 bis 1969 hat die U.S.Airforce diverse UFO-
Sichtungen überprüft. Viele konnten mit irdischen Mitteln erklärt
werden, jedoch nicht alle. 

Dieses Foto wurde 1965 in Kalifornien aufgenommen. Es konnte nie
absolut erklärt werden, wahrscheinlich handelt es sich um einen Jux,
da das Objekt wahrscheinlich nur eine Länge von 30 bis 80cm hatte.
@{"UFO-Foto" SYSTEM "view UFO2:pics/bb1"}

Hierbei handelt es sich um eine Aufnahme, die 1963 in New Mexico
gemacht worden ist. Der Fotograf behauptete, im telepathischen
Kontakt mit den UFOnauten zu stehen. Ebenfalls höchstwahrscheinlich
ein Modell. Diesmal mit dem Durchschnitt von einem halben Meter.
Die Komission vermutete, daß der Fotograf glaubte, in Kontakt zu
den Außerirdischen zu stehen, darum fälschte er später die 
Beweisfotos-
@{"UFO-Foto" SYSTEM "view UFO2:pics/bb2"}

Diese drei UFOs wurden 1960 in Italien fotografiert. Nie ganz 
geklärt worden, allerdings ist auch hier eine Fälschung nicht
auszuschließen.
@{"UFO-Foto" SYSTEM "view UFO2:pics/bb4"}

Quelle: Die UFOs / TIME-LIFE-Bücher


UFOs in der Bibel

Im Alten Testament beschreibt der Prophet Hesekiel (Ezechiel) 
genau ein UFO und die dazugehörende Basis. Der pensionierte
NASA-Chefingenieur Josef Blumrich hat aufgrund dieser
Bibelberichte ein UFO konstruiert. Unabhängig davon entwickelte
der deutsche Ingenieur Herbert Beier eine UFO-Basis. Obwohl
beide ihre Modelle ohne Wissen des anderen konstruierten, 
paßten später beide Modelle haargenau zusammem. Nicht so
spektakulär, aber vielleicht noch aussagekräftiger ist die 
Tatsache, daß in dem Bibeltext ausführlich die Radkonstruktion
beschrieben wurde. Diese hat die NASA nachgebaut. Sie funktionierte
nicht nur tadellos, sondern war auch vollkommen ´neuartig´, so daß
die NASA hierfür ein Paten anmeldetet.
@{"Bibel-UFO" SYSTEM "view UFO2:pics/bibelufo"}

Quelle: Erich von Däniken / Raumfahrt im Altertum


UFOnauten auf der Erde

Dieser Außerirdische wurde 1955 in Kentucky, USA gesehen, 
angeblich sollte er auch imun gegen Gewehrschüsse gewesen
sein.
@{"Alien-Zeichnung" SYSTEM "view UFO2:pics/alien1"}


Verschiedene Zeugen wollen diese Kreatur in den 50ern
gesehen haben. Die Vorlage zu der Zeichnung stammt von
einem amerikanischen Arzt, der den Alien seziert hatte.
@{"Alien-Zeichnung" SYSTEM "view UFO2:pics/alien2"}


1973 wurde diese mumienartige Lebensform in Pascagoula,
Mississippi gesehen.
@{"Alien-Zeichnung" SYSTEM "view UFO2:pics/alien3"}

Quelle: Die UFOs / TIME-LIFE Bücher


Roswell, 1947

Am 4.Juli 1947 stürzte in Roswell, USA ein Objekt ab. Die 
U.S.Airforce bestätigte am ersten Tag den Absturz eines
UFOs, am zweiten Tag sollte es dann nur noch ein
Wetterballon gewesen sein. Danach kamen viele Augenzeugen,
u.a. ein Offizier und ein Arzt, auf mysteriöse Art und Weise ums
Leben. 1995 tauchte ein Film auf, der die Autopsie eines
dort abgestürzten Aliens zeigen soll. Wissenschaftler haben 
diverse Anzeichen dafür gefunden, das er unecht ist, allerdings
auch genausoviele, das er doch echt ist. Es ist also noch nichts
geklärt. Laut v.Butlar allerdings handelt es sich bei dem
Film um eine Fälschung.
@{"Roswell-Film" SYSTEM "view UFO2:pics/alien4"}

Quelle: Space View Nr.2


Die  Mars-Gesichter

Die NASA-Viking-Sonden haben den Mars gründlich fotografiert,
dabei entstanden auch Fotos von Pyramiden und riesigen 
Gesichtern. Computeruntersuchungen der Kopfbilder ergaben,
daß diese Gesichter Augen mit Augäpfeln und Pupillen,
Haarlinie, Mund, Nase und Kinn besitzen. Viele der
weiteren amerikanischen und auch russischen Marssonden
kamen nie bei dem roten Planeten an. Aus nicht geklärten
Gründen verschwanden sie im All.

@{"Mars-Gesicht  " SYSTEM "view pics/mars1"}
@{"Mars-Pyramiden" SYSTEM "view pics/mars2"}

Quellen: NASA, Johannes v.Buttlar / Leben auf dem Mars


Antike Fußabdrücke

Zu einer Zeit, wo noch keine Menschen gelebt haben sollen,
fanden Wissenschaftler diesen Fußabdruck und auch den
eines antiken Hammers. 

@{"Fußabdruck" SYSTEM "view UFO2:pics/fuss-alt"}


Außerirdische = Götter?

Immerwieder finden Archäologen Bilder, die auch einem
Science Fiction-Film entsprungen sein könnten. Während
es für die ´seriösen´ Wissenschaftler sich immer um
Gottesbilder handelt sehen UFO-Forscher hier grundsätzlich
immer Außerirdische. Dieses Kastendenken läßt leider zu
wenig Platz für andere Denkansätze. Wie wäre es wenn 
jemand in tausenden von Jahren unsere Ruinen ausgraben
würde? Sind Helmut Kohl, Michael Jackson oder Donald
Duck Götter? Was wäre wenn jemand sich eine uralte
Star Trek-Folge ansehen würde? Noch immer gibt uns 
unsere Geschichte Rätsel auf, vielleicht waren es Götter,
vielleicht waren es Außerirdische, vielleicht war es auch
ganz anders.

@{"Indianischer Gott" SYSTEM "view UFO2:pics/Gott"}
@{"Indianer 1       " SYSTEM "view UFO2:pics/Indianer1"}
@{"Indianer 2       " SYSTEM "view UFO2:pics/Indianer2"}

Quelle: Erich v.Däniken / Raumfahrt im Altertum


Kornkreise

Sind sie nun die Streiche gelangweilter Studenten oder
die Botschaft von Außerirdischen?

@{"Kornkreise" SYSTEM "view UFO2:pics/Kornkreise"}


Menschen auf dem Mond

Russische Wissenschaftler beschäftigen sich angeblich mit einem
Fuß-Abdruck auf dem Mond.

@{"Fußabdruck" SYSTEM "view UFO2:pics/mondfuss"}

Quelle: BILD-Zeitung


Was wissen afrikanische Eingeborene?

Ein afrikanischer Eingeborenenstamm der Dogonen weiß erstaunlicher 
Weise die genaue Umlaufbahnen von Sirius A und Sirius B. Europäische
Wissenschaftler konnten erst mit der Umlaufbahnbschreibung nichts 
anfangen, da Sirius B (ein weißer Zwerg) erst später in unserem
Jahrhundert entdeckt wurde. Die Maueren einer Ruine in Simbabwe
zeigen erneut die Ähnlichkeit der Sirius-Umlaiufbahnen.

@{"Umlaufbahnen" SYSTEM "view UFO2:pics/Simbabwe"}

Quelle: Erich v.Däniken / Raumfahrt im Altertum


UFO-Prototypen

Immerwieder gibt es Berichte, daß die amerikanische Airforce
abgestürzte UFOs nachgebaut hat. So soll z.B. der Stealt-Fighter
auf außerirdische Technologien beruhen.

@{"UFO-Prototyp" SYSTEM "view UFO2:pics/UFO-Prototyp"}

Quelle: Johannes v.Butler / Adams Planet


UFOs auf dem Radar

In der heutigen Zeit kann man Fotos nahezu perfekt fälschen.
Was ist aber mit dem UFO-Erscheinungen auf (Militär-) Radars?
Durch das ungewöhnliche Flugverhalten ist eine natürliche
Erscheinung auszuschließen.

@{"UFOs auf dem Radar" SYSTEM "view UFO2:pics/UFO-Radar"}

Quelle: Johannes v.Butler / Adams Planet


...und immernoch UFOs!

Zum Abschluß noch ein paar UFO-Fotos, deren Unechtheit
noch keiner Beweisen konnte.

@{"UFO-Foto" SYSTEM "view UFO2:pics/ufo1"}
@{"UFO-Foto" SYSTEM "view UFO2:pics/ufo2"}
@{"UFO-Foto" SYSTEM "view UFO2:pics/ufo3"}

Quelle: Johannes v.Butler / Adams Planet



@ENDNODE

  




