@DATABASE Geschichte.inc
@NODE Geschichte

UFOs in der Erdgeschichte


PowerBrei 12
Pro
@{"Auﬂerirdische" SYSTEM "ppmore 12/Auﬂerirdische"}


PowerBrei 13
Pro
@{"Auﬂerirdische1" SYSTEM "ppmore 13/Auﬂerirdische1"}

Kontra
@{"Auﬂerirdische2" SYSTEM "ppmore 13/Auﬂerirdische2"}


PowerBrei 14
Pro
@{"Anmerkungen           " SYSTEM "ppmore 14/Anmerkungen"}
@{"Auﬂerirdische - Kritik" SYSTEM "ppmore 14/Auﬂ.Kritik"}

Kontra
@{"Auﬂerirdische2        " SYSTEM "ppmore 14/Auﬂerirdische2"}


PowerBrei 15
Pro
@{"Immernoch Auﬂerirdische" SYSTEM "ppmore 15/Immernoch"}

Kontra
@{"Auﬂerirdische          " SYSTEM "ppmore 15/Auﬂerirdische}


PowerBrei 18
Pro
@{"Auﬂerirdische   " SYSTEM "ppmore 18/Auﬂerirdische"}
@{"UFOs, UFOs, UFOs" SYSTEM "ppmore 16/UFOs,UFOs,UFOs"}



@ENDNODE

  



