@DATABASE Sichtung.inc
@NODE Sichtung

Eine Sichtung eines UFOs ist in unserer Gesellschaft nicht
unumstritten. Leicht kann man von Presse und Mitmenschen
ins Lächerliche gezogen werden. Auch gibt es viele Objekte,
die mit man mit einem UFO verwechseln kann. Daher sollte
man sich als Erstes an seriöse UFO-Gruppen wenden. Als
Hilfe dient auch der Fragebogen.

@{" Fragebogen " link Fragebogen.inc/Fragebogen}  


Canada

 Canadian Study Team for Aerial Reseach
 --------------------------------------
 Diese Organisation hat sich auf alle Aspekte von UFOs 
 und Übernatürlichen spezialisiert.

 Adresse: C-Star
          119 Guthrie Cres.
          Whitby, Ontario
          L1P 1A6
          Canada

 Beiträge: Frankierten Rückumschlag für Infos einsenden.

 Für Mitglieder: Informationen zu zahlreichen UFO-Sichtungen,
 Videos inklusive UFO-Filme, TV-Serien und UFO-Beobachtungen.
 Aktuelle Informationen zu allen Aspekten des Unbekannten.


Germany

 Michael Hesemann
 c/o 2000 Film Prod.
 Worringerstr.1
 40211 Düsseldorf

@ENDNODE

