@DATABASE General.inc
@NODE "General"

General Purpose Droids


Name:
 Mouse Droid
Information: 
 A general purpose droid used by the Imperial Armmy and Navy.
 Effective, reliable and cheap, millions of mouse droids became
 fixtures in Imperial installiations ranging from the most temporary
 company camp to any top secret project.
Photo:
 @{"side-view" SYSTEM "view pics/Mouse"}


Name:
 WED-15 Treadwell
Information:
 A wheeled, six-limbed droid skilled in menial labor. Can be
 programmed to perform many functions that require limited
 intelligence such as mining, salvage, transportation and
 sanitation.
Photo:
 @{"side-view" SYSTEM "view pics/WED-15"}


@ENDNODE

