@DATABASE Secretary.inc
@NODE "Secretary"

Secretary Droids


Name:
 CZ-OR6
Information:
 A secretary droid augmented with advanced communications
 packages. As a courier droid, its memory files possess
 advanced encryption algorithms, which make it a secure 
 place to store sensible files.These features make it popular 
 with pilots, business beings and criminal bosses alike.
Photo:
 @{"front-view" SYSTEM "view pics/cz"}



@ENDNODE

