@database Documentation
@node main "  CodePW 2.1. Short english documentation"
@font xCourier.font 13

  Jürgen Einrauch
  Pattbrede 12
  D-49082 Osnabrück
  ++49 (0)541-53678
  
  Note my native language is german.
  If you can`t understand this script, remember I wrote my last
  english technical documentation in the middle of the last century,
  I believe for a gentleman named James Watt.
  ---------
  
  * Please read this documentation very carefully, especially all
    warnings. All use is at your own risk.

  * The warning of wrong input for three times is only a warning
    with no functions.
    
  * Password input is unvisible now, many thanks to Toni Nikolic.
  
  * If you have an old version of codePW on your harddisk first
    use <delete codePW 2.1>, it deletes old versions, too.
   

  The files <install codePW 2.1>, <delete codePW 2.1> and <codePW>
  are freeware, but any distribution must include the infor-
  mation file <read me 2.1>.

  <install codePW> is a script to install the very small file <codePW>
  with a personal identity word or number and the name and address of
  the owner. <codePW> interrupts the boot process until it reads the
  correct password input. 
  
  You can choose another order as it is usual in your country, when
  inputting your name and address. 
           
  Then you can set the password.
           
  * Attention! You must choose only one word or number with no
    space at the begin, the end and between.
  * Reset your amiga to check the correct installation.
  
  To change your password first use <delete codePW 2.1>. Then
  use the install program again.
  
  * It is very useful to reboot the system after every use of the
    install and delete program to clear the RAM. Using the install
    and the delete program without a reset @{b}could@{ub} produce unclear
    results. I believe I fixed this bug, but a reset could be better. 
  
  * Make sure to have a bootable and intact Workbench floppy disk.
    It is the only way to start your computer when <install codePW 2.1>
    misinterprets unclear inputs.
    
  * If this happened, put this disk into your floppy drive and boot your
    Amiga. Then open your WB-directory "S" and delete the file <codePW>.
    Then your can boot your Amiga from harddisk again. 

  Delete the install program, the delete program and this readme file
  from your harddisk after password installation, otherwise everybody
  can input another password and then start your system. Save all this
  files on a floppy disk.
@endnode
