@database "Alternate Floppy Formats.READ.ME"
@author "Leonard Poma"
@(c) "Copyright © 1993 CONSULTRON"
@$VER: "Alternate Floppy Formats.READ.ME" 5.06 (4/6/93)
@smartwrap

@node Main "CrossDOS Plus -- Alternate Floppy Formats"
                           Alternate Floppy Formats
                             June 4 1993

The advanced Format utility (the 1.3/2.0 version only) allows a different
format to be forced on an MS-DOS floppy disk.  Forcing a format on other
disk types such as AmigaDOS will not succeed.

Forcing a format is optional.  Normally the Format utility will format the
disk to the optimal size.  If you can, don't force a alternate format.  If
you do need to force a format, make sure you know what type of disk you are
planning to use.  Forcing a format will override disk size checking.

Floptical drive users may need to force a disk format because the software
mechanisms for checking the size of the media in the drive are not
available.  Follow one of the two procedures detailed in the section 
@{"Notes for Floptical Users" link "Notes for Floptical Users"} for formatting disks.

We recommend that if you must force a format, that you use the icons on the
product disk.  Installed versions can be used if the 1.3/2.0 version of the
Format command is installed.


@{"Alternate Format Types" link "Alternate Format Types"}
@{"Notes for Floptical Users" link "Notes for Floptical Users"}

@ENDNODE

@NODE "Alternate Format Types"
The following are the types of alternate formats supported.  Double-click
on the icon that matches the format desired.  Do not modify any of the
ToolTypes in the icon.  This may result in an improper format.

@{u}MSDOS_720K.Format@{uu}
This is the standard format for an MS-DOS 3 1/2" low density disk.  If you
are using the standard Amiga drive don't use this icon but rather use the
Format utility instead.

This format is useful for floptical drive users because the software cannot
sense when a low density disk is in the drive.

@{u}MSDOS_1.44M.Format@{uu}
This is the standard format for an MS-DOS 3 1/2" high density disk.  If you
are using the standard Amiga high density drive don't use this icon but
rather use the Format utility instead.  If you do not have an Amiga high
density drive, forcing this format will fail.

This format is useful for floptical drive users because the software cannot
sense when a high density disk is in the drive.

@{u}Floptical_20M.Format@{uu}
This is the format for a MS-DOS 20 Meg floptical disk.  This format is not
a hard drive format but a compatible floppy format.  Do not use this format
if your floptical device is configured as a hard disk.

If you do not have a floptical drive, forcing this format will probably
fail.

This format is useful for floptical drive users because the software cannot
sense when a disk the size of a floptical is in the drive.

@{u}ATARI_720K.Format@{uu}
This is the standard format for an Atari ST 3 1/2" low density disk.  Use
this if you must but most Atari-STs can read the standard MS-DOS 720K
format.

@{u}MSDOS_360K.Format@{uu}
This is the standard format for an MS-DOS 5 1/4" low density disk.  If you
are using the standard Amiga drive don't use this icon but rather use the
Format utility instead.

@ENDNODE

@NODE "Notes for Floptical Users"
Formatting with the floptical drive may require forcing a disk format.
This is because your SCSI host controller cannot properly sense the size of
the unformatted disk in the drive.  There are two ways to format using the
floptical drive.

One:  Insert a preformatted MS-DOS disk in the drive with the same
formatted size as you want to format.  If you want to format a 1.44M disk,
for example, insert a preformatted MS-DOS 1.44M disk in the drive first.
Then, execute the @{b}Format@{ub} program.  Proceed with the program until
you come the requester that says "Ok to format volume ...  " then insert
the actual disk to be formatted and proceed.

Two:  Double-click on the format project icon in the @{i}:system/Alt_Formats@{ui}
drawer that corresponds to the desired format.  For example, double-click
on the @{b}MSDOS_720K.Format@{ub} icon to 'force' the format of the disk to
720K.  Proceed through the format.

Choose the method that makes you comfortable.  Experimentation is your best
teacher.

@{b}NOTE:@{ub} At this time, GVP controllers will not permit a format of a
blank floppy using the @{b}Format@{ub} program.  In order to low-level
format a blank floppy you need to use their @{b}FAAASTPREP@{ub} program,
select "Manual Installation" then select "Low Level Format".  When completed,
exit @{b}FAAASTPREP@{ub} and perform a @{b}Format@{ub} with the "Quick Format"
option.

@ENDNODE
