@DATABASE Interrogation.inc
@NODE "Interrogation"

Interrogation Droids


Model:
 16 Interrogation Droid
Pic:
                   ___
      _,----------^.  """---
     -======++==_::.`.
       `--::():' `.`:.\
          //||     \`:.\
   >=.   // ||___   \`:.\
  >=.`=======O  \`-. |`:.|
    `===O_/___|_____\|__:|
        [______________]:|
         |`:.      .:|=:'|
      LS  \`:::::::'/ |:/   I6 Interrogation Droid
           `-.___.-' /_/        - Side View -

@ENDNODE

