@DATABASE Pilot.inc
@NODE "Pilot"

Pilot Droids


Name:
 V1 Pilot
Model:
 Industrial Automaton V1 Pilot
Height:
 1 meter
Skills:
 Astrogation
 Starship Operation
 Computer Programming and Repair
 Starship Repair
Equipped with:
 Three wheeled legs (one retractable)
 One reatractable arm
 Visual range sensor
 Starship interface jack
 Video display screen
 Memory for three pre-programmed hyperspace jumps
Photo:
 @{"front-view" SYSTEM "view pics/V1"}


@ENDNODE

