@DATABASE "Ops/Keine Veränderung.msg"

@NODE MAIN "Der Keine Veränderung Operator"
  Dieser  Operator  benötigt  eine  Quelle  und  macht mit den einzelnen
  Bildern   dann   --   nichts.    Wer   möchte,  kann  mit  dem  "Keine
  Veränderung-Operator"  leere  Bereiche  in der Schnittliste füllen, um
  ein  ästhetisch ansprechenderes Aussehen zu erzeugen.  Dieser Operator
  ist  somit  eigentlich  völlig  unnötig.   Wenn  jemandem  jedoch eine
  sinnvolle  Anwendung  einfallen  sollte,  für Tips haben wir immer ein
  offenes Ohr.

  @{" Beispiel für Einfach-Modus zeigen " RX "MS_GUIDE:OpenAndExecute.msrx LOADTIMELINE TimeLines/Easy/Nop"}
  @{" Beispiel für UPN-Modus zeigen " RX "MS_GUIDE:OpenAndExecute.msrx LOADTIMELINE TimeLines/UPN/Nop"}

@ENDNODE
