@database READ.ME
@author "Leonard Poma"
@(c) "Copyright © 1992-1995 CONSULTRON"

@node Main "CrossDOS"

                       CrossDOS 6 Professional                       
                     $VER: READ.ME 6.00 (3/4/95)                     
                            CIN: IUCA-Q3L9                           

This  file  describes  any  changes,  highlights and special features
for  this  version  and  revision  of CrossDOS. PLEASE READ THIS FILE
FOR IMPORTANT NEWS!

Note: CrossPC is no longer bundled with CrossDOS.

*******************************************
TABLE OF CONTENTS

@{"Running CrossDOS from the Product Disk" link "Running CrossDOS from the Product Disk"}
@{"Installing CrossDOS" link "Installing CrossDOS"}
@{"Configuring an MS-DOS Hard Drive" link "Configuring an MS-DOS Hard Drive"}
@{"Changes from Versions 3 and 4 of CrossDOS" link "Changes from Versions 3 and 4 of CrossDOS"}
@{"Changes from Version 5 of CrossDOS" link "Changes from Version 5 of CrossDOS"}
@{"Notes for Floptical Users" link "Notes for Floptical Users"}
@{"Who Owns This Disk Anyway?" link "Who Owns This Disk Anyway?"}
@{"Troubleshooting" link "Troubleshooting"}
@{"Other CONSULTRON Products" link "Other CONSULTRON Products"}
@{"Electronic Registration" link "Electronic Registration"}
@{"Technical Support" link "Technical Support"}
@{"Electronic Bulletin Board Service" link "Electronic Bulletin Board Service"}
@{"Copyrights, Disclaimers and Trademarks" link "Copyrights, Disclaimers and Trademarks"}

@ENDNODE

@NODE "Running CrossDOS from the Product Disk"
CrossDOS  can  be  executed  from  this product disk (particularly if
you  are  running on a floppy based system). Just double-click on the
appropriate icon.

To  start:  double-click  on  the  "PC0"  icon.  Your internal floppy
drive  will  now  be  configured  as  an  MS-DOS  drive with the name
"PC0:". You can now read and write preformatted MS-DOS disks.

If  you  need  to  format  an MS-DOS disk, double-click on the @{b}Format@{ub}
icon  in  the  @{i}system@{ui}  drawer.  Choose  the device to format from the
device list and answer any of the questions and options given.

It's that simple.
@ENDNODE

@NODE "Installing CrossDOS"
You  may  choose to install CrossDOS using the @{b}Install@{ub} program on the
disk.  This  is  particularly  efficient if you have a hard drive. If
you  do  wish  to  install,  DO NOT move the files over manually! The
@{b}Install@{ub}  program  makes  many  intelligent  choices depending on your
system configuration.

Once  installed,  you  can  use  most  features  immediately.  A  few
features  such  as  MS-DOS  hard  disk  access may require additional
operations  be  performed  before you use it. For further information
see @{"Configuring an MS-DOS Hard Drive" link "Configuring an MS-DOS Hard Drive"}

@ENDNODE

@NODE "Configuring an MS-DOS Hard Drive"
CrossDOS  supports  MS-DOS  formatted  hard  drives. If the drive you
configure   is  already  formatted,  there  are  certain  hard  drive
formats  that  are not 'true' MS-DOS. In this case, we do our best to
decipher the disk but 'all bets are off'.

We  do  require  that  you  install  both  products using our @{b}Install@{ub}
program.  Also,  select  @{b}Configure Hard Disk@{ub} to have us try to create
a proper mountfile to match.

You  will  be  asked  in  the  @{b}Install@{ub}  program  whether  you want to
configure one of three types of hard disks.

@{b}One:@{ub}  A  'true'  MS-DOS hard disk configured as the entire disk. This
type  is  useful if you wish to transfer data between the Amiga and a
stand-alone  PC.  We  do HIGHLY recommend that this type of hard disk
be  formatted  on  the  PC  first  then  brought  to  the  Amiga  for
configuring.
@{"Configure a 'true' MS-DOS hard disk NOW!" SYSTEM ":c/configdisk Disk"}

@{b}Two:@{ub}  An  'image'  of  an  MS-DOS hard disk within an Amiga hard disk
partition.  This  type  is particularly useful with CrossPC, PC-Task,
AtOnce and GoldenGate products.
@{"Configure an 'image' of an MS-DOS disk on an Amiga partition NOW!" SYSTEM ":c/configdisk PARTITION"}

@{b}Three:@{ub}  An  'image'  of  an MS-DOS hard disk within a file. This type
is  useful  with Bridgeboard, CrossPC, PC-Task, AtOnce and GoldenGate
products.
@{"Configure an 'image' of an MS-DOS disk on a file NOW!" SYSTEM ":c/configdisk FILE"}

For   further   information   refer   to  @{b}Chapter  5@{ub}  in  the  manual
"@{b}Configuring  a  Hard  Drive@{ub}" that discusses the different hard drive
types and special considerations.
@ENDNODE

@NODE "Changes from Versions 3 and 4 of CrossDOS"
This  section  is  important for users who have either version 3 or 4
of CrossDOS.

There  have  been  changes  to  CrossDOS  for a multitude of reasons.
These  reasons  range from efficiency, speed, robustness and more. We
hope  you  like  the  changes.  Most of the code is more efficient in
both speed and code size.

CrossDOS  6  requires  2.0  of  the  Amiga  operating  system to run.
Previous versions allowed operation under 1.2 of the OS.

The  name  of  the  file system has been changed from @{b}MSDOSFILESYSTEM@{ub}
to  @{b}CrossDOSFileSystem@{ub}.  The  file system code has been optimized for
speed so that reads and writes are about 10 times faster.

The  old  MS-DOS devices defaulted to the names DI0: through DI3:. We
now use PC0: through PC3:.

We've  replaced  the  MountMF,  MFORMAT  and  MDISKCOPY with standard
system  commands  called  Mount,  Format  and DiskCopy, respectively.
These  commands,  located in the @{i}system@{ui} drawer, have been enhanced to
handle  both  CrossDOS or Amiga disks. Refer to the manual in Chapter
4 for more details.

We've  replaced  the TxFilter and IntlTrans commands with a commodity
called  @{b}CrossDOS@{ub}  located  in your @{i}system@{ui} drawer. Refer to the manual
in Chapter 4 for more details.

The  mfm.device  driver used to access the floppies have been further
optimized  to  read and write about 8 times faster than version 3 and
about 4 times faster than version 4 CrossDOS.

We  support  MS-DOS hard drives. We supply a configuration program to
simplify    the   process   of   creating   the   proper   mountfile.
@{"Configuring an MS-DOS Hard Drive" link "Configuring an MS-DOS Hard Drive"}

We now work across Amiga networks.

Many  other  improvements  have  been  made  that  are designed to be
transparent to the user but which make it easier to use.

@ENDNODE


@NODE "Changes from Version 5 of CrossDOS"
This section is important for users who have version 5 of CrossDOS.

CrossDOS  6  requires  2.0  of  the  Amiga  operating  system to run.
Version 5 allowed operation under 1.2 of the OS.

The  file  system  code  has  been optimized for speed so that writes
are about 10 times faster.

The  mfm.device  driver used to access the floppies have been further
optimized to read and write about 2 times faster.

We've  improved  our  hard  drive  configuration program. We now work
across Amiga networks.

Many  other  improvements  have  been  made  that  are designed to be
transparent to the user but which make it easier to use.

Note:  CrossPC  is  no  longer bundled with CrossDOS. CrossDOS 6 will
operate correctly with CrossPC.

@ENDNODE


@NODE "Notes for Floptical Users"
CrossDOS  supports  floptical  drives. If you do not know if you have
a  floptical  drive  you  probably  don't have one. A floptical drive
can  support  the  MS-DOS  720K, 1.44M and its own 20M floptical disk
format. It can also support an Amiga 20M hard drive format.

To  configure  the  floptical use the @{b}Configure Hard Disk@{ub} to allow us
to  attempt  to  create  a proper mountfile. When you are configuring
the  floptical,  make sure you have a preformatted MS-DOS disk in the
drive  at  the  time.  Any  MS-DOS  disk  should  do (such as an 720K
disk).  This  is  needed  to  sense  the  proper information from the
drive.

Formatting  with  the floptical drive is slightly different too. This
is  because  the  floptical  cannot  properly  sense  the size of the
unformatted  disk  in  the drive. There are two ways to format in the
floptical drive.

One:  Insert  a  preformatted  MS-DOS disk in the drive with the same
formatted  size  as you want to format. If you want to format a 1.44M
disk,  for  example,  insert  a preformatted MS-DOS 1.44M disk in the
drive  first.  Then,  execute  the  @{b}Format@{ub}  program. Proceed with the
program  until  you come the requester that says "Ok to format volume
... " then insert the actual disk to be formatted and proceed.

Two:    Double-click    on   the   format   project   icon   in   the
@{i}:system/Alt_Formats@{ui}  drawer  that  corresponds to the desired format.
For  example,  double-click  on the @{b}MSDOS_720K.Format@{ub} icon to 'force'
the format of the disk to 720K. Proceed through the format.

Choose  the  method  that  makes  you comfortable. Experimentation is
your best teacher.

@{b}NOTE:@{ub}  At  this  time,  GVP controllers will not permit a format of a
blank  floppy  using the @{b}Format@{ub} program. In order to low-level format
a  blank  floppy  you  need  to  use their @{b}FAAASTPREP@{ub} program, select
"Manual   Installation"   then   select   "Low  Level  Format".  When
completed,  exit  @{b}FAAASTPREP@{ub}  and  perform  a  @{b}Format@{ub} with the "Quick
Format" option.

@ENDNODE

@NODE "Who Owns This Disk Anyway?"
Don't  worry,  this  is  not a rehash of the license agreement you've
already  read  on  the  front  of  the  disk  envelope. This concerns
people  who  are using PC emulator products on the Amiga. Examples of
emulators  are  CrossPC,  PC-Task, Bridgeboard, AtOnce, GoldenGate or
EMPLANT/PC-586.

If   you've   configured   an   MS-DOS  disk  for  CrossDOS  that  is
simultaneously  configured  for  one  of  the  emulators, you may run
into a problem.

The  problem:  When  more  than one file system tries to write to the
same  physical  disk volume/partition, the disk may end up corrupted.
Both CrossDOS and the emulators running MS-DOS are file systems.

Let  me  draw  a  simple  analogy.  Let's  say  there is one checking
account  and  you  have  a set of checks and a friend has another set
of  checks  to  the  same account. If the both of you never cooperate
to  balance  the  account  when  checks are written, the account will
eventually be overdrawn.

Similarly,  file  systems tend to cache small portions of the disk so
as  to  speed  disk  access.  Let's suppose CrossDOS and the emulator
(running  MS-DOS)  just happen to cache the same disk information. If
CrossDOS  modifies  the  information it has cached, MS-DOS (the other
file  system)  will  not  know  the  information  was  changed.  Now,
CrossDOS  creates  a  new  file  and  uses some blocks not previously
used.  If  MS-DOS  wishes  to  create  a  file,  it might reuse those
blocks  allocated  by  CrossDOS.  When  this happens the disk is most
likely   corrupted   since   neither  file  system  has  the  correct
information.  Both  have  also  modified  the  disk  with out-of-sync
information.

The  solution:  If both file systems would cooperate when writing new
information  to  the  disk, we'd have our problem solved. For reasons
which are complicated, that solution is not likely to happen.

You  can  have  as  many  file  systems  read  the disk as long as no
writing  occurs.  However,  if  you must write, there are things that
can be done to significantly minimize disk corruption.
    · Create  two  partitions.  One  for  CrossDOS  to  write  to and
      MS-DOS  to  read  from and the the other for MS-DOS to write to
      and CrossDOS to read from.
    · Manually  prevent  multiple  file  systems  from simultaneously
      writing to the disk.
    · After   writing   the  disk  with  MS-DOS,  perform  a  @{b}DiskChg@{ub}
      (diskchange)  for  the CrossDOS device. This action will reread
      the disk from the Amiga side.
    · After  writing  the  disk  with CrossDOS, perform a <CTRL C> (a
      type  of  diskchange)  from  the MS-DOS command prompt. If this
      is  not  possible,  run  the  @{b}CHKDSK@{ub}  program. This action will
      reread the disk for the MS-DOS side.

@ENDNODE

@NODE "Troubleshooting"
Here  are  some  ideas  to  help  you  should  you have trouble using
CrossDOS.

@{b}General@{ub}
    · Ensure  you  have configured the drive in which you wish to use
      the  MS-DOS  disk  by  Mounting it. The device names correspond
      to  the  device  names given by Commodore. For example, PC0: is
      the  MS-DOS  device  name corresponding to DF0: and PC1: is the
      MS-DOS device name corresponding to DF1:.
    · Avoid file names longer than 8 characters.
    · Avoid file extensions longer than 3 characters.
    · Avoid space in file names or file extensions.
    · Make  sure  you  do  not  mix  disk types and format types. For
      example,  do  not  do  a  low  density format on a high density
      disk  or  visa  versa.  Do  not  try  to  read  a  high density
      formatted disk in a low density drive.
    · When  using  Workbench,  avoid  transferring  files  with  file
      extensions. Rename them first if necessary.
    · Ensure  the  file  formats  you  want  to  use between both the
      Amiga  program  and  the  MS-DOS  program  are  compatible. For
      example,  an  Amiga  Final  Copy  file  is  not  readable by an
      MS-DOS WordPerfect wordprocessor.
    · Should  you  exhibit  read  or  write  errors  with no specific
      pattern,  try  cleaning  the  floppy  drive  heads  of both the
      Amiga and MS-DOS computers.
    · The  easiest  way  to check an MS-DOS disk from the Amiga is to
      run  the  DiskChk program included with CrossDOS. The following
      is a list of most of the CrossDOS error codes.Error Messages


@{b}Error Messages@{ub}

@{u}No.      Name                    Description@{uu}

-1  IOERR_OPENFAIL          device/unit failed to open
-2  IOERR_ABORTED           request aborted
-3  IOERR_NOCMD             command not supported
-4  IOERR_BADLENGTH         not a valid data length
20  TDERR_NotSpecified      general catch all error code
21  TDERR_NoSecHdr          couldn't find any sectors on track
22  TDERR_BadSecPreamble    bad sector header
23  TDERR_BadSecID          bad sector header
24  TDERR_BadHdrSum         sector header had incorrect CRC
25  TDERR_BadSecSum         data had incorrect CRC
26  TDERR_TooFewSecs        couldn't find enough sectors
27  TDERR_BadSecHdr bad     sector header
28  TDERR_WriteProt         can't write to a protected disk
29  TDERR_DiskChanged       no disk in the drive
30  TDERR_SeekError         couldn't find track 0
31  TDERR_NoMem             ran out of memory
32  TDERR_BadUnitNum        asked for a unit > 3
33  TDERR_BadDriveType      not a recognized drive
34  TDERR_DriveInUse        someone else allocated the drive
35  TDERR_PostReset         user hit reset; awaiting doom
36  MDERR_OutofTracks       out of physical tracks
37  MDERR_InvParam          invalid parameter (MD_SETPARMS)
38  MDERR_IndexNotSync      index signal not available
39  MDERR_WrongTrack        drive head on wrong physical track


@{b}Possible Problems and Solutions@{ub}

@{i}I  changed  the  MS-DOS disk on the 51/4" drive and still get the old
directory from the previous disk.@{ui}
      The  5  1/4" drive doesn't support the disk change signal. When
     you  change  disks,  execute  the  CLI DiskChange command or our
     DiskChg  command  on  the  drive  before your next access of the
     new disk.

@{i}I  copied  a  file  to  an MS-DOS disk but can't find it when reading
the disk on my PC.@{ui}
      Avoid  using  spaces in file names. The MS-DOS computer ignores
     everything after the space character.

@{i}DF0:????@{ui}
      This  is  OK.  The task that handles the AmigaDOS device called
     DF0: can't recognize foreign disk formats such as MS-DOS.

@{i}Disk Ejected Too Soon.@{ui}
      Disk  removed  before  all  information  was written to it. Put
     the  disk  back  into  the drive and Retry might recover without
     corruption.  We  recommend  you wait at least 3 seconds from the
     last disk access before removing the disk.

@{i}Disk Full.@{ui}
      Exceeded  the  capacity  of the system disk. Remove unnecessary
     files from the disk.

@{i}Error=21.@{ui}
      Could  not  find  any  sectors on the specified track. Probably
     not  an  MS-DOS standard density formatted disk readable by your
     drive.

@{i}Error=22.@{ui}
      Sector  not  aligned  with  index signal from disk. Usually not
     disastrous. Retry might recover.

@{i}Error=23.@{ui}
      Sector not found. Disk might be corrupt. Retry might recover.

@{i}Error=24.@{ui}
      Sector   identification   information   corrupt.   Retry  might
     recover.

@{i}Error=25.@{ui}
      Sector data might be corrupt. Retry might recover.

@{i}Error=38.@{ui}
      Index  signal  from the drive not received. Amiga needs service
     to correct a hardware problem.

@{i}Not a DOS Disk.@{ui}
      Ensure  the  disk  is  an  MS-DOS disk capable of being read by
     your  drive.  The  disk  may  be an AmigaDOS disk or MS-DOS high
     density formatted disk in a low density drive.

@{"Technical Support" link "Technical Support"}
@ENDNODE

@NODE "Other CONSULTRON Products"
In addition to CrossDOS our product line also includes:

@{b}CrossMAC@{ub}  -  Mac  file system for the Amiga. Allows the Amiga to read
and  write  Mac  floppies  and  hard  drives.  CrossMAC  demo archive
(CrossMAC_demo.lha)  on  this disk. This is a READ-ONLY demo allowing
you to read Mac floppies (with the appropriate hardware).

@{b}High-density  floppy  drives@{ub} - internal and external models. Internal
models  for  2000,  3000  and  4000.  External  model for all Amigas.
While supplies last.

@{b}Bernoulli   230M   drives@{ub}  -  internal  and  external  models.  Extra
Bernoulli cartridges can be purchased separately.

Call  (313)  459-7271  for  further information and pricing. Visa and
MasterCard supported.

@ENDNODE

@NODE "Electronic Registration"
We   suggest   that  you  immediately  register  the  product  you've
purchased.  This  will  allow  us  to  inform  you of new products or
upgrades   and  be  eligible  for  product  discounts.  Currently  we
provide  two  methods  of  registering  the  Customer  Identification
Number and address with us:

    · EMAIL.  Send  the file s:Registration.data intact to either our
      Internet      account:     consultron@consultron.plymouth.mi.us
      (primary)  cstron@m-net.arbornet.org  (secondary)  or  logon to
      our BBS.

    · Paper.  Send  us  the paper output generated by or Registration
      program to the address listed in the output.

We  would  appreciate  if  you  would  use  the EMail method since it help to
eliminate typographical errors.
@{"Register NOW!" SYSTEM ":c/Registration :RegistrationInfo"}

@ENDNODE

@NODE "Technical Support"
If  you  purchased  our products as marketed by CONSULTRON, we'll try
to  give  you  the  best  technical support possible. You will notice
your  Customer  Identification Number is located in the third line of
the   READ.ME  file  and  will  automatically  be  entered  into  the
Registration  program.  Please  write this number on the disk, in the
manual  and  anywhere  convenient.  When you call for help, please be
ready  with  your  Customer Identification Number (CIN). We hope this
doesn't  inconvenience  you  much.  This  policy helps keep our costs
down and we can pass those savings on to you.

    @{b}(313) 459-7271@{ub} 10:00 AM to 5:00 PM Eastern Time

@ENDNODE


@NODE "Electronic Bulletin Board Service"
We've  provided  an electronic bulletin board service to better serve
you.  It  may  contain  update  patches  should  there  be any. Other
public  domain  or  shareware  files are available that may be useful
to  you.  We  also  have  demo  versions of most of our programs that
allow you to "try before you buy".

The telephone number of our BBS is:

    @{b}(313) 459-7271@{ub} 6:00 PM - 10:00 AM EST Weekdays
                  and all day on weekends and U.S. holidays

    Currently our service is 2400-14.4 baud 8N1

 Thank you.

@ENDNODE

@NODE "Copyrights, Disclaimers and Trademarks"
@{b}COPYRIGHTS@{ub}

CrossDOSFileSystem,    mfm.device,    MountMF,    DiskChk,   DiskChg,
Registration,   ConfigDisk,   Install,   Dr_CrossDOS   (c)  Copyright
1988-1995 CONSULTRON. All Rights Reserved.

Mount,  DiskCopy,  Format,  CrossDOS, Installer and Installer project
icon,   AmigaGuide,   amigaguide.library,   (c)   Copyright   1991-93
Commodore-Amiga,   Inc.   All   Rights   Reserved.   Reproduced   and
distributed under license from Commodore.

@{b}DISCLAIMERS@{ub}

MOUNT,  FORMAT,  DISKCOPY,  INSTALLER  AND  AMIGAGUIDE  SOFTWARE  ARE
PROVIDED  "AS-IS"  AND SUBJECT TO CHANGE; NO WARRANTIES ARE MADE. ALL
USE IS AT YOUR OWN RISK. NO LIABILITY OR RESPONSIBILITY IS ASSUMED.

@{b}TRADEMARKS@{ub}

CrossDOS  and  CrossPC  are trademarks of CONSULTRON. AmigaGuide is a
trademark of Commodore-Amiga, Inc.

@ENDNODE
