@DATABASE 
@AUTHOR "OFS"
@$VER: Doc.guide 1.4 (21-Août-1996)
@(c) "Copyright Août 1996 Amigazette83"
@index index
@wordwrap
@node main Doc.guide
@{" Recherche " SYSTEM "RUN <>NIL: SearchGuide Doc'-Amigaguide1.4"} <-- Active la recherche de mots clés


@{u}@{b}Doc' d'utilisation d'Amigaguide:@{ub}@{uu}

 @{u}Intro:@{uu}

J'ai rencontré énormément de personnes attirées par Amigaguide, mais déçues par le manque de documentation. Une doc a déjà été faites en 1995 par @{b}Aric R.Caley@{ub}, mais celle-ci était en Anglais.
A tous les francophones qui souhaitent enfin comprendre quelque chose à Amigaguide, je viens vous offrir sa doc' entièrement réalisée sur celui-ci (on ne change pas un soft qui marche).
C'est donc @{b}Freeware@{ub}, faites le passer et éclatez-vous bien.

Et tout d'abord, bienvenue sur la documentation d'Amigaguide, l'excellent outil de création de fichiers intéractifs par Hypertexte. Vous allez créer des Docs, des lettres intéractives ou je ne sais quoi d'autre. Amigaguide, je vous l'assure, n'est pas compliqué. 
Alors, --> @{b}Amigaguidez bien! :^)@{ub}


 @{u}Rappel:@{uu}

Amigaguide est disponible sur Amiga depuis la version 2.1 du système. La réalisation d'un guide est fort simple. Il suffit d'utiliser les codes Amigaguides qui sont précédés du symbole @. 
Vous pourrez créer des pages afin de naviguer à l'intérieur, mais aussi faire appel à des programmes externes tel qu'un viewer. Très pratique depuis l'apparition des Datatypes sur l'OS 3.0.
A noter que certaines fonctions ne sont accessibles qu'à partir de la version 40 de l'amigaguide.library. @{b}Version 40, qui correspond au Workbench 3.1@{ub}.

Pour utiliser @ dans un guide, il suffit de l'écrire normalement. Cependant si vous l'utilisez devant une commande (pour faire une explication d'Amigaguide par exemple), il faudra mettre un Anti-slash devant.
Mais bon, j'ose espérer que vous ne vous lancerez pas dans une doc d'Amigaguide 8^).


@{u}Commandes Amigaguide:@{uu}

@{" Création d'un guide          " link "création"}
@{" Pages du guide               " link "pages"}
@{" Boutons de Commande          " link "commande"}
@{" Modification du texte        " link "texte"}
@{" Appel de programmes externes " link "programme"}
@{" l'Index                      " link "l'index"}
@{" Utilitaires                  " link "utils"}

@{" Contact                      " link "contact"}
@{" Remerciements                " link "merci"}

Attention, Amigaguide ne se limite pas aux commandes expliquées. Il en existe de nombreuses, mais celles qui sont évoquées suffisent à une utilisation plus que correcte.
Je mettrai cette Doc' à jour, au fur et à mesure de mes découvertes de nouvelles commandes.

@endnode

@node "création"
@next pages
@prev main
@toc main
@{" Recherche " SYSTEM "RUN <>NIL: SearchGuide Doc'-Amigaguide1.4"} <-- Active la recherche de mots clés


Pour créer un fichier Amigaguide, il suffit d'utiliser un éditeur de texte (ED), et de sauver son texte en ASCII. Après avoir tapé votre listing, vous créerez une icône @{b}Projet@{ub} au nom du listing, avec comme outil @{b}Amigaguide@{ub} ou @{b}Multiview@{ub}.

La commande principale qui va déclarer à Multiview ou à Amigaguide, que votre listing est un fichier Amigaguide est la suivante:
@{b}\@ Database@{ub}  --> @{u}Placée en tout début de listing@{uu}, suivie ou non par le nom de votre Guide


 @{u}Identification du guide:@{uu}

@{b}\@ AUTHOR votrenom@{ub}  --> Nom de l'auteur
@{b}\@ $VER Nomduguide v1.0 (jj/mm/aa)@{ub}   --> Version et date de création du guide. A utiliser avec la commande Dos "Version". 
@{b}\@ (C) copyright@{ub}  --> Définie un Copyright au guide
A noter que ces informations n'apparaissent pas au lancement du guide.


 @{u}Autres commandes@{uu}

@{b}\@ FONT XHELVETICA.font 11@{ub}   --> Permet de changer la Fonte du guide (Nom-Taille)
@{b}\@ WIDTH 50@{ub}   --> Permet d'avoir des lignes de 50 caractères maximums
@{b}\@ WORDWRAP@{ub}   --> Aligne le guide à la dimension de la fenêtre (v39)
@{b}\@ REM@{ub} ou @{b}\@ REMARK@{ub}  --> Permet d'écrire un commentaire qui ne sera pas affiché
@{b}\@ TAB nombre@{ub}  --> Définie la taille en espace d'une Tabulation. 8 Par défaut (v40)
@{b}\@ HEIGHT lignes@{ub}  --> Définie le nombre de lignes maximums en hauteur
@{b}\@ HELP chemin/node@{ub}  --> Définie la page accessible par le bouton "Aide"
@{b}\@ MASTER chemin@{ub}  --> Définie le chemin d'accès du fichier AmigaGuide principal lors d'une dérivation
@{b}\@ ONOPEN@{ub}  --> Permet d'exécuter un script Arexx lors de l'ouverture du guide. En cas d'erreur du script, le guide ne s'ouvre pas (v40)
@{b}\@ ONCLOSE@{ub}  --> Permet d'exécuter un script Arexx lors de la fermeture du guide (v40)
@{b}\@ MACRO nom commandes@{ub}  --> Définie une macro pour le guide (v40)

Toutes ces commandes sont à placer en début de guide, et permettent de poser les paramètres de celui-ci.


 @{u}Exemple de début de guide:@{uu}

    \@ DATABASE
    \@ AUTHOR vous
    \@ TAB 7
    \@ $VER: votreguide 1.0 (01-01-2000)
    \@ INDEX votreindex  --> Signifie qu'il y a un Index dont le nom est "votreindex"
    \@ WORDWRAP
    \@ NODE main  --> Page principale du guide

    Listing
    Listing
    Listing

    \@ endnode   --> Fin de la page

@endnode

@node "pages"
@next commande
@prev création
@toc main
@{" Recherche " SYSTEM "RUN <>NIL: SearchGuide Doc'-Amigaguide1.4"} <-- Active la recherche de mots clés


Un guide se caractérise par l'accumulation de plusieurs pages. 
Chaque page a un nom et celui-ci doit être placé en début de page.

 @{u}EX:@{uu}   

@{b}\@ NODE page@{ub}   --> Nom de la page
@{b}\@ NODE nomdunode titredelafenêtre@{ub}  --> Si aucun nom n'est spécifié pour le titre de la fenêtre, le nom du node sera utilisé comme Titre.
@{b}\@ TITLE titredelafenêtre@{ub}  --> Autre façon de définir le titre de la fenêtre

Toutes les pages, mise à part la page principale, sont définies par des boutons. 

 @{u}Création d'un Bouton:@{uu}

@{b}\@{" Bouton " LINK "P2"} @{ub}   --> Crée un bouton qui renvoie à la page nommée P2
@{b}\@{" Bouton " LINK "chemin/fichier/MAIN"}@{ub}  --> Permet de renvoyer sur un lien externe, comme un autre guide. Ne pas oublier le /MAIN, il permettra d'activer le bouton "Retour" vers le guide principal

Comme il a été dit plus avant, on peut exécuter des programmes externes par le biais d'un bouton sous Amigaguide.

@{u}EX:@{uu}
@{b}\@{" Bouton " RX script} @{ub}  --> Permet d'exécuter un script ARexx
@{b}\@{" Bouton " RXS commande} @{ub}  --> Permet d'exécuter une chaine ARexx
@{b}\@{" Bouton " SYSTEM commande} @{ub}  --> Permet d'exécuter une commande AmigaDos
@{b}\@ endnode@{ub}  --> Indique la fin de la page

@{u}EX:@{uu}
    \@ DATABASE
    \@ AUTHOR "vous"
    \@ $VER: votreguide 1.0 (01-01-2000)
    \@ INDEX votreindex  --> Signifie qu'il y a un Index dont le nom est "votreindex"
    \@ WORDWRAP
    \@ NODE main --> Page principale du guide

    Listing
    \@{" Texte " LINK "P1"}   --> Renvoie à la page P1 qui traite du texte
    Listing
    Listing
    \@{" Voir " SYSTEM "c:vt Chemin/Image"}   --> Affiche l'Image, par le biais de vt copié dans le c.
    Listing

    \@ endnode   --> Fin de la page

@{u}Voyons l'organisation de la page P2:@{uu}

    \@ node P2   --> Création de la page P2
    \@ next P3   --> Active le bouton Feuilleter> et renvoie sur P3
    \@ prev P1   --> Active le bouton Feuilleter< et renvoie sur P1
    \@ toc main  --> Active le bouton Contenu et renvoie sur la page principale

    Listing
    \@{" Doc " link "P6"}   --> Renvoie à la page P6 qui traite de la Doc
    Listing

    \@ endnode


N'oubliez pas à chaque page de mettre en fin de listing, ou de votre BlaBla, la commande @{b}\@ endnode@{ub}.
Celle-ci indique à Amigaguide la fin de la page. Vous devrez également la mettre à la fin de votre page principale.

@endnode

@node "commande"
@next texte
@prev pages
@toc main
@{" Recherche " SYSTEM "RUN <>NIL: SearchGuide Doc'-Amigaguide1.4"} <-- Active la recherche de mots clés


Cette partie concerne les boutons situées sur la page Amigaguide:
 @{b}Contenu - Index - Aide - Retour - Feuilleter< - Feuilleter>@{ub}

Ils permettent de retourner au contenu du guide, de lire l'index (si il y en un), d'avoir accès à l'aide, de retourner à la page précédente. Ils servent également à la navigation dans le guide, pour aller de page en page.

A chaque page que vous créerez, vous devrez au début, définir les boutons:
Contenu - Feuilleter< - Feuilleter> 
N'oubliez pas non plus de préciser le nom de votre page.

@{u}EX:@{uu}    
    @{b}\@ NODE page3@{ub}       --> Page nommée page3
    @{b}\@ NEXT page4@{ub}       --> Feuilleter> vers page4
    @{b}\@ PREV page1@{ub}       --> Feuilleter< vers page1
    @{b}\@ TOC main@{ub}   --> Active le bouton Contenu, retour à la page principale

Vous n'êtes pas obligé d'activer les boutons "Feuilleter" (NEXT - PREV), l'utilisateur ne pourra pas se balader dans le guide et sera obligé de revenir à la page principale pour activer une autre page.
Si vous faites une doc avec des paragraphes et des sous paragraphes, je vous conseille quand même d'activer le système de navigation.

@{u}EX:@{uu}

    \@ NODE page3
    \@ NEXT page4
    \@ PREV page1
    \@ TOC main

    Listing
    Listing
    Listing

    \@ endnode

@endnode

@node "texte"
@next programme
@prev commande
@toc main
@{" Recherche " SYSTEM "RUN <>NIL: SearchGuide Doc'-Amigaguide1.4"} <-- Active la recherche de mots clés


Amigaguide n'est pas HTML, vous ne pouvez pas insérer des images sur vos présentations, mais vous pouvez quand même modifier le texte, ou tracer des traits.

 @{u}Commandes diverses:@{uu}

@{b}\@{AMIGAGUIDE}@{ub}  --> Affiche le mot @{b} "Amigaguide(R)"@{ub} en gras (v40)
@{b}\@{u} Texte \@{uu}@{ub}   --> Souligne le @{u}texte@{uu} (v39)
@{b}\@{b} Texte \@{ub}@{ub}   --> Pour écrire en @{b}Gras@{ub} (v39)
@{b}\@{i} Texte \@{ui}@{ub}   --> Pour écrire en @{i}Italique@{ui} (v39)
@{b}\@{fg shine} Texte \@{fg text}@{ub}    --> Pour écrire en @{fg shine}Blanc@{fg text}
@{b}\@{fg fill} Texte \@{fg text}@{ub}  --> Pour écrire avec la @{fg fill}Couleur de la Fenêtre@{fg text}
@{b}\@{APEN n}@{ub}  --> Change la couleur du texte. "n" est le numéro du stylo (v40)
@{b}\@{BPEN n}@{ub}  --> Change la couleur du fond. "n" est le numéro du stylo (v40)

@{b}\@{bg fill} Texte \@{bg background}@{ub}   --> Pour écrire en @{bg fill}Noir sur Fond Couleur Fenêtre@{bg background}
@{b}\@{fg shine}\@{bg fill} Texte \@{bg background}\@{fg text}@{ub}   --> Pour écrire en @{fg shine}@{bg fill}Blanc sur Fond Couleur Fenêtre@{bg background}@{fg text}
@{b}\@{bg shine} Texte \@{bg background}@{ub}   --> Pour écrire en @{bg shine}Noir sur Fond Blanc@{bg background}
@{b}\@{fg back}\@{bg text} Texte \@{fg text}\@{bg back}@{ub}  --> Pour écrire en @{fg back}@{bg text}Blanc sur Fond Noir@{fg text}@{bg back}

@{b}\@{BODY}@{ub}  --> Restaure le formatage normal du texte (v40)
@{b}\@{PLAIN}@{ub}  --> Désactive tous les attributs de style (gras, italique...) (v40)
@{b}\@{JCENTER}@{ub}  --> Active la justification centrée (v40)
@{b}\@{JLEFT}@{ub}  --> Active la justification à gauche (v40)
@{b}\@{JRIGHT}@{ub}  --> Active la justification à droite (v40)
@{b}\@{CLEARTABS}@{ub}  --> Restaure la Tabulation à sa valeur par défaut (v40)

@{b}\@{bg shine}      \@{bg background}@{ub}    --> Tracer des traits Blancs @{bg shine}      @{bg background} 
@{b}\@{bg shadow}      \@{bg background}@{ub}   --> Tracer des traits Noirs  @{bg shadow}      @{bg background} 
@{b}\@{bg fill}      \@{bg background}@{ub}     --> Tracer des traits à la Couleur de la Fenêtre  @{bg fill}      @{bg background} 
Plus il y a d'espaces, plus le trait est long. Normal ;-)

@endnode

@node "programme"
@next l'index
@prev texte
@toc main
@{" Recherche " SYSTEM "RUN <>NIL: SearchGuide Doc'-Amigaguide1.4"} <-- Active la recherche de mots clés


Amigaguide permet de déclencher, par l'intermédiaire d'un bouton, un programme externe tel que Viewtek.
Vous pouvez normalement déclencher n'importe quel programme, par l'intermédiaire de l'AmigaDos ou de l'ARexx. Pour des raisons pratiques, je ne vous montrerai que quelques exemples.

 @{u}Affichage d'une image:@{uu}

@{b}\@{" Voir " SYSTEM "c:vt chemind'accès/image"}@{ub}
Le bouton Voir est associée à l'image dont le chemin d'accès est à spécifier. Cette image sera affichée par VT qui se trouve lui dans le c. N'oubliez pas l'espace entre le programme, et le fichier à exécuter (vt ESPACE chemind'accès).

 @{u}Affichage d'une image à l'aide de Multiview:@{uu} AmigaOS 3.0 ou 3.1

@{b}\@{" Voir " LINK "work:Images/Mickey.GIF/MAIN"}@{ub}
Le bouton Voir est associée à l'image dont le chemin d'accès est à spécifier. Cette image sera affichée par Multiview à l'aide des datatypes. C'est le "/MAIN" qui fait appel à Multiview.
A noter que la procédure est la même pour l'écoute d'un son par Multiview.

 @{u}Ecoute d'un son:@{uu}

@{b}\@{" Ecouter " SYSTEM "chemind'accès/sound chemind'accès/son"}@{ub}
Le bouton Ecouter est associée au son, dont le chemin d'accès est à spécifier. Ce son sera lancé par la commande sound dont le chemin d'accès a été spécifié. N'oubliez pas l'espace entre le programme, et le fichier à exécuter (sound ESPACE chemind'accès).

 @{u}Ecoute d'un module:@{uu}

@{b}\@{" Musique " SYSTEM "C:OctamedPlayer Work:Mods/Jazz.mod"}@{ub}
Le bouton Musique est associée au module "Jazz.mod" dont le chemin d'accès est à spécifier. Ce module sera exécuté par "Octamedplayer" dont le chemin d'accès a été spécifié. N'oubliez pas l'espace entre le programme, et le fichier à exécuter.

 @{u}Exécuter un programme:@{uu}

@{b}\@{"Scala" SYSTEM "work:scalamm400/scalamm"}@{ub}
Le bouton "Scala" permet de lancer le programme ScalaMM, dont le chemin d'accès a été spécifié.

 @{u}Appel d'un autre guide:@{uu}

@{b}\@{"Nouveau Guide" link "Work:amigaguide/Nouveau Guide/main"}@{ub}
Indiquez le chemin exact où se trouve l'autre guide. N'oubliez pas de créer un autre lien sur l'autre guide si vous souhaitez revenir sur votre premier guide.

@endnode

@node "l'index"
@next utils
@prev programme
@toc main
@{" Recherche " SYSTEM "RUN <>NIL: SearchGuide Doc'-Amigaguide1.4"} <-- Active la recherche de mots clés


Un Index n'est ni plus ni moins qu'une simple page. 
Son utilisation permet d'accéder à une partie qui vous intéresse, en choisissant un simple mot. Regardez l'index de cette doc pour mieux comprendre.

@{u}Exemple de Page Principale:@{uu}
    \@ Database 
    \@ Author "vous"
    \@ $VER: votreguide 1.0 (01-01-2000)
    \@ index votreindex  --> Si vous oubliez cette commande dans la page principale, l'index ne sera pas activé.
    \@ wordwrap
    \@ NODE main --> Page principale du guide

    Listing
    Listing
    Listing

    \@ endnode   --> Fin de la page

Le début du listing de l'index devra être dans ce cas: @{b}\@ node votreindex@{ub}

@{u}Exemple de Page Index:@{uu}
    
    \@ node votreindex  --> Création de l'Index nommé "votreindex"
    \@ toc main  --> Active le bouton Contenu, et renvoie à la page principale.

    Listing
    Listing
    Listing

    \@ endnode

@endnode

@node "utils"
@prev l'index
@next contact
@toc main
@{" Recherche " SYSTEM "RUN <>NIL: SearchGuide Doc'-Amigaguide1.4"} <-- Active la recherche de mots clés


Il existe des utilitaires qui peuvent s'incorporer à Amigaguide, afin de le rendre plus attractif.

 @{b}@{u}SearchGuide:@{uu}@{ub}

Dans les plus intéressants, il faut noter la création de "@{b}SearchGuide@{ub}". Ce script Arexx a été écrit par Gérard Cornu. Il permet, quand il est incorporé dans un fichier Amigaguide, de lancer une recherche de mot dans le guide, par l'intermédiaire d'une fenêtre. La recherche ainsi faites, vous aurez une nouvelle fenêtre Amigaguide, avec toutes les pages où votre mot est écrit. A vous de choisir, alors, la page qui vous intéresse.
Vous trouverez cet utilitaire, et sa doc sur Aminet, et en plus il est Freeware.

 @{u}Mini-Exemple de création d'un bouton Search:@{uu}

@{b}\@{" Recherche " SYSTEM "RUN <>NIL: SearchGuide Votre.guide"}@{ub}
Vous noterez, que je m'en suis servi pour mon guide.



 @{b}@{u}AddSearchGuide 1.1:@{uu}@{ub}

Il existe un script Arexx écrit par @{b}Remco Van Hoof@{ub} qui complète "SearchGuide", et qui permet d'ajouter un bouton de Recherche dans n'importe quel guide. A condition d'avoir SearchGuide sous la main bien sûr!
Son utilisation se fait à partir du shell, et la syntaxe est la suivante:

@{b}rx AddSearchGuide.rexx FILE/K@{ub}  --> Où "FILE" est le nom de votre Guide. 
A noter que SearchGuide doit se trouver dans le même tiroir que le Guide.



 @{b}@{u}AGIndex_v1.04:@{uu}@{ub}

AGIndex est un outil Freeware, crée par @{b}Camiel Rouweler@{ub}, qui s'exécute du Shell, ou par l'intermédiaire de son interface sous Workbench.
Il permet de créer un Index sur un guide, même si celui-ci n'avait pas été prévu par son auteur. Le programme va chercher tous les boutons (Pages & Programmes) du guide, et réécris le guide avec un Index comportant tous ces nodes. 

 @{u}Exemple de la commande sous Shell:@{uu}

 @{b}agindex work:Fichiers-amigaguide/votre.guide Index.guide REF@{ub}  --> Où REF est la méthode d'indéxage. "Index.guide" sera le nouveau nom de votre guide. A noter qu'AGIndex réécris le guide dans son tiroir afin de ne pas modifier l'original.

@endnode

@node "contact"
@prev utils
@next merci
@toc main
@{" Recherche " SYSTEM "RUN <>NIL: SearchGuide Doc'-Amigaguide1.4"} <-- Active la recherche de mots clés


 @{u}Contact:@{uu}

@{b}  Olivier Ferrer
  9 Av René Delpech
  11500 Quillan
  Tel: 68.20.93.77@{ub}

@{fg shine}  E-Mail: amigazet@strascom.fr@{fg text}
@{b}  3615 Adream Bal Amigazette83@{ub}
@{fg shine}  3615 Rtel1 Bal Amigazette83@{fg text}

@{b}  Amigazette 83
  872 Chemin mon paradis
  83200  Toulon@{ub}

 {~._.~}      
  (_Y_)  
 ()~*~() 
 (_)-(_)     A Bientôt!

                 µµµµµµ                                  ____    __µ__          
               _ØØØØØØM                               _µØ@@@ØÞ _ÆÑM¶ØØr         
              æØØØØØØØ                                ØP   IØF/@´   ØØ´         
            _ÆØØØØØØØØ                               ÆØL__æØP    __ÆØ´          
           aØØØØPØØØØ@                              _ÆØÑÑØØ"    ¢ÑØ&            
          æØØØØ" ØØØØ@                             æØ°   ØØLµ,    ØØ            
        _ØØØØ@  JØØØØF             ,æç            JØ1   µØPÆØL  _ÆØ´            
       µØØØØF   JØØØØÞ             JÑ@            JØ@wµÆØ° ¶Ø@ææØ@              
     ¸ÆØØØØØØØØØØØØØØÞ  µµ_µµ__µµ  aµ _µµµµw _µµ_  ¬°°°¯    ¬"""                
    aØØØØØØØØØØØØØØØØ  JØP"0Ø@°0ØFJØFÆØ"¬ØF '¯¬Ø@           _  _                
   æØØØØK       ØØØØØ ,ØF _ØP  Ø@_Ø@ Ø&µÆ@ _ø*ØØ           J@ JØ                
 ,ÆØØØ@"        ØØØØ@ Ø@  ØØ  ÆØ Æ@ æØ°"  ÆØ_æØLø==ær_amm a@Þa@Þ ,mæ¸           
 ¯¯¯¯¯          ¯¯¯¯¯¬"  ¬"  ¬""¬""JØØØÑr °°"""" _/"µZ__Ø Ø  Æ _Æ__]F           
                                  Ø@__Æ@       _*"_qF""""Æ  á´ Ø""""            
                                   """        æQaæF¬@w*  &* &* ¶wæ"             

     
@endnode

@node "merci"
@prev contact
@toc main
@{" Recherche " SYSTEM "RUN <>NIL: SearchGuide Doc'-Amigaguide1.4"} <-- Active la recherche de mots clés


@{u}@{b}Remerciements  Aux   Meilleurs@{ub}@{uu}

Remerciements @{b}vifs@{ub} et @{b}sincères@{ub}, à l'Homme qui a vu l'Ours, et qui s'en souvient encore. 
Ainsi qu'à mon Testeur de doc --> @{u}Jack Inside 8^)@{uu}, et à @{u}Gérard Cornu@{uu} pour son "SearchGuide" de Folie....

@endnode

@node Index
@toc main
@{" Recherche " SYSTEM "RUN <>NIL: SearchGuide Doc'-Amigaguide1.4"} <-- Active la recherche de mots clés


@{" AddSearchGuide          " link "utils"}
@{" Afficher une image      " link "programme"}
@{" AGIndex                 " link "utils"}
@{" Appel d'un autre guide  " link "programme"}

@{" Bouton Aide             " link "commande"}
@{" Bouton Contenu          " link "commande"}
@{" Bouton Feuilleter<      " link "commande"}
@{" Bouton Feuilleter>      " link "commande"}
@{" Bouton Retour           " link "commande"}

@{" Création du guide       " link "création"}
@{" Créer une page          " link "pages"}

@{" Ecrire en blanc         " link "texte"}
@{" Ecrire en bleu          " link "texte"}
@{" Ecrire en gras          " link "texte"}
@{" Ecrire en italique      " link "texte"}
@{" Exécuter un programme   " link "programme"}

@{" Fin de page             " link "pages"}

@{" Identification du guide " link "création"}
@{" Index                   " link "l'index"}

@{" Lancer un son           " link "programme"}

@{" Script Arexx            " link "pages"}
@{" SearchGuide             " link "utils"}
@{" Souligner le texte      " link "texte"}

@{" Contact --> 8^)         " link "contact"}
@{" Merci                   " link "merci"}

@endnode

Fin de Doc