@DATABASE Leben.inc
@NODE "Leben"

Gibt es Leben auf der Erde?
************************************************
                       Copyright by Patrick Henz


Bericht des Beobachters "LL´ob´us", New York, 23.10.1994 
Planetenzeitrechnung

Dies ist der Abschlußbericht über die Lebensformen auf diesem
Planeten, genannt Erde. Er entscheidet darüber, ob die 
einheimischen Lebensformen den Reifegrad erlangt haben, um in 
die "Galaktische Familie" aufgenommen zu werden. 

Punkt 1 :Verantwortungsbewußtsein
----------------------------------
Die auf der Erde herrschende Rasse lebt vorzugsweise in großen 
Ballungsräume. Trotzdem ist zu beobachten, daß trotz der 
räumlichen Enge, ein Trend zum Egoismus besteht. Man scheint 
gegeneinander zu arbeiten, anstatt in der Familie. Dies ist 
wahrscheinlich biologisch bedingt, Überreste des Raubtieres 
und Einzelgängers, von welchem der Mensch, abstammt. So ist 
auch die Ausbeutung zu erlären, die diese Lebensform gegenüber 
ihrer Umwelt, untergeordnete Lebensformen und sogar gegen sich 
selbst an den Tag legt. Hierbei wird nur der kurzfristige Vorteil 
bedacht, zu einem langfristigen Denken ist diese Lebensform noch 
nicht fähig.

Punkt 2:Technisches Wissen
----------------------------
Wie bei allen Säugetieren, ist auch bei dem Mensch die Neugier 
stark ausgeprägt. Dies hat negative, aber auch positive Aspekte, 
so z.B. wurde in der gesamten kurzen menschlichen Geschichte 
die Wissensschaft vorangetrieben. Deshalb verfügt diese Rasse 
über erstaunliches Wissen im Bezug auf ihre zeitliche Präsens. 
Es ist zu erwarten, daß sie bald die technischen Voraussetzungen 
für eine erste Erkundung ihrer näheren Nachbarschaft, 
wahrscheinlich bis zu den Grenzen ihres Systems, hat.

Punkt 3: Politisches System
----------------------------
Erst seit wenigen Erdenjahren verfügt man hier über die 
Errungenschaft der Demokratie. Bis heute ist sie aber nur in 
wenigen Landabschnitten eingeführt worden. Dies liegt 
wahrscheinlisch an denen in Punkt 1 aufgeführten Gründen. Wie 
sie schon ersehen können fehlt es dem Planeten an einer 
geeinten Regierung. Es gibt zwar Anzeichen dafür. Aber 
dieser Ansatz ist praktisch noch ohne Macht, er hat jediglich 
das Recht, Verfügungen auszusprechen und kleinere Probleme 
zu regeln. Es ist aber zu beobachten, daß er hiermit schon 
überfordert ist.

Ich empfehle der "Galaktischen Familie" aus den oben 
genannten Gründen von einer Kontaktaufnahme mit dem Planeten 
Erde abzusehen. Trotzdem aber verfügt aber diese Rasse über 
einige Potentiale, man sollte daher die Beobachtung an 
Schlüsselpositionen fortsetzen.

                            Mit freundlichen Grüßen

       
                                LL´ob´us, 1.Beobachter, Erde
 
@ENDNODE
