@DATABASE Autoren.inc
@NODE Autoren

UFOs- Autorenverzeichnis


Alexander Carbin

@{"Auﬂerirdische5" SYSTEM "ppmore 13/Auﬂerirdische5"}


Sven Drieling

@{"Mann Leute!" SYSTEM "ppmore 14/MannLeute!"}


Florian Hansch

@{"Kornkreise" SYSTEM "ppmore 16/Kornkreise"}


Patrick Henz

@{"Leben auf der Erde" SYSTEM "ppmore 19/LebenaufderErde"}


Thomas Hollweck

@{"Auﬂerirdische  " SYSTEM "ppmore 12/Auﬂerirdische"}
@{"Anmerkungen    " SYSTEM "ppmore 14/Anmerkungen"}
@{"Kornkreise     " SYSTEM "ppmore 14/Kornkreise"}
@{"Sinn des Lebens" SYSTEM "ppmore 14/SinndesLebens"}


Andreas Kleinert

@{"Auﬂerirdische4       " SYSTEM "ppmore 13/Auﬂerirdische4"}
@{"Auﬂerirdische        " SYSTEM "ppmore 18/Auﬂerirdische"}
@{"UFOs, UFOs, UFOs     " SYSTEM "ppmore 18/UFOs,UFOs,UFOs"}
@{"Schon wieder UFOs    " SYSTEM "ppmore 20/SchonwiederUFOs"}
@{"UFOs - die Millionste" SYSTEM "ppmore 20/UFO-Million"}


Marvin

@{"Kornkreise     " SYSTEM "ppmore 15/Kornkreise"}
@{"Sinn des Lebens" SYSTEM "ppmore 15/SinndesLebens"}


Axel Melzener

@{"Auﬂerirdische1         " SYSTEM "ppmore 13/Auﬂerirdische1"}
@{"Auﬂerirdische - Kritik " SYSTEM "ppmore 14/Auﬂ.Kritik"}
@{"UFO-Guru               " SYSTEM "ppmore 14/UFO-Guru"}
@{"Immernoch Auﬂerirdische" SYSTEM "ppmore 15/Immernoch"}
@{"Phantastische Ph‰nome  " SYSTEM "ppmore 15/PhanPh‰n"}


Andreas Neumann

@{"Auﬂerirdische3         " SYSTEM "ppmore 13/Auﬂerirdische3"}
@{"Einsame Erde           " SYSTEM "ppmore 14/EinsameErde"}
@{"Auﬂerirdische Anmerkung" SYSTEM "ppmore 15/AuﬂerirdischeAnm."}
@{"Keine UFOs             " SYSTEM "ppmore 19/KeineUFOs"}
@{"Der Fall ET            " SYSTEM "ppmore 20/FallET"}


Solo

@{"Die Marsgesichter" SYSTEM "ppmore 13/FOM"}
@{"Auﬂerirdische1   " SYSTEM "ppmore 16/Auﬂerirdische1"}
@{"Auﬂerirdische2   " SYSTEM "ppmore 16/Auﬂerirdische2"}


Many Terzoh

@{"UFOs" SYSTEM "ppmore 15/UFOs"}


Guido Wegener

@{"Auﬂerirdische2" SYSTEM "ppmore 13/Auﬂerirdische2"}
@{"Auﬂerirdische " SYSTEM "ppmore 15/Auﬂerirdische}
@{"UFO-Kritik    " SYSTEM "ppmore 16/UFO-Kritik"}


Georg Windisch

@{"Leserreaktion" SYSTEM "ppmore 14/LeserReaktion"}


YGAR

@{"YGAR" SYSTEM "ppmore 13/YGAR"}


R¸diger Zuber

@{"Auﬂerirdische2" SYSTEM "ppmore 14/Auﬂerirdische2"}


unbekannt

@{"Auﬂerirdische1" SYSTEM "ppmore 14/Auﬂerirdische1"}
@{"Leserreaktion " SYSTEM "ppmore 15/Leserreaktion"}


@ENDNODE

  




