@DATABASE Fragebogen.inc
@NODE Fragebogen



UFO-Meldebogen
**************

1)Ort:________________________________________________
   
   Datum:________________________  Zeit:_______________


2) Wie lange wurde das UFO beobachtet? ________________

3) In welchen    90o            Position des UFOS
   Winkel stand  I  /45o                 N
   das UFO am    I /                NW \I / NO
   Himmel?       I/ ___0o               \I/ 
                                   W-----+-----O
                                        /I\
                                    SW / I \ SO
                                         S

   Skizzieren Sie hier das UFO:




















4) Die Erscheinungsform des UFOs

   Form und Größe:_________________________________________

   Geräusch:_______________________________________________

   Farbe:__________________________________________________

   Bewegungen:_____________________________________________

   Anzahl der beobachteten Objekte:________________________

   Helligkeit:_____________________________________________
   (im Vergleich mit der Venus, dem Mond, der Sonne, etc.)


5) Name und      __________________________________________
   Adresse eines
   eventuellen   __________________________________________
   Zeugen
                 __________________________________________


6) Wetterbedingungen (bitte ankreuzen)

   Wolken        Temperatur       Wind        Niederschläge
   ( ) klarer    () kalt         ()keiner  () trocken
       Himmel
    
   () vereinz.  ()kühl         () Brise   ()Nebel/
                                                  Dunst

   ()viele     ()warm         () gemäßigt() Regen

   () bedeckt   ()heiß         () stark   () Schnee

   Andere Besonderheiten:_________________________________

   _______________________________________________________
 
   _______________________________________________________

   _______________________________________________________

   _______________________________________________________

   
Quelle: UFOs - Rätselhafte Flugobjekte
        
@ENDNODE

