@DATABASE Gesamt.inc
@NODE Gesamt

UFOs- Gesamtverzeichnis

PowerBrei 12
Pro
@{"Auﬂerirdische" SYSTEM "ppmore 12/Auﬂerirdische"}


PowerBrei 13
Pro
@{"Auﬂerirdische1   " SYSTEM "ppmore 13/Auﬂerirdische1"}
@{"Auﬂerirdische4   " SYSTEM "ppmore 13/Auﬂerirdische4"}
@{"Die Marsgesichter" SYSTEM "ppmore 13/FOM"}

Kontra
@{"Auﬂerirdische2   " SYSTEM "ppmore 13/Auﬂerirdische2"}
@{"Auﬂerirdische3   " SYSTEM "ppmore 13/Auﬂerirdische3"}
@{"Auﬂerirdische5   " SYSTEM "ppmore 13/Auﬂerirdische5"}
@{"YGAR             " SYSTEM "ppmore 13/YGAR"}


PowerBrei 14
Pro
@{"Anmerkungen           " SYSTEM "ppmore 14/Anmerkungen"}
@{"Auﬂerirdische - Kritik" SYSTEM "ppmore 14/Auﬂ.Kritik"}
@{"Kornkreise            " SYSTEM "ppmore 14/Kornkreise"}
@{"Leserreaktion         " SYSTEM "ppmore 14/LeserReaktion"}
@{"Sinn des Lebens       " SYSTEM "ppmore 14/SinndesLebens"}

Kontra
@{"Auﬂerirdische1        " SYSTEM "ppmore 14/Auﬂerirdische1"}
@{"Auﬂerirdische2        " SYSTEM "ppmore 14/Auﬂerirdische2"}
@{"Einsame Erde          " SYSTEM "ppmore 14/EinsameErde"}
@{"Mann Leute!           " SYSTEM "ppmore 14/MannLeute!"}
@{"UFO-Guru              " SYSTEM "ppmore 14/UFO-Guru"}


PowerBrei 15
Pro
@{"Immernoch Auﬂerirdische" SYSTEM "ppmore 15/Immernoch"}
@{"Phantastische Ph‰nome  " SYSTEM "ppmore 15/PhanPh‰n"}
@{"UFOs                   " SYSTEM "ppmore 15/UFOs"}

Kontra
@{"Auﬂerirdische Anmerkung" SYSTEM "ppmore 15/AuﬂerirdischeAnm."}
@{"Auﬂerirdische          " SYSTEM "ppmore 15/Auﬂerirdische}
@{"Kornkreise             " SYSTEM "ppmore 15/Kornkreise"}
@{"Sinn des Lebens        " SYSTEM "ppmore 15/SinndesLebens"}
@{"Leserreaktion          " SYSTEM "ppmore 15/Leserreaktion"}


PowerBrei 16
Pro
@{"Auﬂerirdische1" SYSTEM "ppmore 16/Auﬂerirdische1"}
@{"Auﬂerirdische2" SYSTEM "ppmore 16/Auﬂerirdische2"}

Kontra
@{"Kornkreise    " SYSTEM "ppmore 16/Kornkreise"}
@{"UFO-Kritik    " SYSTEM "ppmore 16/UFO-Kritik"}


PowerBrei 18
Pro
@{"Auﬂerirdische   " SYSTEM "ppmore 18/Auﬂerirdische"}
@{"UFOs, UFOs, UFOs" SYSTEM "ppmore 18/UFOs,UFOs,UFOs"}


PowerBrei 19
Kontra
@{"Keine UFOs        " SYSTEM "ppmore 19/KeineUFOs"}

Story
@{"Leben auf der Erde" SYSTEM "ppmore 19/LebenaufderErde"}


PowerBrei 20
Pro
@{"Schon wieder UFOs    " SYSTEM "ppmore 20/SchonwiederUFOs"}
@{"Der Fall ET          " SYSTEM "ppmore 20/FallET"}

Kontra
@{"UFOs - die Millionste" SYSTEM "ppmore 20/UFO-Million"}


@ENDNODE

  



