@DATABASE Kommentar.inc
@NODE Kommentar


Autor: Starman


UFOs und Aliens

Eine der wichtigesten Streitpunkte zwischen Anhängern und Kritikern des 
UFO-Phänomens ist die einfache Tatsache, daß die Außerirdischen nicht einfach 
landen und ´Hallo!´ sagen. Für die einen der Beweis der Nichtexistenz, für die ande-
ren, die Bestätigung, daß sie uns nur als Freunde beobachten wollen. 

"Haaaaalllooooooooo!!!!!" Wer sind wir, daß wir uns einbilden, in eine total fremde
Lebensform hineinversetzten zu können. Die menschlichen Gesetzte der Logik müs-
sen nicht zwangsweise in dem Rest des Universums gelten. Die Frage warum sie, 
vorausgesetzt sie existieren, nicht landen ist daher schlicht nicht beantwortbar!

Wenn ich mir in der letzten Zeit UFO-Berichte im Fernsehen anschaue, sehe ich im-
mer Freaks, die mit gottesgleichen Wesen Sex gehabt haben wollen, die im Schlaf 
mit Aliens kommunizieren, die gar selbst Außerirdische sind oder andere die versu-
chen mit dem größten Sch.... UFO-Gläubige abzuzocken. Durch diese Berichterstat-
tung wird die Diskussion auch nicht versachlicht! 

Man sollte lieber solche Menschen zu Wort kommen lassen, die durch die 
UFO-Erfahrungen materielle, physische wie auch psychische Nachteile erfahren ha-
ben. Ich denke da z.B. an Hypnose (von seriösen Ärzten und Wissenschaftlern 
durchgeführt!).

Auch hat die NASA die UFO-Sichtungswelle in Belgien nie mit irdischen Phänome-
nen erklären können. Das viele Wissenschaftler an UFOs und Aliens glauben ist 
auch unbestreitbar.

Bei der Frage, wie Raumschiffe die großen Weiten des Alls überwinden können, ist 
man auch einen Schritt weiter gekommen. In der Schweiz hat eine Gruppe deut-
scher und italienischer Wissenschaftler zum ersten Mal Antimaterie geschaffen. Eine 
Explosion von Materie und Antimaterie wäre nicht nur Ideal für eine Superbombe, 
sondern auch für Raumschifftriebwerke (siehe Star Trek). Der amerikanische 
Wissenschafter S.Hawking hat nicht nur die Theorie bestätigt, daß die Zeit relativ 
ist, sondern geht noch weiter, indem er behauptet die Lichtgeschwindigkeit sei es 
ebenfalls. Von Weißen und Schwarzen Löchern, Wurmlöchern und Raum-
krümmungen ganz zu schweigen.
  

@ENDNODE

