@DATABASE PD.inc
@NODE PD


UFOS und Aliens in der Amigasoftware


Eine Gruppe von Wissenschaftler hat eine Formel geschaffen,
mit der man die Wahrscheilichkeit von außerirdischen Leben
ausrechnen kann. Sie besteht aus vielen Variablen, die man
vorher schätzen muß. Lies läßt natürlich Befürwortern und
Kritikern der Außerirdischen-Therorien jede Menge offene
Türen. Die Green-Bank-Formel befindet sich als Amiga-Basic-
Programm auf der ´Faces of Mars´-Disk 9. 
´Deep Sky´ ist eine astronomische Datenbank für Profis (FOM
175-177).
Im Internet existieren diverse Newsgroups zu Aliens und UFOs,
hierher stammt der UFO&Aliens-Guide. In Englisch erklärt er
alles zu den verschieden Rassen, ihre Herkunft, ihre
Beziehungen untereinander, ihre Intension gegenüber der
Erdbevölkerung, etc. (FOM 313)
Ein anderer UFO-Guide ist ´Aliens Ahead´ auf der FOM 320.
In Belgien gab es Ende der 80er Jahre eine UFO-Sichtungs-
Welle, die nie mit irdischen Mitteln erklärt worden konnte. Zu
den Augenzeugen zählten neben Zivilpersonen, militärischen
Radars auch Offiziere. Fotos und Informationen hierüber auf
den FOM-Disks 353 und 357.


@ENDNODE

