@DATABASE powerbrei.inc
@NODE powerbrei



Amiga-DiskMag POWER-BREI-Infofile


  Mag-Name ..... : Power-Brei
  Herausgeber .. : Stefan Kremer
  Zielgruppe ... : Alle, die sich für den Amiga interessieren, gerne gute
                   Stories lesen und denen die Power-Brei gefällt
  Themen ....... : News, FD-, Soft- & Hardwaretests, Kurse, Programmieren,
                   Stories, Tips&Tricks, DFÜ, Musik, Bücher, Film-TV-Video
                   und mehr
  Sprachen ..... : Hauptsächlich deutschsprachig, gewürtzt mit englischen
                   Beiträgen
  Umfang ....... : 2 Disketten seit Ausgabe #6
  Redaktion .... : Sven Drieling, Am Breithof 5, 27804 Berne,
                   Tel. (0 44 06) 53 12
  Bezugsquellen  : - Black&White, Burckhard Schmidt, Halmerweg 31,
                     28237 Bremen
                   - AmiNet
                   - Diverse Boxen
  WWW .......... : http://olis.north.de/~indy/Power-Brei-Magazin/Texte/Home.html3
  Preis ........ : 5.-DM inklusive zwei 3,5" Disks plus Porto&Verpackung
  Beschreibung . :

  Die  Power-Brei  ist  vor  5 Jahren entstanden, sie bietet alle zwei Monate
  Texte  in  hervorragender  Qualität, dazu kommen Musik-Module, Grafiken und
  das  eine  oder  andere  gute Programm, wobei der Inhalt des Magazins, ganz
  allein  von  EUCH  bestimmt  wird, insbesondere durch eure Beiträge für die
  Power-Brei in Form von Texten, Grafiken und Programmen.

  Die Power-Brei möchte:
   o Amiga-Fans die Möglichkeit bieten  sich unabhängig von kommerziellen Ma-
     gazinen, in einen von ihnen  selbst gemachten  Magazin,  über neue Soft-
     und Hardwareprodukte informieren zu können.

   o Praktische Hilfen in Form von Tips&Tricks,  Programmierkursen und  Work-
     shops zu Anwenderprogrammen bieten.

   o ProgrammierInnen die Möglichkeit bieten, ihre Programme ausführlich vor-
     stellen zu können.

   o Zu Diskussionen und Kontakten der LeserInnen untereinander anregen.

   o Neben Amiga-Themen z.B. noch über Musik, Bücher, Film-TV und vieles mehr
     informieren.

   o Außerdem  gibt es in  jeder  Power-Brei eine ganze Reihe ausgezeichneter
     und packender Stories.


  Tja, was soll man sonst noch sagen? Es lohnt einfach mal einen Blick in die
  Power-Brei  zu  werfen,  und  schreibt  doch  auch mal was, Du kannst damit
  selbst  bestimmen,  was  in  der  nächsten  - also auch Deiner - Power-Brei
  stehen wird.                                                            



@ENDNODE


