@DATABASE Religion.inc
@NODE Religion

Auﬂerirdische und Religionen

PowerBrei 12
Pro
@{"Auﬂerirdische" SYSTEM "ppmore 12/Auﬂerirdische"}


PowerBrei 13
Pro
@{"Auﬂerirdische1" SYSTEM "ppmore 13/Auﬂerirdische1"}


PowerBrei 14
Pro
@{"Sinn des Lebens" SYSTEM "ppmore 14/SinndesLebens"}

Kontra
@{"Auﬂerirdische2 " SYSTEM "ppmore 14/Auﬂerirdische2"}
@{"Mann Leute!    " SYSTEM "ppmore 14/MannLeute!"}
@{"UFO-Guru       " SYSTEM "ppmore 14/UFO-Guru"}


PowerBrei 15
Pro
@{"Immernoch Auﬂerirdische" SYSTEM "ppmore 15/Immernoch"}

Kontra
@{"Sinn des Lebens        " SYSTEM "ppmore 15/SinndesLebens"}
@{"Leserreaktion          " SYSTEM "ppmore 15/Leserreaktion"}


PowerBrei 16
Pro
@{"Auﬂerirdische1" SYSTEM "ppmore 16/Auﬂerirdische1"}

Kontra
@{"UFO-Kritik    " SYSTEM "ppmore 16/UFO-Kritik"}



@ENDNODE

  



