@DATABASE system.inc
@NODE system


Systemanforderungen


Der verwendete Bildanzeiger benötigt AGA, läuft also problemlos
auf CD32, A1200 und A4000. Bei anderen Amigas kann es zu 
Abstürzen kommen. Man kann aber den Viewer problemlos gegen
einen anderen austauschen. Dies macht man wie folgt:

1) Das Programm ´view´ hier im Hauptverzeichnis löschen.

2) Bevorzugten Viewer (z.B. ViewTek oder FastJPEG) in das 
Verzeichnis kopieren.

3) Bildanzeiger wieder in ´view´ umbenennen.

Jetzt sollte das Programm auch auf älteren Computern
funktionieren!



@ENDNODE

  



