@DataBase
@Node Main ModuleInformation
@TOC ModuleMain.guide/main
@Index Module.index/main
ShowModule v1.10 (c) 1992 $#%!
@{fg shine}now showing: "graphics.m"@{fg text}
NOTE: don't use this output in your code, use the module instead.

LIBRARY gfxbase                                             /* informal notation */
  BltBitMap(A0,D0,D1,A1,D2,D3,D4,D5,D6,D7,A2)               /* -30 (1E) */
  BltTemplate(A0,D0,D1,A1,D2,D3,D4,D5)                      /* -36 (24) */
  ClearEOL(A1)                                              /* -42 (2A) */
  ClearScreen(A1)                                           /* -48 (30) */
  TextLength(A1,A0,D0)                                      /* -54 (36) */
  Text(A1,A0,D0)                                            /* -60 (3C) */
  SetFont(A1,A0)                                            /* -66 (42) */
  OpenFont(A0)                                              /* -72 (48) */
  CloseFont(A1)                                             /* -78 (4E) */
  AskSoftStyle(A1)                                          /* -84 (54) */
  SetSoftStyle(A1,D0,D1)                                    /* -90 (5A) */
  AddBob(A0,A1)                                             /* -96 (60) */
  AddVSprite(A0,A1)                                         /* -102 (66) */
  DoCollision(A1)                                           /* -108 (6C) */
  DrawGList(A1,A0)                                          /* -114 (72) */
  InitGels(A0,A1,A2)                                        /* -120 (78) */
  InitMasks(A0)                                             /* -126 (7E) */
  RemIBob(A0,A1,A2)                                         /* -132 (84) */
  RemVSprite(A0)                                            /* -138 (8A) */
  SetCollision(D0,A0,A1)                                    /* -144 (90) */
  SortGList(A1)                                             /* -150 (96) */
  AddAnimOb(A0,A1,A2)                                       /* -156 (9C) */
  Animate(A0,A1)                                            /* -162 (A2) */
  GetGBuffers(A0,A1,D0)                                     /* -168 (A8) */
  InitGMasks(A0)                                            /* -174 (AE) */
  DrawEllipse(A1,D0,D1,D2,D3)                               /* -180 (B4) */
  AreaEllipse(A1,D0,D1,D2,D3)                               /* -186 (BA) */
  LoadRGB4(A0,A1,D0)                                        /* -192 (C0) */
  InitRastPort(A1)                                          /* -198 (C6) */
  InitVPort(A0)                                             /* -204 (CC) */
  MrgCop(A1)                                                /* -210 (D2) */
  MakeVPort(A0,A1)                                          /* -216 (D8) */
  LoadView(A1)                                              /* -222 (DE) */
  WaitBlit()                                                /* -228 (E4) */
  SetRast(A1,D0)                                            /* -234 (EA) */
  Move(A1,D0,D1)                                            /* -240 (F0) */
  Draw(A1,D0,D1)                                            /* -246 (F6) */
  AreaMove(A1,D0,D1)                                        /* -252 (FC) */
  AreaDraw(A1,D0,D1)                                        /* -258 (102) */
  AreaEnd(A1)                                               /* -264 (108) */
  WaitTOF()                                                 /* -270 (10E) */
  Qblit(A1)                                                 /* -276 (114) */
  InitArea(A0,A1,D0)                                        /* -282 (11A) */
  SetRGB4(A0,D0,D1,D2,D3)                                   /* -288 (120) */
  QbSBlit(A1)                                               /* -294 (126) */
  BltClear(A1,D0,D1)                                        /* -300 (12C) */
  RectFill(A1,D0,D1,D2,D3)                                  /* -306 (132) */
  BltPattern(A1,A0,D0,D1,D2,D3,D4)                          /* -312 (138) */
  ReadPixel(A1,D0,D1)                                       /* -318 (13E) */
  WritePixel(A1,D0,D1)                                      /* -324 (144) */
  Flood(A1,D2,D0,D1)                                        /* -330 (14A) */
  PolyDraw(A1,D0,A0)                                        /* -336 (150) */
  SetAPen(A1,D0)                                            /* -342 (156) */
  SetBPen(A1,D0)                                            /* -348 (15C) */
  SetDrMd(A1,D0)                                            /* -354 (162) */
  InitView(A1)                                              /* -360 (168) */
  Cbump(A1)                                                 /* -366 (16E) */
  Cmove(A1,D0,D1)                                           /* -372 (174) */
  Cwait(A1,D0,D1)                                           /* -378 (17A) */
  VbeamPos()                                                /* -384 (180) */
  InitBitMap(A0,D0,D1,D2)                                   /* -390 (186) */
  ScrollRaster(A1,D0,D1,D2,D3,D4,D5)                        /* -396 (18C) */
  WaitBOVP(A0)                                              /* -402 (192) */
  GetSprite(A0,D0)                                          /* -408 (198) */
  FreeSprite(D0)                                            /* -414 (19E) */
  ChangeSprite(A0,A1,A2)                                    /* -420 (1A4) */
  MoveSprite(A0,A1,D0,D1)                                   /* -426 (1AA) */
  LockLayerRom(A5)                                          /* -432 (1B0) */
  UnlockLayerRom(A5)                                        /* -438 (1B6) */
  SyncSBitMap(A0)                                           /* -444 (1BC) */
  CopySBitMap(A0)                                           /* -450 (1C2) */
  OwnBlitter()                                              /* -456 (1C8) */
  DisownBlitter()                                           /* -462 (1CE) */
  InitTmpRas(A0,A1,D0)                                      /* -468 (1D4) */
  AskFont(A1,A0)                                            /* -474 (1DA) */
  AddFont(A1)                                               /* -480 (1E0) */
  RemFont(A1)                                               /* -486 (1E6) */
  AllocRaster(D0,D1)                                        /* -492 (1EC) */
  FreeRaster(A0,D0,D1)                                      /* -498 (1F2) */
  AndRectRegion(A0,A1)                                      /* -504 (1F8) */
  OrRectRegion(A0,A1)                                       /* -510 (1FE) */
  NewRegion()                                               /* -516 (204) */
  ClearRectRegion(A0,A1)                                    /* -522 (20A) */
  ClearRegion(A0)                                           /* -528 (210) */
  DisposeRegion(A0)                                         /* -534 (216) */
  FreeVPortCopLists(A0)                                     /* -540 (21C) */
  FreeCopList(A0)                                           /* -546 (222) */
  ClipBlit(A0,D0,D1,A1,D2,D3,D4,D5,D6)                      /* -552 (228) */
  XorRectRegion(A0,A1)                                      /* -558 (22E) */
  FreeCprList(A0)                                           /* -564 (234) */
  GetColorMap(D0)                                           /* -570 (23A) */
  FreeColorMap(A0)                                          /* -576 (240) */
  GetRGB4(A0,D0)                                            /* -582 (246) */
  ScrollVPort(A0)                                           /* -588 (24C) */
  UcopperListInit(A0,D0)                                    /* -594 (252) */
  FreeGBuffers(A0,A1,D0)                                    /* -600 (258) */
  BltBitMapRastPort(A0,D0,D1,A1,D2,D3,D4,D5,D6)             /* -606 (25E) */
  OrRegionRegion(A0,A1)                                     /* -612 (264) */
  XorRegionRegion(A0,A1)                                    /* -618 (26A) */
  AndRegionRegion(A0,A1)                                    /* -624 (270) */
  SetRGB4CM(A0,D0,D1,D2,D3)                                 /* -630 (276) */
  BltMaskBitMapRastPort(A0,D0,D1,A1,D2,D3,D4,D5,D6,A2)      /* -636 (27C) */
  AttemptLockLayerRom(A5)                                   /* -654 (28E) */
  GfxNew(D0)                                                /* -660 (294) */
  GfxFree(A0)                                               /* -666 (29A) */
  GfxAssociate(A0,A1)                                       /* -672 (2A0) */
  BitMapScale(A0)                                           /* -678 (2A6) */
  ScalerDiv(D0,D1,D2)                                       /* -684 (2AC) */
  TextExtent(A1,A0,D0,A2)                                   /* -690 (2B2) */
  TextFit(A1,A0,D0,A2,A3,D1,D2,D3)                          /* -696 (2B8) */
  GfxLookUp(A0)                                             /* -702 (2BE) */
  VideoControl(A0,A1)                                       /* -708 (2C4) */
  OpenMonitor(A1,D0)                                        /* -714 (2CA) */
  CloseMonitor(A0)                                          /* -720 (2D0) */
  FindDisplayInfo(D0)                                       /* -726 (2D6) */
  NextDisplayInfo(D0)                                       /* -732 (2DC) */
  GetDisplayInfoData(A0,A1,D0,D1,D2)                        /* -756 (2F4) */
  FontExtent(A0,A1)                                         /* -762 (2FA) */
  ReadPixelLine8(A0,D0,D1,D2,A2,A1)                         /* -768 (300) */
  WritePixelLine8(A0,D0,D1,D2,A2,A1)                        /* -774 (306) */
  ReadPixelArray8(A0,D0,D1,D2,D3,A2,A1)                     /* -780 (30C) */
  WritePixelArray8(A0,D0,D1,D2,D3,A2,A1)                    /* -786 (312) */
  GetVPModeID(A0)                                           /* -792 (318) */
  ModeNotAvailable(D0)                                      /* -798 (31E) */
  WeighTAMatch(A0,A1,A2)                                    /* -804 (324) */
  EraseRect(A1,D0,D1,D2,D3)                                 /* -810 (32A) */
  ExtendFont(A0,A1)                                         /* -816 (330) */
  StripFont(A0)                                             /* -822 (336) */
  CalcIVG(A0,A1)                                            /* -828 (33C) */
  AttachPalExtra(A0,A1)                                     /* -834 (342) */
  ObtainBestPenA(A0,D1,D2,D3,A1)                            /* -840 (348) */
  SetRGB32(A0,D0,D1,D2,D3)                                  /* -852 (354) */
  GetAPen(A0)                                               /* -858 (35A) */
  GetBPen(A0)                                               /* -864 (360) */
  GetDrMd(A0)                                               /* -870 (366) */
  GetOutlinePen(A0)                                         /* -876 (36C) */
  LoadRGB32(A0,A1)                                          /* -882 (372) */
  SetChipRev(D0)                                            /* -888 (378) */
  SetABPenDrMd(A1,D0,D1,D2)                                 /* -894 (37E) */
  GetRGB32(A0,D0,D1,A1)                                     /* -900 (384) */
  AllocBitMap(D0,D1,D2,D3,A0)                               /* -918 (396) */
  FreeBitMap(A0)                                            /* -924 (39C) */
  GetExtSpriteA(A2,A1)                                      /* -930 (3A2) */
  CoerceMode(A0,D0,D1)                                      /* -936 (3A8) */
  ChangeVPBitMap(A0,A1,A2)                                  /* -942 (3AE) */
  ReleasePen(A0,D0)                                         /* -948 (3B4) */
  ObtainPen(A0,D0,D1,D2,D3,D4)                              /* -954 (3BA) */
  GetBitMapAttr(A0,D1)                                      /* -960 (3C0) */
  AllocDBufInfo(A0)                                         /* -966 (3C6) */
  FreeDBufInfo(A1)                                          /* -972 (3CC) */
  SetOutlinePen(A0,D0)                                      /* -978 (3D2) */
  SetWriteMask(A0,D0)                                       /* -984 (3D8) */
  SetMaxPen(A0,D0)                                          /* -990 (3DE) */
  SetRGB32CM(A0,D0,D1,D2,D3)                                /* -996 (3E4) */
  ScrollRasterBF(A1,D0,D1,D2,D3,D4,D5)                      /* -1002 (3EA) */
  FindColor(A3,D1,D2,D3,D4)                                 /* -1008 (3F0) */
  AllocSpriteDataA(A2,A1)                                   /* -1020 (3FC) */
  ChangeExtSpriteA(A0,A1,A2,A3)                             /* -1026 (402) */
  FreeSpriteData(A2)                                        /* -1032 (408) */
  SetRPAttrsA(A0,A1)                                        /* -1038 (40E) */
  GetRPAttrsA(A0,A1)                                        /* -1044 (414) */
  BestModeIDA(A0)                                           /* -1050 (41A) */
  WriteChunkyPixels(A0,D0,D1,D2,D3,A2,D4)                   /* -1056 (420) */
ENDLIBRARY
@endnode
