@DATABASE "index.msg"

@NODE MAIN "MovieShop Guide Index"
@PREV movieshop.guide/MAIN
@NEXT movieshop.guide/MAIN

  @{"  +  " LINK MSGI 2}@{"  -  " LINK MSGI 8}@{"  8  " LINK MSGI 10}@{"  <  " LINK MSGI 14}@{"  >  " LINK MSGI 18}
  @{"  A  " LINK MSGI 22}@{"  B  " LINK MSGI 77}@{"  C  " LINK MSGI 110}@{"  D  " LINK MSGI 115}@{"  E  " LINK MSGI 128}
  @{"  F  " LINK MSGI 152}@{"  G  " LINK MSGI 167}@{"  H  " LINK MSGI 182}@{"  I  " LINK MSGI 195}@{"  J  " LINK MSGI 206}
  @{"  K  " LINK MSGI 211}@{"  L  " LINK MSGI 226}@{"  M  " LINK MSGI 246}@{"  N  " LINK MSGI 265}@{"  O  " LINK MSGI 282}
  @{"  P  " LINK MSGI 290}@{"  Q  " LINK MSGI 317}@{"  R  " LINK MSGI 321}@{"  S  " LINK MSGI 331}@{"  T  " LINK MSGI 392}
  @{"  U  " LINK MSGI 403}@{"  V  " LINK MSGI 415}@{"  W  " LINK MSGI 443}@{"  XY " LINK MSGI 452}@{"  Z  " LINK MSGI 456}

@ENDNODE

@NODE MSGI "MovieShop Guide Index"
@PREV MSGI
@NEXT MSGI
@TOC MAIN


  +

  @{" + " LINK movieshop.guide/ZOOM_IN}				Schnittliste (Titelzeile)

  -

  @{" - " LINK movieshop.guide/ZOOM_OUT}				Schnittliste (Titelzeile)

  8

  @{" 8 Bit|16 Bit|A-Law|µ-Law " LINK movieshop.guide/AUDIOMODE}	Audio-Modus

  <

  @{" < " LINK movieshop.guide/ZOOM_MIN}				Schnittliste (Titelzeile)

  >

  @{" > " LINK movieshop.guide/ZOOM_MAX}				Schnittliste (Titelzeile)

  A

  @{" A " LINK movieshop.guide/CALCULATETIMELINE_AUDIO}				Schnittliste (Titelzeile)
  @{" Abbrechen " LINK movieshop.guide/W_CANCEL}			Einstellungen
  @{" Abspiel Freilauf " LINK movieshop.guide/FREERUNNING}
  @{" Abspielblockgröße " LINK movieshop.guide/AUDIOPLAYBURST}		Audio
  @{" Abspielblockgröße " LINK movieshop.guide/VIDEOPLAYBURST}		Video
  @{" Adresse " LINK movieshop.guide/ADDRESS}			MS MacroSystem Computer GmbH
  @{" AGC " LINK movieshop.guide/AGC}
  @{" Aktion " LINK movieshop.guide/MAC_ACTION}			Makros
  @{" Alle Löschen " LINK movieshop.guide/DELETETIMELINELOCATOR_ALL}		Locator
  @{" Alle löschen " LINK movieshop.guide/FREECLIP}		Zwischenablage
  @{" Alle " LINK movieshop.guide/SELECTTIMELINEENTRY_ALL}			Objecte einer Schnittliste selektieren
  @{" Anfang " LINK movieshop.guide/AUCUT_START}			Audioschnitt
  @{" Anfügen " LINK movieshop.guide/TIMELINEENTRYAUTOATTACH}
  @{" Anwendungszweck " LINK movieshop.guide/PURPOSE}
  @{" Anzeige " LINK movieshop.guide/MOA}			Sonstige Einstellungen
  @{" ARexx Kommandos " LINK movieshop.guide/AREXX}
  @{" Audio Einstellungen " LINK movieshop.guide/AUDIOOPTS}
  @{" Audio Export " LINK movieshop.guide/AUDIOEXPORTOPTS}		Import/Export Einstellungen
  @{" Audio Mischer " LINK movieshop.guide/AUDIOMIX}
  @{" Audio Überblendung " LINK movieshop.guide/AUDIOFADE}
  @{" Audio " LINK movieshop.guide/AUDIOOPTS}			Einstellungen
  @{" Audio " LINK movieshop.guide/CALCULATETIMELINE_AUDIO}			Schnittberechnung
  @{" Audio " LINK movieshop.guide/POA}			Projekt Einstellungen
  @{" Audio... " LINK movieshop.guide/REORGPARTITION_AUDIO}			Reorganisieren
  @{" Audiodaten Bearbeiten " LINK movieshop.guide/AUDIOEDIT}
  @{" Audiodaten importieren... " LINK movieshop.guide/IMPORTSAMPLE}
  @{" Audiodaten zur Szene abspielen " LINK movieshop.guide/AUTOPLAYSAMPLE}
  @{" Audiodaten zur Szene aufnehmen " LINK movieshop.guide/AUTORECORDSAMPLE}
  @{" Audiodaten " LINK movieshop.guide/SAMPLES}
  @{" Audioschnitt " LINK movieshop.guide/AUDIOCUT}
  @{" Audiosteuerung " LINK movieshop.guide/SAMPLECONTROL}
  @{" Auflösen " LINK movieshop.guide/UNGROUPSCENE}			Gruppe
  @{" Auflösung " LINK movieshop.guide/DECIMATION}			Video
  @{" Aufnahme Freilauf " LINK movieshop.guide/RECORDFREERUNNING}
  @{" Aufnahme " LINK movieshop.guide/RECORDSAMPLE}			Audio
  @{" Aufnahme " LINK movieshop.guide/RECORDSCENE}			Video (und Audio)
  @{" Aufnahmeblockgröße " LINK movieshop.guide/AUDIORECORDBURST}		Audio
  @{" Aufnahmeblockgröße " LINK movieshop.guide/VIDEORECORDBURST}		Video
  @{" Aufnahmelänge " LINK movieshop.guide/AUDIORECORDLENGTH}		Audio
  @{" Aufnahmelänge " LINK movieshop.guide/RECORDLENGTH}		Video (und Audio)
  @{" Aufteilen " LINK movieshop.guide/SPLITSCENE}
  @{" Ausgangsmodus " LINK movieshop.guide/OUTPUTVMODE}
  @{" Ausklingen Anschwellen " LINK movieshop.guide/AUDIOFADE_2}
  @{" Ausschneiden " LINK movieshop.guide/BLOCK_CUT}
  @{" Aussteuerung " LINK movieshop.guide/INPUTVOLUME}
  @{" Aussteuerungsanzeige " LINK movieshop.guide/AUDIOLEVEL}
  @{" Auswahl... " LINK movieshop.guide/MAC_SELECT}			Makros
  @{" automatisch Speichern " LINK movieshop.guide/AUTOSAVEENV}
  @{" Automatische Korrektur " LINK movieshop.guide/TIMELINEAUTOCORRECT}
  @{" automatisches Speichern " LINK movieshop.guide/AUTOSAVEPROJECT}
  @{" Aux1 " LINK movieshop.guide/MIXAUX1VOLUME}
  @{" Aux2 " LINK movieshop.guide/MIXAUX2VOLUME}

  B

  @{" B " LINK movieshop.guide/CALCULATETIMELINE_VIDEO_AUDIO}				Schnittliste (Titelzeile)
  @{" Bandpaß " LINK movieshop.guide/BANDPASS}
  @{" Bearbeiten " LINK movieshop.guide/AUDIOCUT}			Audio
  @{" Bearbeiten " LINK movieshop.guide/EDITMENU}			Menü
  @{" Bearbeiten " LINK movieshop.guide/EDIT}			Fenster
  @{" Bearbeiten " LINK movieshop.guide/TIMELINE}			Schnittliste
  @{" Bedienung " LINK movieshop.guide/TL_OPS_USAGE}			Operatoren
  @{" Befehl ausführen " LINK movieshop.guide/COMMAND}
  @{" Begrenzung " LINK movieshop.guide/TRANSFERLIMIT}
  @{" Benutzen " LINK movieshop.guide/TIMELINELOCATOR}			Locator
  @{" Benutzen " LINK movieshop.guide/W_USE}			Einstellungen
  @{" Benutzer " LINK movieshop.guide/USERMENU}
  @{" Benutzerdefiniert " LINK movieshop.guide/SCREENFONT_USER}		Screen Zeichensatz
  @{" Benutzerdefiniert " LINK movieshop.guide/SCREENTYPE_USER}		Screen Typ
  @{" Benutzerdefiniert " LINK movieshop.guide/SMALLFONT_USER}		Kleiner Zeichensatz
  @{" Benutzerdefiniert " LINK movieshop.guide/WINDOWFONT_USER}		Fenster Zeichensatz
  @{" Berechnung " LINK movieshop.guide/CALCULATETIMELINE}
  @{" Bereichswahl " LINK movieshop.guide/COLORKEY_UV}
  @{" Betriebsart " LINK movieshop.guide/OPERATINGMODE}
  @{" Bild Import " LINK movieshop.guide/S_IMPORTOPTS}			Import/Export Einstellungen
  @{" Bild löschen " LINK movieshop.guide/DELETEACTIVEFRAME}
  @{" Bild(er) importieren... " LINK movieshop.guide/IMPORTFRAME}
  @{" Bildbereich " LINK movieshop.guide/FRAMEPOSSIZE}
  @{" Bildformat " LINK movieshop.guide/EXP_FORMAT}
  @{" Bildgröße " LINK movieshop.guide/FRAMEPOSSIZE}
  @{" Block auf der Partition duplizieren " LINK movieshop.guide/DUPPARTBLOCK}
  @{" Block exportieren... " LINK movieshop.guide/EXPORTBLOCK}
  @{" Block markieren " LINK movieshop.guide/BLOCK_MARK}
  @{" Block " LINK movieshop.guide/EDIT_BLOCK}
  @{" Breite " LINK movieshop.guide/CORRECTIMPORTWIDTH}			Import (Falsche Größe bearbeiten)

  C

  @{" Color Keying " LINK movieshop.guide/COLORKEYINGWINDOW}
  @{" Coring " LINK movieshop.guide/CORING}

  D

  @{" Dateitypenliste " LINK movieshop.guide/AEXP_FILETYPES}		Audio Export
  @{" Dateitypenliste " LINK movieshop.guide/EXP_FILETYPES}		Video Export
  @{" Datenrate " LINK movieshop.guide/TRANSFERRATE}
  @{" DeInterlace " LINK movieshop.guide/EXPORTDEINTERLACE}
  @{" Die Schnittliste " LINK movieshop.guide/TIMELINEDESC}
  @{" Disk Font wählen... " LINK movieshop.guide/SCREENFONT_SELECT}		Screen Zeichensatz
  @{" Disk Font wählen... " LINK movieshop.guide/SMALLFONT_SELECT}		Kleiner Zeichensatz
  @{" Disk Font wählen... " LINK movieshop.guide/WINDOWFONT_SELECT}		Fenster Zeichensatz
  @{" Display Info " LINK movieshop.guide/DISPLAYINFO}
  @{" Dokumentationen " LINK OpList.msg/MAIN}

  E

  @{" E " LINK movieshop.guide/CALCULATETIMELINE_SINGLEFRAME}				Schnittliste (Titelzeile)
  @{" Effekten " LINK movieshop.guide/TL_OPS}
  @{" Effektmodul speichern als... " LINK movieshop.guide/SAVEOPAS}
  @{" Effektmodul speichern " LINK movieshop.guide/W_SAVEOPAS}
  @{" Effektmodule " LINK movieshop.guide/EFFECTS}		Fenster
  @{" Effektmodule " LINK OpList.msg/MAIN}
  @{" Effektmodule " LINK movieshop.guide/SETPATH_EFFECTS}		Pfad
  @{" Einfügen " LINK movieshop.guide/BLOCK_PASTE}
  @{" einfügen " LINK movieshop.guide/TIMELINEENTRYDESTMODE_INSERT}			Schnittlisten Zielmodus
  @{" Eingang, während des Abspielens " LINK movieshop.guide/INPUTMUTEONPLAY} automatische Stummschaltung
  @{" Eingang/Freilauf " LINK movieshop.guide/VOEF}		Video Einstellungen
  @{" Eingangsmodus " LINK movieshop.guide/INPUTVMODE}
  @{" Eingangswahl " LINK movieshop.guide/AUDIOINPUT}		Audio
  @{" Einstellungen " LINK movieshop.guide/SETTINGSMENU}
  @{" Einträge markieren " LINK movieshop.guide/SELECTTIMELINEENTRY}
  @{" Einzelbild Vorschau " LINK movieshop.guide/SINGLEFRAMEPREVIEW}
  @{" Einzelbild " LINK movieshop.guide/CALCULATETIMELINE_SINGLEFRAME}
  @{" Ende " LINK movieshop.guide/AUCUT_END}
  @{" Endung " LINK movieshop.guide/EXPORTEXTENSION}
  @{" Entfernen " LINK movieshop.guide/REMOVEMACRO}
  @{" ersetzen " LINK movieshop.guide/TIMELINEENTRYDESTMODE_REPLACE}

  F

  @{" Farbbalken " LINK movieshop.guide/COLORBAR}
  @{" Farbe " LINK movieshop.guide/CHROMINANCE}
  @{" Fenster " LINK movieshop.guide/ALLWINDOWS}
  @{" Fenster " LINK movieshop.guide/WINDOWSMENU}			Menü
  @{" Fenster-Zeichensatz " LINK movieshop.guide/WINDOWFONT}
  @{" Fensteranordnungen " LINK movieshop.guide/WINDOWS}
  @{" Fenstergröße " LINK movieshop.guide/PREVIEWWINDOWSIZE}
  @{" Fixieren " LINK movieshop.guide/LOCKTIMELINELOCATOR}			Locator
  @{" Fixieren " LINK movieshop.guide/LOCKTIMELINE}			Komplette Schnittliste
  @{" Fixierten Bereich markieren " LINK movieshop.guide/SHOWLOCKEDTIMELINE}
  @{" Freigeben " LINK movieshop.guide/UNLOCKPARTITION}
  @{" Funktionen zum Probehören " LINK movieshop.guide/AUCAT_TIME}

  G

  @{" Gadget " LINK movieshop.guide/ASSIGNGADGET}
  @{" Genlock-Modus " LINK movieshop.guide/COLORKEYING}
  @{" Geschützte Partitionen " LINK movieshop.guide/LOCKLIST}
  @{" Gewichtung " LINK movieshop.guide/WEIGHT}
  @{" Glätten " LINK movieshop.guide/VOS}
  @{" Glätten-H " LINK movieshop.guide/HSMOOTHING}
  @{" Glätten-V " LINK movieshop.guide/VSMOOTHING}
  @{" Grundlegende Betrachtungen " LINK movieshop.guide/TL_OPS_BASICS}
  @{" Gruppe auflösen " LINK movieshop.guide/CLIP_UNGROUPSCENE}
  @{" Gruppe erstellen " LINK movieshop.guide/GROUPSCENES}
  @{" Gruppe verbinden " LINK movieshop.guide/JOINCLIPGROUP}
  @{" Gruppe " LINK movieshop.guide/EDIT_GROUP}

  H

  @{" Halbbild " LINK movieshop.guide/SHOWFIELDMODE}
  @{" häufig " LINK movieshop.guide/SAFETYLEVEL_HIGH}
  @{" Hauptebene " LINK movieshop.guide/SC_ROOT}
  @{" Helligkeit " LINK movieshop.guide/BRIGHTNESS}
  @{" Hintergrundspur " LINK movieshop.guide/TIMELINEBACKTRACK}
  @{" Hinzufügen " LINK movieshop.guide/ADDTIMELINELOCATOR}
  @{" Höhe " LINK movieshop.guide/CORRECTIMPORTHEIGHT}
  @{" Horizontal " LINK movieshop.guide/HSMOOTHING}
  @{" HUE " LINK movieshop.guide/HUE}
  @{" Hüllkurve " LINK movieshop.guide/AUDIOEDIT}

  I

  @{" Iconify " LINK movieshop.guide/ICONIFY}
  @{" Icons Speichern " LINK movieshop.guide/SAVEICONS}
  @{" Import/Export Einstellungen " LINK movieshop.guide/IMPORTOPTS}
  @{" In (Anfang) " LINK movieshop.guide/AUCUT_START}			Audioschnitt
  @{" In " LINK movieshop.guide/SETTIMELINELOCATOR_IN}				Locator
  @{" in " LINK movieshop.guide/ZOMM_IN}				Zoom
  @{" Index " LINK movieshop.guide/INDEX}
  @{" Indexlinien " LINK movieshop.guide/INDEXLINES}

  J

  @{" Jogshuttle " LINK movieshop.guide/JOGSHUTTLE}
  @{" JPEG-Qualität " LINK movieshop.guide/JPEGQUALITY}

  K

  @{" Kanäle " LINK movieshop.guide/AUDIOCHANNELS}
  @{" kein Screen " LINK movieshop.guide/SELECTPUBSCREEN_DEFAULT}
  @{" keine " LINK movieshop.guide/SAFETYLEVEL_LOW}			Sicherheitsabfragen
  @{" Keine " LINK movieshop.guide/SELECTTIMELINEENTRY_NONE}			Schnittlisteneinträge deselektieren
  @{" Keinen " LINK movieshop.guide/SELECTTIMELINEENTRY_NONE}
  @{" Kleiner Zeichensatz " LINK movieshop.guide/SMALLFONT}
  @{" Klonen " LINK movieshop.guide/CLONESCENE}
  @{" Kommentar " LINK movieshop.guide/SAMPLENOTE}			Zum Ton
  @{" Kommentar " LINK movieshop.guide/SCENENOTE}			Zur Szene
  @{" Kontrast " LINK movieshop.guide/CONTRAST}
  @{" Kopieren " LINK movieshop.guide/BLOCK_COPY}			Block
  @{" kopieren " LINK movieshop.guide/TIMELINEENTRYSRCMODE_COPY}			Schnittlistenmodus

  L

  @{" Laden... " LINK movieshop.guide/LOADMACROS}			Makros
  @{" Laden... " LINK movieshop.guide/LOADSETTINGS_SELECT}			Einstellungen
  @{" Laden... " LINK movieshop.guide/LOADTIMELINE}			Schnittlisten
  @{" Länge " LINK movieshop.guide/A_LENGTH}			Der Szene
  @{" Länge " LINK movieshop.guide/SC_LENGTH}			Des Tons
  @{" Länge " LINK movieshop.guide/TIMELINEENTRYAUTOLENGTH}			Schnittlisten Einfügeautomatik
  @{" Lautstärke " LINK movieshop.guide/OUTPUTVOLUME}
  @{" Line " LINK movieshop.guide/MIXLINEVOLUME}
  @{" Line|Aux1|Mix|Mic " LINK movieshop.guide/AUDIOINPUT}
  @{" ListView-Formatierung " LINK movieshop.guide/LVFORMAT}
  @{" Locator " LINK movieshop.guide/LOCATOR}
  @{" Loopback " LINK movieshop.guide/LOOPBACKVOLUME}
  @{" Löschen " LINK movieshop.guide/BLOCK_DELETE}			Block
  @{" Löschen " LINK movieshop.guide/DELETEPREVIEW}			Vorschau
  @{" Löschen " LINK movieshop.guide/DELETESCENE}			Szene
  @{" Löschen " LINK movieshop.guide/DELETETIMELINELOCATOR}			Locator aus Liste
  @{" Löschen " LINK movieshop.guide/DELETETIMELINE}			Schnittliste

  M

  @{" Makro hinzufügen... " LINK movieshop.guide/ADDMACRO_MENU}
  @{" Makros " LINK movieshop.guide/MACROS}
  @{" Master-Szene erstellen " LINK movieshop.guide/MAKEMASTERSCENE}
  @{" Mathematik " LINK movieshop.guide/UPNMATH}
  @{" max " LINK movieshop.guide/ZOOM_MAX}				Zoom
  @{" Menü " LINK movieshop.guide/ASSIGNMENU}			Makros
  @{" Menüs " LINK movieshop.guide/MENUS}
  @{" Methode " LINK movieshop.guide/EXPORTMETHOD}			Export
  @{" Methode " LINK movieshop.guide/IMPORTMETHOD}			Import
  @{" min " LINK movieshop.guide/ZOOM_MIN}				Zoom
  @{" Mischer " LINK movieshop.guide/AUDIOMIX}
  @{" Mit Szenenliste tauschen " LINK movieshop.guide/SWAPSCENESCLIP}
  @{" Modus " LINK movieshop.guide/AEXP_MODE}			Audioexport
  @{" Modus " LINK movieshop.guide/COLORKEYING}			Color Keying
  @{" MovieShop beenden " LINK movieshop.guide/QUIT}
  @{" MovieShop Projektinformationen " LINK movieshop.guide/W_PROJECTINFO}

  N

  @{" Nach Ablage in der Schnittliste " LINK movieshop.guide/MUTENEWTIMELINESCENE} automatische Stummschaltung
  @{" Nachdigitalisieren... " LINK movieshop.guide/BATCHPROJECT}
  @{" Nächste Szene " LINK movieshop.guide/GOTOSCENE_NEXT}
  @{" Nächstes Sample " LINK movieshop.guide/GOTOSAMPLE_NEXT}
  @{" Neu " LINK movieshop.guide/ADDTIMELINELOCATOR}				Locator
  @{" Neu " LINK movieshop.guide/MAC_NEW}				Makros
  @{" Neu " LINK movieshop.guide/NEWPROJECT}				Projekt
  @{" Neu " LINK movieshop.guide/NEWSCENE}				Szene
  @{" Neu... " LINK movieshop.guide/T_NEWTIMELINE}			Schnittliste
  @{" Neue Schnittliste " LINK movieshop.guide/NEWTIMELINE}
  @{" Neuer Screen " LINK movieshop.guide/NEWSCREEN}
  @{" Neues Projekt " LINK movieshop.guide/W_NEWPROJECT}
  @{" Neues Sample generieren " LINK movieshop.guide/CLONESAMPLE}
  @{" normal " LINK movieshop.guide/TIMELINEENTRYDESTMODE_NORMAL}

  O

  @{" Objekt-Aufgreif Wartezeit " LINK movieshop.guide/MOVEDELAYTIME}
  @{" Öffnen... " LINK movieshop.guide/OPENPROJECT}
  @{" Out (Ende) " LINK movieshop.guide/AUCUT_END}			Audioschnitt
  @{" Out " LINK movieshop.guide/SETTIMELINELOCATOR_OUT}				Locator
  @{" out " LINK movieshop.guide/ZOOM_OUT}				Zoom

  P

  @{" Parent " LINK movieshop.guide/SC_PARENT}
  @{" Partition(en) freigeben... " LINK movieshop.guide/M_UNLOCKPARTITION}
  @{" Partition(en) reorganisieren " LINK movieshop.guide/REORGPARTITION}
  @{" Partition(en) schützen " LINK movieshop.guide/LOCKPARTITION}
  @{" Pause " LINK movieshop.guide/PAUSESAMPLE}			Audiosteuerung
  @{" Pause " LINK movieshop.guide/PAUSESCENE}			Szenensteuerung
  @{" Pause " LINK movieshop.guide/PAUSETIMELINE}			Schnittsteuerung
  @{" Pegel " LINK movieshop.guide/VOP}
  @{" Pfade " LINK movieshop.guide/MOP}
  @{" Position " LINK movieshop.guide/TIMELINEENTRYAUTOPOS}			Schnittlisten Einfügeautomatik
  @{" Position " LINK movieshop.guide/TIMELINEPOS}			Fenster
  @{" Positionierung " LINK movieshop.guide/GOTOFRAME}		Szenensteuerung
  @{" Positionierung " LINK movieshop.guide/GOTOTIMELINEFRAME}		Schnittsteuerung
  @{" Positionsanzeige " LINK movieshop.guide/SAMP_POS}		Audiosteuerung
  @{" Positionsanzeige " LINK movieshop.guide/SC_POS}		Szenensteuerung
  @{" Positionsanzeige " LINK movieshop.guide/TL_POS}		Schnittsteuerung
  @{" Positionsmarkierung " LINK movieshop.guide/POSMARKER}
  @{" Prioritäten " LINK movieshop.guide/ADV_PRIORITIES}
  @{" Projekt Einstellungen " LINK movieshop.guide/PROJECTOPTS}
  @{" Projekt " LINK movieshop.guide/PROJECTMENU}			Menü
  @{" Projektinformationen... " LINK movieshop.guide/PROJECTINFO}
  @{" Puffer " LINK movieshop.guide/PREVIEWBUFFER}			Vorschau
  @{" Puffergröße " LINK movieshop.guide/AUDIOBUFFER}			Audio
  @{" Puffergröße " LINK movieshop.guide/VIDEOBUFFER}			Video

  Q

  @{" Quellmodus " LINK movieshop.guide/TIMELINEENTRYSRCMODE}

  R

  @{" Recorder " LINK movieshop.guide/MACHINES}			Fenster
  @{" Recorder " LINK movieshop.guide/OPENWINDOW_R}			Menü
  @{" Recorderauswahl " LINK movieshop.guide/MCOPTSSEL}
  @{" Recordersteuerung " LINK movieshop.guide/MACHINECONTROL}
  @{" Referenz setzen " LINK movieshop.guide/SETREFFRAME}
  @{" Reorganisation " LINK movieshop.guide/REORGPARTITION}
  @{" Rückwärts einfügen " LINK movieshop.guide/BLOCK_PASTEREVERSE}

  S

  @{" S " LINK movieshop.guide/CALCULATETIMELINE_FAST}				Schnittliste (Titelzeile)
  @{" Sample exportieren... " LINK movieshop.guide/EXPORTSAMPLE}
  @{" Sample-Liste " LINK movieshop.guide/A_LIST}
  @{" Samplefrequenz " LINK movieshop.guide/SAMPLERATE}
  @{" Schleife " LINK movieshop.guide/LOOPPREVIEW}			Vorschau
  @{" Schleife " LINK movieshop.guide/LOOPSAMPLE}			Audiosteuerung
  @{" Schleife " LINK movieshop.guide/LOOPSCENE}			Szenensteuerung
  @{" Schleife " LINK movieshop.guide/LOOPTIMELINE}			Schnittsteuerung
  @{" Schließen " LINK movieshop.guide/CLOSEPROJECT}
  @{" Schnittliste überprüfen " LINK movieshop.guide/CHECKTIMELINE}
  @{" Schnittliste " LINK movieshop.guide/TIMELINEMENU}		Menü
  @{" Schnittliste " LINK movieshop.guide/TIMELINE}		Fenster
  @{" Schnittlisten Einstellungen " LINK movieshop.guide/TIMELINEOPTS}
  @{" Schnittlisten Positionierung " LINK movieshop.guide/TIMELINEPOS}
  @{" Schnittlisten " LINK movieshop.guide/TIMELINES}
  @{" Schnittsteuerung " LINK movieshop.guide/TIMELINECONTROL}
  @{" Screen Wechseln " LINK movieshop.guide/PUBSCREENLIST}
  @{" Screen-Typ wählen... " LINK movieshop.guide/SCREENTYPE_SELECT}
  @{" Screen-Typ " LINK movieshop.guide/SCREENTYPE}
  @{" Screen-Zeichensatz " LINK movieshop.guide/SCREENFONT}
  @{" selten " LINK movieshop.guide/SAFETYLEVEL_MEDIUM}			Sicherheitsabfragen
  @{" Sicherheitsabfragen " LINK movieshop.guide/SAFETYLEVEL}
  @{" Smooth Scrolling " LINK movieshop.guide/SMOOTHSCROLLING}
  @{" Sonstige Einstellungen " LINK movieshop.guide/MISCOPTS}
  @{" Speichern als... " LINK movieshop.guide/SAVEMACROS}		Macros
  @{" Speichern als... " LINK movieshop.guide/SAVEPROJECTAS}		Projekt
  @{" Speichern als... " LINK movieshop.guide/SAVESETTINGS_SELECT}		Einstellungen
  @{" Speichern als... " LINK movieshop.guide/SAVETIMELINEAS}		Schnittliste
  @{" Speichern " LINK movieshop.guide/SAVEPROJECT}			Projekt
  @{" Speichern " LINK movieshop.guide/SAVESETTINGS_FORCE_ENVARC}			Einstellungen
  @{" Stamps " LINK movieshop.guide/MOS}
  @{" standard " LINK movieshop.guide/SCREENFONT_DEFAULT}			Screen Zeichensatz
  @{" standard " LINK movieshop.guide/SCREENTYPE_DEFAULT}			Screen Typ
  @{" standard " LINK movieshop.guide/SMALLFONT_DEFAULT}			Kleiner Zeichensatz
  @{" standard " LINK movieshop.guide/WINDOWFONT_DEFAULT}			Fenster Zeichensatz
  @{" Standbild " LINK movieshop.guide/SHOWFRAMES}
  @{" Status " LINK movieshop.guide/STATUS}
  @{" Steuerung " LINK movieshop.guide/MACHINECONTROL}			Recorder
  @{" Steuerung " LINK movieshop.guide/SAMPLECONTROL}			Audio
  @{" Steuerung " LINK movieshop.guide/SCENECONTROL}			Szenen
  @{" Steuerung " LINK movieshop.guide/TIMELINECONTROL}			Schnittliste
  @{" Stopp " LINK movieshop.guide/STOPPREVIEW}			Vorschau
  @{" Stopp " LINK movieshop.guide/STOPSAMPLE}			Audiosteuerung
  @{" Stopp " LINK movieshop.guide/STOPSCENE}			Szenensteuerung
  @{" Stopp " LINK movieshop.guide/STOPTIMELINE}			Schnittsteuerung
  @{" SubCarrier " LINK movieshop.guide/SUBCARRIER}
  @{" Synchrones Sample " LINK movieshop.guide/POSTSCENESAMPLE}


  @{" Szene einlesen... " LINK movieshop.guide/LOADSCENE}
  @{" Szene speichern als... " LINK movieshop.guide/SAVESCENEAS}
  @{" Szenen " LINK movieshop.guide/EDIT_SCENES}			Bearbeiten
  @{" Szenen " LINK movieshop.guide/SCENES}			Fenster
  @{" Szeneninformation " LINK movieshop.guide/INFO}
  @{" Szenenliste drucken... " LINK movieshop.guide/PRINTSCENELIST}
  @{" Szenenliste in die Zwischenablage " LINK movieshop.guide/SCENESTOCLIP}
  @{" Szenenliste " LINK movieshop.guide/SC_LIST}
  @{" Szenensteuerung " LINK movieshop.guide/SCENECONTROL}

  T

  @{" Tastaturkürzel " LINK movieshop.guide/SHORTCUTS}
  @{" Taste " LINK movieshop.guide/ASSIGNKEY}			Makros
  @{" Temporäre Dateien " LINK movieshop.guide/SETPATH_TEMP}
  @{" ToolBox Einstellungen " LINK movieshop.guide/TOOLBOXOPTS}
  @{" ToolBox " LINK movieshop.guide/TOOLBOX}
  @{" Typ " LINK movieshop.guide/EXPORTPICTYPE}				Export
  @{" Typ " LINK movieshop.guide/IMPORTPICTYPE}				Import
  @{" Typ " LINK movieshop.guide/MAC_TYPE}				Makros

  U

  @{" Ü " LINK movieshop.guide/CHECKTIMELINE}				Schnittliste (Titelzeile)
  @{" Über MovieShop... " LINK movieshop.guide/ABOUT}
  @{" Überkreuz " LINK movieshop.guide/AUDIOFADE_1}
  @{" Überprüfung " LINK movieshop.guide/CHECKTIMELINE}
  @{" Übersicht " LINK movieshop.guide/MACHINES}			Recorder
  @{" Übersicht " LINK movieshop.guide/SAMPLES}			Audiodaten
  @{" Übersicht " LINK movieshop.guide/SCENES}			Szenen
  @{" Übersicht " LINK movieshop.guide/TIMELINES}			Schnittlisten
  @{" UPN " LINK movieshop.guide/NEWTIMELINE}

  V

  @{" V " LINK movieshop.guide/CALCULATETIMELINE_VIDEO}				Schnittliste (Titelzeile)
  @{" Verbinden " LINK movieshop.guide/JOINGROUP}			Gruppe
  @{" Verfügbare Operatorbeschreibungen " LINK OpList.msg/MAIN}
  @{" verschieben " LINK movieshop.guide/TIMELINEENTRYSRCMODE_MOVE}
  @{" Verschiedenes " LINK movieshop.guide/AOV}
  @{" Vertikal " LINK movieshop.guide/VSMOOTHING}
  @{" Verzeichnis erstellen " LINK movieshop.guide/EFFECTDRAWER}
  @{" Video Einstellungen " LINK movieshop.guide/VIDEOOPTS}
  @{" Video Export " LINK movieshop.guide/VIDEOEXPORTOPTS}
  @{" Video und Audio " LINK movieshop.guide/CALCULATETIMELINE_VIDEO_AUDIO}		Berechnen
  @{" Video und Audio... " LINK movieshop.guide/REORGPARTITION_VIDEO_AUDIO}		Reorganisation
  @{" Video... " LINK movieshop.guide/REORGPARTITION_VIDEO}			Reorganisation
  @{" Video/Audio Partition " LINK movieshop.guide/PARTITIONS}
  @{" Videonorm " LINK movieshop.guide/INPUTVMODE}
  @{" VNR " LINK movieshop.guide/VNR}
  @{" Voreinstellung " LINK movieshop.guide/W_DEFAULT}
  @{" Vorfilter " LINK movieshop.guide/PREFILTER}
  @{" Vorgabe Name " LINK movieshop.guide/DEFAULTNAME}
  @{" Vorherige Szene " LINK movieshop.guide/GOTOSCENE_PREV}
  @{" Vorheriges Sample " LINK movieshop.guide/GOTOSAMPLE_PREV}
  @{" Vorladegröße " LINK movieshop.guide/AUDIOPRELOAD}		Audio
  @{" Vorladegröße " LINK movieshop.guide/VIDEOPRELOAD}		Video
  @{" Vorschau " LINK movieshop.guide/PREVIEW}
  @{" Vorschaudatei " LINK movieshop.guide/SETPATH_PREVIEW}
  @{" VTR " LINK movieshop.guide/VTR}

  W

  @{" Weitere Einstellungen " LINK movieshop.guide/ADVOPTS}
  @{" Werkzeugleiste " LINK movieshop.guide/TOOLBAR}
  @{" Wiedergabe " LINK movieshop.guide/PLAYPREVIEW}			Vorschau
  @{" Wiedergabe " LINK movieshop.guide/PLAYSAMPLE}			Audiosteuerung
  @{" Wiedergabe " LINK movieshop.guide/PLAYSCENE}			Szenensteuerung
  @{" Wiedergabe " LINK movieshop.guide/PLAYTIMELINE}			Schnittsteuerung

  Y

  @{" YUV-Komponenten Modul Einstellungen " LINK movieshop.guide/YUVOPTS}

  Z

  @{" Zeichnen beim Verschieben " LINK movieshop.guide/DRAWONLINE}
  @{" Zeige am Szenenende " LINK movieshop.guide/MARKSCENEEND}
  @{" Zeige bei aktivierung der Szene " LINK movieshop.guide/SHOWFRAMEMODE}
  @{" Zeitlup/raffer " LINK movieshop.guide/QUICKMOTION}
  @{" Zielmodus " LINK movieshop.guide/TIMELINEENTRYDESTMODE}
  @{" Zoom " LINK movieshop.guide/ZOOM_DUMMY}
  @{" zu Selektierten " LINK movieshop.guide/TIMELINEENTRYAUTOALIGN}
  @{" Zweit-Zeichensatz " LINK movieshop.guide/SMALLFONT}
  @{" Zwischenablage in die Szenenliste " LINK movieshop.guide/CLIPTOSCENES}
  @{" Zwischenablage " LINK movieshop.guide/CLIP}

@endnode
