@DATABASE "OpList.msg"

@NODE MAIN "Verfügbare Operatorbeschreibungen"
@PREV timeline.msg/TL_OPS
@NEXT timeline.msg/TL_OPS
  @{" Alpha " LINK "MS_GUIDE:Ops/Alpha.msg/MAIN"}
  @{" Ausschneiden " LINK "MS_GUIDE:Ops/Ausschneiden.msg/MAIN"}
  @{" Farbbereichs-Begrenzung " LINK "MS_GUIDE:Ops/Farbbereichs-Begrenzung.msg/MAIN"}
  @{" Farbe zu Graustufen " LINK "MS_GUIDE:Ops/Farbe zu Graustufen.msg/MAIN"}
  @{" Farbtiefe " LINK "MS_GUIDE:Ops/Farbtiefe.msg/MAIN"}
  @{" Flip " LINK "MS_GUIDE:Ops/Flip.msg/MAIN"}
  @{" Hintergrund " LINK "MS_GUIDE:Ops/Hintergrund.msg/MAIN"}
  @{" Keine Veränderung " LINK "MS_GUIDE:Ops/Keine Veränderung.msg/MAIN"}
  @{" Maske " LINK "MS_GUIDE:Ops/Maske.msg/MAIN"}
  @{" Mosaik " LINK "MS_GUIDE:Ops/Mosaik.msg/MAIN"}
  @{" Negativ " LINK "MS_GUIDE:Ops/Negativ.msg/MAIN"}
  @{" Rahmen " LINK "MS_GUIDE:Ops/Rahmen.msg/MAIN"}
  @{" Rauschen " LINK "MS_GUIDE:Ops/Rauschen.msg/MAIN"}
  @{" Rausschieben " LINK "MS_GUIDE:Ops/Rausschieben.msg/MAIN"}
  @{" Relief " LINK "MS_GUIDE:Ops/Relief.msg/MAIN"}
  @{" Rotieren " LINK "MS_GUIDE:Ops/Rotieren.msg/MAIN"}
  @{" Schnelles Skalieren " LINK "MS_GUIDE:Ops/Schnelles Skalieren.msg/MAIN"}
  @{" Skalieren " LINK "MS_GUIDE:Ops/Skalieren.msg/MAIN"}
  @{" Spiegeln " LINK "MS_GUIDE:Ops/Spiegeln.msg/MAIN"}
  @{" Standbild " LINK "MS_GUIDE:Ops/Standbild.msg/MAIN"}
  @{" TimeCode " LINK "MS_GUIDE:Ops/TimeCode.msg/MAIN"}
  @{" Titel " LINK "MS_GUIDE:Ops/Titel.msg/MAIN"}
  @{" Trapez " LINK "MS_GUIDE:Ops/Trapez.msg/MAIN"}
  @{" Verzögern " LINK "MS_GUIDE:Ops/Verzögern.msg/MAIN"}
  @{" Wischblende " LINK "MS_GUIDE:Ops/Wischblende.msg/MAIN"}
  @{" Zusammenfügen " LINK "MS_GUIDE:Ops/Zusammenfügen.msg/MAIN"}
  @{" Überblendung " LINK "MS_GUIDE:Ops/Überblendung.msg/MAIN"}
@ENDNODE
