@database 00331ae8-0
@master Ram Disk:Amiga4ever/Amiga4ever.Ausg.1
@$VER: 2.0
@author "Rainer Thieke"
@(c) "Freeware"
@index Inhalt
@remark Created with Heddley v1.1 (c) Edd Dumbill 1994

@node "Main" "Titelpage"


         AAA   M   M  I GGGG  AAA
        A   A M M M M   G    A   A
        AAAAA M  M  M I G GG AAAAA
        A   A M  M  M I G  G A   A
        A   A M  M  M I GGGG A   A

 
             4   4
             4   4
             4   4  
             44444
                 4
                 4  
                 4  E V E R

      @{fg shine}@{bg fill}Ausgabe@{fg text}@{bg back}: @{fg shadow}1@{fg text} @{fg shine}(Mai/Juni 98)@{fg text}

  (zum abbrechen der Musik beide Maustasten gedrückt halten)

  @{" Musik " system " Run c/AMFMPLAY c/M"}

  @{" Musik II " system " Run c/AMFMPLAY c/M3"}

  @{"Credits" link "credits" 0}
  

  @{"Weiter..." link "Inhalt" 0}
@endnode

@node "credits" "Music-Magician"

 Musik1:

 Song: "@{fg shine}Interference@{fg text}"

 Size: @{fg shine}@{bg shadow}100000@{fg text}@{bg back} @{fg shadow}@{bg fill}(packed)@{fg text}@{bg back}

 Author: @{fg highlight}Virgill@{fg text}

 ---
 Musik2:

 Song: "@{fg shine}Recollection@{fg text}"

 Size: @{fg shine}@{bg shadow}60000@{fg text}@{bg back} @{fg shadow}@{bg fill}(packed)@{fg text}@{bg back}

 Author: @{fg highlight}X-Ceed@{fg text}


 @{"zurück..." link "Main" 0}
@endnode

@node "Inhalt" "Inhalt"
@toc "Inhalt"


                          ---------------
                          - I N H A L T -
                          ---------------
                            @{fg highlight}Amiga 4ever@{fg text}




 @{"---VORWORT---" link "Vorwort" 0}


 @{"° PERSONAL STUFF °" link "Personal" 0}


 @{"° USER-TALK °" link "TALK" 0}


 @{"° GAMES °" link "Games" 0}


 @{"° TOOLS °" link "Tools" 0}


 @{"° HARDWARE NEWS °" link "Hardware-news" 0}


 @{"° EXCLUSIV °" link "EXCLUSIV" 0}


 @{"° CD-32 CORNER °" link "CD32Corner" 0}


 @{"° CD-ROM NEWS °" link "CD-NEWS" 0}


 @{"° BILDER GALERIE °" link "BilderGalerie" 0}
@endnode

@node "Vorwort" "Vorwort"
@toc "Inhalt"



  @{fg highlight}@{bg shine}VORWORT...@{fg text}@{bg back}


 Tja,wo wir also bei meinem ersten (und hoffentlich auch nicht letzten) 
 Vorwort angekommen wären.
 Ich möchte es nutzen um Euch die einzelnen Rubriken ein wenig 
 vorzustellen.Für diejenigen von Euch sicherlich interessant,die 
 Amiga 4ever als Mitglied beitreten möchten.Zum einen wäre da dieses 
 Obligatorische Vorwort.Da heisst es für mich: Einmal tief luft holen 
 und drauflosschreiben was mir gerade so wichtiges durch die Birne 
 schwebt,ohne Rücksicht auf Verluste und ohne Beachtung der 
 Rechtschreibfäähläer.Die restlichen Rubriken sind für
 Mitglieder frei gestaltbar.

 Personal Stuff - Hier werden alle Mitglieder sowie alle Redakteure 
 die an der jeweiligen Ausgabe mitgefeilt haben aufgelistet.

 @{"User-Talk" link "TALK" 0} - Dies ist die Talk-Ecke für alle die mal richtig Dampf 
 ablassen wollen.Ich persönlich hoffe ja,das diese Rubrik demnächst 
 knallevoll wird,denn das verleit dem Mag einen persönlichen Touch.

 Games - Unverkennbar: Hier werden die Spiele getestet,Demoversionen 
 angeschnuppert und die aktuelle Top Five wird hier ebenfalls angegeben.
 Natürlich darf hier auch keine Cheat-Ecke fehlen...

 Tools - Etwas das ich bei vielen Mag`s vermisse: Eine Anwender-Ecke,wo
 Anwendersoftware getestet und geprüft wird.Hier wird es sie geben 
 und zwar jede Ausgabe.

 Hardware News - Dies ist die Rubrik für neue Hardware auf dem Markt.
 Wenn Berichte in diversen Computerzeitschriften erscheinen,wird hier
 darüber Berichtet.

 Exclusiv - Hierunter kann sich alles mögliche befinden.Berichte über 
 eine Computermesse,eine neue Amiga Zeitung...
 Grenzen sind hier fast keine gesetzt.Es sollte aber irgendwie mit Compis
 zusammenhängen.

 CD-32 Corner - Hier werden CD-32 Games auf Herz und Nieren geprüft.Das
 sind meist ältere (Da neue leider rar geworden sind) aber nicht
 desto trotz (richtig geschrieben???) interessant.

 CD-ROM News - Massendatenträger (like Aminet) werden hier
 getestet.

 @{"Bilder Galerie" link "BilderGalerie" 0} - Ist z.Z. noch leer,da hier die Pics von Mitgliedern
 hinein kommen.Wer also gute Grafische fähigkeiten sein eigen nennt,der
 sollte sich hier austoben können (siehe MACH MIT-DOKUMENT).

 Nun,wie gesagt ist das noch nicht die komplette Themenvielfalt dieses
 Mags.Wenn die Resonanz von Amiga 4ever einigermassen gut ist,werden noch
 zahlreiche Themen hinzu kommen.Aber von Euch hätte ich auch gerne 
 Vorschläge zur Erweiterung sowie Verbesserungsvorschläge.

 Das Vorwort wird nun geschlossen.

 Viel Spass mit der ersten Ausgabe von Amiga 4ever...

 (Beam me Up)               
   Rainer !


 @{"zurück..." link "Inhalt" 0}
@endnode

@node "Personal" "Personal Stuff"
@toc "Inhalt"


       ------------------
       - Personal Stuff -
       ------------------


   @{fg shadow}Mitglieder von AMIGA 4EVER@{fg text}:
  =============================

 ---


   @{fg highlight}Redakteure von AMIGA 4EVER@{fg text}:
  =============================


  Rainer Thieke



   @{fg fill}@{bg shadow}Erscheinungstermin der AMIGA 4EVER@{fg text}@{bg back}:
  =====================================

    Alle 2 Monate auf den Aminet CD`s




 @{"zurück..." link "Inhalt" 0}
@endnode

@node "TALK" "Talk"
@toc "Inhalt"



                       -----------
                       - T A L K -
                       -----------


 --- @{fg highlight}z.Z.@{fg text} @{fg highlight}@{bg fill}ein Vakuum@{fg text}@{bg back} ---




 @{"zurück..." link "Inhalt" 0}
@endnode

@node "Games" "Games"
@toc "Inhalt"




                        -------------
                        - G A M E S -
                        -------------


 @{"REVIEWS" link "REVIEWS" 0}


 @{"PREVIEWS" link "Previews" 0}


 @{"TOP FIVE" link "top FIVE" 0}


 @{"CHEAT-ECKE" link "Cheats" 0}


 @{"zurück..." link "Inhalt" 0}
@endnode

@node "Previews" "Previews"
@toc "Inhalt"


        Games-Previews
       ================


 @{"STREET RACER" link "Streetracer" 0} - Neuer Mario Kart-Klone

 @{"FINAL ODYSSEY" link "finalodyssey" 0} - Vulcan Strikes back



 @{"zurück..." link "Games" 0}
@endnode

@node "Streetracer" "Street Racer"
@toc "Previews"



 PREVIEW: @{fg highlight}STREET RACER@{fg text}

 Style: Arcarde-Autorennen

 System: ECS


 1994 wurde dieses Autorennen von Newline bereits angekündigt.Jetzt
 (nach sensationellen 4 Jahren) ist dieser Mario-Kart-Klone endlich
 im Handel erhältlich.Das Spiel kommt als Disketten- und als CD-Rom
 Version daher.Werfen wir einen blick zurück...

 1994 erschien Bump`n`Burn,das kein richtiges 3D beinhaltete,der
 SuperNES-Raserei aber ziemlich nahe kam.Mit hübscher Bonbon-Grafik
 sowie lustigen Charakteren wusste dieses Rennspiel damals zu
 begeistern,obwohl die 3D Engine dem Klassiker Lotus Turbo Challenge
 abgekupfert wurde.Eine 3D Engine die man bestenfalls als kein reales
 3D ansehen konnte.360 Grad Turns waren da einfach nicht möglich,der
 Blick vom Fahrer aus ging immer nach vorne.Und genau in dieselbe
 Kerbe schlägt Streetracer.
 In einer Zeit wo Spiele wie Xtreme Racing und Virtual Karting
 Standart sind ist es fraglich ob Streetracer dem Kunden das Geld
 aus der Tasche locken kann.Sobald mir die Vollversion vorliegt
 werde ich Newline auf die Finger schauen.

 Rainer


 @{"zurück..." link "Previews" 0}
@endnode

@node "finalodyssey" "Final Odyssey"
@toc "Previews"



 PREVIEW: @{fg highlight}FINAL ODYSSEY@{fg text}

 Style: Action-Adventure

 System: ECS


 Ein recht vielversprechendes Spiel kommt aus dem Hause Vulcan Software.
 Die Macher der Mini-Series (Timekeepers,Tiny Troops) sind jetzt
 auf die MEGA-SERIES umgestiegen...

 Final Odyssey kommt ausschliesslich auf CD-Rom daher,läuft aber auf
 jedem gängigen Amiga mit mindestens 2MB Ram.Das Game läuft aus der
 Isometrischen Sicht ab und ist eine Mischung aus Action-Adventure mit
 Strategie Elementen.Die ersten Screenshots sehen sehr vielversprechend
 aus.Eine sehr schöne und detaillierte Grafik das man fast nicht glauben
 mag es mit einem ECS-Spiel zu tun zu haben.

 Zum alljährlichen Feste bekommt der böse Minotaurus 6 Jungfrauen 
 zum Frass vorgeworfen und unser Held (Minos genannt) will dies auf
 keinen Fall zulassen.Also macht er sich auf dem Weg durch das
 Labyrinth des Minotauren um alle Jungfrauen vor dem Tode zu bewahren.

 Laut Vulcan soll das Spiel 5 Riesige Level mit über 500 Bildschirmen
 beinhalten,wobei Minos auf 5 verschiedene Waffen zurückgreifen kann.
 Das Spiel selbst soll in 7 verschiedenen Sprachen spielbar sein und
 dementsprechend verschiedene Sprachausgabe haben.Was an diesen 
 Statistiken nun wahres drann ist,war bis zu diesem Zeitpunkt noch nicht
 feststellbar da das Spiel den Weg in die Läden noch nicht gefunden
 hat.
 Lassen wir uns überraschen wieviel Fun die Reise in die Antike
 wirklich bringt.
 
 
 Rainer


 @{"zurück..." link "Previews" 0}
@endnode

@node "REVIEWS" "Reviews"
@toc "Games"


        Games-Reviews
       ================


 @{"XP8" link "xp8" 0} - Ballerlust oder Frust?

 @{"THE STRANGERS" link "Strangers" 0} - Blutales Beat em Up

 


 @{"zurück..." link "Games" 0}
@endnode

@node "xp8" "XP8"
@toc "REVIEWS"



 REVIEW: @{fg highlight}XP8@{fg text}

 Style: Shoot em Up

 System: ECS,1MB RAM

 Preis: ca.30 DM

 Empfohlen: Festplatte


 XP8 ist ein Horizontal scrollendes Shoot em Up von der Firma
 Efiggy Software.
 Das Game kommt auf 3 Disketten daher und ist Festplatten-Tauglich.
 Dies ist auch bitter nötig,da man die Diskettenwechselei schnell 
 leid wird.

 Nach dem Start wird die Geschichte des Spiels in einem kleinen
 Intro erzählt,das jedoch so ärmlich ist,das man es sich kein zweites 
 mal anschaut.Was ebenfalls negativ auffällt ist die Grauenvolle
 Titelmusik (und zugleich einzige Musik im Spiel) ! Was einen da aus
 den Aktivboxen dröhnt erreicht schnell die Schmerzgrenze.
 Bevor das Geballere losgeht noch schnell in den Optionsschirm.
 Hmmm...an Einstellungen mangelt es nicht.Nicht nur der
 Schwierigkeitsgrad lässt sich einstellen,sondern auch die Anzahl
 der zur Verfügung stehenden Schiffe,Die Bonus-Rate,Die Schwierigkeit der
 Missionen und und und...!
 Individuell eingestellt wird das Spiel dann gestartet.
 In jedem der insgesamt 5 Level gilt es eine bestimmte Mission zu 
 erfüllen (z.B.Radare ausschalten,Bodenkanonen zerstören).Wiviele
 Ziele man zerstören muss hängt von den anfänglich eingegebenen
 Missions-Schwierigkeitsgrad ab.

 Die Level an sich sind sehr Gross und beinhalten immer mehrere
 Endgegner,die leider leicht durchschaubar sind.An Extrawaffen
 mangelt es auch nicht,man kann sogar mehrere auf einmal haben und
 nach belieben die Waffen durchschalten.
 Die Steuerung ist einwandfrei und das Spiel (meistens) fair.
 Insachen Grafik kann man geteilter Meinung sein...Ein paar
 Farben hier und da hätten nicht schaden können,ausserdem ist
 der vorbeifliegende Hintergrund nicht so doll.Andererseits sind
 die Animationen der Schiffe eine wahre Augenweide.Raytracing heisst
 hier das Stichwort.Auch gibt es keinerlei Geschwindigkeitseinbussen,
 selbst bei vollem Gegnergetümmel.

 Nun ja...Eine Abschlusswertung fällt nicht leicht.Das Spiel macht
 Spass,ist aber auch keine langwierige Sache da nicht genug
 Abwechslung vorhanden ist.Shoot em Up Fans dagegen werden an
 XP8 ihre wahre Freude haben.

 Bewertung:
 ==========

 Grafik: Ausreichend

 Animation: Gut

 Sound: Mangelhaft

 Fun: Befriedigend



 Rainer



 @{"zurück..." link "REVIEWS" 0}
@endnode

@node "Strangers" "Strangers"
@toc "REVIEWS"



 REVIEW: @{fg highlight}THE STRANGERS@{fg text}

 Style: Beat em Up

 System: AGA,2MB RAM,CD-DRIVE,FESTPLATTE

 Preis: ca.60 DM

 Empfohlen: FastRAM


 In weit entfernter Zukunft regiert ein Mafiaboss über eine
 Kleinstadt.Dieser ist für die Gewalttaten seiner Schlägerbande 
 verantwortlich (die er regelmässig losschickt).Diesem Mafiaboss gilt
 es nun das Handwerk zu legen...

 Nach dem ersten Testspielen von The Strangers wird klar,das man es hier
 mit einem Beat em Up a la Double Dragon zu tun hat.Es gibt keinen 
 Solofight gegen einen Gegner (wie z.B. in Streetfighter üblich),sondern
 es tümmeln sich gleich ein halbes Dutzend verschiedene Schläger auf
 dem Bildschirm herum.
 Diese gilt es dann mit diversen Schlägen und Tritten ausser Gefecht zu
 setzen.Waffen findet man von Zeit zu  Zeit ebenfalls (Eisenstangen,
 Knüppel...),was das Metzeln um einiges erleichtert.
 Wo wir beim einzigen richtigen Manko in diesem Spiel angekommen wären...
 Der Schwierigkeitsgrad !
 Das Game ist alleine so gut wie unspielbar,dermassen schlagen die
 Mafia-Anhänger auf einem ein.Sehr schnell gesellt sich der Frust
 dem Spiel hinzu.Einigermassen anständig wird es erst wenn sich ein
 Freund in der Schlägerei mit einschaltet,denn wenigstens zu zweit
 ist die Sache halbwegs schaffbar.

 Grafisch macht Strangers einiges her.Von den hübsch gerenderten
 Hintergrundgrafiken bis zu den gnadenlos guten Animationen der
 Pixelmännchen (und weibchen).Auch wird hier mit dem roten Lebenssaft
 nicht gespart (der sogar am Boden liegen bleibt).
 Auch der Sound ist stimmungsvoll peppig und die Sound FX gehen von
 den typischen Schlaggeräuschen bis hin zu bösen Kommentaren die die
 Gegner desöfteren ablassen.
 Schade ist,das eine Padunterstützung fehlt,denn mit dem Joystick
 erfordert es einiges an Erarbeitungszeit.Mit etwas übung sind aber
 auch zahlreiche Special Moves möglich.

 Vulcan Software hat sich wahrlich Mühe gegeben,auch wenn es letzten 
 Endes zu einem Hit nicht ganz gereicht hat.Man sollte sich das
 Spiel auf alle Fälle mal anschauen und (wenn möglich) schon mal
 zum Telefon greifen um seinen Freund um Hilfe zu bitten.
 
 Bewertung:
 ==========

 Grafik: Gut

 Animation: Sehr Gut

 Sound: Befriedigend

 Fun: Befriedigend



 Rainer



 @{"zurück..." link "REVIEWS" 0}
@endnode

@node "Cheats" "Cheats"
@toc "Games"



                     ---------------
                     - C H E A T S -
                     ---------------

            Quelle: Amiga Joker,Amiga Games




 @{"ALIEN 3" link "alien3 cheat" 0}


 @{"BURNTIME" link "burntime cheat" 0}


 @{"DRAGONSTONE CD-32" link "DRAGONSTONECHEATS" 0}


 @{"MICROCOSM CD-32" link "microcosm cheat" 0}


 @{"SLAMTILT" link "slamtilt cheat" 0}


 @{"SOFTWARE MANAGER" link "softmanager cheat" 0}


 @{"SUPER STARDUST" link "SuperStardust chest" 0}


 @{"WENDETTA 2175" link "Wendetta" 0}


 @{"XP8" link "xp8 cheat" 0}



 @{"zurück..." link "Games" 0}
@endnode

@node "alien3 cheat" "Alien 3"
@toc "Cheats"

  Cheat zum Actiongame
        Alien 3


 Wenn man im Optionsbildschirm "Hard"
 auswählt und sechs "Credits" nimmt
 braucht man einfach nur die Leertaste + N
 zu drücken um in das nächste Level zu
 gelangen !


 Rainer



 @{"zurück..." link "Cheats" 0}
@endnode

@node "burntime cheat" "Burntime"
@toc "Cheats"

 TIP ZU BURNTIME

 Wenn einem die Mutanten und die Hunde wiedereinmal zunahekommen
 kann man diesem "Problem" auch unblutig Abhilfe schaffen! Klickt doch
 einen Punkt irgendwo auf der Spielfläche an, während das Männlein
 lostingelt sollte man seinen Mauszeiger einfach auf einen Störenfried
 fahren, wichtig ist hierbei daß Reden eingestellt sein muß und man nicht
 aufs Mausohr drückt. Wenn man sich an den oben geschilderten Weg hält,
 bewegt sich unser Spieler Sprite vom Gegner weg, der solange man mit dem
 Mauszeiger auf ihn zeigt stehenbleibt! Das klappt aber auch nur auf eine
 bestimmte Entfernung!

 Rainer



 @{"zurück..." link "Cheats" 0}
@endnode

@node "microcosm cheat" "Microcosm"
@toc "Cheats"

 Hier ein Cheat für diejenigen, die im CD³²-Game Microcosm schon immer 
 einmal unsterblich sein wollten:
 Sobald ihr im Spiel seit, geht ihr auf Pause, dann betätigt ihr
 irgendwelche Buttons des'Joypads. Wie Ihr bemerken werdet,
 ertönen verschiedene Klänge bei jedem Knopfdruck. Nun müßt ihr die
 Knöpfe in der Reihenfolge betätigen, daß nur hohe Töne erklingen.
 Nach einer Weile kommt dann ein Bonus-Sound und Ihr könnt wieder
 zurück in das Spiel. Ihr seit nun Unsterblich.
 Der Preis für die Unsterblichkeit sind aber die genialen Animationen
 des Spieles, die als Strafe nur noch in Schwarz-Weiss zu bestauenen
 sind!!!!

 Rainer



 @{"zurück..." link "Cheats" 0}
@endnode

@node "slamtilt cheat" "Slamtilt"
@toc "Cheats"
 
           SLAMTILT !

  Die Mogelwörter werden wie gewohnt zwischen den
  Spielen eingegeben.

  ARCADE ACTION -startet den Videomode des jeweiligen
                 Flippers.
  LONGPLAY      -5 Bälle.
  RADIOACTIVE   -andere Farben.
  SMILE         -grinsender Ball
  STONED        -chaotiches Ballverhalten
  WIPEOUT       -löscht die Highscores des Tables
 
  Und da sind noch ein paar versteckte Meldungen:
  Bleistiftsweise:  BARRY, CHEAT, COW, DANIEL, IAIN,
                    KLAUS, KOTTEN, LIQUID, STEWART
                    und WHIPLASH.


 Rainer



 @{"zurück..." link "Cheats" 0}
@endnode

@node "softmanager cheat" "Software Manager"
@toc "Cheats"

 Software Manager

 Hier ein "Trick" um sich Angestellte zu angeln:
 Jeder weiß, daß man sich Grafiker, Musiker und Coder erst noch in
 einem Gespräch "verdienen" muß, was anfangs gar nicht so leicht ist.
 Hier der ultimative Tip:

 1.: Begrüßung
 2.: positives Lob
 3.: negatives Lob
 4.: negativer smalltalk
 5.: positiver smalltalk

 Jetzt richtet sich alles nach der Stimmung der Person:
 Mittelmäßig heißt mittleres Gehalt, sauer heißt höchstes Gehalt!!

 Rainer



 @{"zurück..." link "Cheats" 0}
@endnode

@node "SuperStardust chest" "Stardust AGA"
@toc "Cheats"

 SUPER STARDUST

 Um bei Super Stardust im Rennen zu
 bleiben solltest Du folgendes
 Paßwort eingeben um Deine
 Feuerkraft zu erhöhen:ZZZZZZZZZZZZZ
 Dazu erhältst du zusätzlich noch
 20 Leben.


 Rainer



 @{"zurück..." link "Cheats" 0}
@endnode

@node "Wendetta" "Wendetta 2175"
@toc "Cheats"

 Wendetta Codes:


 LFKMZGU       GIJMXGT

 KIJIZFQ       UMKHHTR

 YGJYYFR       SRJHJUW
 

 Rainer




 @{"zurück..." link "Cheats" 0}
@endnode

@node "xp8 cheat" "XP8"
@toc "Cheats"


 XP8 Levelcodes:


 Mission     Code
 =======     ====

    2        112048210a24
   
    3        95205a214b3b

    4        120a4a01032a

    5        968257014030


 Rainer




 @{"zurück..." link "Cheats" 0}
@endnode

@node "top FIVE" "Top Five CFS"
@toc "Games"


                        ------------
                        - TOP FIVE -
                        ------------

                    @{fg fill}@{bg shadow}Spiele Verkaufcharts@{fg text}@{bg back}
                        @{fg shadow}@{bg shine}Monat:  Mai@{fg text}@{bg back}
                        @{fg highlight}Quelle: CFS@{fg text} 


 ( 1 )   MYST


 ( 2 )   TRAPPED II


 ( 3 )   PINBALL BRAIN DAMAGE


 ( 4 )   UROPA II


 ( 5 )   SLAMTILT



 @{"zurück..." link "Games" 0}
@endnode

@node "Tools" "Tools"
@toc "Inhalt"




                        -------------
                        - T O O L S -
                        -------------


 @{"PREVIEWS" link "TOOLS PREVIEWS" 0}


 @{"REVIEWS" link "Tools reviews" 0}



 @{"zurück..." link "Inhalt" 0}
@endnode

@node "Tools reviews" "Reviews"
@toc "Tools"


        Tools-Reviews
       ================


 @{"SIEGFRIED TRANSLATE" link "siegfried" 0} - Umfangreiches Lexikon ?


 @{"PICTURE MANAGER 5" link "PICTURE MANAGER5" 0} - Die Bilderverwaltung



 @{"zurück..." link "Tools" 0}
@endnode

@node "TOOLS PREVIEWS" "Previews"
@toc "Tools"


        Tools-Previews
       ================


 @{"CYGNUSED 4" link "Cygnused4" 0} - Der Klassiker in neuer Version

 


 @{"zurück..." link "Tools" 0}
@endnode

@node "siegfried" "Siegfried Translate"
@toc "Tools reviews"



 REVIEW: @{fg highlight}SIEGFRIED TRANSLATE@{fg text}

 Style: FREMDSPRACHEN ÜBERSETZER

 System: ECS,1MB RAM,AB OS 2.04,FESTPLATTE

 Empfohlen:  Arexx-kenntnisse

 Preis: ca.60 DM


 Bisher versorgte Siegfried Soft uns mit Qualitativ Hochwertiger
 Anwendersoftware.Das Tolle Kopierprogramm Siegfried-Copy und der
 gute Virenkiller Siegfried Anti-Virus gehörten dazu.

 Siegfried Translate ist ein Englisch=Deutsch/Deutsch=Englisch
 Übersetzungsprogramm.
 Die 3 Disketten im soliden Umschlag lassen zuerst etwas Misstrauen
 aufkommen.Ein komplettes Englisch-Lexikon auf mageren drei 
 Scheibchen ?
 Nach der HD-Installation aber ein aufatmen.ST hatte sich dort auf 
 satte 11MB ausgedehnt.

 ST umfasst über 65000 Englische Begriffe von Hause aus.Die sind 
 natürlich nach Belieben erweiterbar,aber etwas dermassen Komplexes 
 sucht man im PD-Sektor vergeblich.
 Die wirklichen Stärken von dem Translator liegen aber bei
 der Benutzerführung,die einfach Kinderleicht ist.Sämtliche Fenster
 die ST für sich beansprucht lassen sich vergrössern/verkleinern 
 und verschieben,so das man sich selbst Ordnung verschaffen kann.
 Ein weiterer Pluspunkt ist das verwenden von ARexxkommandos,das
 das Programm vollstens unterstützt.
 Ein rundum gelungenes "Nachschlagewerk" also.Der einzige Manko der
 mir auffiel war,das komplette Englische Texte immer noch
 schwierigkeiten beim übersetzen bereiten.Hier sollte Siegfried
 Soft noch mal drann arbeiten.

 Positiv:  Viele Begriffe,leichte Handhabung,Arexx-unterstützung

 Negativ:  schlecht für`s Übersetzen kompletter Texte

 Bewertung: GUT
 ==========

 Rainer



 @{"zurück..." link "Tools reviews" 0}
@endnode

@node "PICTURE MANAGER5" "Picture Manager V"
@toc "Tools reviews"



 REVIEW: @{fg highlight}PICTURE MANAGER 5@{fg text}

 Style: BILDER-VERWALTUNG

 System: ECS,4MB RAM,AB OS 2.1,FESTPLATTE

 Empfohlen: AGA,CD-DRIVE,6MB+MEHR,68030 PROZESSOR

 Preis: ca.120 DM


 Wer schon immer einmal seine Pictures ordentlich Kartalogisieren
 wollte,dem wird nun von IrseeSoft ein neues Programm
 angeboten.Der Picture Manager 5,über dessen Vorgänger ich leider
 nichts berichten kann (da kein Testmuster vorliegt).Somit kann
 ich auch nicht auf Verbesserungen eingehen (die der 5.P-Manager
 sicherlich besitzt).

 Das Katalogisieren gestaltet sich recht einfach.Schnell hat man 
 hier die Grundelemente begriffen um seine Bilder einzuladen und zu
 sortieren.Man kann jedoch auch tiefer in die Materie eingreifen und
 mit PM5 seine Bilder auch gleichzeitig bearbeiten.
 Das Programm unterstützt dabei zahlreiche Grafikformate (über 40...)
 und selbst LHA-gepackte Grafiken werden ohne Probleme gelesen.
 Apropo Grafik:ECS,AGA sowie einige Grafikkarten werden unterstützt
 (Cybergraphics,Picasso...usw) womit dieses Programm wohl jedem User
 zu empfehlen währe.
 PowerPC heisst hier das Stichwort,denn das wird laut Anleitung
 ebenfalls unterstützt.Das ergibt sicher eine atemberaubende
 Aufbau-Geschwindigkeit,denn die ist auf einem Standart 1200er
 einfach zu langsam.Erst ab einem 68030er wirds erträglich.
 
 Der Picture Manager 5 ist einfach grandios (sofern die Computer-
 Referenzen stimmen).Es ist nicht nur nützlich um einen guten 
 Überblick über seine (Bilder-)Datenmasse zu bekommen...nein...es
 macht auch tierischen Spass sich sein eigenes Photoalbum
 aufzubauen.


 Positiv:  Handhabung,viele Grafikformate werden unterstützt

 Negativ:  erst ab 68030 annehmbare Geschwindigkeit

 Bewertung: SEHR GUT
 ==========

 Rainer



 @{"zurück..." link "Tools reviews" 0}
@endnode

@node "Hardware-news" "Hardware"
@toc "Inhalt"



                -----------------------------
                - H A R D W A R E   N E W S -
                -----------------------------



 @{"E/BOX" link "E-Box" 0} - Der ultimative Towerumbau für den A1200 !!!



 @{"KLEIN ABER FEIN" link "Modem" 0} - Neues Modem der Firma Max !!!



 @{"BETRIEBSSYSTEM" link "os3.5" 0} - Kein Gerücht !!! Entwicklung von 
                  OS 3.5 schreitet voran !!!




 @{"zurück..." link "Inhalt" 0}
@endnode

@node "Modem" "Modem-News"
@toc "Hardware-news"



                    -------------
                    - M O D E M -
                    -------------


 Ein neues Modem kommt aus dem Hause "Max Computersysteme".
 Für 299 DM bekommt der User ein kleines kompaktes Modem,das
 an dem PCMCIA-Port des A1200 angeschlossen wird.Es erreicht
 eine Datenübertragungsrate von 33.600 bps und verfügt über
 einen sogenannten FIFO-Speicher mit dem die Übertragung von Computer 
 zu Modem Superschnell vonstatten geht ( Rate: 115.200 bps ).
 Die Geschwindigkeit des Faxens liegt bei 14.400 bps.
 
 Dazu bekommt der Käufer noch Treibersoftware,ein Terminalprogramm,
 Anschlusskabel sowie ein Handbuch.
 Das Modem benötigt keinerlei extra Stromresourcen,da es den benötigten
 Saft
 direkt vom Amiga-Netzteil schluckt.

 Meiner Meinung nach ein anständiges Preis/Leistungs-Verhältniss.

 Max Computersysteme Tel.06164/912151


 Rainer



 @{"zurück..." link "Hardware-news" 0}
@endnode

@node "E-Box" "E-Box"
@toc "Hardware-news"


               --------------------
               - TOWERUMBAU E/BOX -
               --------------------

 Irgendwann ist der 1200er insachen interne Erweiterungen ausgereizt.
 Eine Turbokarte sowie eine Festplatte nimmt das Tastaturgehäuse
 gereade mal soeben noch auf,aber das wars dann auch.
 Ein Towergehäuse muss also herhalten,doch sind die meisten "Türme"
 zu teuer und bieten zu dem auch nicht genügend Platz für Peripherie.
 Eine gute Alternative wäre da die E/Box vom Conny Figge Schnellversand,
 die für einen Preis von 360 DM eine Menge zu bieten hat.
 Leider ist die Anleitung nur auf Polnisch,aber wer auch nur ein wenig
 von seinen Amiga versteht,der wird keine Probleme beim Umbau haben
 (selbst ohne Anleitung).Hier ein paar positive Daten zur E/Box:
 
 - Towergehäuse aus Metall und optisch ansprechend
 - 200 Watt Netzteil
 - Adapter für PC-Tastaturen (auch mit mit Windows-Tasten)
 - Eine PC-Tastatur wird mitgeliefert
 - Diverse Kabel,Schrauben und Beschriftungskleber sind vorhanden
   um den Anschluss möglich zu machen
 - Spezielles Werkzeug zum lösen der Schrauben wird mitgeliefert
 - Stromversorgung wurde mit einem Stecker intern gelöst
 - Perfekte Halterung für ein 1200er Motherboard
 - Platz: drei 5,25" und vier 3,5" Einbauschächte,davon zwei für
   Festplatten
 - Genügend Platz für Turbo- und/oder Grafikkarten

 Und hier ein paar negative Daten zur E/Box:

 - Kein Anschluss für eine Amiga Tastatur vorhanden
 - Schwierigkeiten bei verwendung einer 2 1/2 Zoll Festplatte,da
   diese "kleine" Festplatte auf die Hauptplatine befestigt werden
   muss
 - PCMCIA-Port ist ein wenig blockiert,hier muss man selbst Abhilfe 
   schaffen
 

 Insgesamt gesehen ist mein persönlicher Eindruck von der E/Box
 sehr gut.Den einzigen richtigen Nachteil den das Gehäuse besitzt
 ist der blockierte PCMCIA-Port,aber ein wenig handwerkliches 
 schaffen und auch dieses Problem wäre gelöst.
 
 Wer also noch auf der Suche nach einem preiswerten Towergehäuse ist,
 dem kann ich die E/Box ruhigen Gewissens empfehlen.

 Conny Figge Schnellversand   Tel.(0201)8379960


 Rainer



 @{"zurück..." link "Hardware-news" 0}
@endnode

@node "os3.5" "OS 3.5"
@toc "Hardware-news"



                        ----------
                        - OS 3.5 -
                        ----------


 Anfangs noch für ein Gerücht haltend,so bestätigte jetzt
 auch die Amiga Special über die Entwicklung des neuen Amiga
 Betriebssystems.Leider gibt es hier noch keine genaueren
 Informationen.Wer jetzt genau (ausser Amiga Inc.) an der
 Entwicklung beteiligt ist,ist zur Zeit noch unklar.
 Ebenfalls unklar ist,in wie fern sich die neue OS Version von
 der alten unterscheiden wird.Werden nur (?) die Fehler von 3.1
 behoben,oder wird es auch zusätzliche nützliche Erweiterungen geben ?
 Fragen über Fragen...Amiga 4ever bleibt weiter am Ball.


 Rainer



 @{"zurück..." link "Hardware-news" 0}
@endnode

@node "Cygnused4" "Cygnused"
@toc "TOOLS PREVIEWS"



 PREVIEW: @{fg highlight}CYGNUSED 4@{fg text}

 Style: Texteditor

 System: ECS,1MB RAM,OS 2.X


 Einer der bekanntesten Texteditoren geht in die 4.Runde.
 Cygnused (kurz CED) kam bereits 1987 in seiner ersten Version auf dem
 Markt.Ein einfach gehaltener Texteditor,der dennoch effizient seine
 arbeit verrichtete.Weitere Versionen folgten im laufe der Jahre und
 nun (1998) schickt Ossowskis Schatztruhe die V.4.2 auf dem Markt.
 Dabei ist zu beachten,das CED keine Textverarbeitung (like Wordworth or
 Final Writer) ist,sondern ein ganz normaler Texteditor der ohne grossen
 SchnickSchnack auskommt.

 CED4 wird es ausschliesslich auf CD-Rom geben obwohl das eigentliche
 Programm gerade mal 150000 Bytes gross ist.Ebenfalls befinden sich
 eine menge Arexx-Scripts sowie einige Dokumente auf der Silberscheibe.
 
 Der Editor soll gute Geschwindigkeiten selbst auf einem 7-MHZ Rechner
 bringen.
 Welche Vorteile dieses vierte Update nun tatsächlich bringt ist 
 fraglich.Die Antwort demnächst...

 Rainer


 @{"zurück..." link "TOOLS PREVIEWS" 0}
@endnode

@node "EXCLUSIV" "Exclusiv"
@toc "Inhalt"



                -------------------
                - E X C L U S I V -
                -------------------



 @{"WING COMMANDER" link "WingCommBooks" 0} - Das Buch zum Spiel !!!




 @{"zurück..." link "Inhalt" 0}
@endnode

@node "WingCommBooks" "Bücher"
@toc "EXCLUSIV"



                -------------------
                - WING COMMANDER  -
                -------------------



 Buchtitel: Wing Commander - Die Befreier

 Seitenanzahl: 250

 Autor(en): Mercedes Lackey und Ellen Guon

 Verlag: Bastei Lübbe

 Preis: 8.90 DM



 Nachdem ich zufällig herrausbekam,das es Geschichten
 rund um das Kilrathi-Universum gibt,konnte ich nicht anders und
 musste mir unbedingt alle Wing Commander Bücher auf einmal kaufen.
 Um es vorweg zu nehmen: Ich habe es in keinster Weise bereut.

 Zur Zeit gibt es insgesamt 4 Bücher und das fünfte ("Preis der
 Freiheit") wird wohl auch nicht lange auf sich warten lassen,da
 das Computerspiel ja auch schon länger im Handel erhältlich ist
 (soll angeblich auch irgendwann für den Amiga erscheinen,sobald sich
 die Marktlage beruhigt hat).
 Dabei sind die ersten drei Bücher frei erfundene Geschichten der 
 Autoren und lediglich das letzte basiert auf die Geschichte des
 Computerspiels "Das Herz des Tigers".
 Man muss nicht unbedingt Science Fiction-Fan sein,um an den Büchern
 gefallen zu finden,allerdings wäre ein gewisses Grundwissen insachen
 Wing Commander besser,da viele Charaktere sowie bekannte Raumschiffe
 in den Geschichten vorkommen.Da wären zum Bleistift Personen wie 
 Paladin,Hunter,Maniac die man schon aus dem ersten Teil des
 Wing Commander Spiels kennt.Im späteren verlauf der Geschichte tritt
 auch noch Christopher Blair hinzu.
 Ebenfalls möchte ich empfehlen die Bücher der Reihe nach durchzulesen
 (mit Band 1 anfangen),da die ersten 3 Bücher stets übergreifend sind...
 ja...eigentlich schon eine zusammengehörende Trilogie.Wenn man mit
 Band 2 anfangen sollte,ist man nicht über die Geschehnisse des ersten 
 Bandes aufgeklärt,was sicherlich manchmal zu Verwirrungen führt.
 Ich werde nicht zu sehr auf die einzelnen Geschichten eingehen und
 sie nur sehr Oberflächlich behandeln,da ich auch nicht zuviel verraten 
 möchte.
 Also der Reihe nach...

 "Die Befreier" ist Band 1 der Wing Commander-Saga und ist ein guter
 Einführungsband in den Krieg zwischen den Menschen und den
 Katzen ähnlichen Wesen.Die Hauptperson der Geschichte ist Hunter,
 ein erfahrener Terranischer Pilot.Es kommt hier zu der Begegnung mit
 dem Kilrathi Lord Ralgha,der als Spion für die Menschheit arbeitet.
 Als dieser entführt wird,macht sich Hunter auf dem Weg um ihn aus den
 Klauen der Katzen zu befreien.Begleitet wird er dabei von seinem
 alten (mittlerweile pensionierten) Freund Paladin.

 Eine sehr spannende Geschichte die ihren absoluten Höhepunkt bei der
 waghalsigen Rettungsaktion erreicht.

 Bewertung: Gut

 Für Wing Commander-Fans: Sehr Gut


 Buchtitel: Wing Commander - Der Hinterhalt

 Seitenanzahl: 315

 Autor(en): William R.Forstchen und Christopher Stasheff

 Verlag: Bastei Lübbe

 Preis: 8.90 DM 


 Mittlerweile ist Die Menschheit den Kilrathis insachen Technologische 
 Waffen Überlegen.Deswegen geht man ein grosses Risiko ein und dringt 
 bis weit in das feindliche Imperium vor um die Kilrathis in einem
 Hinterhalt zu stellen.
 Jason "Bear" Bondarevsky ist Captain der Intrepid,der bei diesem
 "Himmelfahrtskommando" mit von der Partie ist.Er ist die Hauptperson
 in diesem spannenden Roman.Erstmals ist auch Admiral Tolwyn mit von
 der Partie.

 Wer glaubte eine Steigerung wäre nicht mehr möglich,der wird hier
 eines besseren belehrt."Der Hinterhalt" ist noch spannender als sein
 Vorgänger und ist Story-mässig noch ausgefeilter.

 Bewertung: Sehr Gut

 Für Wing Commander-Fans: Spitzen-Roman



 Buchtitel: Wing Commander - Die Geheimflotte

 Seitenanzahl: 315

 Autor(en): William R.Forstchen

 Verlag: Bastei Lübbe

 Preis: 8.90 DM



 Jason Bondarevsky,Paladin,Tolwyn und einige andere bekannte Personen
 spielen in diesem 3.Teil mit.
 Frieden scheint eingekehrt zu sein.Die Kilrathis haben sich 
 zurückgezogen!
 Dieser Frieden ist jedoch trügerisch,denn es liegt in der Absicht der
 Katzen die Menschheit in Sicherheit zu wiegen,denn die basteln an einer
 Geheimflotte die die Terranische Abwehr überrollen soll.
 Nachdem die grösste Kilrathische Armada,die es jemals gab,fertiggestellt
 ist,gilt es mit einem Schlag die Menschheit zu zerstören.
 Dieser Angriff wird von den Terranern erst viel zu spät bemerkt.

 "Die Geheimflotte" ist ein gut gewordener Roman,der Qualitätsmässig mit
 Band 1 gleichzieht.Das endgültige Eintreffen der Geheimflotte ist
 sicherlich der spannendste Teil im ganzen Roman.

 Bewertung: Gut

 Für Wing Commander-Fans: Sehr Gut



 Buchtitel: Wing Commander - Das Herz des Tigers

 Seitenanzahl: 380

 Autor(en): William R.Forstchen und Andrew Keith

 Verlag: Bastei Lübbe

 Preis: 10.90 DM



 Die Story wurde 1:1 vom gleichnamigen Computerspiel übernommen.
 Der Krieg zwischen den Menschen und den Kilrathi`s geht weiter.
 Gegen jede Chance wagen die Menschen einen verzweifelten
 Angriff auf den Heimatplaneten der Katzen,um endlich eine
 Entscheidung herbeizuführen.
 Die TCS Victory spielt hier die Hauptrolle.An Bord: Captain
 Eisen,Colonel Christopher Blair,Maniac und einige andere
 interessante Charaktere.

 Was einem an diesem Buch sofort auffällt ist die etwas andere
 Schreibweise der beiden Autoren.
 Die Story ist die bisher beste der Commander-Reihe,kennt man
 jedoch schon den interaktiven Movie des Computerspiels,so verliert
 die Sache etwas seinen Reiz.
 Deswegen geht meine Bewertung diesesmal genau andersrum.

 Bewertung: Sehr Gut

 Für Wing Commander-Fans: Gut


 ----------
 So,das war`s von meiner Seite aus.Vielleicht konnte ich den einen oder
 andern zum kauf eines der Bücher animieren.
 Wenn der vierte Teil erhältlich ist,werde ich mich unter EXCLUSIV
 wieder melden.
 ----------

 Rainer



 @{"zurück..." link "EXCLUSIV" 0}
@endnode

@node "CD32Corner" "CD-32"
@toc "Inhalt"


                      ----------------
                      - CD-32 CORNER -
                      ----------------


 @{"CEDRIC" link "cedriccd32" 0} - Plattformer mit Adventure-Elementen


 @{"GRANDSLAM GAMER GOLD" link "Grandslam Collection" 0} - 3 Games!!!


 @{"DRAGONSTONE" link "Dragonstonecd32" 0} - Supergeiler Zelda-Klone?


 @{"BATTLE CHESS" link "battlechess cd32" 0} - Schach Matt für Battlechess?



 @{"zurück..." link "Inhalt" 0}
@endnode

@node "battlechess cd32" "Battlechess"
@toc "CD32Corner"



 @{fg highlight}Battlechess@{fg text}

 Style: Chess

 Preis: ca.25 DM

 CD`s: 1

 Wer kennt das gute alte Battlechess eigentlich nicht ? Gibt es da
 überhaupt jemanden ?
 Erstmals erschien BC 1988 und wurde damals ein absoluter Top-Hit.
 Da es schon damals recht blutig zur Sache ging,verschwand es auch
 wieder schnell aus den Verkaufs-Regalen.

 Was ist Battlechess ? Nun...Schach (um es kurz auszudrücken) !
 Nur mit dem Unterschied,das sämtliche Schachfiguren voll animiert
 sind.Die Ritter,Bauern,Türme...alle besitzen ein Mittelalterliches 
 Flair und bekämpfen sich in witzigen Animationen (wenn es denn zum
 Kampf kommt).Allerdings ist ein Eingreifen in diesem Kampf nicht
 möglich,vielmehr dienen diese Sequencen dazu,dem Schach eine
 Portion Atmosphäre zu verpassen (was übrigens gelingt).
 Natürlich kann man auch eine "normale" Partie Schach spielen,ohne
 irgendwelche Grafischen Ergüsse.
 Der Computer ist ein ziemlich harter Brocken und selbst auf der
 niedrigsten Stufe (1von9) besitzt er einen hohen Intelligenzquotienten.
 Aber das liegt vielleicht auch an mir,da ich zwar gerne Schach spiele
 aber nicht besonders gut.
 So...all dies beinhaltete eigentlich auch schon die Diskettenversion,
 was ist also so besonderes an dieser CD-32 Konvertierung ?
 Zum einen das Tutorial (das man anfangs auswählen kann).
 Man wird dort in die Welt des Schachs geführt,bekommt dessen Ursprung
 erklärt und wie man Schach letztendlich spielt.Dabei stellen sich alle
 vorkommenden Charaktere vor und erzählen in digitalisierter englischer 
 Sprachausgabe ! Das ganze dauert dann auch eine dreiviertel Stunde,wird
 aber nie langweilig da einige lustige Gags mit eingebunden wurden.
 Die zweite Neuerung sind die Audio-Tracks.Mehrere Orchestralische 
 Musikstücke begleiten einen während des "Gefechts".Dazu hat jede
 einzelne Figur noch eine art "Tusch" wenn sie am Zuge ist.
 Bewegt man z.B. den Bauern,so ertönt ein kleines Flötenspiel,während
 Der Turm (das Monster) mit einer Gruseligen Melodie begleitet wird.
 Ein wenig geändert haben sich auch die SFX.Leider zum negativen,denn
 die Schmerzensschreie hören sich recht albern an (Ungefähr so,als
 hätte man Mickey Mouse in die Ei.. getreten).
 An der Grafik/Animation wurde nichts geändert (warum auch !),da
 sie trotz ECS immer noch Up to Date ist.

 Fazit ist,wer Battlechess immer noch etwas abgewinnen kann,dem kann
 ich die CD-32 Version nur empfehlen.Hier lebt es nochmal richtig
 auf.Dank der tollen Musik kommt gute Atmösphäre auf (aber das sagte
 ich doch bereits).
 Wer kein Schach mag,der sollte aber die Finger von diesem Spiel lassen
 (schliesslich geht es in diesem Spiel um nichts anderes !!!).
 Meiner persönlichen Meinung nach ein gutes Werk,was Interplay da
 ablieferte.
 
 Bewertung:
 ==========

 Grafik: Befriedigend

 Animation: Sehr Gut

 Sound: Gut

 Fun: Gut



 Rainer



 @{"zurück..." link "CD32Corner" 0}
@endnode

@node "Grandslam Collection" "Grandslam"
@toc "CD32Corner"



 @{fg highlight}Grandslam Gamer Gold Collection@{fg text}

 Style: 3 Games

 Preis: ca.20 DM

 CD`s: 1

 Auf dieser CD-32 Sammlung befinden sich drei Spiele die in diversen
 englischen Amiga Magazinen über 90% bekamen.Bump`n`Burn,Nick 
 Faldo`s Golf und Jetstrike.Deswegen auch Gold Collection benannt.
 Aber ist denn alles Gold was glänzt ???
 Was alle drei im einzelnen taugen steht hier:

 @{fg shine}Bump`n`Burn@{fg text}

 Ist das Beste Spiel auf dieser CD.
 Am ehesten kann man das Spiel als eine Mischung aus Mario Kart und
 Lotus Turbo Challenge beschrieben.Man hat die Wahl von 7 verschiedenen
 Charakteren.Da wäre z.B. Frank`n`Steiner in seiner Grusel-Karre oder
 Colonel Carnage in seinem zum Wagen umgebauten Panzer.
 Nun gilt es 14 Strecken (7 Welten) zu durchfahren und mindestens
 immer den 3.Platz zu erreichen.Ziel ist es am Ende dieser "Saison"
 auf den ersten Platz der Tabelle zu landen.
 Man fährt also in Lotus-3D-Manier durch die Landschaft und kann
 sich Extrawaffen und Bonuspunkte einheimsen wenn man über
 Stern-Felder driftet.Schusswaffen,Bomben,Öllachen...undundund...findet
 man in diesen Feldern,die man natürlich an die Gegner Missbraucht um
 sich Vorteile im Rennen zu verschaffen.Dieser Teil des Games erinnert
 sehr stark an das SNES-Spiel Mario Kart.Dabei kommen (je nach Welt)
 verschiedenartige Sprungschanzen,Klüfte,Pfützen und sonsterlei
 Hindernisse einem im Weg,die das Rennen zusätzlich erschweren.
 
 Grafisch ist das alles (wie schon gesagt) gut in Szene gesetzt
 worden und auch die Audiotracks sind gelungen.Toll ist auch
 der englische Kommentar,der die neue Rennstrecke vorstellt.
 Da kommt Fun auf.Die Steuerung ist sehr gut,das Pad wird hier
 vollkommen unterstützt.Der Schwierigkeitsgrad ist ein wenig hoch
 und erfordert ein wenig Einarbeitungszeit,sorgt aber für 
 Langzeitmotivation.
 Eine Zwei-Spieler Option (Splitscreen) ist ebenfalls vorhanden.
 Fans der Lotus-Trilogie werden ihren Spass an Bump`n`Burn haben.
 Einzig die etwas langen Ladezeiten stören.Ich empfehle deswegen 
 ein Quadro-CD-Drive.

 Bewertung:
 ==========

 Grafik: Gut

 Animation: Befriedigend

 Sound: Gut-Befriedigend

 Fun: Gut


 @{fg shine}Jetstrike@{fg text}

 
 Dieses Game ist eine Action-Simulation.Doch eher Action,da sich
 alles in 2D abspielt.
 Man hat eine sehr grosse Palette von Flugzeugen,Jets und Hubschraubern
 zur Auswahl.Damit begibt man sich dann in Rettungs-,Kampf- und
 Beobachtungsmissionen.Dabei kann man sein Jet (oder was auch immer)
 beliebig mit Waffen aufrüsten,von denen es eine Unmenge gibt.
 Das Spiel selber spielt sich dann (wie gesagt) in 2D ab,nach allen
 Richtungen scrollend.Das Spiel bietet insgesamt über 100 Missionen,dazu
 noch einige Missionen im Übungs-Modus.An Abwechslung fehlt es 
 eigentlich nicht,da die Missionsziele sich immer ändern.Aber...
 das Spiel lässt sich einfach grausam Steuern.Zwar wird das CD32 Pad
 unterstütz,aber die Tastaturbelegung (des Pads) ist so beknackt belegt,
 das man selbst nach zweistündigem spielen noch so seine
 Problemchen hat.Und leider hat man keine andere Wahl,als mit der
 vorgegebenen Steuerung zu zocken.
 Verdorbene Steuerung=Verdorbenes Spiel ? Leider ja...denn Jetstrike
 bietet mehr Frust als Lust.Der Schwierigkeitsgrad ist viel zu hoch
 angesetzt.Der Luftkampf gegen feindliche Flieger erweist sich als ein
 wahres Glücksspiel,da man schnell den Überblick verliert und sich 
 andauernd fragt:"Ja,wo issa denn?".Der Bodenkampf erweist sich als noch
 schwieriger.Man saust mit so einem Affenzahn an die Ziele vorbei,das 
 man garnicht dazu kommt die Bomben genau dann fallen zu lassen wenn es 
 nötig wäre.Ehe man sich versieht sind alle Bomben an Bord verbraucht 
 und keines der Ziele getroffen.Man fliegt also zurück zur Basis,lädt
 neue auf und versucht sein Glück ein zweites mal...und ein drittes...
 und ein vi...usw!
 Als akzeptabel kann man die Rettungs- und Bergungsmissionen bezeichnen.
 Die sind zwar auch nicht gerade leicht,aber allemal leichter als 
 irgendwelche Kampfmissionen.
 Eine 2-Spieler Option ist vorhanden und wenigstens einigermassen 
 spassig.Fazit ist,das der User früher oder später das Pad genervt 
 in die Ecke feuert (Frust sei dank),da können auch die verdammt guten 
 Audio-Tracks nichts dran ändern.
 Die Grafik könnte man mit dem Klassiker "Wings of Fury" vergleichen,
 obwohl Jetstrike noch ein wenig besser aussieht.
 
 Bewertung:
 ==========

 Grafik: Ausreichend

 Animation: Befriedigend

 Sound: Sehr Gut

 Fun: Ausreichend-Mangelhaft


 
 @{fg shine}Nick Faldo`s Championship Golf@{fg text}

 Über dieses Game fasse ich mich nur kurz,da ich in die Materie des
 Golf spielens wohl nicht weiter eingehen brauche.NFCG besitzt
 eigentlich alles was ein Golf-Fan erwarten müsste.
 36 verschiedene Parcours (keine Ahnung wie man das schreibt) und
 sämtliche Schläger (Wood,Iron,Putt,Sand...usw) die nötig sind.
 Man hat die Wahl von mehreren verschiedenen Gegnern (darunter auch
 Nick Faldo höchstpersönlich) und kann sich einen Coach zur Seite 
 stellen (der aber meistens nur dumme Kommentare von sich gibt).

 Die Grafik ist gut,nicht so grobpixelig wie man es sonst von 
 Golfspielen gewohnt ist.Ein scrolling entfällt aber aufgrund der
 hoch detaillierten Grafik.Der Aufbau der Bilder dauert auf einem
 Standart CD-32 ein wenig.Ein wenig Fast-Ram verbringt hier Wunder. 
 Der Sound (diesmal nix mit Audio-Track) ist angenehm.
 Golf Freaks müssen dieses Spiel einfach haben.Allround-Spielern
 (like me) gilt die nun abschliessende Bewertung.

 Bewertung:
 ==========

 Grafik: Gut

 Animation: Befriedigend

 Sound: Befriedigend

 Fun: Befriedigend



 GesamtFAZIT:
 ============

 3 Games für 20 Mark ? Da darf man nicht meckern,auch wenn das einzig
 wahre Highlight hier Bump`n`Burn ist.Schliesslich haben alle drei Games
 1995 noch über 60 Märker (einzeln,versteht sich) gekostet.Nick Faldo`s
 Golf ist ebenfalls ein anständiges Spiel,was den Kauf dieser Collection
 nur unterstreicht.Von dieser CD gibts übrigens nur noch einen
 Restposten,also zuschlagen bevor es ein anderer tut.


 Rainer



 @{"zurück..." link "CD32Corner" 0}
@endnode

@node "Dragonstonecd32" "Dragonstone"
@toc "CD32Corner"



 @{fg highlight}Dragonstone@{fg text}

 Style: Action-Adventue

 Preis: ca.15 DM

 CD`s: 1

 Dragonstone war eines meiner Spontankäufe,da man für schlappe 15
 Märker (eigentlich) nichts falsch machen kann.
 Das Game ist von Core Design und eine Mischung aus Action,Adventure
 und Rollenspiel.Es spielt sich aus der Vogelperspektive (mit leicht
 isometrichen Touch) ab.

 Zur Story möchte ich nicht zuviel sagen,da sie sich während des
 Spielens langsam aufbaut.Es geht um einen gewissen Dämon namens Agon,
 den es zu töten gilt.
 So schlägt man sich durch 7 Fantasy Welten,trifft auf 
 unterschiedlichste Monster,die man mit seinem Breitschwert 
 niedersticht,und auf freundlich gesinnte Passanten.Mit denen kann man
 sich dann auch unterhalten und ihnen bei ihren Problemen zur Seite
 stehen.Gegenstände können aufgenommen,untersucht und angewendet
 werden.Hierzu muss man mittels eines anderen Buttons ein Untermenü
 aufrufen.Dort sieht man auch seine aktuellen Werte (Schlagkraft,
 Magiepunkte...),wobei sich die magischen Fähigkeiten des Helden auf
 das feuern von Feuerbällen beschränkt.Diese "Rollenspiel-typischen"
 Werte lassen sich durch erkaufte Zaubertränke erhöhen (und durch noch
 einer anderen Sache...es wird nix verraten).

 Ein gewisses "Zelda-Feeling" kann man diesem Spiel nicht abstreiten.
 Die Rätsel sind zu 80% logisch und nachvollziehbar und auf einige
 kommt man erst nach ein wenig herumprobieren.
 Etwas abschreckend wirkt das erste Level,denn das besitzt einen ziemlich
 langweiligen Adventure-Teil.Das zweite Level ist in Ordnung,aber richtig
 viel Spass kommt erst ab dem 3.Level auf.Die Szenen (und Szenarien)
 die dann auftauchen sind einfach interessant und spannend.
 Die Story wird von Level zu Level dichter gespannt und erreicht ihren
 Höhepunkt im letzten Level.
 Der Grund,warum einige Leute dieses Spiel so "zerrissen" haben ist
 wahrscheinlich der,weil sie über das erste Level nicht hinaus gekommen
 sind (nicht wahr,Roman B.?).Wie schon erwähnt,ab dem 3.Level fängt die
 Sache erst an richtigen Spass zu machen und man möchte am liebsten
 gar nicht mehr aufhören.Fantasy pur!!!

 Zu den technischen Dingen: Die Grafik/Animation ist in Ordnung.
 Sicherlich kein AGA,aber trotzdem sind Personen und Monster sehr 
 detailliert gezeichnet worden.Der Sound beschränkt sich während 
 des spielens auf SFX,die teilweise Super und teilweise auch Blöde 
 klingen...insgesamt Überdurchschnittlicher Qualität also.Der zu anfangs 
 gespielte Audiotrack ist einfach toll,nur leider etwas zu kurz.
 
 Das Game habe ich in 3 Tagen fast (bin beim harten Endgegner) 
 durchgezockt,deswegen gibts die Codes in der Cheat-Ecke.

 Bewertung:
 ==========

 Grafik: Befriedigend

 Animation: Befriedigend

 Sound: Befriedigend

 Fun: (anfangs) Befriedigend (nach längerem spielen) Gut



 Rainer



 @{"zurück..." link "CD32Corner" 0}
@endnode

@node "DRAGONSTONECHEATS" "Dragonstone CD32"
@toc "Cheats"
          

   Dragonstone
   ===========

 Alle Levelcodes mit dem Helden namens "Rainer":
 ACHTUNG: Gross- und Kleinschreibung beachten...

 Gebiet+Code:        
 ------------

 2:Dorf Burghanden

 Code: ykaATHs-oLINT5nwFkAB

 3:Der Berg "unmöglich"

 Code: NrpmIMsBbL88O5nkOk4N

 4:Petit Port

 Code: NrpAzksBdL88THJkOM4B

 5:Die Dracheninsel

 Code: yypAbko-MLKBO5JkOt4B

 6:Die Dracheninsel Teil 2

 Code: Urp4bks-MLKBO5JkOT4B

 7:Die Dracheninsel Teil 3

 Code: Uya4OkL-oLsBO5JwOTAN


 Rainer



 @{"zurück..." link "Cheats" 0}
@endnode

@node "cedriccd32" "Cedric"
@toc "CD32Corner"



 @{fg highlight}Cedric@{fg text}

 Style: Action-Adventue

 Preis: ca.20 DM

 CD`s: 1

 Cedric kommt in einer Stabilen Verpackung daher,indem sich neben
 der CD auch noch eine 4 seitige Anleitung und eine Registrierungskarte
 befindet.
 Das Spiel lässt sich ohne Probleme vom CD32 aus booten und kann zudem
 auch auf HD installiert werden,da das Spiel keinerlei Audiotracks
 besitzt.Das Spiel ist ca.5MB gross und ist die normale 
 ECS-Diskettenversion (halt nur auf einer Silberscheibe gepresst).
 Es kann in englischer sowie deutscher Sparche gespielt werden.

 Cedric ist der Held dieses Action-Adventures.Er muss für seinen König
 das verlorene Zepter wiederbeschaffen,damit er dessen Tochter zur Frau 
 nehmen kann.Ein kleines (lustiges) Intro macht einem diese Aufgabe 
 schmackhaft.

 Im Spiel steuert man Cedric durch insgesamt 11 Level,die man durch 
 springen,klettern und rohe Gewalt meistert.Es erinnert dabei ein wenig
 an den Klassiker "Shadow of the Beast".
 Das besondere an diesem Game ist aber der gehörige Adventure-Teil.
 Immer wieder findet Cedric Gegenstände,die man zu bestimmten zwecken
 gebrauchen muss.Er kann (im Choice-Verfahren) mit anderen Personen
 reden,knallhart komische Konversation führen und Aufgaben erhalten.

 Dabei sind die Rätsel,die es zu lösen gilt stets Logisch und
 Nachvollziehbar.Einzig der Action-Teil wird stellenweise ein wenig 
 Unfair (im ersten sowie im neunten Level).
 Die Level sind sehr abwechslungsreich gestaltet worden und entführen
 einen immer in neue Szenarien.
 Die Steuerung ist leider nur mässig gelungen.Zwar wird das CD32 Pad
 unterstützt,aber zum springen muss das Steuerkreuz nach oben
 gedrückt werden.Dafür kann man mittels eines zweiten Buttons das
 Inventarmenü aufrufen.

 Die Grafik ist in 32 Farben gehalten worden und entspricht (wie
 das ganze Spiel selbst) der normalen 500er Version.Nicht das die
 Grafik schlecht wäre (Nein!Die ist wirklich gut!),aber man hätte
 sie doch trotzdem noch weiter verbessern können (den Hintergrund
 z.B.).Ein paar coole Audiotracks hätten dem Spiel auch nicht geschadet,
 da die Musik (in manchem Level) recht langweilig wirkt.
 Insgesamt kann ich dieses Spiel nur für gut heissen,da besonders
 der Adventure-Flair sehr gut rüberkommt.Es enthält sehr witzige
 Dialoge und Kommentare von Cedric,wo man sich so manches mal einen Ast
 ablacht.Auch werden einige Spiele auf die Schüppe genommen,wie z.B.
 Monkey Island oder Lionheart,was den Humor der Programmierer nur 
 Unterstreicht.Apropo Programmierer: Alcatraz hat dieses Game 
 geschaffen.Hää ? Ist doch ne Demogruppe,oder nicht? Richtig...!

 Bewertung:
 ==========

 Grafik: Gut

 Animation: Befriedigend

 Sound: Befriedigend

 Fun: Gut



 Rainer



 @{"zurück..." link "CD32Corner" 0}
@endnode

@node "CD-NEWS" "CD-News"
@toc "Inhalt"




                        -------------------------
                        - C D - R O M   N E W S -
                        -------------------------


 @{"REVIEWS" link "CD-NEWS-REVIEWS" 0}



 @{"zurück..." link "Inhalt" 0}
@endnode

@node "CD-NEWS-REVIEWS" "Reviews"
@toc "CD-NEWS"

        CD-Rom News         
          Reviews
       =============


 @{"SOUND AND VISION" link "SoundandVisionCD" 0}

 


 @{"zurück..." link "CD-NEWS" 0}
@endnode

@node "SoundandVisionCD" "Sound and Vision"
@toc "CD-NEWS-REVIEWS"



 REVIEW: @{fg highlight}SOUND AND VISION@{fg text}

 Preis: ca.10 DM


 Diese Sound and Vision CD-Rom wurde von der Firma Nightshift
 zusammen gestellt.Für schlappe 10 Mark bekommt der User diese
 Silberscheibe mit dem Schwerpunkt Grafik+Sound.
 Folgende Daten dazu:

 284 MB Grafiken (Pictures,grösstenteils ECS-IFF)

 117 MB Animationen (sehr gute Eric Schwarts Animationen sind
                     dabei)

 185 MB Module (meist ältere -1989 - 1994-)

 32 MB Samples (zahlreiche ST-Samples,aber auch viele Voice-Samples
                und Sequencen)

 15 MB Programme (darunter die Vollversion von "GFX Manager",eine
                  Bilderverwaltung ähnlich PictureManager.Qualitativ 
                  nicht ganz auf dem Niveau,dennoch nützlich.
                  Alle anderen Programme sind Tracker,Abspielroutinen
                  und Picture-viewer die schon etwas älter sind)

 Insgesamt gesehen kann man mit der S+V CD rundum zufrieden sein.Für
 10 Mark bekommt man hier eine Menge geboten,auch wenn die meisten
 Sachen schon schlichtweg veraltet sind.

 Positiv:  Preis/Leistungs-Verhältniss

 Negativ:  Viele Module,Pictures und Programme veraltet

 Bewertung: BEFRIEDIGEND
 =========

 Rainer



 @{"zurück..." link "CD-NEWS-REVIEWS" 0}
@endnode

@node "BilderGalerie" "Pictures"
@toc "Inhalt"




                        ------------------
                        - BILDER GALERIE -
                        ------------------


    --- Hier sollen Eure Pictures hinein.Siehe Mach Mit-Dokument
        für weitere Informationen. ---


 @{"zurück..." link "Inhalt" 0}
@endnode

