@DATABASE WitzeGuide
@Rem $VER: Witze.Story 1.1 (20.12.94)
@WIDTH 80

@NODE Stor "Stories und längere Geschichten"
@TOC Witze.guide/Inhalt
@PREV Stor
@INDEX Witze.Index/Index



	Kleine oder größere Geschichten, Lexika oder Listen, die sonst
	nirgendwo ganz reinpassen...












	@{" Neues " link ST0028}						@{" Index " link EndStor}

@ENDNODE

@NODE ST0001 "kleines  C O M P U T E R L E X I K O N"
@TOC Witze.guide/Inhalt

	1 Bit:		bekanntes Pils aus der Eifel
	1 Byte:		8 Bits
	1 Kilobyte:	ca. 8,2 Hektoliter Bit
	3 1/2 Zoll:	Drei Zollbeamte + ein kleinwüchsiger strafver-
			setzter Schupo
	5 1/4 Zoll:	Fünf Zollbeamte + ein Drogensuchhund
	BILDschirm:	Regenschutz mit Springer-Reklame
	Bus:		öffentliches Verkehrsmittel
	Chip:		Spielkasino-Geld/Knabberei aus frittierten
			Kartoffeln
	Commodore:	Offizier der Luftwaffe
	Controller:	Eltern, Lehrer usw.
	Coprozessor:	Nebenkläger (beim Strafprozess)
	Datei:		Ei mit aufgedrucktem Legedatum
	Directory:	engl. für 'Direktion'
	EDV (Abk.):	Ende der Vernunft
	File:		Werkzeug zur Bearbeitung von Fingernägeln
	Freezer:	engl. für 'Gefriertruhe'
	Hardware:	Granit, Diamant, 8-Minuten-Ei
	Interface	:Fahndungsfotokartei von Interpol
	Lichtstift:	Elektrolehrling
	Lightpen:	leichter Schlaf (vgl. oben)
	Mailbox:	Schlägerei zwischen Postbeamten
	Maus:		bissiges, hochgefährliches Raub- und Nagetier
	Mikroprozessor:	sehr kleiner Staatsanwalt
	Monitor:	politisches Fernsehmagazin
	Port:		Kurzform für 'Portwein'
	RAM:		Milchprodukt
	ROM:		Hauptstadt Italiens
	Schnittstelle:	Wurst- od. Käsetheke/Friseur/Verletzung
	Software:	Gummibärchen, Softeis, Drei-Minuten-Ei
	Space Bar:	Weltraumkneipe
	SYSOP (Abk.):	Säuft Yankeewhisky Ständig Ohne Peilstab

@ENDNODE

@NODE ST0003 "Radio FFN"
@TOC Witze.guide/Inhalt

	In den deutschen Mittelgebirgen und sogar im Harz schmilzt der
	Schnee. Gelegenheit für uns Naturfreunde, wieder ausgedehnte
	Spaziergänge durch den Wald zu unternehmen. Vielleicht sogar unter
	Absingen lustiger Wanderlieder, beispielsweise den von Onkel Hotte
	verfaßten "Im Frühtau die Zwerge..." oder "Ein Zwerglein hängt
	im Walde..." :

	MUSIC ON

	Im Frühtau die Zwerge, sie gehn - fallera,
	Sie taumeln, sie schwanken und sie gröhln - fallera,
	Ja seht, wie krumm sie laufen,
	Denn gestern war'n sie saufen,
	Ihr kennt das, Ihr ward das ja auch schon 'mal.

	Vom Freibier die Zwerge, sie komm' - trallala,
	Zu einer ander'n Kneipe woll'n sie zieh'n - rumtata,
	Sie sind grad' rausgeflogen,
	Weil sie sich nackt auszogen,
	Der Suff macht sie alle pervers - tütata.

	Im Frühtau die Zwerge bleib'n steh'n - lalala,
	Sie kotzen in die Büsche und die Seen - rumsassa,
	Was soll man dazu sagen,
	Sie könn' halt nichts vertragen,
	Naja, Zwerge sind nun 'mal blöd - fallera.

	MUSIC OFF

	* Piiiiep *
	Radio FFN mit dem Verkehrsservice: Achtung Autofahrer!
	Auf der A2 zwischen Hannover-Herrenhausen und Zauberwald befinden
	sich Zwerge auf der Fahrbahn. Bitte fahren Sie äußerst rechts,
	überholen Sie nicht, wir informieren Sie, sobald die Gefahr vorüber
	ist.
	* Piiiiep *

	MUSIC ON

	Ein Zwerglein hängt im Walde ganz still und stumm,
	Es hat um's purpur Hälschen ein Stricklein drum.
	Sagt wer mag das Zwerglein sein, das da hängt im Wald allein,
	Mit dem blaßrot-blau gefärbten Köpfelein.

	Ein Brieflein liegt im Walde ganz still und stumm,
	Es hat vor lauter Wörtern 'nen Umschlag drum.
	Wird der Abschiedsbrief wohl sein, von dem kleinen Zwergelein,
	Das sich aufgehängt hat an dem Bäumelein.

	Ein Bäumlein steht im Walde so ganz allein,
	Es hängt an seinem Ästchen ein Strickelein.
	Baumelt dort im Wald so fein, wartet auf ein Gnömelein,
	Das dort stecken mag sein Zwergenköpflein 'rein.

	MUSIC OFF

	* Piiiiep *
	Radio FFN mit dem Verkehrsservice: eine Entwarnung für die A2. Die
	Zwerge wurden überfahren, Sie haben wieder freie Fahrt.
	* Piiiiep *

@ENDNODE

@NODE ST0004 "Begriffe aus der Welt der Politik"
@TOC Witze.guide/Inhalt

	SOZIALISMUS:
	 Du besitzt zwei Kühe. Eine Kuh mußt Du Deinem Nachbarn geben.

	KAPITALISMUS:
	 Du besitzt zwei Kühe. Du verkaufst eine und kaufst Dir einen
	 Bullen.

	LIBERALISMUS:
	 Du besitzt zwei Kühe. Die Regierung nimmt Dir beide weg und
	 schenkt Dir die Milch.

	NATIONALISMUS:
	 Du besitzt zwei Kühe. Die Regierung nimmt Dir beide weg und
	 erschießt Dich.

	BÜROKRATIE:
	 Du besitzt zwei Kühe. Die Regierung nimmt Dir beide weg und
	 schlachtet eine Kuh ab. Die andere Kuh wird gemolken und die
	 Milch vernichtet.

	DEMOKRATIE:
	 Du besitzt zwei Kühe und läßt diese darüber abstimmen, ob eine
	 verkauft wird.

	ANARCHIE:
	 Du besitzt zwei Kühe. Du sprengst die Molkerei in die Luft und
	 machst deinen Käse alleine.

	NIHILISMUS:
	 Du besitzt keine Kuh.

	TERRORISMUS:
	 Du besitzt keine Kuh und bringst die von Deinem Nachbarn auch
	 noch gleich mit um.

	KANNIBALISMUS:
	 Du besitzt keine Kuh und frißt Deinen Nachbarn auf.

	ALTERNATIVE:
	 Du besitzt zwei Schafe und strickst Dir einen Pulli.

@ENDNODE

@NODE ST0005 "Wie ich eine Cola-Dose richtig aufmache."
@TOC Witze.guide/Inhalt

	"Was soll den DAS schon wieder?", werden jetzt sicherlich einige
	fragen, aber eine Dose öffnen heißt nicht gleich eine Dose öffnen.
	Vielmehr kann man viel Über den Charakter des sogenannten Dosen-
	Öffners erfahren, indem man ihm bein Dosen öffnet zusieht. Um
	Laien in der Dosen-Psychologie die elementarsten Elemente der
	elementaren Psychologie bei Dosen zu erklären, folgen nun einige
	einfach nachzuvollziehende Beispiele :

	1. Der 08-15-Typ:
	Dieser hält die Dose in einer Hand. Der Daumen wird vor die Dose
	gebracht und der Öffner wird mit dem Zeigefinger langsam, unter
	dem mittlerem Zischen der entweichenden Kohlensäure, nach oben
	gebogen. Sobald die Dose auf ist, wird der Öffner wieder zurück-
	gebogen.

	2. Der coole Typ:
	Er öffnet die Dose mit einer (!) Hand. Dazu klemmt er den Finger
	unter den Öffner schwingt die Hand (mit der Cola-Dose) nach oben
	und reißt sie dann blitzschnell nach unten. Das Zischen der Kohlen-
	säure ist übermäßig laut, um auch genügend Aufsehen zu erregen.

	3. Der Rambo-Typ:
	Er stellt die Dose in 50-80 cm Entfernung auf und ballert mit
	seiner Utzi auf die Dose. Danach nimmt er die Dose und versucht
	die auslaufende Cola zu trinken. Versuche mit Handgranaten schlugen
	übrigens fehl, da sich die Cola im Umkreis von ca. 150 m gleich-
	mäßig verteilte. Die Kohlensäure kommt erst gar nicht zum Zischen.

	4. Der Säufer:
	Bohrt ein Loch in den Dosenboden, hält dieses an den Mund und
	öffnet die Dose (Fast genauso wie der 0815-Typ, jedoch schneller!).
	Die rausströmende Cola ist in ca. 3-5 sec. verschwunden (In der
	Regel im Magen, manchmal auch (bei Leuten mit schwachen Mägen)
	nach weiteren 3-5 sec. wieder außerhalb im Umkreis von ca. 120
	cm). Das Zischen der Kohlensäure wird vom Rauschen der Cola
	überlagert!

	5. Der Snob:
	Zieht sich erstmal die weißen Handschuhe an und desinfiziert die
	Cola-Dose mit einem Spray. Dann hält er die Dose mit einer Hand
	fest. Mit dem Daumen und dem Zeiger packt er den Öffner (mit aus-
	gespreiztem Kleinem Finger, Wichtig!) und zieht den Öffner so
	leicht nach vorn, daß kaum ein Zischen wahrzunehmen ist. Dann
	klappt er den Öffner zurück. Er setzt den desinfizierten, ver-
	goldeten Schütt-Aufsatz auf die Dose und schüttet sich einen
	Schluck in sein Bleikristallglas.

	6. Der gewalttätige Typ:
	Er packt die Dose in einer Hand und quetscht sie solange bis der
	Verschluß durch den Druck wegspringt. Abgesehen von einem leichten
	Knall ist auch hier kein Zischen zu hören.

	7. Der Programmierer:
	Er schreibt erst ein Fluß-Diagramm und programmiert dann eine
	Simulation, die ihm das Öffnen einer Cola-Dose erklärt. Aus dem
	selbstgeschriebenem Doc-File kann er dann weitergehende Informa-
	tionen entnehmen und so die Dose öffnen. Das Zischen ist normal
	bis etwas lauter.

	8. Der Bastler:
	Baut sich aus Fischer-Technik einen Cola-Dosen-Öffnungs-Auto-
	maten. Das Öffnen erfolgt über einen Kran-ähnlichen Arm, der über
	der Dose angebracht wird. Bastler, die über einen Computer ver-
	fügen steuern das Öffnen natürlich über ihre Schnittstelle direkt
	vom Computer aus. Durch die doch etwas wackelige Konstruktion
	und der ungenauen Ansteuerung der Schrittmotoren zischt es beim
	Öffnen etwas lauter.

	9. Der Physiker:
	Er berechnet den optimalen Aufzieh-Winkel unter Beachtung des
	geringsten Energie-Aufwandes. Anschliesend leistet er Verformungs-
	arbeit beim Aufziehen des Öffners. Die Cola ist für ihn die un-
	wichtigste Sache überhaupt. Ihn interessiert die Vektor-Addition
	der Kräfte, die beim Öffnen auftreten oder der Energie-Gehalt
	des entweichenden Gases. (Wobei er das Gas nachweist!). Das
	Zischen ist auch nicht lauter als normal.

	10.Der Chemiker:
	Sprengt den Öffner plus Deckplatte mit einem selbstgemachten
	Sprengstoff ab. Der Knall übertönt das Zischen. Er analysiert
	die Zusammensetzung, wartet auf das Ergebnis, liest es, fängt
	an zu schwitzen und stellt die Dose weg.

	11.Der Mantafahrer:
	Obwohl an Manta-Fahrer noch keine Cola verkauft werden darf
	(Jugend-Schutz-Gesetz - Irgendwer muß ja die Jugend vor denen
	schützen!) kommen einige Manta-Fahrer doch an eine Cola-Dose.
	Nachdem sie 3 Std. an der Dose rumgekratzt haben (mit dem Auto-
	schlüssel) und den Öffner (ohne die Dose zu öffnen) im Eifer
	ihres Unwissens abgebrochen haben, legen sie die Dose auf die
	Straße und heizen einmal mit ihrem Manta rüber und dann nochmal
	über die ausgelaufene Cola, um die Bakterien abzutöten. An-
	schließend schlürfen sie die Cola auf.

	12.Der Sozial-Psychologe:
	Versucht die Cola-Dose zu überreden, sich von selbst zu öffnen,
	Selbstinitative zu ergreifen. Wenn das nach 5 Std. härtester
	Konversation (sofern man davon sprechen kann, bis jetzt hat noch
	keine Cola-Dose geantwortet) nichts hilft und die Dose immer noch
	zu ist, bricht er heulend vor der Dose zusammen. Bis jetzt ist
	noch kein Sozial-Psychologe gesehen worden, der eine Cola trinkt,
	daher also auch kein Zischen.

	13.Der Ostfriese:
	Er sucht 2 Std. auf der Unterseite nach dem Öffner. Anschliesend
	geht er ins Geschäft und reklamiert die Dose und kauft sich dafür
	lieber einen Küstennebel, weil man den oben aufschrauben kann!
	Kein Zischen (logisch!)!

	14.Der Indianer
	Er macht einen Regentanz um die Dose. Es fängt an zu regnen. An-
	schließend wartet er, bis die Cola-Dose genügend oxidiert ist,
	bis er sie skalpieren kann. Das Zischen ist bei dieser Methode
	auch gleich Null.

	15.Der Prol:
	Er setzt die Cola-Dose in einen Dosenhalter im Golf-GTI-Look und
	holt seinen vergoldeten Dosenöffner aus der Hose (Äch so, der
	Dosenöffner war das..."), an dem Glöckchen hängen, damit auch
	alle gucken! Anschließend setzt er den Dosenöffner an und hebelt
	die Dose auf. Beim letzten Hebeln jedoch rutscht er ab und bricht
	sich die Hand. Beim Trinken reißt er sich die Lippen an den
	Schnittstellen auf und beim Abnehmen des GTI-Dosen-Halters bricht
	er sich die andere Hand, worauf er wutentbrannt gegen eine Mauer
	tritt und sich den Fuß bricht. Aber das wichtigste: Er ist Mit-
	telpunkt des Abends (und später im Krankenhaus!)

	Man kann also allein am Aufmachen der Cola-Dose erkennen, mit
	welchen Charakteren man es zu tun hat. Man sollte sich mit seiner
	Wertung sehr vorsichtig geben, da die gegebenen Beispiele ziemlich
	pauschal (wenn auch zutreffend!) sind.

@ENDNODE

@NODE ST0006 "WinDOOF-Fehlermeldungen"
@TOC Witze.guide/Inhalt

	MONOPOLY-ERROR:
	Verlassen Sie sofort die Anwendung, gehen Sie nicht über den Pro-
	gramm-Manager, ziehen Sie kein Fenster auf.

	BUNDESBAHN-ERROR:
	Anwendung hat leider einige Minuten Verspätung.

	BEAMTEN-ERROR:
	Ihr Vorgang ist in Bearbeitung, bitte verwenden Sie beim nächsten
	Systemaufruf Ihre Personalnummer, die wir Ihnen binnen drei Monaten
	zuteilen.

	SOZI-ERROR:
	Stelle Geschäftsordnungsantrag auf Einstellung der Systemfunktionen.

	GEWERKSCHAFTS-ERROR:
	Tariflich vereinbarte Arbeitszeit überschritten, Systemfunktionen
	eingestellt, Arbeitsgericht benachrichtigt.

	IBM-ERROR:
	Sie können doch nicht von mir erwarten, mit einem IBM-Rechner
	zusammenzuarbeiten.

	MONTY-PYTHON-ERROR:
	And now to something completely different...

	MÜSLI-ERROR:
	Also weißte, das finde ich jetzt mal nicht so doll von Dir, daß
	Du da solche Sachen mit mir machst. Ich meine, wir hätten da schon
	mal vorher drüber reden können. Da brauchste Dich echt nicht wun-
	dern, wenn ich jetzt abhaue! Ich geh jetzt ins Systemhaus.

	HARTER-ERROR:
	Sitzen Sie...?

	MANAGER-ERROR:
	Lassen Sie es mich einmal so ausdrücken...

	POSITIVER ERROR:
	Sie brauchen heute nichts mehr zu arbeiten!

	KOMPROMISS-ERROR:
	Wollen wir nochmal darüber reden?

	KÜNDIGUNGS-ERROR:
	Wir bedanken uns für Ihre Mitarbeit!

	TOM-DOOLEY-ERROR:
	"Hang down your head ..."

	SCHUSSEL-ERROR:
	Wo hab ich bloß die Anwendung hingelegt...?

@ENDNODE

@NODE ST0007 "Zitate von Lehrern und Schülern"
@TOC Witze.guide/Inhalt

  Schüler: "Wie würden sie folgenden Satz stilistisch verbessern: Viele
            Stunden in der freien, herrlichen Natur ließen unsere Freude am
            Schönen erstrahlen?"
  Lehrer:  "Hmm.. Hilfe, wir schießen auf Kühe und sie wollen nicht
            umfallen."

  Lehrer:  "Die Schäden in hundert Kilo Entfernung ist weniger groß."

  Lehrer:  "Entweder man ist Mädchen oder man ist kein Mädchen. Das ist
            jedenfalls meistens so."

  Lehrer:  "Dann ist noch das Glas umgekippt und der Goldfisch ertrunken."

  Lehrer:  "Jetzt seid mal ruhig, wenn ihr schon sonst nichts sagt!"
@ENDNODE

@NODE ST0008 "Die besten ATARI-Witze"
@TOC Witze.guide/Inhalt

	I) Abstürze

	Wann besteht bei einem Atari ST keine Absturzgefahr?
	 Während eines Stromausfalls.

	Wie erkennt man, daß ein ST eingeschaltet ist?
	 Auf dem Bildschirm stehen ein paar Bömbchen.

	Wie brachte man früher ST-Basic zum Absturz?
	 PRINT 75.3 (kein Witz!)

	Was ist die Bedeutung der Zahl 10?
	 Sie ist ziemlich genau die Durchschnittszeit (Minuten)
	 zwischen zwei Abstürzen

	Wie bewahrt man den ST-User vor Abstürzen?
	 Man zieht den Netzstecker.

	Letzte Worte eines ST-Freaks?
	- "Mein Text ist schon 40K lang, und gleich werde ich ihn
	   speich..."

@ENDNODE

@NODE ST0009 "Die besten ATARI-Witze"
@TOC Witze.guide/Inhalt

	II) Erweiterungen

	Warum kann man in den ST keinen 68020er einbauen?
	 Er ist's eh nicht wert.

	Wozu hat der ST MIDI?
	 Damit man seine System-Erweiterungen dran anbringen kann (wo sonst?)

	Warum ist beim ST der Systembus nicht herausgeführt?
	 Jede Erweiterung wäre eine Fehlinvestition.

	Warum hat der ST einen ROM-Schacht?
	 Man wollte zu den Atari-Spielkonsolen kompatibel bleiben.

	Warum ist der ST-Freak so stolz auf sein MIDI-Interface?
	 Keiner hat ihm gesagt, daß der Amiga-Besizter es für 100.-
	 kaufen kann.

	Warum entwickelt Atari eine Parallelrechnerkarte zum ST?
	 Weil es 4 T800 braucht, bis die GEM und ST-Basic genügend
	 schnell laufen.

@ENDNODE

@NODE ST0010 "Die besten ATARI-Witze"
@TOC Witze.guide/Inhalt

	III) Grafik/Sound

	Wie erkennt man eine typische ST-Farbgrafik?
	 Am Filzstift auf dem Monitor.

	Wie nennt der ST-User eine Auflösung von 640 x 200 Punkten in
	vier Farben?
	 Multicolor!

	Für wen ist der ST der ideale Computer?
	 Für Farbenblinde, die keine Graustufen unterscheiden können.

	Wie schaltet man den ST von Schwarzweiß nach Farbe um?
	 Man kauft einen Zweitcomputer - ansonstem ausschalten, um-
	 stecken, booten!

	Wie verbessert man den Sound des ST?
	 Man baut den Soundchip eines VC-20 ein.

	Warum hat der ST MIDI?
	 Keine Frage bei DEM Soundchip!

	Warum kann der ST nicht mal als Kopfkissen dienen?
	 Seine Tastatur ist viel zu weich.

	Wie erkennt man den eingefleischten ST-Freak?
	 An den abgewinkelten Fingern zur Bedienung der Funktionstasten.

	Warum hat der ST kein CLI oder sonst eine Kommandozeilen-Shell
	wie MSDOS?
	 Wie sollte er - bei DER Tastatur!

	Warum ist der ST so schlecht konstruiert?
	 Atari steckt alles Geld in Fernsehspots.

	Wie kommt man beim 1040 ST zu einer abgesetzten Tastatur?
	 Sägen!

	Warum bietet Atari auch einseitige Drives an?
	 Man wollte C64-Usern den Umstieg erleichtern.

	Wie verdoppelt man den Wert eines Atari ST?
	 Man schiebt eine Leerdisk ins Drive.

	Warum ist der ST für nichts zu gebrauchen?
	 Er ist zu hart, um sich damit den Arsch abzuwischen.

	Was liegt in der Ecke und modert vor sich hin?
	 Der ST-User, der sich geschworen hatte, auf den Blitter zu warten.

@ENDNODE

@NODE ST0011 "Die besten ATARI-Witze"
@TOC Witze.guide/Inhalt

	IV) Software

	Was meint der ST-User zu UNIX?
	 "Mein TOS ist moderner!"

	Und wie denkt er über Multitasking?
	 "Kann man das essen?"

	Warum hat der Mega ST 4 4 Megabytes Speicher, aber kein Multitaksing?
	 Damit man seine 3.5 Megabytes langen Texte bearbeiten kann.

	Was ist der Traum jeden ST-Freaks?
	 Das fünfte Window.

	Was ist klein, schwarz und ruckelt im Sekundentakt?
	 Der Mauszeiger von GEM.

	Was ist eine der Großtaten der ST-Softwareentwickler?
	 Sie schafften es, den Font häßlicher als jeden 8x8-Pixel Font
	 zu machen.

	Worin zeigt sich der Fortschritt in der ST-Systemsoftware?
	 Heute braucht es für Datenverluste 100 statt 40 Directories
	 auf der HD.

	Wie erkennt man, daß ein ST läuft?
	 Anhand von Zeitrafferaufnahmen!

@ENDNODE

@NODE ST0012 "Die besten ATARI-Witze"
@TOC Witze.guide/Inhalt




	V) IQ des Users

	Was meint der ST-User zum 68020er?
	 Nichts, so weit kann er nicht zählen.

	Warum benutzt GEM nur eine Maustaste?
	 Man wollte den User nicht überfordern.

@ENDNODE

@NODE ST0013 "Die besten ATARI-Witze"
@TOC Witze.guide/Inhalt

	VI) Abkürzungen

	Was bedeutet GEM?
	 Genial Emulierter Mist.

	Was bedeutet ST?
	 Super-trash.

	Was bedeutet TT?
	 Tramiel's thoughts.

	Was bedeutet TOS?
	 Trash operating system.

	Was meint ein ST-User zu Desk Top Video?
	 "Jaja, ich hab einen Rekorder auf meinem Pult!"

	Und wenn man die Abkürzung DTV benutzt?
	 "Das ist doch ein Taschenbuch-Verlag?"

@ENDNODE

@NODE ST0014 "Fanta (V)Fier auf Coca Cola!"
@TOC Witze.guide/Inhalt

	Dieser Satz ist so inspirierend! Er beinhaltet so viel in so
	wenigen Worten. Das Leben, die Realität, die Welt schwindet
	dahin, wenn man sich in ihn vertieft. Er beinhaltet so viele
	Gegensätze. In ihm werden Anfang und Ende vereint. Anfang und
	Ende, Alpha und Omega, Fanta und Cola, Gelb und Schwarz. Friede,
	Freude, Crack und Coffein. Dies widerspricht sich so sehr und
	ist doch so eng vereint. Diese gekonnte Alliteration (F F C C)
	verknüpft sich sofort mit diesen grandiosen Assoziationen:

	- Frisch, Fromm, Fröhlich, Frei 

	- Crack, Coffein, Cash, Calamari

	Dieser grandiose Gegensatz zwischen biederer, konservativer
	Naturverbundenheit, die die Welt durch eine Coca-Cola-rote
	Brille sieht, die alles zum Guten verfärbt, und dieser welt-
	verdrossenen, depressiven Weltflucht, die die Welt als solche
	nur mit Hilfe von Drogen und Geld ertragen kann.
	Das Leben in der Extravaganz gegen Biedermaier.

	Auch dder Inhalt dieser Dose weiß zu erzählen! Er zeigt einen
	Gegensatz dieser Welt, der sich selbst auf so vorbildhafte Weise
	hier gelöst hat. Eine schwarze Flüssigkeit in einer Weißblechdose.
	Schwarz und Weiß friedlich nebeneinander, so wie es sein sollte
	aber oft nicht ist. Ein weiterer Rassengegensatz schließt sich
	noch an. Fanta - Gelb und Cola - Schwarz. Asien und Afrika.
	Auch Fanta wird in Weißblechdosen verkauft => Gelb und Weiß!
	Dieser Satz umspannt die Welt!

	Und dann diese Blasen aus Kohlendioxid. Vollkomen silbern
	scheinen sie durch die Flüssigkeit und steigen sanft nach oben.
	Ihre Form ist so vollkommen! Ökonomisch Rund um den Druck
	(der Welt) am leichtesten zu kompensieren. Sie spiegeln den
	ewigen Kampf, an die Spitze zu gelangen, wieder.

	Dann der Widerspruch zwischen süßem Zucker, der ja doch so
	schädlich ist (wie das meiste Gute in der Welt), und der
	Ascorbinsäure (Vitamin C oder auch E 300), die, so sauer sie auch
	sein mag, doch gesund ist (aber nur in Maßen, denn in MASSEN
	gibt es DÜNNPFIFF!).

	Das Leben ist voller Lebensweisheiten, die sich alle in einer
	Dose vereinen (und Dank des grünen Punktes auch wieder RECYCELN
	lassen):

	- Alles Gute ist schlecht.
	- Alles Schlechte ist gut.
	- Das Leben ist voller Widersprüche.
	- Cola löst den Kaffesatz als Orakel ab.
	- Weißblech gehört zu den Edelmetallen.
	- Dieser philosophische Disput ist absolute Scheiße (bis auf
	  diesen Satz) und sagt doch nichts über die unermeßlichen
	  Weiten des Weltraums mit seinen unerforschten Welten, die noch
	  nie ein Mensch zuvor gesehen hat, aus.

	P.S.: Sollte er (der Artikel) Euch dennoch gefallen, so kann ich
	Euch auch nicht helfen, aber ich empfehle Euch: Kauft Euch eine
	Dose und meditiert darüber und predigt der Welt Eure so gewonnen
	Weisheiten! (Und vergeßt nicht, zu erwähnen, wie Ihr zu ihnen
	gekommen seid...)

@ENDNODE

@NODE ST0015 "Ende eines PC-Users"
@TOC Witze.guide/Inhalt

		Top 10 - Gründe für das vorzeitige Ende
				 von
			     PC-Benutzern

	1.) Sie versuchen mit Windows zu arbeiten. Das ist so
	    deprimierend und der User stürzt sich irgendwann aus dem
	    Fenster.

	2.) Windows macht einen Fehler und funktioniert! Der total
	    verschreckte PC-Benutzer denkt an den Weltuntergang und
	    erschießt sich.

	3.) User wartet auf Windows und stirbt an Altersschwäche.

	4.) User versucht, Windows von Disk zu starten und vom vielen
	    Diskettenwechsel fällt ihm der Arm ab und er verblutet.

	5.) User fährt zu Vobis und stellt sich brav hinten ans Ende der
	    Schlange. Leider ist das Ende der Schlange auf einer viel-
	    befahrenen Hauptstraße und der User wird von einem 80t-LKW
	    plattgefahren, wo dick "Motorola" auf der einen und
	    "Intel Outside" auf der anderen Seite steht.

	6.) User started ein Spiel und es läuft auf Anhieb ohne vor-
	    herige Konfiguration, ohne Ruckeln, mit 1 MB Speicher! Das
	    hält der erfahrenste PC-Benutzer nicht aus: HERZINFARKT!

	7.) User sieht einen Amiga 4000 mit Grafikkarte in Aktion und
	    wird dadurch bekehrt. Er wift seinen PC aus dem Fenster,
	    verbrennt feierlich die Windowsdisketten und kauft sich noch
	    heute einen Amiga 4000 mit ALLEM.

	8.) Er hat ein Spiel falsch konfiguriert und der Sound wird über
	    den Speaker ausgegeben. Da er einen Kolani-Rechner hat und
	    leider kein spitzer Gegenstand in der Umgebung liegt, das
	    Programm den Reset gesperrt hat und der User den Rechner
	    nicht ausschalten kann, weil in seiner Ramdisk/Cache noch
	    Daten liegen könnten, wird der User wahnsinnig und läuft
	    solange mit dem Kopf gegen den PC, bis der explodiert oder
	    die Männer mit den weißen Kitteln kommen.

	9.) User fährt sein Windows auf einem zu kleinem Rechner, mit
	    der Folge, daß Windows tierisch auf der Platte ackert und
	    diese dadurch so heiß wird, daß es zu einem China-Syndrom
	    kommt. Es findet aufgrund der hohen Temperaturen eine Kern-
	    schmelze statt und die Platte frißt sich durch die Erde auf
	    die andere Seite derselben.

	10.) User klickt nichtsahnend ein Menü an und dekodiert so ver-
	    sehentlich die Windows-Highscore. Windows wurde von Microsoft
	    am Anfang als Spiel gedacht. Nur die PC-Benutzer haben das
	    Spiel für eine Benutzeroberfläche gehalten und Micro-Soft
	    konnte keinen Rückzieher mehr machen. User stirbt, an Welt-
	    bildveränderung: Windows=Spiel???

@ENDNODE

@NODE ST0016 "Dornröschen"
@TOC Witze.guide/Inhalt

	Und nun aus unserer beliebten Reihe
	"Die Großmutter von heute"
	präsentieren wir: DORNRÖSCHEN.

	Das muß ein ziemlich nobler Schuppen gewesen sein, wo die die
	Taufe gefestet haben. Mit dem Kind, das hatte am Anfang nicht
	so richtig geklappt. Vielleicht war die Dame schon zu alt oder
	mit den Hormonen hat was nicht gestimmt. Jedenfalls war jetzt
	alles unheimlich happy und ließ so richtig die Sau raus.

	Unheimlich viele People waren eingeladen, aber eine von den
	Tanten hatten se wieder ausgeladen, weil sie kein Geschirr mehr
	für die hatten. Und wie das mit der Verwandtschaft so ist, die
	alte Schachtel war wohl unheimlich Sauer, hat se nen ziemlichen
	Terror gemacht und rumgekeift: Das Kind solle sich, wenns 15 ist,
	an so nem spitzen Ding stechen unn tot umfallen. Dann war ihr
	das wohl doch ein bißchen zu dicke und sie hat gesagt, nich tot
	sondern nur 100 Jahre pennen sollte se.

	Und wie das Baby 15 war und so ne richtig heiße Biene, da
	latscht sie so durch den Nobelschuppen durch, ackern brauchte
	sie ja nicht, weil die Alten so viel Kies an den Füßen hatten.
	Da kommt sie an eine Tür, die immer verrammelt war. Dahinter
	saß ne Alte, wahrscheinlich die von eben, und machte mit so nem
	Spinnrad rum. Irgendwie muß sie dann an ne Nadel gegriffelt
	haben, jedenfalls kippte sie aus den Latschen und pennte voll
	ein. Und der ganze übrige Laden machte auch die Poofe. Um den
	Schuppen rum machte dann ein Mords Grünzeug dicht. Also unser
	Nachbar hätte da ja einen unheimlichen Zoff wegen gemacht. Aber
	so reichen Peoplen, denen kann man ja nix wollen. Es kamen dann
	ziemlich viele starke Typen angeheizt, die scharf auf den Zahn
	waren und ihn abschleppen wollten. Die kamen nicht rein und
	machten die Mücke. Schließlich kam ein unheimlich heißer Macker,
	der ein Sauglück hatte, weil nämlich gerade die 100 Jahre gelaufen
	waren. Der kam durch das Grünzeug wie nix, geht zu Couch, wo der
	Teeny flezt, knutscht sie ordentlich, die wacht auf un der ganze
	übrige Laden auch.

	Und zum Schluß haben die dann alle zusmmen ne unheimlich heiße
	Show abgezogen!

@ENDNODE

@NODE ST0017 "Schülergebet"
@TOC Witze.guide/Inhalt

			I C H  G L A U B E
		an die Schule, den Ursprung aller
		Leiden und Qualen, und Mathe, das
		größte Übel über unserer Schule,
		empfangen durch den Lehrer, erlitten
		von den Schülern, die gequält,
		gestorben und auferstanden, zugrunde
		gegangen am Streß der Lehrer,
		aufgefahren aus dem Schulschlaf,
		sitzen sie zur Rechten des Kumi, von
		dort werden sie kommen zu richten
		die Lehrer und die SMV.

			I C H  G L A U B E
		an die seligen Ferien und das heilige
		Wochenende, an das erlösende
		Klingelzeichen, an die
		Zusammenarbeit bei Examen, an die
		Vergebung von Verweisen und an die
		möglichst baldige Erlösung!

			    A M E N

@ENDNODE

@NODE ST0018 "Tagebuch eines Studenten"
@TOC Witze.guide/Inhalt

		* 1. Semester *

	-05:30 Der Quarz-Uhr-Timer mit Digitalanzeige gibt ein zaghaftes
	 "Piep-Piep" von sich. Bevor sich dieses zu energischem Ge-
	 zwitscher entwickelt, sofort ausgemacht, aus dem Bett gehüpft.
	 Fünf Kilometer Jogging um den Aasee, mit einem Besoffenen zu-
	 sammengestoßen, anschliessend eiskalt geduscht.

	-06:00 Beim Frühstück Wirtschaftsteil der Vortagszeitung re-
	 petiert und Keynes interpretiert. Danach kritischer Blick in
	 den Spiegel, Outfit genehmigt.

	-07:00 Zur Uni gehetzt. H1 erreicht. Pech gehabt: erste Reihe
	 schon besetzt. Niederschmetternd. Beschlossen, morgen doch noch
	 eher aufzustehen.

	-07:30 Vorlesung, Mathe Kolberg. Keine Disziplin! Einige Kommili-
	 tonen lesen Sportteil der Zeitung oder gehen zu Bölling früh-
	 stücken. Alles mitgeschrieben. Füller leer, aber über die Witz-
	 chen des Dozenten mitgelacht.

	-08:00 Vorlesung, Buchführung Issel. Verdammt! Extra neongrünen
	 Pulli angezogen und trotz eifrigem Fingerschnippens nicht dran-
	 gekommen.

	-10:45 Nächste Vorlesung. Nachbar verläßt mit Bemerkung "Sinnlose
	 Veranstaltung" den Raum. Habe mich für ihn beim Prof entschuldigt.

	-12:00 Mensa Stammessen II. Nur unter größten Schwierigkeiten 
	 weitergearbeitet, da in der Mensa zu laut.

	-12:45 In Fachschaft gewesen. Mathe Skript immer noch nicht fertig.
	 Wollte mich beim Vorgesetzten beschweren. Keinen Termin bekommen.
	 Daran geht die Welt zugrunde.

	-13:00 Fünf Leute aus meiner 0-Gruppe getroffen. Gleich für drei
	 AG's zur Klausurvorbereitung verabredet.

	-13:30 Dreiviertelstunde im Copyshop gewesen und die Klausuren der
	 letzten 10 Jahre mit Lösungen kopiert. Dann Tutorium: Ältere
	 Semester haben keine Ahnung.

	-15:30 In der Bibliothek mit den anderen gewesen. Durfte aber statt
	 der dringend benötigen 18 Bücher nur vier mitnehmen.

	-16:00 Proseminar. War gut vorbereitet. Hinterher den Assi über
	 seine Irrtümer aufgeklärt.

	-18:30 Anhand einschlägiger Quellen die Promotionsbedingungen ein-
	 gesehen und erste Kontakte geknüpft.

	-19:45 Abendessen. Verabredung im "Blauen Haus" abgesagt. Dafür
	 Vorlesungen der letzten paar Tage nachgearbeitet.

	-23:00 Videoaufzeichnung von "WiSo" angesehen und im Bett noch
	 das "Kapital" gelesen. Festgestellt, 18-Stunden-Tag zu kurz. 
	 Werde demnächst die Nacht hinzunehmen.


		* 13. Semester *

	-10.30 Aufgewacht! Ach, Kopfschmerzen, Übelkeit, zu deutsch: KATER!

	-10.45 Der linke große Zeh wird Freiwilliger bei der Zimmertem-
	 peraturprüfung. (Arrgh!) Zeh zurück. Rechts Wand, links kalt;
	 Mist, bin gefangen.

	-11.00 Kampf mit dem inneren Schweinehund: Aufstehen oder nicht -
	 das ist hier die Frage.

	-11.30 Schweinehund schwer angeschlagen, wende Verzögerungstaktik
	 an und schalte Fernseher ein (inzwischen auch schon verkabelt).

	-12.05 Mittagsmagazin beginnt. Originalton Moderator: "Guten Tag
	 liebe Zuschauer - Guten MORGEN liebe Studenten." Auf die
	 Provokation hereingefallen und aufgestanden.

	-13.30 In der Cafetaria der Mensa am Aasee beim Skat mein 
	 Mittagessen verspielt.

	-14.30 In Rick's Cafe hereingeschaut. Geld gepumpt und 'ne Klei-
	 nigkeit gegessen: Bier schmeckt wieder! Kurze Diskussion mit
	 ein paar Leuten über die letzte Entwicklung des Dollar-Kurses.

	-15.45 Kurz in der Bibliothek gewesen. Nix wie raus, total von
	 Erstsemestern überfüllt.

	-16.00 Fünf Minuten im Seminar gewesen. Nichts los! Keine Zeitung,
	 keine Flugblätter - nichts wie weg.

	-17.00 Stammkneipe hat immer noch nicht geöffnet.

	-18.15 Wichtiger Termin zuhause: BINGO!

	-18:20 Mist! Kein BINGO! Stattdessen Live-Übertragung von Stöhn-
	 Seles. SAT 1 war auch schon besser...

	-19.10 Komme zu spät zum Date mit der blonden Erstsemesterin im
	 Havanna. Immer dieser Streß!

	-01.00 Die Kneipen schließen auch schon immer früher... Umzug ins
	 Jovel.

	-04.20 Tagespensum erfüllt. Das Bett lockt.

	-05.35 Am Aasee von Erstsemester über'n Haufen gerannt worden. 
	 Hat mich gemein beschimpft.

	-06.45 Bude mühevoll erreicht. Insgesamt 27,50DM ausgegeben. Mehr
	 hatte die Kleine nicht dabei.

	-07.05 Schlucke schnell noch ein paar Alkas und schalte kurz das
	 Radio ein. Stimme des Sprechers: "Guten Morgen liebe Zuhörer, 
	 gute NACHT liebe Studenten."

@ENDNODE

@NODE ST0019 "Tagebuch eines Trinkers"
@TOC Witze.guide/Inhalt

	-28.1. Schlafstörungen, Kopfkissen in Wodka getränkt. Lautes
	 nächtliches Pfeifen läßt sich nicht lokalisieren. Gegen Morgen
	 Heizkörper abgeschraubt, keine Änderung. In der Nacht wieder
	 Angst, vor dem Fenster könnten Aborigines auf Traumtröten blasen.

	-30.1. Unverändert Schlafstörungen. Gläschen zählen erfolglos.
	 Fläschchen Baldriantiktur (68%) ex. Hätte sicher Schlaf gefunden,
	 wenn sich die Nachbarskatze nicht schreiend auf meinem Gesicht
	 gewälzt hätte. Hände gerungen. Schwedenbitter, Harndrang.

	-12.2. Früh zu Bett, um Mitternacht wegen Schlaflosigkeit wieder
	 aufgestanden. Unter Zuhilfenahme aller Finger mindestens bis
	 fünfzehn gezählt, dabei manches Mal die Augen verdreht und den
	 Mund verzogen. Nachbarkeller aufgebrochen, getrunken.

	-14.2. Teures Mittel gegen Magnesiummangel gekauft. Viel von
	 Paralleluniversen gelesen, versucht hinzugelangen, häßlicher
	 Sturz. Noch am Boden liegend Wunder erlebt! Verstorbener Groß-
	 vater erschien, um mir Scharlachbergflasche hinzustellen.
	 Große Hilfe.

	-20.2. Ich warf alles nach jedem. Ruhe erlangt durch Insel-Samos.

	-27.2. Wegen Henriette in der "Schimpansenbar". Verbrüderungs-
	 szenen im Keller, Whisky aus Schuhen, zuletzt wieder so eine
	 dreiste Person rittlings auf mir. Nach heimischer Badewanne
	 gesehnt (Eierlikör-Oberkörpereinreibung), später des Nachts
	 urethrale Schikanen.

	-1.3. Perfekter Tag. Spät abends habe ich mir dann noch ein
	 Käsebrot geschmiert und mich draufgesetzt. Viel Wein.

	-10.3. Obsession beschlossen: ins Treppenhaus schleichen und das
	 entblößte Gesäß an die Wohnungstür gegenüber drücken. Der ver-
	 gilbte Lack muß angenehm kühl sein. Wann werde ich es zum
	 erstenmal tun?

	-11.3. Obsession ist Scheiße. Anläßlich eiliger Flucht vor
	 Nachbarin vom eigenen Schlafrock zu Fall gebracht. Liegen-
	 geblieben, totgestellt. Tiefe Scham, später massives Trinken.

	-19.3. Nachgedacht über Worte eines Freundes: "Die Sonne müßte
	 Nachts scheinen, am Tage ist es doch sowieso hell."
	 Wieder geweint. Rum.

	-4.4. Allein im Haus. Vorsichtig Bällchen in alle Zimmer
	 geworfen. Keine Reaktion. - Hastig getrunken, übergeben (5x).

	-9.4. Zwecks Betrachtung des Sonnenunterganges Rangierbahnhof
	 aufgesucht. Allergrößtes Mitleid für zwei alte D-Zugwagen auf
	 dem Abstellgleis empfunden. Ihr Anblick ließ mich aufschluchzen
	 und unter konvulsivischen Zuckungen Liter von Tränen vergießen.
	 Erst lange nachdem man mich in eine Nachtbar fortgeschafft
	 hatte und mir unter stetigem Einschenken gut zuredete, konnte
	 ich nach und nach zur Ruhe kommen.

	-15.4. Wieder "Schimpansenbar". Auf der Heimfahrt vom Taxi-
	 fahrer Nottaufe erhalten. Lange gemeinsam Mond betrachtet und
	 Geld gezählt.

	-27.4. Haydn gehört, Flaschen leergetrunken.

	-2.5. Gestern im Ärztehaus. Drei Stunden in der falschen Arzt-
	 praxis gewartet, dann versehentlich Termine bei Heilgymnastin
	 besorgt. Panik im Treppenhaus verursacht, Hausverbot in der
	 Apotheke. Schändlich besoffen, beidseitiges Trommelfellflattern.

	-8.5. Letzten Abend mit zwei Flaschen Chianti im Opernhaus,
	 "Orpheus und Eurydike", sehr geschimpft. Nichts ist so ekelhaft
	 wie Knabensopran, darüber hinaus vehement bemängelt, daß Orpheus
	 von einer Frau (Zarah Leander?) gesungen wird. Jede Kontrolle
	 verloren, hinausgetragen worden. Überfallkommando, sehr ver-
	 stimmt, Gaderobenfrau wollte mich mit ihrer mißratenen Tochter
	 verkuppeln.

	-10.5. Im Kino wieder zwei Finger abgestorben. Im Foyer Hans
	 und Rose getroffen, die sich als Junge und Mädchen verkleidet
	 hatten. Unguter Auftritt in der Bar, Notarztwagen.

	-14.5. Mit Henriette weißen Rheinwein probiert. In Karohemden
	 stundenlang an der Decke gekniet. Immer gesagt: "Aufpassen,
	 daß sich nichts verschiebt (Ebenen!)." Gegen Morgen heftige
	 Önomanie. In der Notaufnahme Akten vernichtet.

	-29.5. Gedicht geschrieben: "Managerschulung - ritsch ratsch
	 reisele, geht die Welt im Kreisele"; Rotwein, in der Badewanne
	 eingeschlafen, Prostataentzündung.

	-2.6. Viel Gin auf Anraten Hansens, Wasserlassen klappt besser.

	-9.6. Der Arzt macht mir Hoffnung; ich höre, wie die Urologen
	 lachen. Heute zum ersten Mal versehentlich Wein in die Pfeife
	 geschüttet.

	-12.6. Es wird behauptet, ich hätte letzte Nacht versucht, im
	 Schlafanzug den Straßenverkehr auf der Kreuzung zu regeln.
	 Mißtrauen, unsicher und verkrampft getrunken.

	-18.6. Nervengeschichten... fremde Bohnen sahen mich aus dem
	 Spiegel an - unbedingt Abstinenz üben!

	-21.6. Für diesen Satz hätte ich Karl May geliebt: "Winnetou
	 starb, ließ sich jedoch nichts anmerken." Etwas geweint, Brandy
	 durch Strohhalm.

	-30.6. Reimepos erwogen. Anfangs Lob der Frau, dann müßte Schil-
	 derung der Begegnung mit einem Nilpferd folgen oder Himmel-
	 fahrtswitz. Schlußformel könnte sein: "Und ein nackter Mann
	 stand tumb dabei." In der Küche vergeblich nach Cherry-Rest
	 gesucht, daher "Schimpansenbar". Halmasteinchen gekotzt,
	 Personalausweis verkauft.

	-2.7. Stimme aus der Steckdose gehört. Werde ich wahnsinnig?
	 Wein, Wein.

	-11.7. Seit heute zwei Stimmen. Eine sagt "Puppenhuhn", die
	 andere "Paradieswurst". Trotziges Trinken, aber doch Furcht.

	-12.7. Wenn ich J.S. Bach wäre, würde ich folgenden Satz vertonen
	 (Kantate): "Ich bleibe oft lange auf, trinke viel und schäme
	 mich für alle"; elterliche Hausbar vorgeknöpft, wieder Notarzt.

	-17.7. Nachmittags weinender Mann vor der Haustür. Wehe, wehe,
	 ich war es selbst. Strenger Cocktail, schließlich wieder Mut.
	 Ab 20 Uhr wieder gewissenhaft getrunken. Wohin sind die Tage,
	 wo Wasserlassen eine Selbstverständlichkeit war?

	-18.7. Gegen Abend in völlig fremden Kleidern aufgewacht. Starker
	 Wunsch, etwas über Hamster zu schreiben. Persiko-Trinkkur
	 begonnen.

	-29.7. Unleserliche Flammenschrift am Himmel; schon wieder diese
	 Bolzen im Teppich. Eierlikör.

	-31.7. Das Geräusch aneinanderklirrender Weinflaschen lockte
	 mich gestern Abend in den Nachbargarten. Zunächst geduldet,
	 trank ich allen süßen Wein. So wie ich aber anfing, den Nach-
	 barn von Schrödingers Katze und den Wundern der Quantenwelt zu
	 berichten (wobei ich bedauerlicherweise bis zum Ellenbogen
	 im Dekolltee der Tochter des Hauses stecken blieb), warfen sie
	 mich über die Hecke. Mildtätige Zwerge fanden mich und pflegten
	 mich in ihrer Höhle gesund.

	-1.8. Geträumt: nach 37 Jahren erstmals wieder aus dem Fenster
	 geschaut. Die Landschaft hatte sich stark verändert, der Fluß
	 trug sogar Koteletten.

	-5.8. Mit Person, an die ich mich nicht erinnern kann (Henriette?
	 Hans?) irgendwie über Land gegangen. Wir liefen bergab durch
	 Gärten hindurch. Oder dran vorbei. Wir legten uns nach reif-
	 lichen Überlegungen an den Straßenrand und versuchten, zu sterben.
	 Auf den Tod wartend schauten wir in die Luft. Die Fliegen flogen
	 verkehrt herum und sahen aus wie große Damen. Auf dem Heimweg
	 Glossolalie: indogermanische Trinklieder mit leicht schlüpf-
	 rigen Kehrreimen. Champagner!

	-23.8. Heute den vierten Tag bei herabgelassenen Jalousien und
	 Kunstlicht in der Wohnung, meist im Bett. Hatte mir große
	 Inspiration von solcher Lebensweise versprochen (etwa wie H.P.
	 Lovecraft), bis jetzt aber nur mit Voodoo-Puppen herumgefudelt.
	 Rechter Hausschuh ins Klo gefallen. Danziger Goldwasser bis zum
	 Erbrechen.

	-4.9. Seit Wochen nur über moderne Physik und das Bermudadreieck
	 gelesen. Spüre, wie mein Leben wieder einen Halt bekommt. Im
	 Kaufhof haben sie neue Rolltreppen. Leberwerte verheerend. Am
	 leicht geöffneten Fenster verbrachte ich im Clubsessel sitzend
	 eine der glücklichsten Zeitspannen meines Lebens.

	-6.9. Brief vom Wiener Verleger. Muß echt sein, Henriette sieht
	 ihn auch. Einladung zur Lesung. Große Angst vor weiter Reise,
	 "Mut angetrunken", Rasierapparat und einzig gute Hose ruiniert.

	-12.9. Eine Woche lang mit Henriette verreist gewesen. Nach der
	 Rückkehr erfahren, daß wir in der Bretagne waren und nicht, wie
	 ich irrtümlich annahm, in der Toskana. Wieso aber bekomme ich
	 heute eine Ansichtskarte von uns aus Florenz? In Jeans Weindepot
	 alle Reste ausgetrunken, nachdenklich.

	-14.9. Sitze im Zug nach Wien. Henriette hat Affäre mit VHS-
	 Kursleiter. Soll ich lieber in Wien bleiben? Habe mir elegantes
	 Halstuch im Hemdkragen installiert. Markenwodka aus der Ther-
	 moskanne. Sehr weltmännisch, jedoch Fahrkarte verloren.

	-15.9. Wieder zu Hause. Anzeigen wegen Schwarzfahrens, Belei-
	 digung und Sachbeschädigung. Desolater Zustand. Versucht, von
	 Streifenpolizisten erschossen zu werden. Nur Ohrfeige erhalten.
	 Immerzu geschrien: "Ich sterbe, ich sterbe!" Zur nächsten
	 Lottoannahmestelle geschleppt, Magenbitter auf Kredit.

	-19.11. Durch jenseitige Beeinflussung Schlager geschrieben:
	 "Ball-a-Ball-a-Ball-Ball-a-Ball ... (etc.), der Blumenhund anbei,
	  so find ich euch, dem treff ich euermaßen an (quella) - Kwu
	  Kwäck-Ball-a-Ball-a-Ball-a-Ball ... (etc.) Und die Hirten-
	  mädchen lesen: So bist du du du mit deinem Blarr Blamm Blu-
	  menhund (wiederholen)"
	 Mit abnehmenden Flascheninhalt kristalliert sich die Melodie
	 heraus. Erregt, Zierleisten abgebrochen.

	-28.11 Religiöser Exzeß, Hausrat auf die Straße gestellt.
	 Schlaflos, brünstige Abstinenz.

	-29.11 Zwangsvorstellungen bezüglich Nachfolge Christi sind
	 abgeklungen. Viehisch besoffen.

	-1.12. Unbekannte Frau in der Fußgängerzone verbot mir, in ihren
	 Armen zu sterben. Wenig schöne Szene. Danach Glühwein und rück-
	 sichtslose Kirchenkritik auf dem Weihnachtsmarkt. Schürfwunden.

	-3.12. Im Keller sitzen seit ein paar Tagen zwei alte Männer
	 unter einer Abdeckplane und essen schreckliche Butterbrote.
	 Zwischendurch gehen sie hinaus (in Unterhemden) und schlagen
	 mit großen Hämmern auf die Treppe. Betroffenheit meinerseits,
	 nicht länger vor marokkanischem Wein zurückgeschreckt.
	 Wadenkrampf.

	-6.12. Die Flasche ist 2 Monat und 15 Tagen nicht so leer gewesen.

	-28.12. Alkohol wirkt nicht mehr bei mir. Vor einer Stunde Gift
	 genommen. Enttäuschung: es wirkt auch nicht, Scheiße!

@ENDNODE

@NODE ST0020 "Anleitung (I)"
@TOC Witze.guide/Inhalt

   Hier Ausschnitte aus der *ultimativen Anleitung*.
   Weil die Anleitung von Fehlern nur so wimmelt (und die Gefahr
   groß ist, dabei welche zu übersehen :-) habe ich die schönsten
   gekennzeichnet.Besonders im "Finale" erreicht die Anleitung
   literarische Qualität ;-)

   Wer keine Lust hat, alles zu lesen, sollte sich unbedingt das
   Ende der Anleitung zu Gemüte führen.

   Kein Übersetzungscomputer hätte es schöner machen können, als
   die sprachliche Symbiose von Übersetzer und Drucker in Fernost...


				ANTLEITUNG
	    Technische Anderungen, die dam fortschritt dienen,
				Vorbahalten
		     DIGITAL-QUARTZ-REISEEWECKER
				      <^^^>

	* 4 *stallige* LCD-Anzeige-Kalenderautomatik

	* Alarmzeit in Stunden und Minuten

	* Stunden-Alarm, d.h. zu jeder vollen Stunde eront ein (Biib)
	  Ton - Abschaltbar.

	* Belsuchtung des LCD-Anzeigefellues auf Knopfdruck.

	BEDIENUNG DER UHR:

   <hübsches Bildchen - - - ohne Fehler :-)))>

	NORMALZEIT UND DATUM-FUNKTION:
	In Normal funktion Zeight die Uhr Stunden/Minuten an. Doppalpunkt
	blinkt im Sekundentak. Durch 2 mal Druck auf A-,B- oder C-knopf
	erscheinen Monat/Datum. Rückkehr zur Normalzeit-Anzeige erfolgt
	automatisch. Durch 3 mal Druck auf A-,B- oder C-Knopf erfolgt
	dauernde Sekunden Anzeige, Ruckkehr zur Normalzeit-Anzeige durch
	erneuten Durck auf A-,B- oder C-Knopf.

	MELODIE-ALARM-FUNKTION:
	Durch 1 mal Druck auf A-,B- oder C-Knopf wird die Uhr von
	Normalzeit auf Alarmzeit-Anzeige umgeschaltet. *Anziege* der
	Alarmzeit in Stunden und Minuten, zussmen mit dam indikator
	'AL'. Alle Stunden von 0-12 Uhr Mittage werden ohne und als
	Stunden von 12-24 Uhr mit 'P'gekennzeichner. Ruckkshr zur
	Normalzeit-Anzeige erifogt automatisch, Zum Ein- bzw, Ausschalten
	des Alarms bitte wahrend der Alarmzeit-Anzeigo F-Schalter von
	'LOCK' Position nach rechts oder nach links schieben und dan
	1 mal Druck auf E-Knopf. Alarm EIN/AUS wird durch Erschedinen
	oder Verschwinden des Alarm-Symbols verdeutlich Wenn die
	Normaizeit die eingestewllte Alarmzeit erreicht und des Alarm-
	Symbol <des? in Bayern Deutsch gelernt???> sichtbar ist, ertont
	die Melodie, Zum vorzeitigen Abschal jes Alarms bitte 1 mal
	Druck auf A-, B- oder C-Knopf.

	TEST-ALARM-UNDSTUNDEN-ALARM-FUNKTION:
	(Normalzeit ist in der Anzeige)
	Durch anheltenden Druck auf A-, B- oder C-knopf ertont die
	Melodie. Gleichzeitig wird der Stunden-Alarm *ain- bzw.
	Ausgwschaltet*. An dern blinkenden Doppeipunkt in der Alarmzeit-
	Anzeige konnen Sie erkwnnen, dass der Stunden-Alarm eingeshaltet
	ist. In diesem Fall ertont zu jeder vollen Stunde ein (biib)
	Ton. Zum Ausschalten des Stunden-Alarms wiederhoien Sie einfach
	den Alarmtest.

	EINSTELLUN G: NORMALZEIT UND DATUM
	(Normalzeit ist in der Anzeige)
	Bitte F-Schalter von Position 'LOCK'nach rechts oder nach links
	achiban Dann anhaltend (über 3 Sekunden) auf E-Knopf drücken.
	Sekunden blinken und Können durch Druck auf A-, B- oder C-Knopf
	auf Null *gesstzi* werden. Durck auf E-Knopf: 1 mal Stunden
	blinken mit 'A' oder 'P', Einstellung mit A-, B- oder C- Knopf
	 A = alle Stunden von 0-12 Uhr mittags
	 P = alle Stunden von 12-24 Uhr.
	Nur wenn Sie dies genau beachten, wird auch des Detum <des?
	tatsächlich Bayern!> sofort nach Mitternacht automatisch auf den
	nächsten <man beachte den ERSTEN Umlaut des Textes> Tag
	eingestellt. 2 mal Erstes Minuten-Segment blinkt, Einstellung
	mit A-, B- oder C-knopf 3 mal Zweites Minuten-Segment blinkt,
	Einstellung mit A-, B- oder C-Knopf
	 4 mal   Monat blinkt, Einstellung mit A-, B- oder C-Knopf
	 5 mal   Datum blinkt, Einstellung mit A-, B- oder C-Knopf
	Einstellung ist beendet, Rückkehr zur Normalanzeige durch
	erneuten Druck E-Knopf. Wenn Sie nicht die gessmits Reihenfoige
	durchs möchten, kann die Uhr nach jedor bellebigen Einstellung
	durch Sekunden langes Drücken des E-Knopfes auf Normalanzeige
	Zurückgebracht werden. Ausserdem schaltst sich die Normalanzeige
	nach 2 Minuten automatisch wieder ein Bitte F-Schalter wieder
	auf Position 'LOCK' schiban, so kann die Einstellung nicht
	durch versehentliches *Drucken auf Irgendwetche Knopfe
	gesndert* werden.

	EINSTELLUNG: ALARMZEIT
	(Normalzeit) ist in der (Anzeige) <was wollen uns diese Klammern
	sagen?> Bitte F-Schalter von Position 'LOCK' nach rechts oder
	nach links schieben. Dann die Uhr durch Druck auf A-, B- oder
	C-Knopf auf Alarmzeit-Anzeige umachalten <irgendwetche Knopfe
	achiban??? :-)> Danach schnellfolgend, bevor die Uhr automatisch
	auf *Normalenzeige* umschaltet, Anhaltender druck (uber 3
	Sekunden) auf E-Knopf. Al-Stunden blinken, Einstellung mit A-,B-
	oder C-Knopf
	Druck auf E-knopf:
	  1mal	Erstes AL-Minuten-Segment blinkt, Einstellung mit A-,B-
		oder C-Knopf.
	  2mal	Zweites AL <ohne Bindestrich> Minuten-Segment blinkt,
		Einstellung mit A-,B- oder C-Knopf.
	  3mal	Einstellung ist beendst, Ruckkehr zur Normalzeit
		Anzeige erfolgr automatisch.
	bitte F-Schalter wieder auf Position 'LOCK' schieben.


   <JETZT KOMMT'S!!! Keine Kommentare mehr von mir - Dieses
    Prunkstück deutscher Literatur muß ab hier unkommentiert
    genossen werden!>


	BELEUCHTUNG DES LCD-ANZEIGEFELDES:
	Durch Druck auf D-Knopf wird das LCD-Anzeigefeld belsuchtet

	BATTERIEVERBRAUCH:
	Batterien sind Verschiessteils. Bitte beachten Sie, dass
	haufiges Batatigen der Beleuchtung bei LCD Uhran die Lobensdauer
	der eingosetzten Batterien entacheldend verkurzti

	AUSWECHSELN DER BATTERIS:
	Wenn die Anzeige schwach oder ungenau wird, ist dies ein Zeichen,
	dass die Batterie ausgewechsalt werden muss. Das Batteriefach
	betindet sich auf der Rucksalte des Reisewackers Entfernen Sie
	den Schiabeduckei und wechsein Sie die verbrauchte Batterie
	gegen sins neue aus. Bitte achten Sie auf die richtige Poleritat
	(3+ nach oban) der Batteris.

	Benotigt wird eins Batterie vom Typ: UCAR 392


   Abschließende Bemerkungen:

   Besonders schön finde ich, daß man nach mehrfachem Lesen immer
   mehr Kleinigkeiten entdeckt:

   So z.B. daß der Übersetzer vielleicht einige Zeit in Bayern
   verbracht hat, wo mundartlich "des" anstelle von "das" gesagt
   wird. Überhaupt schreibt er vieles nach Gehör ("ain", "oban" usw.)

   Seine Englisch-Kentnisse beweist er uns, mit den Worten "Zeight"
   und "eingeshaltet". Und "oban" -englisch ausgesprochen- klingt
   tatsächlich wie deutsch "oben"!

   Völlig verzweifelt ist er sicher an der Groß-/Kleinschreibung.
   Aber er löst das Problem geschickt, indem er in Zweifelsfällen
   einfach abwechseld groß und klein schreibt.

   Auch scheint die Übersetzung handschriftlich angefertigt geworden
   zu sein. Der Drucker hatte offensichtlich große Schwierigkeiten
   "e" und "s" zu unterscheiden (oder waren die e's knapp? ;-) und
   oft fügt er bei "ll" oder "nn" noch ein "w" ein; ich habe keine
   Ahnung warum.

   Kopfzerbrechen bereitet mir noch folgende Zeile:
   (Normalzeit) ist in der (Anzeige)
   Es ist ja manchmal üblich Bezeichnungen für Tasten einzuklammern
   wie (ESC) oder (CTRL) usw. aber was soll das hier? Und warum nur
   unter einer Überschrift...immerhin taucht die Zeile noch zweimal
   ohne Klammern auf!

   Und dann muß mir unbedingt 'mal jemand erklären, warum der
   Reisewacker :-) eigentlich drei Knöpfe A, B und C hat.

   Ein Stück Literatur.
   Stundenlang könnte ich mich damit beschäftigen! ;-)

   Ich glaube nicht, dass die zu schlagen ist...

@ENDNODE

@NODE ST0021 "DFÜ im Jahre 2011"
@TOC Witze.guide/Inhalt

	Hallo, hier ist die Z.D.M.

	 > Please press 'Return' :


	# Zimmermann Datenbank München
	Nur für eingetragene User!

	 #######    #####     ###  ###
	     ##      #  ##     #\  /#
	    ##       #   #     # \/ #
	   ##        #  ##     #    #
	 ####### ## #####  ## ###  ###

	Die Datenbank unseres Vertrauens

	BREAK!

	 > Geben Sie ihre Daten ein!

	Username:SAMMY
	Passwort:********

	Wait!

	SYSTEM:

	Beim letzten Login haben Sie wesentlich  schneller  eingetippt!
	Da wir nicht  ausschließen können, daß Sie ein Hacker sind,
	geben Sie Sicherheitsabfrage 2 ein. Danke!

	ABFRAGE 2:********

	Mmmmm..nun gut,  hoffentlich fangen sie sich wieder. Sicher-
	heitshalber nur Level 7.

	* SET LEVEL TO 7 *

	Hallo Herr Winz!

	Seit ihrem letzten Anruf kamen 2653 Gigabyte Daten unter 325434
	verschiedenen Stichwörtern hinzu. Sie haben derzeit 15
	Recherchen laufen. Es liegen 2 Ergebnisse vor:


	1) Recherche "Pornografie in EMMA" .... 230 KB
	2) Recherche "Kohlwitze"           .... 230 GB

	Es wurden 14 Briefe von geringer Wichtigkeit gelöscht!


	=> HELP


	Vermerk in Akte!

	LESEN	   SCHREIBEN	 INHALT		BRETT	RECHERCHE
	PROTEST	   BRIEF   	 HILFE/HELP	SET	POST

	=> INHALT

	Inhalt am 13.6.2011

	* Vorselektierung *


	Allgemeine Weltpolitik..763MB  Strickmuster 2011............800MB
	Witze der Welt.........1324MB  Mailboxliste..................60MB
	CAC INTERNATIONAL.......342MB  Was ist für den Staat zu tun?.80MB

	0.76 % des Inhaltes

	=> SET VORSELEKTIERUNG AUS

	Systemmeldung: Leider nicht möglich. Überprüfung des Accounts
	läuft noch.

	=> BRIEF

	Folgende User sollten sie mal anschreiben:

	HELMUT
	HEINRICH
	KARL
	ADOLF

	Name:

	* BREAK *

	SYSTEM: Eintrag in die Akte!



	=> PUST

	Unbekannte Befehlsfolge "PUST", Eintrag in Akte.


	=> POST

	SYSTEM: War nicht von Interesse, wurde daher gelöscht.

	=> BRIEF SYSOP

	SYSTEM: Sie haben immer noch keine Briefe an die
		vorgeschlagenen Personen geschickt!
		Eintrag in Akte.

	Editor
	------

	(S)chreiben   (E)dit     (G)enerieren

	SYSTEM: START AUTO.GEN...

	=> G

	1> Hallo Chef!
	2>
	3> Ich möchte nur sagen wie froh ich bin daß ich in deinem
	4> System sein darf

	* BREAK *

	SYSTEM: Sie haben den automatischen Briefgenerator ausgeschaltet.
		Das gibt eine Eintragung im Zentralregister.

	* LEVEL SET TO 3 *

	=>BRIEF SYSOP

	(S)chreiben   (E)dit     (G)enerieren

	=>S

	 1>Hey Sysop!
	 2>
	 3>Ihr meint wohl ihr könnt mich verarschen, was?  Wieso wird
	 4>meine Post gelöscht? In den 80'ern nannte man das "Zensur"!
	 5>Und was heißt hier Akte? Ich verlange, daß alle Daten sofort
	 6>gelöscht werden!
	 7>Mfg
	 8>
	 9>SAMMY!
	10>======
	11>.

	(S)chreiben   (E)dit     (G)enerieren

	<TASTE>_______=> E

	Edit:

	(L)esen       (D)elete   (Z)eilenedit

	=> L

	 1>Grüß dich Sysop!
	 2>
	 3>Ich bin ein wenig verwirrt. Ich fand es zwar richtig daß
	 4>meine unwichtige Post gelöscht wurde, würde aber gerne
	 5>(wenn es geht) mal einen Blick hinein werfen. Danke daß
	 6>du so sorgsam die Akten führst! Bis bald.
	 7>Der dich bewundernde
	 8>
	 9>SAMMY!
	10>======

	(L)esen       (D)elete   (Z)eilenedit

	=> D

	SYSTEM: Nein, der Brief war gut. Machen Sie bitte weniger
		Fehlentscheidungen.


	10 Zeilen abgespeichert!

	=> B ALL

	SYSTEM: Das Brett "Allgemeine Mail" enthält keine für sie
		wichtigen Einträge.

	=> PROTEST

	Möchten Sie gegen etwas protestieren (J/N) =>J

	Betreff: SCHEISSLADEN!

	Wählen Sie:

	1. Zu wenig Sicherheit   2. Zu wenig Ordnung  3. Zu viel Chaoten
	4. Mehr Überwachung      5. Sonstiges

	=>>5

	SYSTEM: Soso, sie protestieren wegen irgentwelchem
		unwichtigen Scheiß!
		Eintrag in Akte.


	=>BRIEF SNORR

	Hinweis des Systems: Diese Person wird seit geraumer Zeit von uns
	überwacht,und dürfte wohl kaum zum Umgang mit Ihnen geeignet sein.
	Sollten sie auf einem (natürlich zensierten) Kontakt bestehen,
	so werden sie automatisch als "Schädling" eingeordnet, und beim
	nächsten Update ausgedünnt.

	SYSTEM: User wurde ausgesondert, daher kein Kontakt möglich

	=>E

	SYSTEM: Sie haben nur 23% ihres wöchentlichen Pensums
		erfüllt!! Des weiteren haben sie den vorgeschlagenen
		Personen noch nicht geschrieben. Tun sie erstmal was,
		dann können sie auch gehen!

	=>IHR KÖNNT MICH MAL!

	NO CARRIER

@ENDNODE

@NODE ST0022 "Neulich im Funkverkehr"
@TOC Witze.guide/Inhalt

	Übrigens: alle Funk-Stories sind aus verschiedenen Ausgaben
	des FliegerMagazins unter dem Thema "Rodscher".

	Und sorry für das Englisch hier innem deutsche File, aber
	manche Witze kann man nun mal nicht übersetzen... :-(

	Pilot: "Bratislava Tower, this is Oscar Oscar Kilo estabished
	   ILS 16."
	Tower: "Oscar Oscar Kilo, Guten Tag, cleared to land 16, wind
	   calm - and by the way: this is Wien Tower."
	P: (Nach einer Denkpause) "Bratsilava Tower, Oscar Oscar Kilo
	   passed the outer marker."
	T: "Oscar Oscar Kilo roger, and once more: you are approaching
	   Vienna!"
	P: (Nach einer Denkpause) "Confirm, this is NOT Bratislava?"
	T: "You can believe me, this is Vienna!"
	P: (Nach einer erneuten Pause) "But why? We want to go to
	   Bratislava, not to Vienna!"
	T: "Oscar Oscar Kilo, roger. Discontinue approach, turn left
	   030 and climb to 5000 feet, vectors to Bratislava."

	T: "Delta Delta Whiskey, rollen Sie über Teerweg zwo null neun
	   Charlie und Mike zum GAT."
	P: "Äh...Teerweg zwo...?"
	T: "Das ist der kleine rechts. Sie sind gerade dran vorbei-
	   gerollt."
	P: "Sorry."
	T: "Don't worry, nehmen Sie den Mike."
	P: "Äh, ...Mike ?"
	T: "Das ist der letzte ganz hinten rechts..."

	P: "Condor 471, gibt's hier keinen Follow-me ?"
	T: "Negativ, sehen Sie mal zu, wie Sie allein zum Gate 10 kommen."

	P: "...Tower, please call me a fuel truck."
	T: "Roger. You are a fuel truck."

	Controller: "Phantom-Formation crossing controlzone without
	   clearance, state your callsign!"
	P: "I'm not silly..."

	C (in Stuttgart): "Lufthansa 5680, reduce to 170 knots."
	P: "Das ist ja wie in Frankfurt. Da gibt's auch nur 210 und
	   170 Knoten... Aber wir sind ja flexibel."
	C: "Wir auch. Reduce to 173 knots."

	C: "RFG 312, fliegen Sie direkt nach Olno VOR. Brauchen Sie
	   einen Radar-Vektor?"
	P: "Nein, es geht auch so, wir können das VOR schon empfangen.
	   Es liegt genau in der Richtung, wo der Mond steht."
	C: "Ja, aber den haben wir nicht auf dem Radarschirm."

	P: "Ground, XY-line 195, requesting start-up."
	Ground: "Sorry, XY-line 195, we don't have your flight plan.
	   What is your destination ?"
	P: "Wie jeden Montag, nach Leipzig."
	G: "Aber, wir haben heute Dienstag!"
	P: "WAS ? Am Dienstag haben wir doch frei!"

	C: "Hawk 20, is this the same aircraft declaring emergency
	    about two hours ago ?"
	P: "Negativ, Sir. It's only the same pilot."

	P: "Tower, da brennt ein Runway-light."
	Lotse: "Ich hoffe, da brennen mehrere."
	P: "Sorry, ich meine, es qualmt."

	C: "Delta Zulu Romeo, turn right now and report your heading."
	P: "Wilco. 341, 342, 343, 344, 345..."

	T: "Lufthansa 893, number one, checkcar on the runway."
	P: "Roger we'll check the car on the runway."

	C: "Delta Romeo Zulu, confirm you are inbound to Sulz NDB?"
	P: "Affirm, but we don't receive it."

	C: "Delta Oscar Mike, squawk 0476."
	P: "Say again."
	C: "Squawk 0476."
	P: "Four, zero...?"
	C: "Wollen Sie'n leichteren haben ?"

	C: "Delta Bravo Charlie, ist Ihr Squawk wirklich
	   sieben null vier sechs?"
	P: "Positiv."
	C: "Ich mag's kaum glauben, Sie haben eine angezeigte Höhe
	   von minus neunzig Fuß."

	C: "Hotel Papa Oscar climb four thousand to six thousand
	   and maintain."
	P: "Hotel Papa Oscar, climbing flight level 100."
	C: "Hotel Papa Oscar, climb to flight level 60 and maintain."
	P: "Aber vier plus sechs ist doch zehn, oder?"
	C: "Sie sollen steigen, nicht addieren."

	C: "DE..., fliegen Sie weiter im Gegenanflug für die
	    26, Landenummer 2 hinter einer DC 9 im kurzen Endteil."
	P: "Verstanden, fliege weiter für die 29 und folge der DC 6."
	C: "Nicht ganz richtig: Die Landebahn war 26 und
	   Ihr Verkehr eine DC 9."
	P: "Okay, ich folge der DC 26... Wie war die Landebahn?"

	Hubschrauber-Lehrer (zu seinem Flugschüler):
	"Sehen Sie zu, daß Sie innerhalb der betonierten Fläche bleiben."
	Und nach ein paar Minuten:
	"Ach was, bleiben Sie wenigstens in der Bundesrepublik!"

	In Memoriam München-Riem, wo gleichzeitig eine TB10 auf der
	25R und eine 737 auf der 25L landen.
	Pilot der 737: "War das jetzt eine Formationslandung?"
	T: "Nee. Formationsflug ist's ja nur, wenn ihr auf derselben
	   Bahn landet. Aber sah trotzdem gut aus.
	   Außerdem: die Bahnen sind ja zwei Kilometer auseinander,
	   da kann nichts passieren."
	737-Pilot beim Rollen auf dem Taxiway: "Ist das nicht komisch?
	   Die Bahnen sind doch höchstens 200 Meter auseinander!?"
	T: "Natürlich! Ein Bayer hätt' das schon längst gemerkt."

	P: "Frankfurt Information, hier Delta Bravo Zulu. Wir sind
	   jetzt über Dinkelsbühl in Flugfläche 95."
	C: "Sie sollten doch München Information rufen!"
	P: "Ja, weiß ich, aber bei Ihnen gefällt mir das Programm
	   besser."

	C: "Flamingo 019, do you have a 'Springbock' in sight, twelve
	   o'clock five miles crossing from left to right ?"
	P: "If you mean a 737...?"
	C: "Yeah, you got it, you got it!"

	T: "Delta Fox Alpha, hold position, Marshall will park you."
	P: "Roger. Looking out for John Wayne."

	München II
	T: "LH 8610 cleared for take-off."
	Pilot (LH 8610): "Wir sind aber noch gar nicht gelandet."
	T: "Ja, wer steht denn da auf der 26 south ? "
	Pilot (LH 8801): "LH 8801."
	T: "Na ja, dann seid ihr cleared for take-off."

	T: "Delta Mike Zulu, after landing cleared to taxi Alpha 7,
	    Alpha 5, Whiskey 2, Delta 1 and Oscar 2."
	P: "Wo ist denn das, wir kennen uns hier noch nicht so aus?"
	T: "Das macht nichts. Ich bin auch erst zwei Tage hier."

	Flugschüler: "Lichtenfels Info, DEITN, im rechten Queranflug
	   Landebahn 22, zum Durchstarten und Aufsetzen."
	T: "DEITN, ich habe eine große Bitte: erst aufsetzen
	   und dann durchstarten!"

	T: "You have traffic at 10 o'clock, 6 miles!"
	P: "Give us another hint, we have digital watches!"

	T: "Mission 123, do you have problems?"
	P: "I think, I have lost my compass."
	T: "Judging the way you are flying, you lost the whole
	   instrument panel!"

	P: "Good morning, Frankfurt ground, KLM 242 request start up
	   and push back, please." (Turbinen starten und vom Terminal
	   zurückschieben lassen)
	T: "KLM 242 expect start up in two hours."
	P: "Please confirm: two hours delay?"
	T: "Affirmative."
	P: "In that case, cancel the good morning!"

	P: "Tower, give me a rough timecheck."
	T: "It's tuesday."
	P: "WHAT?"
	T: "Tuesday afternoon..."

	Amerikanischer Pilot im Anflug auf einen mittlerweile wohl
	geschlossenen Flughafen bei München:
	P: "This is Delta-Bravo-one-ou-one. Requesting landing
	   permission for Oberpfa..., sorry, Overpupp...<click>"
	T: "..."
	P: "This is Delta-Bravo-one-ou-one, requesting landing permission
	   for Over... Oberpuff'n hopp... Overplaffing...<click>"
	T: "..."
	P: "This is Delta-Bravo-one-ou-one! Last try to get landing
	   permission for Oubrpfafen-o... FUCK IT, I fly to Firstie!"

	T: "Unknown flight approaching from south-east,
	   please identify."
	P: "Guess who I am..."
	T: "I repeat, unknown flight approaching from s-e, please
	   identify!"
	P: "Guess who I am..."
	T: "Last chance, unknown fligth approaching from s-e, identify!"
	P: "Guess who I am..."
	<Fluglotse schnippt mit dem Finger an einem Schalter und die
	 Landelichter gehen aus>
	T: "Guess where I am..."

	T: "Cannot read you, say again!"
	P: "Again!"

	T: "Are you familiar with Nordholz?" (=Naval Airstation)
	P: "No, my family lives in Kiel."

	Ein Testpilot soll einen neuen Jet testen.
	Während des Testfluges fällt auf einmal die Hydraulik aus.
	Der Pilot bleibt cool, und schaut ins Manual.
	Dort steht: 'Drücken Sie den grünen Knopf.'
	Der Pilot drückt ihn und die Nothydraulik läuft an.
	Kaum ist der Schaden behoben, fällt das Seitenruder aus.
	Der Pilot ist nicht mehr ganz so cool und liest erneut nach:
	'Drücken Sie den gelben Knopf.'
	Er drückt ihn und die Kiste aktiviert die automatische Trimmung.
	Der Pilot ist nun echt happy, daß der Jet alles so gut hinkriegt.
	Da fangen beide Triebwerke an zu brennen.
	Der Pilot bleibt sehr gelassen und schaut wieder in sein Manual:
	'Drücken Sie den schwarzen Knopf.'
	Er drückt ihn und es ertönt Orgelmusik und eine Stimme:
	- "BITTE SPRECHEN SIE MIR JETZT LANGSAM NACH:
		VATER UNSER IM HIMMEL
		GEHEILIGT WERDE DEIN NAME
		DEIN REICH KOMME..."

@ENDNODE

@NODE ST0024 "Expeditionen ins Bierreich"
@TOC Witze.guide/Inhalt

	Sehr verehrte Damen und Herren!

	In userer heutigen Folge unserer Serie will ich, Prof. Dr. Dr.
	Fielmann, sie über eine weit verbreitete aber wenig bekannte
	Tierart informieren.

	Die große Gruppe der Tiere bringt mannigfaltige Formen hervor,
	so die Aiere, die Biere, die Ciere, die Diere und so fort.
	Heute wollen wir uns der intensiven Erkundung der Biere witmen.

	Biere sind heutzutage als Kulturtiere in der ganzen Welt ver-
	breitet. Die Entstehung und das ursprüngliche Vorkommen des
	Wild-Bieres (Cervisia silvestre) ist heute nicht mehr nach-
	zuvollziehen, es ist aber anzunehmen, daß es im mitteleuro-
	päisch-mediterranen Regionen zuerst auftrat. Vermutlich er-
	reichte es von hier in Lemming-artigen Wanderungen den afri-
	kanischen, asiatischen und nordamerikanischen Raum.

	Im Zuge der menschlichen Entwicklung wurde es schnell domesti-
	ziert und regional modifiziert, so daß von Cervisia domestica
	gesprochen werden muß. Aus dem Cervisia domestica, auch als
	gemeines Bier oder C. communis bekannt, wurden durch gezielte
	Züchtung auch Spezialformen kreiert. Dazu zählen das Champinon-
	oder Pilz-Bier (C. pilsen), das Weizenbier (C. weizenäckerensis),
	das Kölnisch-Wasser-Bier (C. kölschensis) und das Auswanderungs-
	oder Export-Bier (C. emmigrantis). In neuerer Zeit sind auch
	noch die Modezüchtungen des Licht-Bieres (C. light) und des
	Impotenz-Bieres (C. antialkoholensis oder C. kastratensis)
	dazugekommen.

	Wenden wir uns nun dem Lebenszyklus des Bieres zu.
	In der Kultur werden die meisten Biere weit vor dem Erreichen
	ihrer Lebenserwartung geschlachtet. Dies geschieht rituell durch
	Enthauptung. Die Biere, die am jüngsten geschlachtet werden
	sind die Weizen-, Kölnisch-Wasser- und Export-Biere sowie die
	neuen Modeformen. Die Pilz-Biere haben deutlich bessere Chancen
	eine geringfügig höheres Lebensalter zu erreichen, doch auch
	bei diesen bedauernswerten Geschöpfen kommt es zunehmend in
	Mode, sie bereits im pubertären Alter zu köpfen.

	Schafft es einmal ein Bier durch geschicktes Tarnverhalten,
	sich über längere Zeit der Schlachtung zu entziehen, wird es
	zunächst verschmäht, da man diesem dann einen bitteren Ge-
	schmack nachsagt. Hat man es entdeckt, wird es trotzdem nicht
	in die Freiheit entlassen, um in Ruhe seinem Lebensabend ent-
	gegen zu sehen, sondern man beäugt es kritisch, um es sofort
	nach Eintritt in die senile Phase als dann sogenanntes oder
	auch Alt-Bier (Cervisia senilis) zu schlachten. Durch alters-
	bedingte Verwesungsprozesse hat sich der Geschmack des senilen
	Bieres derart verändert, daß es eine deutlich verwesungs-süße
	Geschmacksnote bekommen hat, die jedoch nicht überall auf
	Gefallen stößt.

	Das Sozialverhalten der Biere ist durch alle Formen mehr oder
	weniger gleich. Das Bier ist ein Gruppen- bis Herdentier. Die
	kleinste häufig anzutreffende Anzahl ist die Sechser- oder auch
	Träger-Gemeinschaft. Weit verbreiteter sind jedoch Großfamilien
	mit 20 bis 24 Mitgliedern, die es sich in einem sogenannten
	Kasten gemütlich machen. Hierbei kann es noch zu weiteren
	Aggregationen von Träger- und Kasten-Gemeinschaften zu den
	gelegentlich gefundenen Paletten kommen. Derartige Paletten
	stellen jedoch besondere klimatische Ansprüche, so daß an einem
	geeigneten Ort meist ganze Paletten-Lager zu einem oft als
	Bier-Verlag bezeichneten Ökosystem kummulieren. Dabei sind die
	verschiedensten Arten von Bieren bunt miteinander gemischt,
	jedoch werden in den Kästen nur selten artfremde Mitglieder
	geduldet.

	Innerhalb jeder Träger- oder Kastengemeinschaft bewohnt jedes
	Individuum stets eine einzelne, genau der Körperform angepaßte
	Behausung, die Flasche. Da sich die Flaschen nicht vermehren
	können, sind die Bierkäufer aufgefordert, die leeren Bier-
	behausungen wieder den Bierzüchtern zukommen zu lassen, damit
	sie von der nächsten Biergeneration bewohnt werden können.

	Hiermit wären wir bei dem interessanten Vorgang der Bierzucht.
	Die Bierzucht unterscheidet sich von den meisten anderen Tier-
	zuchten unter anderem dadurch, daß sie nur selten vom Hobby-
	züchter ausgeübt werden kann. Ein Bierzüchter wird daher meist
	ehrfurchtsvoll als Brauer bezeichnet, in Anlehnung an die
	kommerziellen Züchter der anderen Haustierformen, die Bauern.
	Zur Vermehrung werden dabei ganze Großrudel von Bieren in
	riesigen Gefäßen gehalten, die Kessel genannt werden.

	Durch ständige Kopulationen und die damit umgesetzte Energie
	der Biere wird eine enorme Menge an Wärme frei, sodaß die
	Kessel gelegentlich bis an den Siedepunkt erhitzt sind. Nur
	bei lange in Kultur befindlichen Bierarten muß der Mensch
	hier helfend eingreifen, indem er von außen Wärme zuführt,
	um die Bierweibchen in Hitze zu bringen. Um den Energiebedarf
	der Biere zu decken, müssen den Kesseln zum Beginn eines
	Zuchtansatzes größere Mengen an energiereichen Substanzen in
	Form von Malz, Hopfen und Hefe zugesetzt werden, da die Biere
	sonst zu schnell erschöpft sind und die Bierweibchen nicht im
	täglichen Rhythmus ihre Jungen werfen können.

	Einzig der Sortiervorgang, mit dem die Bierbabys von den
	Zuchttieren getrennt werden, wird von den professionellen
	Brauern streng geheim gehalten, sodaß hier noch Raum für die
	zukünftige Forschung bleibt. Die wenigen Hobby-Brauer trennen
	meist nicht die Eltern von den Babys sondern schlachten, egal
	welche Altersschicht.

	Wenn sie also demnächst gedenken, ein Bier zu schlachten, oder
	eines der seltenen Widbiere als Bierjäger zur Strecke zu
	bringen, denken sie bitte auch an den wundervollen und viel-
	gestaltigen Organismus, den das Bier darstellt und legen sie
	vor dem Verzehr eine Gedenkminute in. Und damit möchte ich mich
	von ihnen verabschieden und ihnen noch einen schönen Abend
	wüschen,
					ihr Prof. Dr. Dr. Fielmann

@ENDNODE

@NODE ST0025 "Stilblüten aus Kinderaufsätzen"
@TOC Witze.guide/Inhalt

	1.  Neben Prunksälen hatten die Ritter auch heizbare Frauenzimmer.
	2.  Alle Welt horchte auf, als Luther 1642 seine 95 Prothesen
	    an die Schloßkirche zu Wittenberg schlug.
	3.  Cäsars Legikonäre machten das Lager voll und jeder stand
	    stramm bei seinem Haufen.
	4.  Graf Zeppelin war der erste, der nach verschiedenen Rich-
	    tungen schiffte.
	5.  Die Alm liegt hoch im Gebirge. Dort ist der Senner und die
	    Sennerin.
	    Im Frühjahr wird aufgetrieben, im Herbst abgetrieben.
	6.  Unsere Schule war früher ein Waisenhaus. Daran erinnert über
	    dem Eingang eine eingehauene Frau, die vorne einen Knaben
	    und hinten ein Mädchen empfängt.
	7.  Eine katholische Schwester kann nicht austreten, da sie
	    zeitlebens im Kloster leben muß.
	8.  Die Macht des Wassers ist so gewaltig, daß selbst der
	    stärkste Mann es nicht halten kann.
	9.  Wir gingen in den Zoo. Es waren große Affen im Käfig. Mein
	    Onkel war auch dabei.
	10. Der leichtsinnige Viehbrigadier hatte mit seinem Karren den
	    ganzen Zaun umgefahren. Das Schwein konnte erst später
	    eingefangen werden.
	11. Mit starkem, großen Strahl geben die Feuerwehrleute ihr
	    Wasser ab.
	12. Der Landwirtschaftsminister ließ die Bauern zusammenkommen,
	    denn die Schweine fraßen zuviel.
	13. Beim Roten Kreuz widmen sich Männer und Frauen der Liebe.
	    Manche tun es umsonst, andere bekommen es bezahlt.
	14. Als der Jäger den dicken Bauch der Großmutter sah, wußte er
	    sofort was geschehen war. (aus Rotkäppchen)
	15. Dort wo jetzt die Trümmer ragen, standen einst stolze Burg-
	    fräuleins und warteten auf ihre ausgezogenen Ritter.
	16. Es war eine machtvolle Demonstration. Der Marktplatz war
	    voller Menschen. In den Nebenstraßen pflanzten sich Männer
	    und Frauen fort.
	17. In Lappland wohnen zwei Sorten Menschen. Die reichen Lappen
	    fahren im Rentiergespann, die armen Lappen gehen zu Fuß.
	    Daher der Name Fußlappen. Auch wohnen dort die Menschen sehr
	    dicht zusammen. Daher das Sprichwort:
	    'Es läppert sich zusammen.'
	18. Nachdem die Männer 100m gekrault hatten, spritzten die
	    Frauen aus ihren Löchern und wickelten ihre 200m Brust ab.
	19. Die Streichhölzer müssen gut versteckt werden, damit sie
	    keine kleinen Kinder bekommen.
	20. Meine Tante schenkte mir eine Sparbüchse. Sie war ein
	    Schwein. Sie hatte zwei Schlitze. Hinten einen für's Papier,
	    und vorne für's Harte.
	21. ...und wir gingen mit unserer Lehrerin im Park spazieren.
	    Gegenüber dem Park war ein Haus, wo die Mütter ihre Kinder
	    gebären. Eine Gebärmutter schaute aus dem Fenster und winkte
	    uns freudig zu.
	22. Und die Skiläufer standen startbereit an den Hängen und
	    Pisten...

@ENDNODE

@NODE ST0026 "Abkürzungen"
@TOC Witze.guide/Inhalt

	ACRONYM:
	- Alphabetic Collocation Reducing Or Numbing Your Memory
	ADIDAS:
	- All Day I Dream About: Sex
	AEG:
	- Alles Ein Gammel.
	- Alt Eisen Gesellschaft
	- Am Eigensinn Gescheitert
	- Auf Einmal Geht's ??!
	- Aus Entfernung Gut
	- Auspacken - Einpacken - Gutschrift
	- Auspacken - Einschalten - Gabutt!
	- Auspacken - Einschalten - Geht nicht.
	- Auspacken - Einschalten - Geld zurück 
	- Auspacken - Einschalten - Garantiefall.
	AI:
	- Allah Informed!
	ALITALIA:
	- Always Late In Take-off And Late In Arrival
	- Airplane Lands In Tokio And Luggage In Amsterdam
	ATARI:
	- Alles Teile Aus Runderneuerten IC's
	- Alles Teile Aus Restposten der Industrie
	- Als Türstopper Absolut Riesig Installiert
	AT&T:
	- Alles Teuer Und Taugt Nix
	AUDI:
	- Accelerates Under Demonic Influence

	BASF:
	- Band Aus Scheiße Fertigen
	- Besser Arbeiten Sonst Fliegst
	- Bezahlt Alles Seine Firma
	- Byte Abweisende Schutz-Folie
	BMW:
	- Babbling Mechanical Wench
	- BART / Muni / Walking (transportation in San Francisco)
	- Basic Marin Wheels
	- Bastel Mal Wieder
	- Bayerischer Mist Wagen
	- Bayerischer Müll-Wagen
	- Beastly Monstrous Wonder
	- Beautiful Masterpieces on Wheels
	- Beautiful Mechanical Wonder
	- Bei Mercedes Wegwerfen
	- Bee-Emm-Double-u, Bee-Emm-Trouble-You
	- Berliner Motorrad Werke
	- Big Money Waste
	- Big Money. Why?
	- Big Money Works
	- Blasphemous Motorized Wreck
	- Born Moderately Wealthy
	- Bought My Wife
	- Break My Windows
	- Break My Windshield
	- Bring Mich (in die) Werkstatt
	- Broken Money Waster
	- Broken Monstrous Wonder
	- Brutal Money Waster
	- Bumbling Mechanical Wretch
	BVG:
	- Berlins Vereinigte Gaukler

	CAD:
	Computer Aided Desaster
	CAM/CAD:
	Computer Am Montag / Chaos Am Dienstag
	COMMODORE:
	-	(C)ompany
	       f(o)r
	      Ra(m)sch
		(m)ismanagement and
		(o)bscure
		(d)evices
		(o)f
	 Compute(r)
		(e)quipment
	- Company Of Maximal Mismanagement, Offering Devices Of
	  Rubbish Equipment
	- Come On Make My Ordinary Day Once Really Exciting!

	DATSUN:
	- Diese Autos Töten Sanft Unsere Nation
	DOS:
	- Durchweg Ohne Sinn

	EMACS:
	- Eight Megabytes And Constantly Swapping
	- Escape-Meta-Alt-Control-Shift

	FIAT:
	- Failure In Automotive Technology
	- Failure in Italian Automotive Technology
	- Feeble Italian Attempt at Transportation
	- Fehler in allen Teilen
	- Feuer In Allen Töpfen
	- Fix It Again, Tony!
	- Fucked In the Ass Twice
	- Für Idioten Allgemein Tauglich
	- Für Italiener Ausreichend Technik
	- Futile Italian Attempt at Transportation
	FORD:
	- Ford fahren, heim laufen.
	- Im Ford fort, im Zug zurück.
	- First On Race Day
	- Fails On Rainy Days
	- First On Recall Day
	- First On Road to Dump
	- First On Rust and Deterioration
	- Fix Or Repair Daily
	- Flip Over, Read Directions
	- Found On Road Dead
	- Found On a Rubbish Dump
	- Fraternal Order of Restored DeSotos
	- Fucked On Race Day
	- Fucker Only Runs Downhill
	- Fucked Over Rebuilt Dodge
	- Fucked Over Road Debris
	- Fucking Obsolete Road Device
	- Fucking Old Rust Dog

	GOLF:
	- Gogo Ohne Lebensfreude
	- Got Another Little Friend

	HIGHSCREEN:
	- Lieber High als Screen...
	HONDA:
	- Heute Ohne Nennenswerte Defekte Angekommen
	- Himmlischer Orgasmus nach dem Absteigen
	- Höllischer Orgasmus nach dem Anfahren
	HP:
	- High Price.

	IBM :
	- I Believe in Mama
	- I Believe in Mammon
	- I Believe in Mediocrity
	- I Believe in Miracles
	- I Buy Macintosh2
	- I've Been Moved  (Die Mitarbeiter werden angeblich extrem
			    oft in andere Städte/Länder versetzt.)
	- Ich Beuge Mich!
	- Ich Bezahle Mehr
	- Ich Bin Massa
	- Ich Bin Masochist
	- Ich Bin Müll
	- Idioten Bauen Maschinen
	- Idiotie Braucht Methode
	- If Bought Malefunctioning
	- Im Betrieb Miserabel
	- Immens Beknackte Maschinen
	- Immer Beim Meeting
	- Immer Besser Manuell
	- Immer Blöde Meldungen
	- Immer Bloß Meetings
	- Immernoch Besser Manuell
	- Inadequate But Marketable
	- Incredible Bad Maschines
	- Incredibly Boring Machines
	- Industrieller Büro- Müll
	- Ingenieure Bauen Mist
	- Innovation Blocking Machine
	- Install Bigger Memory
	- Intel Basierter Mist
	- Internal Bug Machines
	- International Brotherhood of Motherfuckers
	- Intrigante, Brutale Management-Methoden
	- Invented By Monkeys
	- Iranian Broom Makers
	- Ist Bestimmt Müll
	IKEA:
	- Ich Kaufe Einfach Alles
	ISDN:
	- IBM Schafft Das Nicht
	- Ich Seh Da Nix
	- Immer Siemens Denkt Nixdorf
	- Ist Sowas Denn Nötig?
	ITT:
	- Immer Total Tot

	KLM:
	- Kauft Lookhead, Majestät
	- Keine Lust Mehr

	LISP:
	- Large and Incredibly Slow Programs
	- Lots of Irritating and Senseless Parentheses
	LUFTHANSA:
	- Let Us Fuck The Hostess As No Steward Available

	MANTA:
	- Mit Allgemeinbildung Nur Teilweise Ausgestattet
	MARLBORO:
	- Manch Alter Reicher Lustmolch Bumst Ohne Richtigen Orgasmus
	MAZDA:
	- Mein Auto Zerstört Deutsche Arbeitsplätze
	- Most Always Zipping Dangerously Along
	MIPS:
	- Meaningless Indicator of Processor Speed
	MSDOS:
	- Mehr Spaß Durch Organisierten Schwachsinn

	NASA:
	- Need Another Seven Astronauts
	NeXT:
	- Nicht einmal Xenix Tauglich (naja...)
	- Nur ein XT
	NTSC:
	- Never the same colour
	- Never Twice Same Color

	OLDSMOBILE:
	- Oh, Look, Dammit! Some Massive Oil Burning Idiot's Leaking
	  Everything
	- Old Ladies Driving Slowly Make Others Behind Infuriatingly
	  Late Everyday
	- Old Loose Dented Sheet Metal Out-dated By Infamies Like Edsel
	OPEL:
	- Ohne Panne Ewig Laufen
	OS/2:
	- Half an Operatingsystem
	- Operationssystem, halb so schnell

	PAL:
	- Pay All The Luxury
	- Pictures At Last!
	PC:
	- Programmable Canker
	PIA:
	- Please Inform Allah
	PORSCHE:
	- Piece Of Retired Scrap, Continually High Expense
	POST:
	- Personen Ohne Sinnvolle Tätigkeit
	- People Of Slow Transport
	- Primitive Organisation Sexueller Triebtäter
	- Public Organisation for Supressing Technology
	PROFEX:
	- Profitable Reparaturen Ohne Fehler-EXterminierung
	PUMA:
	- Probier' Unbedingt Mal Adidas

	RITMO:
	- Rost In Turin Montiert

	SAAB:
	- Send Another Automobile Back
	- Stupid, Arrogant Asshole Babies
	- Such An Arrogant Bastard
	- Swedish Automobile - Always Broken
	- Swedish Automobiles Are Best
	SABENA:
	- Such A Bloody Experience Never Again
	  (Die sind mal auf 'nem Fußballfeld gelandet...)
	SECAM:
	- Sans Experience Contre Les Americains
	- System Even Crappier than American Method
	SIEMENS:
	- Sicher Ist Eines, Man Erhält Nur Schrott!
	- SIE Müssen Einen Nixdorf Stornieren
	- Spinnerte Ingenieure, Exzentrische Mechaniker Erfinden
	  Nur Schrott
	- Suche Innerhalb Eines Monats Eine Neue Stelle!
	SIEMENS AG:
	- Suche In Einem Monat Eine Neue Stelle Als Gartenzwerg
	SOLDAT
	- Soll Ohne Langes Denken Alles Tun
	SUBARU:
	- (rückwärts) U-R-A-Bus
	SUZUKI:
	- Sinnlose, Unzusammenhängende Zusammenstellung Unzähliger
	  Konstruktions-Irrtümer
	SYSOP
	- Säuft Yankee-Whiskey Ständug Ohne Peilung

	TARGON:
	- Tausend Anwender Rufen Gemeinsam: Oh Nixdorf...
	- Total Ausgeflippter Rechner, Geht Ohnehin Nicht
	TELEKOM:
	- Teure Einfache Leistungen Eines Klug Organisierten Monopols
	- Teure Einfältige Leistungen Eines Klug Organisierten Monopols
	TOS:
	- Tod Ohne Sterbeurkunde
	TOYOTA:
	- Too Often Yankees Overprice This Auto
	TÜV:
	- Technischer Überraschungs-Verein
	TWA:
	- Takeoff With Another
	- Time-Waste Airlines.
	- Travel With Arabs
	- Try Walk Across
	- Try With Another

	UNIX:
	- Unser Neuestes Intelligenz EXperiment

	VOBIS:
	- Verkäufer Ohne Branchenkenntnisse Im Streß
	- Viele Ohne Brille Im Suff
	- Vomit On Bad Incompetent Service
	VW:
	- Virtually Worthless

	WANG:
	- Wenn Alles Nicht Geht
	- Wird Auch Nix Gescheites
	- Wollen Auch Nur Geld

	XENIX:
	- EXklusiv: Ein Neues Intelligenz EXperiment

@ENDNODE

@NODE ST0027 "Mensa-Umfrage"
@TOC Witze.guide/Inhalt

		Umfragebogen zum Thema "UNI - MENSA"
		====================================


	I. Fragen zur Mensa:

	1.) Wie finden Sie die Mensa?
	    o jahrelange praktische Erfahrung
	    o mit meiner Nase
	    o einfach immer den grünen Gesichtern folgen

	2.) Was halten Sie vom angebotenen Fleisch?
	    o was für Fleisch?
	    o paßt farblich gut zum Tablett
	    o paßt geschmacklich gut zum Tablett

	3.) Wie essen Sie ein Steak am liebsten?
	    o mit den Fingern
	    o mit dem Mund
	    o roh
	    o sehr roh

	4.) Wie möchten Sie Ihren Salat?
	    o schnell
	    o ohne Schnecken (bin Vegetarier)
	    o mit Schnecken (bin Schädlingsbekämpfer)
	    o mit Essig
	    o mit Öl
	    o mit Spargelcremesuppe, Steak, Pommes und Chateau de Pape '59

	5.) Essen Sie heute in der Mensa?
	    o ja
	    o nein

	6.) Essen Sie regelmäßig in der Mensa?
	    o ja
	    o nein

	Falls Sie eine der letzten beiden Fragen mit "ja" beantwortet
	haben:

	7a.) Würden Sie sich als Masochisten bezeichnen?
	     o ja
	     o klar
	 b.) Wie sind Sie krankenversichert?
	     _______________________


	II. Fragen zu Ihrer Person:

	8.) Stehen Sie jeden Morgen auf?
	    o ja
	    o nein
	    Wenn ja:
	 a.) Wie?
	     o voller Tatendrang
	     o voller Restalkohol
	 b.) Wann?
	     o 7 Uhr (morgens)
	     o 7 Uhr (abends)
	     o doch lieber nicht

	9.) Um wieviel Uhr kommen Sie täglich an die Uni?
	    o Täglich?
	    o An die Uni?
	    o __.__h
	 a.) Wenn nein: Wie oft in der Woche?	____ mal
	 b.) Wenn nein: Wie oft im Monat?	____ mal
	 c.) Wenn nein: Wie oft im Semester?	____ mal
	 d.) Wenn nein: Viel Glück beim Examen!

	10.) Was wollen Sie einmal werden?
	     o Müllmann
	     o Rentner (sobald wie möglich)
	     o Millionär (dto.)
	     o 1.70m, 1.71m, ...

	11.) Wie finden Sie die Uni?
	     o architektonisch vollauf ansprechend
	     o auf dem Stadtplan
	     o ganz toll, wenn... o es keine Vorlesungen gäbe
				  o es keine Prof's gäbe
				  o es keine Prüfungen gäbe
				    (Mehrfachnennungen möglich)
	     o mich stört ihr monopolkapitalistischer Charakter
	     o langweilig (aber die Etablissements rund um die Uni...)
	     o zwischen halb elf und halb zwölf
	     o ist mir bisher noch nicht passiert

	12.) Was halten Sie von Genforschung an der Uni?
	     o solang es nicht meine sind...
	     o Nichts gegen Genforschung, aber sobald ich so ein Ding
	       in meiner Suppe schwimmen sehe...
	     o GENitief ins Wasser (weil's Datief ist!)

	13.) Ich bin für einen allgemeinen Numerus Clausus...
	     o bei Prof's
	     o bei Hausmeistern
	     o bei Mensaköchen

	14.) Warum studieren Sie?
	     o mir fiel nach dem Abi nichts besseres ein
	       (Bitte mindestens eine Antwort ankreuzen)

	15.) Was sind Ihre Hobbies?
	     o das Studium
	       Wenn ja: wann waren Sie das letztemal beim Psychiater?
		am __.__.____
	     o Frauen/Männer
	     o in Ketchup baden
	     o in Sekt baden
	       Wenn ja: bekommen Sie BAFöG?
		o ja
		o nein, aber meine Eltern/Kinder
		o meinen Sie 'legal'?

	16.) Nehmen Sie regelmäßig Drogen, wenn ja: welche?
	     o Alkohol
	     o Nikotin
	     o Kaffee
	     o zählen Vorlesungen auch?
	     o Gras (badisches Gras, von der Sonne verwöhnt...)
	     o Trips
	     o Flips (Erdnuss-)
	     o Flops (Flip-)
	     o Chips (Kartoffel-)
	     o Chips (die anderen, schwarzen mit dem kernigen Mampf!)
	     o Informatik-Skripte

	17.) Ihr Sexualleben:
	     o Sie stehen auf Männer
	     o Sie stehen auf Frauen
	     o Sie stehen auf beides (verdoppelt die Chancen!)
	     o Sie stehen nie auf (s.Frage 8)


	Wir gratulieren Ihnen zum Ausfüllen des Fragebogens!
	Zählen Sie Ihre Kreuzchen irgendwie zusammen (erlaubte Hilfs-
	mittel: nicht programmierbarer Taschenrechner), addieren Sie
	Ihr Alter, Ihren derzeitigen Blutalkoholgehalt und die Anzahl
	der Gummibärchen, die Sie pro Minute verdrücken koennen, teilen
	Sie das Ganze durch Ihren Intelligenzquotienten (Vorsicht bei
	Division durch Null!) und schicken Sie die Quersumme an das
	I nstitut für  B efragungen und  M einungsforschung (IBM).
	Jeder 500000. Einsender erhält das Porto zurück und gewinnt
	einen Rundflug für 21 Personen durch die Karlsruher Kanalisa-
	tion - das Mitmachen lohnt sich also!

@ENDNODE

@NODE ST0023 "Anleitung (II)"
@TOC Witze.guide/Inhalt

   Aufgrund heftiger Resonanz in diversen Brettern auf den Beitrag
   "Anleitung" folgen hier einige ausgewählte Höhepunkte aus An-
   leitungen und Computerprogrammen unter dem Stichwort:
   'Chinesisch von Arabern ins Deutsche übersetzt'.


   Anleitung für eine italienische Schleifmaschine

		*Anlage und betrieb der maschine*
		---------------------------------

	Nach her ist die elektrische Verbindung ausegefuehert
	worden, muessen Sie den Gangschalter Kuppeln  und
	kontrollieren dass der Schleifstein in der Richtung kreift
	so wie der Anzeiger will.
	   [...]
	Bearbeitung zu vermeiden. Dies ist besser erreichbar mit dem
	auf anfrage lieferbaren Zubehoer L 21 <<Halbautomatischer
	Diamantschleifer>>.


   Auszug aus der Bedienungsanleitung eines Drehmomentschlüssels:

		VERSTELLEN VON SETZEN DES DREHMOMENT
		------------------------------------

	Wie Können Sie Ihrer neue Drehmomentschlüssel verwenden
	A) Den Schlüssel in das links Hand mit sichtbare Gradierung
	   ausgleichen und den gezeichneten Pfeil Elementarskala auf
	   sein lassen, den gerändelte Handel durch Umdrehen der
	   geschlossene Mutter gegen dem Uhrzeigersinn aufschließen.
	B) Das angesprüchte Drehmomentausmaß durch umdrehen des
	   gerändelte Handel setzen, um das exakte Ausmass in
	   Gradierungskiste auszulesen.
	   Z.B. 96ft lbs
	1) Den gerändelte Handel umdrehen bis das die Nullgradierung an
	   die Schräge Kante des gerändelte Handel sich mit der verti-
	   kale Zeichnung an die Kiste in linie aufstellen und sich an
	   80ft Gradierung revanchieren.
	2) Den gerändelte Handel umdrehen gegen den Uhrzeigersinn bis
	   daß die 16 ft lbs Gradierung an die Schräge Kante des
	   Handels mit die vertikale linie an die Kiste uebereinstimmt.
	3) Durch Umdrehen der geschlossene Mutter im Uhrzeigersinn den
	   Handel festschließen.  Schlüssel wird nun um 96 ft lbs.
	   drehmomentgesetzt und is fertig zu gebrauchen (siehe fig.2.)
	C) Das Setzen von Metrik ist gleich wie oben genannte Verfahren
	   für Setzen on ft-lb
	D) Die geellgente Hülse oder andere Befestigungen in den vier-
	   eckige Antrieb setzen und auf die Mutter oder Schraube an-
	   wenden, und den Handel ziehen bis daß das Knacken des
	   Schlüssel gehört wird. Das Ziehen auslösen, der Schlüssel
	   wird dann automatisch für nächstes Operation wieder gesetzt.
	ZIEHEN NICHT DEN HANDEL WEITER NACHDEM AUSLÖEN DES SCHLÜSSEL.
	BEACHTEN AUF DIE NIEDRIGE DREHMOMENT SETZEN WENN DAS ZIEHEN
	AUFHÖREN UND SCHLÜSSEL KLICKT.
	[...]

   Irgendwas mit WinDOOF:

	Sie einbauen Detrina Detrina WinFax fuer einen [14, 400 bps]
	fax/modem. Sicherstellen Betriebssicherheit wenn [faxes] bei
	dieser Geschwindigkeit senden, empfehlen wir den ComxFIFO
	unfähig zu machen, Ihren SYSTEM.INI einse [Fuee mehre Auskunft,
	sehen den LESEN.MIR nach Installation datei, sind vollstaendig.]
	Wuenschen Sie, dass macht diese Aenderung automatisch?
	Ja - Nein - Beenden Sie Umstaende
	(Ich sags ja, WinDOOF ist umständlich... :-)


   Und hier noch ein paar Kurzzitate:

	- 'Legen Sie Diskette 1.' (aus Civilization)
	- 'Einsetzt Disk 1 und press return'
	- 'Bitte geben sie Lautsärke 1 eine'
	(Als provisorische Übersetzung von 'Please insert volume 1'.)


	- 'Es wird besser sein, NICHT das Unit wieder anspringen nach
	   der Aufhörung der Operation.'
	('Nach dem abschalten etwas warten')


	- 'Fahren Sie das Unit auf und ab, benutzende den Schalter
	   des Erdes'
	(Umschreibung für einen Ein/Aus-Schalter)


	- 'Knopf 7 betätigt die Kehrmaschine des Autos'
	(ein sog. 'Auto sweeper', ein Luftumlenksystem)


	Und der ultimative Höhepunkt des Artikels:
	- 'Pressen Sie einen Schluessel'


   Und wer mir als erster schreibt, was eine
	'Zisterne der Humidifaktion'
   ist, dem schick' ich die nächste Version des Witze.guide's
   auf einer von mir persönlich spendierten Disk gratis zu.
   (KEIN WITZ, mach ich echt(!), aber der 'Einsendeschluß'
   ist der 'Erscheinungstermin' der Version 1.03, in der dann
   auch die Lösung steht.)


   zu @{b}Version 1.03@{ub}:

   Tjaaa, das war wohl nix... Keine Einsender bisher :-(
   Vielleicht sollte ich dafür sorgen, daß das Guide etwas mehr "in
   Umlauf kommt"...
   Wie dem auch sei, die Lösung ist:
		  @{b}Kondenswasserbehälter@{ub}
   Das nächste mal etwas mehr Begeisterung bitte!

@ENDNODE

@NODE ST0032 "Anleitung (III)"
@TOC Witze.guide/Inhalt

   Und nochmal was zum Schieflachen. Diesmal handelt es sich um
   eine Einbauanleitung für einen Festplatten-Wechselrahmen.
   Viel Spaß...

	AUFBAUANWEISUNG

	1. Beschlagen den Fixed-Rack auf dem Floppy-Drive-Slot im
	   Computer mit 4 Schrauben (sehen in der Figur 1).

	2. Verbinden 20-Nadels und 34-Nadels Platt-Kabel vom Hard-
	   Diskette-Konteller zum Fixed-Rack. (sehen in der Figur 2).
	   Versichern Sie die richtige Richtung, wenn die Kabels
	   verbunden werden. Die Rot-Farbe daneben der Kabels soll nah
	   vom Slot der PCB-Schaltung sein.

	3. Verbinden die Kraft-Kabel vom Kraft-Vorrat zur 4-Nadel
	   Steckdose am Fixed-Rack. (sehen in der Figure 3).

	4. Verbinden entweder 20-Nadel oder 34-Nadel und die Kraft-Kabel
	   zur Hard-Diskette. (Kabels bieten den Werkzeug an). Sichern
	   die 3.5" Hard-Diskette mit 4 Schrauben in der Abnehmende-
	   Ablage (sehen in der Figur 4).

	5. Machen Sie Bed-Platte mit 6 Schrauben fest (sehen in der
	   Figur 5).

	6. Schlittern die Abnehmende-Ablage in Fixed-Rack hinein.
	   Schliessen Sie auf dem Schluessel-Schalter. Machen Sie den
	   Computer an und gestalten Ihren Computer auf das Setup-
	   Pragram. Format Ihrer Hard-Diskette, wenn eine neue
	   unformende Hard-Diskette beschlagen wird.

	Vorsicht, wenn Sie den MOBILERACK benutzen

	Der Vorteil vom MOBILERACK

	- Sie koennen alle vertragliche 3.5" Halbhoehe ST-506 oder SCSI
	  Hard-Disketten, die im MOBILERACK beschlagen, benutzen. Damit
	  sich die Hard-Disketten bieten und kleinst tragbar sind. Alle
	  Akten und Daten sind jetzt einfach uebertragbar zwischen Ihren
	  Buero und den Fernasteil, oder sogar auch zu Hause. Sie
	  koennen den MOBILERACK wegrauecken, wo einer Computer einen
	  Fixed-Rack, der im floppy-Slot beschlagen wird, hat.
	- Wenn eine Menge Daten zwischen den Computers uebertragen wird,
	  kann der MOBILERACK 20-100 Disketten Kopierarbeiten an die
	  Stelle setzen.
	  (Es haengt von der Groesse der Hard-Diskette ab.) Es ist sehr
	  benutzbar in der Auflegung, Z.B. CAD, GRAPHIC oder MUSIC.
	- Die vertrauliche Daten, Z.B. Kunde-Akten, die Buchaltung oder
	  andere empfindliche Material, koennen weg vom Computer
	  behalten werden und in einem sicherlichen Platz stellen.

	Lesen Sie daunten durchaus, bevor Sie ihn an die Arbeit bringen

	A. Schliessen Sie nicht den Schluessel-Schalter auf und nehmen
	   die Hard-Diskette weg, wenn Read/Write zugaenglich fuer die
	   Hard-Diskette ist. Es ist der Verlust der Daten zu verhindern.

	B. Immer parken Sie das Head der Hard-Diskette, bevor sie vom
	   Computer weggenommen wird. Ausser wenn die Hard-Diskette die
	   automatische parkende Funktion hat.

	C. Um den Stoss-Schaden waehrend der Versendung zu verhindern,
	   sichern Sie, dass der MOBILERACK auf dem Sack geparkt wird.
	   Durch dem Sack hat die Stoss-Absorption. Aber seien
	   vorsichtig! Faellt der MOBILERACK nicht auf den Boden.

	D. Sie koennen die abnehmende Ablage wechseln, wenn der Computer
	   noch anmacht, schliessen Sie nur den Schuessel-Schalter auf
	   und wechseln andere abnehmende Ablage und schliessen sie.
	   (Wenn Sie die gleiche Typ der Hard-Diskette benutzen, braucht
	   das Setup-Program nicht zu laufen, Sie koennen andere Daten
	   uebernehmen, was Sie brauchen.

   Ich sage nur: "Zusammenknüllen Sie Anleitung fest" :-))))

@ENDNODE

@NODE ST0028 "Krötenlecken"
@TOC Witze.guide/Inhalt

	Neulich, im Spiegel (Nr.32/8.8.94) S.92
		"Mutwilliges Lecken"

	[...] Die Festgenommenen gehören zur wachsenden Schaar von
	US-Bürgern, die einen billigen wenn auch befremdlichen Weg zu
	einem schnellen Rausch entdeckt haben: Krötenlecken. Fuer die
	höchst unappetitliche Prozedur drückt man einer ausgewachsenen
	Colorado-Kröte kräftig in den Nacken. Nach wenigen Sekunden
	quillt aus Giftdrüsen hinter den Augen ein milchiges Sekret,
	dessen Wirkstoffe der chemischen Struktur von LSD ähnelt. Die
	Liebhaber von Bufo alvarius lutschen die Droge frisch von der
	Kröte, weshalb sie von Polizisten als "Toadies" verspottet wer-
	den.
	Den Leckern ist juristisch nur schwer beizukommen. Zwar sind
	Bufotenin und Dimethyltryptamin, die beiden Wirkstoffe des Krö-
	tengifts, illegale Drogen. Inhaber gültiger Angelscheine können
	jedoch völlig legal bis zu zehn Tierchen halten.
	- "Wenn jemand im Besitz dieser Kröte ist, müssen wir ihm nach-
	weisen, daß er an der Kröte vorsätzlich geleckt hat oder sie
	jemandem zum mutwilligen Lecken gereicht hat" erklärt Robert
	Sager, Chef des DEA-Labors in San Francisco [...]

	Wieder ein Beweis für den Spruch: Man muß viele Frösche küssen,
	um...
	Vielleicht sollte man wirklich über die Anschaffung eines
	Terrariums nachdenken. ;-)

@ENDNODE

@NODE ST0029 "Die Geschichte der Datenfernübertragung"
@TOC Witze.guide/Inhalt

	<ACHTUNG!!! Die Story ist EXTREM lang (wie man vielleicht
	 schon an der Sliderlänge bemerkt. Also Zeit nehmen!
	 Und sagt nicht, ich hätte Euch nicht gewarnt!>

	DFÜ, die Datenfernübertragung, ist schon seit Anbeginn der
	Menschheit ein Wunschtraum derselben. Nicht immer konnte man
	dabei auf Computer zurückgreifen, manchmal musste es eben auch
	einfacher gehen. Bereits in der Steinzeit, genau gesagt an einem
	Freitag den 13. fünf vor Zwölf bayerischer Atomzeit, erfand
	der Stammesfürst Kawumm von Sumpfland, derer zu Neanderthal,
	die theoretischen Grundlagen. Es müßte doch möglich sein, so
	sagte er sich, durch zärtliches Schleudern einiger Bits mit dem
	Nachbarstamm in Kommunikation zu treten. Zwar bestanden die Bits
	damals noch aus dem Naturstoff Stein (vgl. auch Hardware) - es
	war ja schließlich Steinzeit - doch wurde die erste
	Datenfernübertragung trotzdem ein voller Erfolg, der nur
	deshalb nicht in die Geschichte einging, weil es noch keine gab.

	So mancher geriet angesichts dieser bahnbrechenden Entwicklung
	in eine Verzückung aus der er nicht mehr erwachte. Wie der
	Sysop der Feuerstein-Mailbox. Ihn erschlug die Informationsflut.
	Diese besonders grausame Art der Jenseitsbeförderung hat sich
	bis in die heutige Zeit in einigen Ländern gehalten, wird aber
	nur bei besonders schweren Vergehen, etwa Verbreitung falscher
	Mailboxnummern, angewandt. Andere wiederum konnten sich für die
	Sache nicht so recht begeistern, und standen den Steinbits
	ratlos bis ablehnend gegenüber. Dieses Steinzeitdenken läßt
	heute noch einige reaktionäre Individuen gegen den Computer
	wettern. Ganz instinktiv eben.

	Doch zurück in die Vergangenheit: Die herumliegenden Bits, also
	Felsbröckelchen, ließen die damaligen Bewohner etwas
	leichtfertig mit den natürlichen Ressourcen umgehen. Schon bald
	ging der Rohstoff aus, und so endete die Steinzeit.
	
	Kawumm erlebte den Niedergang seiner Idee nicht mehr; er starb
	frühzeitig am ersten Acknowledge-Signal, auf dem Höhepunkt
	seiner Arbeit, so wie er es sich gewünscht hatte. Sein Grab
	konnte aufgrund der unpräzisen Adressierung leider bis heute
	nicht gefunden werden. Der Verlust dieses Genies einerseits und
	das Ende der natürlichen Signalvorkommen andererseits (es wurde
	offensichtlich schon gespeichert) führten dazu, daß die DFÜ
	in Vergessenheit geriet. Wie es sich herausstellen wird, jedoch
	nur für kurze Zeit.
	
	Im alten Rom war es dann, als man wieder Daten auf Reisen
	schickte. Cäsar, der größte Hacker der damaligen Zeit, liebte
	geradezu die DFÜ und schickte seine Grüße in die ganze damals
	bekannte Welt. Zwar mußten wieder einige Sysops daran glauben,
	die Entwicklung war aber nicht mehr aufzuhalten. Die römischen
	Imperatoren wurden so die ersten Opfern der hohen
	Telefonrechnungen. Zwar besaßen sie noch keinen solchen
	Apparat, aber ob Daten oder Soldaten, der Versand kostete
	Unmengen von Sesterzen und das Römische Reich mußte Konkurs
	anmelden. Tausende der im Gleichklang der Sandalen synchron
	marschierenden menschlichen Bits wurden arbeitslos.
	
	Die Geschichte feierte wieder ein paar Geburtstage, bis ein
	Organisationstalent namens Napoleon Bonaparte die Idee der DFÜ
	wieder aufgriff. Er war ein absoluter Freak, der keine Anwendung
	ausließ. So ließ er sich in Frankreichs bekanntester Software-
	schmiede, dem Bastille-Verlag in Paris, das erste Adventure-Game
	entwerfen. Monatelang saß ein junger übriggebliebener Adliger
	an dem Programm "Nappy goes to Moscow", kam aber nie über ein
	Flowchart hinaus. Nappy, Pardon, Napoleon nicht bis nach Moskau.
	(Auch ein etwa 150 Jahre später herausgebrachtes Remake,
	diesmal unter dem Titel "Adi goes to Moscow" scheiterte an der
	damals üblichen Röhrentechnik, weil die Verlustleistung nicht
	ausreichte, um ganz Sibirien ausreichend zu beheizen.) Der erste
	Programmierer wurde dann im Zuge der Französischen Revolution
	der Öffentlichkeit vorgestellt und verließ angesichts der
	begeisterten Menge das Podium ziemlich kopflos. Aber das hat mit
	der DFÜ nichts mehr zu tun.
	
	Napoleon, unterdessen ständig in Sachen Kriegskunst unterwegs,
	gab eine erfolgreiche Vorstellung nach der anderen und eroberte
	mit seinem einnehmenden Wesen die Welt (natürlich nur die
	damals bekannte). Die häufige Abwesenheit machte allerdings
	eine sorgfältige und sichere Datenübertragung erforderlich.
	Schließlich war Krieg, und bei dem wüsten Getümmel arbeitete
	die Post nicht besonders zuverlässig, was sie zwar heute auch
	nicht tut, dafür haben wir aber wenigstens keinen Krieg.
	
	In manch durchschlafener Nacht überlegte der Heerführer, von
	seinen Untergebenen liebevoll Europas größter Zwerg" genannt,
	fieberhaft, wie eine Lösung aussehen könnte. Eines Tages kam
	dieselbe, wie alles Gute, von oben. Eine Taube erleichterte sich
	ein wenig und wählte als Ziel ausgerechnet den kleinen Korsen
	aus. Der machte erstens den Dreck weg und zweitens das Beste
	daraus indem er die Brieftaube erfand, und damit wiederum die
	DFÜ förderte. Führende Köpfe der damaligen Zeit arbeiteten
	den Einfall aus und perfektionierten die Idee. Nach dem
	neuentwickelten Code benötigte man acht Tauben, die im
	Formationsflug einen Buchstaben bildeten. Zwar gab es schon den
	ASCII, den American Standard Code, der mit nur sieben Tauben
	auskam, aber das war eben in Amerik[36m
	Nappy stand vor einem seiner besten Fights, als er erschrocken
	feststellte, daß er seine Parade-Pantoffeln zu Hause bei seiner
	Josephine vergessen hatte. Sofort sandte er per Tauben-DFÜ die
	Nachricht: "Habe Pantoffeln vergessen. Sofort nachsenden. N.B."
	
	Dazu waren, wie sich leicht nachrechnen läßt, immerhin 560
	Tauben notwendig - inklusive Leerzeichen. Über den Alpen kam
	die ganze schöne Formation angesichts eines Lämmergeiers
	derart durcheinander, daß die Nachricht infolge mangelnder
	Redundanz unleserlich und in Paris falsch dekodiert wurde. Statt
	Pantoffeln bekam der Feldherr ein Paar Kartoffeln. Und da bei
	einem Sieg die Parade mangels schicker Schlappen ausgefallen
	wäre, verlor der Kriegskünstler die Lust an der Sache sowie
	die anschliessende Schlacht, und die Sache war für ihn
	erledigt. Für die Tauben allerdings auch. Da die meisten
	Nachrichten geheim waren, mußten die Boten, in diesem Falle
	also die Tauben, im Interesse der Sicherheit zum Schweigen
	gebracht werden. Eine Cousine des Schlachtenlenkers erfand
	daraufhin einige neue Rezepte die dann auch nach ihr benannt
	wurden. In der "Nouvelle Cuisine" (so hieß das Kochbuch) stand
	so manches Täubchen auf der Speisekarte. Dies führte
	zwangsläufig dazu, daß die flugtauglichen Bits immer knapper
	wurden. Der Erhalt der Gattung wurde glücklicherweise durch das
	Ende der napoleonischen Kriege, welches ziemlich zeitgleich mit
	dem Ende des Namensgebers fiel, gesichert.
	
	Nappy fiel nicht der Vergessenheit anheim: Denkmal für Denkmal
	schoß aus dem Boden - so daß manch braver Ackersmann nicht
	mehr wußte, wie er noch gerade pflügen sollte. Und sogar die
	kleine Anekdote, als der Vogel den Geistesblitz auf den kleinen
	Korsen fallen ließ, wird bis in die heutige Zeit bei jedem
	seiner Monumente exakt nachgespielt.
	
	Den nächsten entscheidenden Impuls bekam die Nachrichtentechnik
	dann in Deutschland, welches damals zwar noch nicht so hieß,
	aber schon so war. Ein Fürst namens Tut und Sagtnix erkannte
	folgerichtig daß es noch keine Post gab, als er einmal einen
	Brief in den nicht vorhandenen Briefkasten werfen wollte. Man
	bediente sich bis dato des einfachen Weges der Flaschenpost und
	versenkte die Briefe samt Leergut in den Starnberger See. Der
	geschäftstüchtige Fürst nahm flugs in der eigenen Bank ein
	Darlehen auf und kaufte auf dem nächsten Flohmarkt ein reich
	verziertes Postmonopol. Damit kam endlich Schwung in den Laden,
	und fürstliche Beamte sorgten dafür, daß alles klappte. Sie
	erhoben Porto, druckten und leckten die Briefmarken, und
	stempelten diese, bevor sie auf die Flaschen geklebt wurden, die
	dann im Starnberger See landeten. Mit der Post ging es
	aufwärts. Leider verlor der Postfürst sein Monopol am
	Spieltisch an den Kanzler, welcher damit nichts anfangen konnte
	und das Ding seinem Minister schenkte.
	
	Dieser schlug dann auch sofort zu, und erfand das deutsche
	Postmodem. Leider unterliefen ihm dabei einige
	Entwicklungsfehler, da der Computer noch nicht auf dem Markt
	war, und somit Kompatibilitätsprobleme die zwangsläufige Folge
	waren. Die Zeit bis zum Erscheinen der ersten Rechner wollte man
	dadurch überbrücken, daß man die Modems als solche
	verschickte, nach dem Motto: "soll sich doch der Empfänger
	darum kümmern, was darin steht". Jedoch ging auch dieser
	Versuch daneben, da das Gerät zu schwer und außerdem nicht
	wasserdicht war und auf Nimmerwiedersehen im Starnberger See
	versank. Glücklicherweise hatte man jedoch zwei Prototypen
	gebaut, so daß das Alternativexemplar auf seine Mängel hin
	untersucht werden konnte. Diese anspruchsvolle Aufgabe wurde dem
	renommierten Zentralinstitut für Zufallsforschung, ZZF in
	Darmstadt unter der Leitung der ersten Mailboxerin Deutschlands,
	Sylvia Soppelmann, übertragen. In Ihrem kleinen und zugigen
	Forschungslabor nahm die Wissenschaftlerin das Gerät auf seine
	Fehler hin auseinander. Was nicht funktionierte, bekamen die
	Japaner, den Rest behielt sie für den Bau eines neuen Modells
	im Labor zurück. Leider war es nicht sehr viel: Der
	verbliebene, einpolige, zirka vier Zentimeter lange Klingeldraht
	funktionierte zwar tadellos, ergab aber keinen Sinn. Ein drittes
	Modem mußte her, und daran scheiterten die ganzen weiteren
	Arbeiten. Die flotte Sylvia, in Kollegenkreisen Sysop genannt,
	wartet heute noch auf ein Postmodem, welches seinen Dienst
	ordnungsgemäß verrichtet; den Herren Bell und Hayes sei's
	geklagt, vergebens. Soweit also der geschichtliche Aspekt. Und
	da wir gerade bei der Geschichte sind, stelle ich Euch jetzt ein
	Paar Fragen, auf die es ebenso traditionsgemäß keine Antwort
	gibt:
	
	Was ist ein Sysop?
	
	a.) ein Steinzeithacker
	b.) ein alpenländischer Lämmergeier auf Taubenfang
	c.) ein Opfer grausamer Postbestimmungen
	
	Wieviele Tauben sind zur Übertragung einer Nachricht notwendig?
	
	a.) jede Menge
	b.) mehr oder weniger
	c.) nur eine Cousine
	
	Wie funktioniert ein deutsches Postmodem?
	
	a.) überhaupt nicht
	b.) eher zufällig
	c.) Sonntags nie
	
	
	Und hier die Antworten:
	
	Ein Sysop ißt so ziemlich alles, außer Knoblauch. Warum dem so
	ist, kann ich nicht sagen - vermutlich löst die Angst vor
	daraus sich ergebenden Kommunikationsproblemen die Freßhemmung
	aus, obwohl man das Allium Sativum durch ein Modem gar nicht
	riechen kann.
	
	Die zweite Frage war die schwerste. Sie fiel mir während des
	Schreibens in den Starnberger See und ist samt der
	dazugehörigen Antwort bis heute nicht wieder aufgetaucht.
	
	Die dritte war, ganz klar, eine Fangfrage. Sie stammt vom
	Bundespostminister selbst, der die Antwort dringend für seine
	weitere Planung benötigt. Antworten nimmt jeder Briefträger
	entgegen. (Bitte den Postboten ausreichend frankieren und NICHT
	in den Starnberger See werfen !!!)
	
	Nun aber zur Sache. Wie funktioniert DFÜ, die Sache mit dem
	Pfiff, eigentlich? Richtig, auf das Piepen kommt es in der Tat
	an. Der Gedanke läge nahe, sich einen Vogel zuzulegen, doch
	darf ich davon ausgehen daß ein Hacker bereits einen hat, den
	wie käme er sonst auf die Idee, sich auf eine so abenteuerliche
	Sache einzulassen. Sinnvoller, ja fast unersetzlich ist der
	Besitz einer Schnittstelle. Mancher Computer hat eine, ein
	anderer nicht. In diesem Falle hat man sich bereits beim Kauf
	des Computers geschnitten und muß nachrüsten, was teuer ist.
	
	Dadurch bekommt man bereits einen Vorgeschmack auf die Kosten,
	die auf einen noch zustürmen werden. Weiterhin ist noch ein
	Akustikkoppler notwendig. Dabei gehe ich davon aus, daß... Ach
	was, ich bleibe lieber hier. Es ist nämlich ziemlich sicher,
	daß die Post bis zur Drucklegung dieses Artikels immer noch
	kein Modem - außer ihrem eigenen - genehmigt hat. Und dieser
	Aufsatz soll berichten wie die DFÜ funktioniert und nicht wie
	sie es dank eines Postmodems NICHT tut. Ohne amtliche Elektronik
	kann es nun losgehen. Nein, noch nicht ganz, denn es wird noch
	eine Kabelverbindung zwischen Koppler und Schnittstelle
	benötigt, damit die Geräte nicht so frei im Raum
	herumschweben. Wie immer, wenn man es mit hochwertiger
	Elektronik zu tun hat, ist es mit einer einfachen Strippe nicht
	getan, da muß schon etwas teureres her. Ohne Kabelsalat macht
	die Sache sowieso keinen Spaß. Nun muß man nur noch über ein
	geeignetes Kommunikationsprogramm verfügen (nach Meinung der
	Freaks gibt es keine wirklich guten, man schreibt sich seine
	Software also am besten selbst).
	
	Dem Willigen stellt sich meist nur noch ein Hindernis in den Weg
	- das Telefon: Hat man eines, dann ist es schlecht, hat man
	keines, dann erst recht. Behandeln wir zuerst den Fall des nicht
	vorhandenen Telefons: Meist steht dann irgendwo an einer nahen
	Ecke eine Telefonzelle zur Verfügung. Man muß dann nur noch
	die gesamte Ausrüstung in dieses gelbe Häuschen transportieren
	und ein ausreichend langes Verlängerungskabel besorgen. Mit
	einem reichlich bemessenen Vorrat an Münzen steht einem
	geselligen Verkehr mit Gleichgesinnten nichts mehr im Wege.
	
	Weniger empfehlenswert ist es, mit Computer, Disketten,
	Akustikkoppler usw. beladen bei der Nachbarin aufzukreuzen, und
	mit harmloser Miene anzufragen ob man eben mal kurz telefonieren
	könne. Falls die Dame für ein derartiges Ansinnen überhaupt
	Verständnis aufbringt, besteht immer noch die Gefahr, daß sie
	unter dem "geselligen Verkehr mit Gleichgesinnten" was völlig
	Falsches versteht.
	
	Aber es soll ja Leute geben, die über einen eigenen Anschluß
	verfügen, wenngleich sie damit immer noch nicht besser dran
	sind. Moderne Apparate haben nämlich viereckige Sprech- und
	Hörmuscheln die sich so an die Ohrform des Verbrauchers
	angepaßt, und damit gleichzeitig von den Aufnahmehalterungen
	eines Durchschnittskopplers entfernt haben. Aber das ist nur ein
	kleines Problem, das sich im Laufe einer Nacht im Bastelkeller
	beseitigen läßt. Hier wird aus einem Kilo Einmachgummis und
	einem Eimer Kleister ein Adapter für den Hörer gebastelt:
	Einmachgummis aufkochen und eine Stunde ziehen lassen. Dann den
	Leim hinzufügen und das Ganze durch kräftiges Pusten
	abkühlen. Wenn der Kleber trocken ist, kauft man sich einen
	neuen, induktiven Koppler, und schmeißt den alten weg. Nun kann
	es aber endgültig losgehen.
	
	Zuerst wird die Nummer einer bekannten Mailbox gewählt. Haltet
	ruhig mal den Hörer ans Ohr, es tut gar nicht weh. Was ihr da
	hört, ist das Besetztzeichen, welches für bekannte Mailboxen
	typisch ist. Wählt also lieber eine weniger bekannte an, etwa
	die des Katholischen Hilfswerkes. Und was kann man jetzt hören?
	Richtig, immer noch das Besetztzeichen. Es müßte sich ja
	mittlerweile herumgesprochen haben, daß das Telefonnetz tags-
	über nicht und nachts höchst selten funktioniert. Solange die
	Sonne scheint ist die Leitung schon bei der Vorwahl überlastet
	und läßt den DFÜ-Freaks keine Chance. Wir lassen also die
	Nummernfummelei bleiben, verlegen die Aktion auf die Nachtzeit,
	und widmen uns in der Zwischenzeit der Theorie.
	
	Besorgt Euch bitte mal acht wohlklingend piepende, hübsch
	anzusehende, graue (wie die Theorie) Ratten. Ratten sind, das
	weiß man aus dem Kino, gesellige, lernwillige Tiere, so ganz
	anders als der gemeine Goldhamster, die für einen DFÜ-Versuch
	abgerichtet werden können. Gebt den Schmusetierchen die Namen
	Bittie-Null bis Bittie-Sieben (abgeleitet von Bit).
	
	Jetzt kommt es nur noch darauf an, diese wilde Horde so zu
	dressieren, daß sie wunschgemäß piept. (Sie haben doch auf
	wohlklingende Exemplare geachtet?) Nun schaut ihr Euch bitte den
	ASCII-Code für den Buchstaben "A" im Handbuch an und übersetzt
	ihn in die Binärform. Habt Ihr das gecheckt? Prima, obwohl es
	gar nicht nötig war, denn meine Ratten haben es mir schon
	verraten: Binär heißt das "A" eigentlich "01000001". Jetzt
	wißt Ihr es also, und könnt inzwischen überprüfen, ob die
	Ratten noch auf ihren Plätzen sind. Falls nicht, empfiehlt sich
	die Suche unter nahegelegenen Schränken und Betten, da nur
	extrem träge Exemplare auf derselben Stelle verharren, während
	Ihr Euch mit den Codetabellen herumschlagt. Nun laßt Ihr die
	Ratte Null und Ratte Sechs durch sachtes Kneifen piepsen. Das
	Ergebnis ist der DFÜ-Ton des Buchstabens.
	
	Kenner der Materie wissen schon daß man für die reine
	Textübertragung keine 8 Ratten benötigt, da ja bereits 7 Bits
	für alle Zeichen ausreichen. Diese Schnellmerker werden jetzt
	gleich fragen, was ich denn mit dem letzten Tierchen mache (es
	ist übrigens ein Weibchen, und sie heißt Helene). Ihre
	ursprüngliche Aufgabe war es, den Telefonhörer zu halten.
	Leider war derselbe zu schwer. Da sie (Helene) sich jedoch als
	außerordentlich klug erwies, habe ich beschloßen, ihr den Piep
	des Paritätsbits zu übertragen. Dazu ist mathematisches Talent
	erforderlich, muß doch die Summe aller abgeschickten Pieper auf
	even oder odd gebracht werden. Hier wäre die Anschaffung eines
	billigen Taschenrechners zu erwägen, um, insbesondere bei
	höheren Übertragungsraten (ab etwa 150 Baud), dem Vorwurf der
	Tierquälerei wirkungsvoll zu begegnen. Sollte Euch eine
	ähnlich gute Dressurleistung gelingen, könnt Ihr damit im
	Zirkus auftreten, die Verwandtschaft beeindrucken, oder im
	Fernsehen auftreten. Was Ihr nicht könnt, ist DFÜ. Hierzu ist
	nämlich noch einiges mehr nötig. Da gibt es das Stoppbit, für
	das am besten eine von Natur aus langsame Ratte benutzt wird.
	(Bei Zweien ist der Bremsweg entsprechend kürzer.) Außerdem
	wird ein Antwortsignal benötigt, bei dem solch ein Tierchen
	auch die Fähigkeit zum Zuhören haben muß. Kurz und gut, da
	auch noch dauernd der Käfig saubergemacht werden muß, sollte
	man auf diese Arbeitsweise verzichten, und die Ratten in die
	Freiheit entlassen, vielleicht in der Umgebung eines Postamtes.
	
	Mittlerweile ist es auch schon Mitternacht, und wir können
	wieder mal versuchen eine Mailbox zu erreichen. Also: wieder
	wählen und lauschen. Und tatsächlich, es ist ein mehr oder
	weniger deutliches "Pieep" zu vernehmen. Es ist der Computer,
	genauer gesagt das Programm, ganz genau gesagt der Carrier, der
	uns zu verstehen gibt: "hier bin ich, die DFÜ kann beginnen".
	
	Mist! Das hätte man vorher wissen sollen! Bis Ihr jetzt den
	Computer eingeschaltet, die Software geladen und gestartet habt,
	ist die Verbindung längst weg. Das Ganze nennt sich Timeout,
	und dient dazu, auch anderen Freaks die Möglichkeit zu geben
	dem "Pieep" (auch Carrier genannt) der Mailbox zu lauschen.
	
	Für den zweiten Versuch sollte der Computer also eingeschaltet
	und das Programm geladen sein. Wenn Ihr das Zeichen hört,
	drückt den Hörer schleunigst in den Koppler, und schon
	erscheint das Titelbild der Box auf dem Bildschirm. Die
	darauffolgende Frage nach dem Namen könnt Ihr nur beantworten,
	wenn Ihr einen habt. Wenn nicht, dann nehmt bitte etwas
	Originelles, z.B. Dr. Bakterius, Glombofax oder Megasieb. Namen
	wie Hacker, Superman oder Joshua werden nur noch von den
	phantasielosesten Gesellen in der allerersten Anfangszeit
	benutzt, und verweisen auf einen niedrigen Intelligenzquotien-
	ten. Die nächste Frage ist jene nach dem Paßword. Holt nun
	Euren neuen, maschinenlesbaren Personalausweis, schaut nach,
	welche Zeichenfolge Euch am besten gefällt, und gebt dieselbe
	ein. Da die ja dem Sysop naturgemäß fremd ist, werdet Ihr auf
	Gastlevel niedergestuft. Die Frage GAST JA/NEIN beantworte man
	tunlichst mit "J", da es vielleicht etwas zu trinken gibt.
	
	Merke: die wenigsten Sysops sind Abstinenzler (abgesehen
	vielleicht von denen der Katholischen Sozialhilfe). Die ganze
	Prozedur heißt "Einloggen", was soviel wie "Reinkommen"
	bedeutet. Ist man erstmal drin (in der Mailbox) steht man vor
	einer Bretterwand. Das Inhaltsverzeichnis einer anständigen
	Mailbox wird nämlich in sogenannte Bretter unterteilt. Diese
	Unterteilung ist auf den berühmten Hundezüchter und allseits
	anerkannten Dünnbrettbohrer Christian Blackpenny
	zurückzuführen. Dieser entwickelte das Mailboxsystem und
	führte es international ein - daher der Name FidoNet. Leider
	verirrte er sich in demselben und gilt seit dem Zeitpunkt als
	vermißt, in dem ein unvorsichtiger Sysop die Leitung durch
	einen voreiligen ATH0-Befehl kappte.
	
	Damit es Euch nicht ähnlich ergeht, solltet Ihr die Bretter
	systematisch durchforsten. Das kostet zwar Zeit, (und die ist
	bekanntlich Geld) das ist aber nicht besonders tragisch wenn man
	ein Firmentelefon benutzen kann, und nicht gerade stundenlange
	Chats mit Übersee fährt. Und damit sind wir schon beim letzten
	Punkt, nämlich der Telefonrechnung. Zum unbedingten
	Statussymbol eines halbwegs ernstzunehmenden Hackers gehört in
	jedem Falle eine Telefonrechnung die mindestens 20% des
	monatlichen Bruttoeinkommens ausmacht. Niedrigere Summen lassen
	berechtigte Zweifel an der Ernsthaftigkeit des Hobbys aufkommen,
	und haben im Wiederholungsfalle eine Sperrung des Teilneh-
	meranschlusses sowie einen zwangsläufigen Anschluß an BTX zur
	Folge; im Wiederholungsfall kann auch eine Verkabelung verfügt
	werden.
	
	Zum Abschluß noch einmal einige Fragen:
	
	Wohin mit den Ratten?
	
	a.) der Freundin schenken
	b.) ab in die Natur
	c.) an die nächste Mailbox schicken
	
	Bretter sind...
	
	a.) dazu da, durchbohrt zu werden
	b.) Kopfschmuck eines Hackers
	c.) die rustikale Verkleidung einer Mailbox
	
	Eine gute Mailbox erkennt man...
	
	a.) an den gutdressierten Ratten
	b.) am Belegtzeichen
	c.) an der Telefonrechnung
	
	(Die Antworten findet Ihr demnächst in irgendeiner Mailbox.)
	*** Text gefunden in der chip-Mailbox (leicht bearbeitet) ***

@ENDNODE

@NODE ST0002 "Namen, die keiner haben möchte..."
@TOC Witze.guide/Inhalt

   Jaaa, und mal wieder sind ein paar neue Namen eingetroffen.
   Wer weiß, welche??? :-)

	Roy Aal		
	Alf Abet	
	Ann Alphabet	
	Ole Ander	
	Alex Andria	
	Paul Aner	
	Peer Anhalter	
	Mark Ant	
	Chris Antheme	
	Bill Anz	
	Minni Apolis	
	Bill Ard	
	Al Arm		
	Mark Aroni	
	Claire Asil	
	Tom Ate		
	Bill Ateralismus
	Karl Auer	
	Don Aumonarchie	
	Rudi Ch. Aus	

	Allah Bama	
	Roy Bär		
	Ted I. Bär	
	Chris T. Baum	
	Johannes Beer	
	Jo Ch. Bein	
	Mercedes Benz	
	Frank N. Berg	
	Oli Bergott	
	Ali Bi		
	Buddy Bilding	
	Z. L. Block	
	Harry Bo	
	Ellen Bogen	
	Tom Bola	
	Anna Bolika	
	Lisa Bonn	
	Anke Brandt	
	Nick L. Brille	
	Gret Britten	
	Johannes Brotbaum
	Tim Buktu	
	Wilma Bumsen	
	Gunther Bunt	
	Johannes Burg	
	Glenn Buterol	

	Ali Cante	
	Fred Chen	
	Anna R. Chie	
	Al Chimie	
	Mary Christmas	
	Anna Chronismus	
	Bo Chum		
	Dr. A. Cula	
	Toni Cwater	
	Sally Cylsäure	

	Marina D.	
	Jack Daniels	
	Stan Dard	
	Addi Dass	
	Zita Delle	
	Phil A. Delphia	
	Bill Derbuch	
	Theo Derkaffee	
	Ellen Desau	
	Bud Dha		
	Benny M. Dich	
	Bernhard Diener	
	Dick S. Ding	
	O. Dohl		
	Theo Dorand	
	K. T. Drale	
	Ernie Drigt	
	Wanda Düne	
	Bill Dung	
	Stalin Dustrie	
	Cliff Dwellings	

	Ben Ediktiner	
	Ben Ehmen	
	Ed Eka		
	Bert Elsmann	
	Ben Elux	
	Dan Emark	
	Matt Emathik	
	Steve  Enkelchen
	Chris T. Entum	
	Norman Estomen	
	Jeff Etage	
	Bill Ett	
	Jack Ett	
	Al Euten	

	Anna L. Fabet	
	Connie Fähre	
	Clara Fall	
	Todd S. Fall	
	Roy Al Family	
	Olli Fanten	
	Ernst Fall	
	Elli Fant	
	Luzi Fer	
	Perry Ferie	
	Heinz Fiction	
	Pom S. Fritz	
	Frank Furt	

	Ben Galien	
	Ali Gator	
	Ann Geber	
	Al Gebra	
	Bela Gerung	
	Bud Get		
	Jo Ghurt	
	Ann Gina	
	Armin Gips	
	John Gleur	
	Resi Gnation	
	Anna Gramm	
	Philly Gran	
	Pit A. Goras	
	Al Gorithmus	
	Claire Grube	

	Dick Häuter	
	Franz Hösisch	
	Rainer Hohn	
	Kurt Hose	
	Marie Huana	

	Bill Ich	
	Bart Ik		
	Buck Inghampalace
	Wayne Interessierts
	Martin Ipur	
	Kurt Isane	

	Louis Jana	
	Gregor Janisch	
	Bill Jard	
	Matt Jeshering	
	Henry Jette	
	Marie Juana	

	Jaques Kahl	
	Lea Kasten	
	Indy Kator	
	Hans A. Keks	
	Cindy Kerzenan	
	Eddi Kett	
	Paul S. Kirche	
	Ole Kmichamarsch
	Jeff Koch	
	Jo Kohama	
	Al Kohol	
	Sammy Kolon	
	Anna Konda	
	Klara Korn	
	Boy Kott	
	Christoph S. Kraut
	Maria Kron	

	K. K. Lacke	
	Falk Land-Inseln
	Ellen Lang	
	T. LéFon	
	Pedro Leum	
	Connie Lingus	
	Theo Loge	
	Anna Logie	
	Rainer Lös	
	Buddy Lotion	
	Toto Lotto	
	Anna Lüttich	
	Anna Lyse	

	Anne Marie	
	S. N. Smarke	
	Anni Mation	
	Kai Mauer	
	K. Melle	
	Rudi Mentär	
	Ali Mente	
	Sam Mel		
	H. Mell		
	Achim Merdasgleiche
	Ede L. Metall	
	Milli Meter	
	Alex Miamorsch	
	Witta Mine	
	Otto Motor	
	Max I. Mumm	

	Alma Nach	
	Gert Nähr	
	Rosi Nante	
	Anna Naß	
	Rosi Ne		
	Anke Nehm	
	Gert Nerei	
	Kai Nerwas	
	Mario Nette	
	Inge Nieur	
	Pia Nist	

	Bettina Oberfläche
	Perry Ode	
	Frank Furt Oder	
	Her Odes	
	Karel Ofen	
	Konstantin Opel	
	Frank Ophil	
	Tobi Ornottobi	
	Fret Öse	
	Franz Osen	
	Phil O'Soph	
	Rob Otter	
	André Otti	

	Sham Paine	
	Jim Panse	
	Leo Pard	
	Sepp Pell	
	Wim Pell	
	Martha Pfahl	
	Neil Pferd	
	M. Pfinden	
	Hans A. Plast	
	Markus Platz	
	Dennis Platz	
	Jack Pot	
	Lilly Putaner	

	Manne Quinn	

	Jupp Heidi Rassa
	Peter Rast	
	Alf Reed	
	Frank Reich	
	Theo Rettisch	
	Mike Rhosoft	
	Lotte Rie	
	Sabine Rinnen	
	Sam A. Riter	
	Bill D. Röhre	
	Alf A. Romeo	
	Karl S. Ruhe	

	Rene Sangs	
	Tino Saurier	
	Claas Scheibe	
	Todd N. Schein	
	Knut Schfleck	
	Olle Schleuder	
	Rosa Schlüpfer	
	Axel Schweiß	
	Cher Selongue	
	Erwin Selter-Bärmlich
	Kai Ser		
	Rod Sfahne	
	Peer Sil	
	Peter Silie	
	Hal Sinki	
	Klara Sprudel	
	Peer Sonal	
	Sam Soneit	
	Ken Stdudenschon
	Dina Stee	
	Frank N. Stein	
	Chris T. Stollen
	Todd S. Strafe	
	Polly Styrol	

	Ken Tacki	
	M. N. Taler	
	Claus Taler	
	Ali Talia	
	Sunny Täter	
	Dick Tator	
	Ken Taurus	
	Sepp Tember	
	Alf A. Teilchen	
	Al T. S. Testament
	Anna Tomie	
	Claus Thaler	
	Karl S. Thum	
	Chris Tiane	
	Roman Ticker	
	Nico Tien	
	Ina R. Tikuliert
	Chris Tina	
	Ann Tipathie	
	Dan Tist	
	Anna Tomie	
	Chris Topher	
	Moni Tor	
	Ray Tracing	
	Jeff Trainer	
	Klaus Trophobie	
	Hinrich Tung	
	Chris Tus	
	Ann Tworten	

	Sheila Uf	
	Al Uminium	
	Farin Urlaub	

	Ed V.		
	Steve Vater	
	Olli Ven	
	Peer Verser	

	Hella Wahnsinn	
	Don R. Wetter	
	Al Wissend	
	Claus E. Witz	
	Peer Woll	
	Gutfried Wurst	
	Hans Wurst	
	Ken Wutt	

	Bo Xer		

	Brad R. Zaun	
	Polly Zei	
	Ann Zeiger	
	Sarah  Zene	
	Egon Zentrisch	
	Effi Ziens	
	Ken Ziffer	
	Ben Zin		
	Ben Zinka-Nister
	Polly Zist	
	Reiner G. Znich	
	Ben Zpyrenaldehyd
	Werner Zuela	
	Rainer Zufall	
	Ann Zug		

	Rick Olaschweizerkräuterzuckerbonbon	

   Und für alle, die mir Namen schicken wollen, die hier noch nicht
   drin sind, die offiziellen Rules für die Namensbildung:

   - Der gesamte Name muß einen sinnvollen Begriff oder eine Aussage
     ergeben.

   - Der Vorname muß bekannt bzw. belegbar sein. Kurzformen, z.B.
     "Kalli" oder "Leo", sind erlaubt.

   - Bei ausländischen Vornamen entscheidet die Aussprache über den
     Namen. Beispiel: "Ann" wird wie "Änn" ausgeprochen, daher ist
     "Ann Derung" zulässig, nicht aber "Ann Geber".

   - Doppelte Vornamen sind nur erlaubt, wenn beide das gleiche
     Geschlecht haben.

   - Abkürzungen sind nur in Verbindung mit einem ausgeschriebenen
     Vornamen an erster Stelle (z.B. "Art E. Fakt") oder als zwei
     Buchstaben erlaubt. Der Name muß sich aus der gesprochenen Form
     der Abkürzung ergeben, z.B. "R.-G. Ben".

   - Ein Name kann sich auch durch etwas nachlässige Aussprache
     ergeben, z.B. "Karl Ender" oder "Joe Kolade".

   - Der Nachname muß einzeln aussprechbar sein, z.B. ist "Gero Det"
     erlaubt, aber nicht "Gero Ntologie".

   - Der Nachname kann zur Verdeutlichung der Aussprache des
     gebildeten Begriffes falsch geschrieben werden, z.B. "Polly
     Meer".

   Nicht eigentlich zu dieser Rubrik gehörend, aber vom Stil her
   doch passend ist folgende kleine Story:

	Das ist ein Kerl! Er heißt Eddy und gehört in die Familie Tor.
	Seine Schwester heißt übrigens Moni.
	Das ist die, welche mit dem Naturkosthändler *Mike* *Rohsoft*
	liiert ist.
	Übrigens, auch dessen Vater *Bill* *gehts* neuerdings recht gut,
	seit er endlich *die* *Skoppi* in einem Durchgang schafft, ohne
	dauerndes rein-raus, aber jetzt wirds ordinär.
	Daher: *"Sei"*, *mahnt* *Egg*, der alte Eierkopf, "zu *B.* *Z.*
	  *Uhls* doch gnädig, sonst verschlägt es eines Tags auch dich
	  an einen *bittern* *Ort* *ohn'* Speed und Soft!"

@ENDNODE

@NODE ST0030 "Raumschiff Pfannekuchen"
@TOC Witze.guide/Inhalt

		Raumschiff Pfannekuchen - Angriff der Spaghetti
		***********************************************

	"Der Obstkuchen. Unendliche Birnen und Äpfel. Wir essen die
	 Torte im Jahre 2300 mit Rosinen und Schlagsahne. Immer auf
	 der Suche nach neuen Früchten und Tortenböden, ist das
	 Raumschiff "Pfannekuchen" unterwegs, um auch andere Nahrungs-
	 mittel zu erforschen und nutzbar zu machen!"
	 Viele Gummibärchen von der Erde entfernt erlebt die Besatzung
	 der "Pfannekuchen" Abenteuer, die nie eine Quarktasche vorher
	 erlebt hat."

	Birnenzeit: 23451.1 Capt.Apfelkuchen:
	Wir durchfliegen mit der "Pfannekuchen" Kirschensektor Gamma
	9. Eine Raumsonde hat uns einen Eindringling gemeldet der den
	Planeten Erdnussbutter angreifen will. Wir wissen bis jetzt
	nicht wer die Eindringlinge sind. Aber wir müssen alles
	versuchen um die Eroberung des Planeten Erdnussbutter zu
	verhindern, da dieser unsere gesamten Reserven an Ölsardienen
	hat. Die Crew ist vorbereitet, ich habe Alarm lila gegeben!

	- "Mr. Bröselbein, schon irgendwelche Zeichen des feindlichen
	   Schiffes gescant?"

	- "Nein Captain. Ich justiere noch die Brotkrümmel im System...
	   Moment, ich bemerke eine Puddingspur auf Kurs 77343.2.
	   Diese Spur ist ist mit keiner uns bekannter Schiffsbauart
	   identisch. Es könnte der Feind sein..."

	- "Gut Mr. Bröselbein. Fähnrich Gräßlich setzen Sie Kurs!"

	- "Aye, aye, Captain....Kurs gesetzt!"

	- "Geschwindigkeit: Waffel 3...Energie!"

	Birnenzeit:23452.3 Capt.Apfelkuchen:
	Wir sind auf den Weg das feindliche Raumschiff abzufangen. Was
	wird uns erwarten?
	Inzwischen habe ich Lt.Negerkuß den Befehl gegeben die Engergie
	der "Pfannekuchen" auf alle Schilde und Waffen zu verlegen.
	Er teilte mir mit, daß die Systeme zu 85% einsatzbereit sind.
	Machmal frage ich mich wirklich wie dieser Mann mit soviel
	Schokolade im Gesicht, es immer wieder schaft, die "Pfanne-
	kuchen" so in Schuß zu halten. Ich bin froh, daß er zu meiner
	Crew gehört.

	- "Capt. Apfelkuchen, wir sind jetzt in Abfangreichweite des
	   feindlichen Schiffes. Möchten Sie visuellen Kontakt zu dem
	   Raumschiff?"

	- "Ja Mr. Gräßlich. Auf den Pizzaboden!"

	- "Sir, es ist ein Raumschiff der Spaghetti. Nach meinem Scan
	   sind ihre Waffen einsatzbereit, ich schlage vor das Feuer
	   zu eröffnen!"

	- "Nein, Mr. Bröselbein. Stellen Sie Kontakt zu den Spaghettis
	   her. Ich möchte erst wissen ob sie zu Verhandlungen bereit
	   sind!"

	- "Captain! Das Schiff führt als Bewaffnung Ketchup-Torpedos.
	   Wir sind kaum in der Lage diese lange standhalten zu können.
	   Ich rate zur Vorsicht!"

	- "Danke, Mr. Gräßlich. Aber nach allen was ich über diese
	   Spaghetti gehört habe greifen sie erst an, wenn sie provziert
	   werden!"

	- "Welcher Art von Provokation?"

	- "Nun, Cmdr Dödelbirne, sie haben etwas gegen Spaghetti mit
	   Speck und Zwiebeln. Wenn Sie das in deren Gegenwart an-
	   sprechen, werden sie agressiv und verlieren jede Beherr-
	   schung. Daher sollten wir strikt vermeinden über Zwiebeln
	   und Speck zu sprechen!"

	- "Ich habe verstanden, Captain!"

	- "Sir, Geruchssequenzen offen!"

	- "Danke Mr. Bröselbein!
	   Hier ist das Milchraumschiff "Pfannekuchen". Ich bin Captain
	   Apfelkuchen. Sie befinden sich in unserem Gebiet. Nennen
	   Sie mir den Grund Ihres Hierseins!"

	- "Captain, wir empfangen jetzt ein vanilliges Bild der
	   Spaghetti!"

	- "Auf die Pizza, Mr. Gräßlich!"

	- "Sie sehen sehr quirlig im Gesicht aus, Captain. Glauben Sie,
	   man kann mit ihnen verhandeln?"

	- "Mr. Dödelbirne, wenn Sie ständig Nudeln im Gesicht hätten,
	   glauben Sie, daß Sie nicht irgendwann mal was anderes auf
	   den Teller wollen? Das wird sicher der Grund sein, warum
	   sie den Planeten Erdnussbutter angreifen wollen. Sie sind
	   scharf auf was Neues... auf Ölsardienen. Und sie wissen,
	   daß wir es niemals zulassen werden unsere Reserven freizu-
	   geben.
	   Es wird schwer werden, überberzeugend zu sein. Ich hoffe,
	   es geht gewaltlos!"

	- "Mein Name ist Capt. Nudelsuppe, ich bin Captain des Schiffes
	   "Macaroni". Ich fordere sie auf uns umgehend den Weg frei
	   zu machen, oder wir ketchupen Sie..."

	- "Captain Nudelsuppe, sollten wir lieber nicht versuchen,
	   erst einmal rauszukriegen, warum Sie hier sind? Vielleicht
	   können wir das Problem ja gemeinsam lösen!

	- "Einverstanden, Capatain. Ich schlage vor, daß wir uns auf
	   Ihrem Schiff treffen und dort alles weitere besprechen,
	   ich bringe meinen ersten Offizier Pamesan mit."

	- "Einverstanden, in 10 Mintuten an Bord meines Schiffes! Mr.
	   Bröselbein, Geruchssquenzen wieder schließen!"

	- "Aye, Sir!"

	- "Counselor Drollig, was können Sie mir über das Empfinden
	   dieser Wesen sagen?"

	- "Nun, sie ist sehr konsequent. Ich rate zur Vorsicht. Das
	   Wort "Speck" würde ich in jedem Falle vermeiden, darauf
	   reagieren sie am agressivsten. Aber ich glaube sie sind zu
	   Verhandlungen bereit, wenn auch nur unter Vorbehalt.

	- "Mr. Bröselbein, Negerkuß und Counselor Drollig, sie begleiten
	   mich in den Gemüseraum unsere Gäste zu empfangen. Cmdr.
	   Dödelbirne, Sie übernehmen die Brücke."

	Birnenzeit: 23458.3 Capt.Apfelkuchen:
	Wir haben unsere Gäste an Bord unsere Schiffes gepuderzuckt.
	Diese Wesen sehen  sehr hmm... interessant aus. Sie tragen
	Tomaten in den Haaren und an ihren Händen sind große Nudel-
	löffel befestigt. Ihre Kleidung besteht hauptsächlich aus
	roten Sabberlätzchen und an ihren Gürteln tragen sie Ketchup-
	Phaser. Eine der schlimmsten Handfeuerwaffen im Universum.
	Ich habe für unsere Gäste im Konferenzraum eine große Schüssel
	Spaghetti bereitgestellt, natürlich ohne Zwiebeln und Speck.

	- "Captain Nudelsuppe, ich freue mich sie an Bord meines
	   Schiffes begrüßen zu dürfen, fühlen Sie sich wie zu Hause!"

	- "Danke, Captain Apfelkuchen. Und vielen Dank für die Spa-
	   ghetti, ich sehe, Sie sind mit unseren Sitten vertraut."

	- "Das ist doch wohl das Mindeste was wir für Sie tun können.
	   Nun, ich denke, wir sollten darüber sprechen, was Sie hier
	   herführt!"

	- "Captain, wir wollen ihren gesamten Vorrat an Ölsaerdienen.
	   Sie und ich wissen, das er auf Planet Erdnussbutter ist.
	   Machen Sie uns keine Schwierigkeiten. Dann könnte ein Krieg
	   vermieden werden."

	- "Wir können Ihnen auf keinen Fall die Ölsardienen überlassen.
	   Sie sind unsere Energiereserven, das sollten Sie wissen.
	   Wir möchten keinen Kampf, aber wir sind bereit alles zu
	   tun um den Planeten Erdnussbutter zu verteidigen. Aber wir
	   können Ihnen unseren Vorrat an Thunfisch anbieten..."

	- "Dann ist unsere Verhandlung hiermit beendet, wir werden
	   uns umgehend auf unser Schiff zurückpudern und das Feuer
	   eröffnen, kommen Sie Cmdr. Pamesan."

	- "Ja, My Lord!"

	Birnenzeit:23455.4 Capt.Apfelkuchen:
	Die Spaghetti kehrten auf ihr Schiff zurück. Ich veranlaßte
	sofort, die Schilde aufzubauen und die Eier-Bänke zu aktivieren.
	Wir mußten uns nun auf einen schweren Kampf vorbereiten.

	- "Captain, die Spaghetti feuern mit Ketchup auf uns."

	- "Lt. Bröselbein, sind die Schilde oben?"

	- "Ja, Sir!"

	(Klatsch!)

	- "Sir, die Schilde sind völlig mit Ketchup verklebt, wir haben
	   noch 60% Energie für die Schilde"!

	- "Lt. Bröselbein, eröffnen Sie das Feuer. 20 Eier vor den Bug!"

	- "Aye, Sir!"

	(Klatsch - Klatsch!)

	- "Sir, mehrere Treffer an ihren Sekundärschilden, kaum Schäden!"

	- "Mr. Gräßlich, berechnen Sie einen neuen Kurs um der nächsten
	   Angriffswelle auszuweichen!"

	- "Aye, Sir!"

	- "Mr. Bröselbein, feuern Sie 60 Salatköpfe auf ihren Antrieb,
	   in dem Moment, wenn wir auf neuen Kurs gehen!"

	- "Sir, sie schießen mit Tortenböden auf uns...!"

	- "Mr. Gräßlich, gehen Sie sofort auf den neuen Kurs, Mr.
	   Bröselbein, Feuer!"

	(Klatsch - Klatsch - Klatsch!)

	- "Sir, wir haben neuen Kurs erreicht, wurden aber noch von
	   mehren Tortenböden getroffen!"

	- "Captain, schwere Schäden auf den Abteilungen: Rosenkohl,
	   Scampis und Puderzucker..außerdem wurde unser Waffelantrieb
	   beschädigt!"

	- "Mr.Negerkuß, informieren Sie die Gärtner, Fischer und
	   Bäcker... sie sollen mit den Reperaturarbeiten beginnen!"

	- "Sofort Captain!"

	- "Captain, ich schlage vor unsere neue Geheimwaffe einzu-
	   setzten, damit könnten wir sie außer Gefecht setzten!"

	- "Nein, Mr.Bröselbein. Niemals. Diese neue Waffe ist so
	   schrecklich, das können wir nicht verantworten, diese
	   bedauernswerten Wesen wären sofort manövrierunfähig,
	   vielleicht sogar vernichtet. Wir müssen uns etwas anderes
	   ausdenken"!

	- "Captain, eine weitere Angriffswelle folgt, laut Computer
	   torpedieren sie uns mit Tomatenmark!"

	- "Mr. Bröselbein feuern Sie sofort mit Oliven zurück, viel-
	   leicht können wir einen Gegendruck erzeugen, so, daß uns
	   das Tomatenmarkt nicht mehr erreicht!"

	- "Ich feuere...Treffer...100% des Tomatenmarks wurde abge-
	   halten. Aber dafür ist unser Vorrat an Oliven zu Ende.
	   Einen nächsten Beschuß werden uns unsere Schilde kosten!"

	Birnenzeit: 23343.9 Capt.Apfelkuchen:
	Die Lage scheint aussichtslos. Lt. Bröselbein empfahl die neue
	Geheimwaffe zu benutzen, aber dürfen wir das wirklich? Mein
	Gewissen plagt mich, ich habe nicht mal mehr Appetit auf meine
	Hühnersuppe. Was sollen wir bloß tun?

	- "Lt. Bröselbein, Geruchssequenzen aktivieren. Schiff an
	   Schiff!"

	- "Sie können sprechen,Sir!"

	- "Captain Nudelsuppe. Hören Sie sofort mit den Angriffen auf,
	   oder wir sind gezwungen unsere neue Waffe auf Sie anzuwenden,
	   ich kann Ihnen garantieren, es wird schrecklich. Lassen Sie
	   uns doch vernünftig miteinander reden...!"

	- "Captain Nudelsuppe an Capt. Apfelkuchen: Niemals, entweder
	   ihre Ölsardienen oder Tod für alle!"

	- "Captain, Verbindung wurde abgebrochen!"

	- "Sir, wir haben keine Wahl mehr, eröffnen Sie endlich mit
	   der neuen Waffe das Feuer, oder wir sind alle tot!"

	- "Na gut, Cmdr. Dödelbirne... Mr. Bröselbein, aktivieren Sie
	   die Waffen. Mr. Gräßlich, Ausweichmanöver vorbereiten um
	   der Druckwelle zu entgehen. Mein Gott... was tun wir hier?
	   Das ist ja Wahnsinn!!
	   Mr. Bröselbein. Feuern Sie 1000 Kilo Speck und 5000 Kilo
	   Zwiebeln ab. Feuer!!

	(Wusch - Wusch - Wusch... Wisch - Wisch - Wisch... Klatsch -
	 Klatsch - Klatsch!)

	- "Captain, volle Treffer... alle Schilde der Spaghetti sind
	   verschwunden. Schwere Treffer auf all ihren Decks...
	   empfange Nachricht!"

	- "Mr. Bröselbein, Geruchssequenzen aktivieren!"

	- "Aktiviert!"

	- "Cap... Captain... Apf... Apfelkuchen... Sie hinterhältiger
	   Apfelgriebsch. Sie haben meine Manschaft auf den Gewissen.
	   Wir ersticken hier in Zwiebeln und Speck... Sie... Sie M...
	   Mörder!"

	- "Sie haben uns keine andere Wahl gelassen. Verlassen Sie
	   auf der Stelle unseren Kirschsektor, oder wir entkernen
	   Sie... ich gebe Ihnen 1 Minute Zeit... Apfelkuchen Ende!"

	- "Captain, das Schiff dreht ab... es verläßt unseren Sektor!"

	- "Gut Cmdr. Dödelbirne! Mr. Gräßlich, Kurs setzen auf Sahne-
	   torte 12... Mr. Negerkuß, was macht der Waffelantrieb?"

	- "Sir, wieder OK, Sie haben 90% Energie zu Verfügung!"

	- "Hervorragend... Mr. Gräßlich! Waffel 9... Energie!"

	Birnenzeit:24434.0 Capt. Apfelkuchen:
	Wir haben unsere Mission erfüllt, der Angriff wurde abgewehrt.
	Und wieder einmal wurde bewiesen, daß der menschliche Intellekt
	den der anderen über ist.  Doch wir müssen auf der Hut sein.
	Viele Wesen im All wollen uns in die Suppe spucken... aber
	solange wir Speck und Zwiebeln haben, werden wir immer unbe-
	siegbar bleiben. Und vielleicht wird das auch eines Tages
	diese Spaghetti-Rasse begreifen... vielleicht!!!

						Ende... Ende?

		(c) By Hartmut Droste

@ENDNODE

@NODE ST0031 "Der Erlkönig - und seine Verarschungen"
@TOC Witze.guide/Inhalt

		DIE BALLADE VOM BITKÖNIG

	Wer tastet sich nachts die Finger klamm?
	Es ist der User mit seinem Programm.
	Er tastet geschwind, er tastet schnell,
	Im Osten wird der Himmel schon hell.

	Sein Haar ist ergraut, seine Hände sie zittern,
	Vom unablässigen Kernspeicherfüttern.
	Da - aus dem Programm tönt ein Geflüster:
	'Wer popelt an meinem Befehlsregister?'

	Bleib' ruhig, bleib' ruhig, meine liebe ZE,
	Ich tu' dir ganz bestimmt nicht weh.
	Mein Meister, mein Meister und siehst du nicht dort,
	Aus dem Akku schleicht sich ein Vorzeichen fort.

	Nur ruhig, nur ruhig, mein liebes Kind,
	Ich hole es wieder, ganz bestimmt.
	Mein Meister, mein Meister, hörst du das Grollen,
	Die wilden Bits durch den Speicher tollen?

	Nur ruhig, nur ruhig, das haben wir gleich,
	Die sperren wir in den Pufferbereich.
	Er tastet wild, er tastet besessen,
	Mist - er hat das  S i c h e r n  vergessen.

	Der Rechner schreit auf in höchster Qual,
	Da zuckt durch das Fenster ein Sonnenstrahl.
	Die Konsole schimmert im Morgenrot,
	Der Bitkönig lebt - das Programm ist tot.

@ENDNODE

@NODE ST0033 "Wenn Programmiersprachen Autos wären..."
@TOC Witze.guide/Inhalt

   BASIC:	Eine Ente - weder modern noch besonders schnell, aber
		für jeden erschwinglich. Und manch einer, der sich
		daran gewöhnt hat, will garnichts anderes mehr haben.

   GFA-BASIC:	Eine Ente, bei der die Rückbank einem Super-Turbo-
		Einspritz-Kompressor-Hochdruck-Hochleistungsmotor
		geopfert wurde.

   PASCAL:	Entwurf eines amerikanischen Straßenkreuzers, der nur
		durch ein Versehen in die Serienproduktion gelangte.

   TurboPASCAL:	Eine verbesserte Version des amerikanischen Straßen-
		kreuzers; neben dem praktischen Nutzen auch hervor-
		ragend zum Angeben geeignet. Paßt aber leider in keine
		Parklücke.

   Modula II:	Wie PASCAL, aber mit dreifachen Sicherheitsgurten,
		seitlichen Stoßstangen und separatem Gaspedal für jeden
		der fünf Gänge.

   ADA:		Ein als amerikanischer Straßenkreuzer getarnter Schüt-
		zenpanzerwagen.

   Forth:	Ein englischer Sportwagen aus den 60er Jahren mit dem
		Lenkrad auf der falschen Seite.

   C:		Ein offener Geländewagen. Kommt durch jeden Matsch und
		Schlamm, aber der Fahrer sieht hinterher auch entspre-
		chend aus.

   COBOL:	Ein dunkelroter Daimler mit getöntem Panzerglas und
		kostbaren Intarsien-Arbeiten im Fond. Kein Mensch fährt
		diesen Wagen selbst; man läßt sich fahren.

   Assembler:	Ein Go-Cart ohne Sicherheitsgurte und Überrollbügel.
		Gewinnt jedes Rennen, wenn er nicht vorher im Graben
		landet.

   FORTRAN:	Ein Schlitten aus den 50er Jahren mit riesigen Heck-
		flossen. Erntet beim TÜV stets mißtrauische Blicke,
		überholt aber noch manches neuere Gefährt.

   Logo:	Ein als Schildkröte getarntes Tretauto.

   Prolog:	Enthält statt eines Lenkrades eine Automatik, die alle
		Straßen solange absucht, bis das gewünschte Ziel er-
		reicht ist. Gegen Aufpreis sind Tank-Erweirungsmodule
		in Stufen zu 64, 128 und 256 Litern möglich.

   APL:		Ein Wagen in Kompaktbauweise. Alle Funktionen wie Gas-
		geben, Schalten oder Lenken werden durch Drehen, Drük-
		ken, Ziehen, Kneten oder Verkanten eines einzigen Be-
		dienungshebels ausgelöst.

   Pearl:	Ein Kraftfahrzeugverbund bei dem mehrere unbemannte
		KFZ's von einem zentralen Führerstand aus gesteuert
		werden.

   PL/1:	Ein handgefertigter Eigenbau, mit Einzelteilen von
		FORTRAN, COBOL, PASCAL und ADA. Näheres unter den je-
		weiligen Stichwörtern.

   Rexx:	Kein Auto ansich, mehr eine hyperkomplexe 64-Kanal-
		Fernbedienung, aber nicht nur für Autos, sondern auch
		für Schiffe, Flugzeuge, Hubschrauber, Fernlenkdrachen,
		Raumsonden, Satteliten usw...

@ENDNODE

@NODE ST0034 "Star Trek Lost Episodes"
@TOC Witze.guide/Inhalt

 <Picard> "Mr. LaForge, hatten Sie Erfolg mit Ihren Versuchen,
	   eine Schwachstelle des Borg zu finden? Und Mr. Data,
	   hatten Sie Erfolg, Zugriff auf dessen Kommandoablauf
	   zu bekommen?"

 <Geordi> "Ja, Captain. In der Tat, wir fanden eine Möglichkeit beim
	   durchsuchen der Archive über die Computertechnologie des
	   20 Jahrhunderts."

 <Geordi drückt eine Taste und es erscheint ein Logo auf derm Bildschirm>

 <Riker>  (schaut verduzt) "Was zur Hölle ist 'Microsoft'?"

 <Data>   (Antwortet) "Erlauben Sie mir, dies zu erklären. Wir werden
	   dieses Programm, genannt 'WinDOOF' in den Kommandoablauf
	   des Borg einschleusen. Wenn es sich erst einmal in dessen
	   Komandokernel installiert hat, wird es die Systemressourcen
	   unaufhaltbar verbrauchen.

 <Picard> "Aber der Borg hat die Fähigkeit sich anzupassen. Werden
	   die nicht ihre Systeme dazu bringen, die Speichergröße zu
	   erweitern?"

 <Data>   "Ja, Captain. Aber wenn 'WinDOOF' das entdeckt, erzeugt es
	   von sich selbst eine neue Version, genannt 'Upgrade'. Der
	   Verbrauch an Ressourcen steigt exponentiell mit jeder
	   Iteration. Der Borg wird nicht in der Lage sein, sich
	   schnell genug anzupassen. Schließlich wird 'WinDOOF' die
	   gesamte Rechenleistung benutzen und es wird keine mehr für
	   deren normale Operationen verbleiben."

 <Picard> "Exzellente Arbeit. Dies ist wesentlich besser als irgend-
	   ein unlösbares geometrisches Rätsel"

 <... 15 Minuten später...>

 <Data>   "Captain, wir haben 'WinDOOF' erfolgreich in den Kommando-
	   ablauf des Borg installiert. Wie erwartet hat es sofort 85%
	   aller vorhandenen Systemresourcen beschlagnahmt. Jedoch
	   haben wir noch keine Bestätigung für das erwartete 'Up-
	   grade'."

 <Geordi> "Unsere Scanner melden eine Erhöhung der Rechenleisung und
	   Speichergröße des Borg, es gibt jedoch noch immer keine An-
	   zeichen für das 'Upgrade' um die Erhöhung zu kompensieren."

 <Picard> "Data, überprüfen Sie nochmals die Geschichtsdatenbank und
	   untersuchen Sie, ob wir etwas übersehen haben."

 <Data>   "Sir, ich glaube, ich habe den Grund für die Nichtfunktion
	   des 'Upgrades'. Anscheinend hat der Borg diesen Teil un-
	   seres Plans umgangen, indem er es unterlassen hat, die
	   Registrierungskarte einzusenden."

 <Riker>  "Captain, wir haben keine Wahl, ich erwarte Ihre Erlaubnis,
	   den Notfluchtvorgang in Sequenz 3F einzuleiten..."

 <Geordi> (aufgeregt) "Warten Sie Captain! Die freie CPU Kapazität des
	   Borg ist plötzlich auf 0 % gefallen!"

 <Picard> "Data, was zeigen Ihre Scanner?"

 <Data>   (die Anzeigen studierend) "Offensichtlich hat der Borg das
	   WinDOOF-interne Programmmodul Namens 'Solitaire' entdeckt
	   und dieses hat alle Systemresourcen restlos verbraucht."

 <Picard> "Nun warten wir und wollen sehen, wie lange dieses 'Soli-
	   taire' ihre Funktionalität reduzieren kann."

 <... zwei Stunden vergehen...>

 <Riker>  "Geordi, wie ist der Status des Borg?"

 <Geordi> "Wie erwartet, der Borg versucht eine Neuentwicklung von
	   Systemressourcen um die erhöhte CPU- und Speicherbelegung
	   zu kompensieren. Aber jedes mal, wenn er erfolgreich seine
	   Systemresourcen erhöhen kann, übertrage ich weitere
	   'WinDOOF'-Module von etwas, das 'Microsoft Entertainment-
	   Pack' genannt wird."

 <Picard> "Wieviel Zeit wird uns das bringen?"
           
 <Data>   "Die momentanen Lösungszeiträume des Borg lassen eine Zeit-
	   spanne von mehr als 6 Stunden vorhersagen."

 <Geordi> "Captain, an anderes Objekt ist in unseren Sektor einge-
	   drungen."

 <Picard> "Identifizieren."

 <Data>   "Es zeit deutliche Ähnlichkeit mit dem 'Microsoft' Logo..."

 <Stimme> (über die Lautsprecher) "HIER SPRICHT ADMIRAL BILL GATES VOM
	   MIRCRSOFT FLAGGSCHIFF 'MONOPOL'. WIR HABEN DIE BESTÄTIGUNG,
	   DASS SICH IN DIESEM SEKTOR UNREGISTRIERTE SOFTWARE BEFIN-
	   DET. GEBEN SIE ALLE EXEMPLARE HERAUS UND WIR KÖNNEN UNAN-
	   NEHMLICHKEITEN VERHINDERN. SIE HABEN 10 SEKUNDEN ZEIT."

 <Data>   "Das fremde Schiff hat soeben die Vordertüren geöffnet und
	   tausende von menschenähnlichen Objekten herausgelassen."

 <Data>   "Richten Sie den ForwardViewer auf das fremde Schiff aus."

 <Riker>  "Mein Gott, Captain! Das sind Menschen, die geradewegs zum
	   Borgschiff fliegen - ohne Raumanzüge! Wie können Sie nur
	   die Torturen des Weltalls überleben?"

 <Data>   "Ich glaube nicht, das das Menschen sind, Sir. Wenn Sie
	   näher hinsehen, werden Sie sehen, das die Gestalten Uni-
	   formen und Schlagstöcke tragen."

 <Riker and Picard, zusammen - entsetzt> "Gesetzeshüter"

 <Geordi> "Das kann nicht sein. Alle Gesetzeshüter wurden 2017 beim
	   'Großen Erwachen' eingefangen und auf die Sonne verbannt."

 <Data>   "Stimmt, aber anscheinend haben einige überlebt."

 <Riker>  "Sie haben das Borgschiff umkreist und bedecken es mit
	   Formularen aller Art."

 <Riker>  "Sie zerschneiden das Borgschiff in Teile"

 <Picard> "Schalten Sie die Monitore aus, Data. Ich kann nicht hin-
	   sehen. Selbst der Borg verdient einen so grausamen Tod
	   nicht."

				** Ende **

@ENDNODE

@NODE ST0035 "Anleitung (IV)"
@TOC Witze.guide/Inhalt

   Noch ein paar Anleitungen, und diesmal ist sogar eine dabei, die
   ich selbst zusammen mit einem Telespiel bekommen habe. Ich hätte
   nie gedacht, daß mir sowas auch mal passieren kann...

	023A Einleitung füe Familiespiel mit Musik

   [Kleines Bildchen des Displays mit 4 Knöpfen drunter, von S1 bis
    S4 beschriftet]

	A. Uhrweise
	Setzung der Zeit
	Normale Zeit zu aufzeigen	    11:00
	S1 and S4 :			ALM 11:00
	(in Setzungweise zu setzen)
	S4 (Sekunde)			      :00
	(S2 Sekundenrückkehr zu Null)
	S1				    12:00
	(S2 Stunde zu setzen)
	S1				     0:00
	(S3 12/24 Stundenformat zu verändern)
	S1 (Minuten)			     0:01
	(S2 Minuten zu serzen)

	Alarm zu setzen
	Normale Zeit zu aufzeigen	    12:00
	S1 und S4			ALM 12:00
	(in Setzungweise zu setzen)
	S2 (Stunde zu setzen)		ALM  1:00
	S1 (Minuten)			ALM  1:01
	(S2 Minuten zu setzen)
	Stundenlautsymbol und tägliches Alarmsymbol zu setzen:
	1. Auf Anzeige de Normaler Zeit S1 drücken und um den
	   Stundenlauf und taglichen Alarm zu setzen nach folgende
	   Weise S2 drücken

   [kleines Bildchen des Displays]

	2 S1 entlassen um die Setzung zu vollenden

	B. SPIELWEISE
	Erklärung der Spielweise:
	- De Spieler muss "Spiel 1" oder "Spiel 2" in Spieldemon-
	  stration mit S2 auswählen, darauf das Symbol des Pieles
	  "G 1" oder "G 2" auf der AUfzeige erscheint
	- Um das Spiel zu beginnen drücken S3
	-  Um die Gegenstände zu nehmen für Rechnung drücken S1 S4

	Rechnung
	- Um 1 Punkt zu rechnen ein Gegenstand nehmen
	- In der niedrigen rechten Seite erscheint ein Symbol einer
	  Prämie und bleibt hier 2 Sekunden wenn Sie S1 drücken das
	  den "Catcher" leitet und sie nehmen rechnen Sie 5 Punkten
	- Alle Fehlschüsse werden widerrufen auf jede 2000 oder 500
	  Punkten
	- Nach 3 Fehlschüsse endet das Spiel
	- Die hochste Rechnung ist 999

	C. VERANDERUNG DER BATTERIE
	Den Deckel der Batterie beseitigen und die alte Batterie mit
	einer neuen Batterie SR1130, SR44 oder gleichweriger ersetzen

   Das beste an der Sache war, daß das Spiel, abgesehen von den beiden
   üblichen Rechts- und Links-Knöpfen nur DREI andere Knöpfe hatte...


   Bedienungsanleitung für ein Kofferkombinationsschloß:

	Die Handkoffer Schlüssel Nummer errichten wir '0-0-0'. Sie
	können diese Nummer bleiben. Oder errichten Ihre eigene
	geheime Nummer. Die Weisen wie folgen.

	Erst	Wenden die Nummer zum öffnenden Platz

	Zweite	Knopf nach hinten drücken und die zu festlegende rote
		karte herausholen, dann stellen die knopf nach Rich-
		tung der Nummerwendung fest. (Sieht B. Teil)

	Dritt	Wenden die Wendung zur rechtige Nummer, die Sie mögen
		z.B. Telefon, Geburtstag oder Aderesse usw. und
		schreiben die Nummer auf die Notiz, um nicht zu ver-
		gessen.

	Vierte	Drücken die Knopf zum ersten Platz, dann stehen die
		klar Karte zurück, hat die Nummer dann errichtet.

	Wenn Sie die Nummer verändern wollen, errichten Sie wie die
	oben Weisen.

	Bemerkung

	(1) Wenn Sie es vermeiden wollen, dass jemande die Nummer
	    verstohlen blicken, nachdem Sie den Koffer öffnen, ver-
	    wirren die Wendung, dann drücken die Knopf, und ist es im
	    Schloß.

	(2) Die Wirkung der klaren Karte ist, es zu vermaiden, jemande
	    die Nummer verwirrend machen. Die Karte kann gehalten
	    werden oder nicht.


   Übersetzung der Anleitung eines Monitors:

	DIE INSTALLATIONSMETHODE DER NEIGUNG UND DREBRINGSTANDTEILEN

	Ihr Farbe-Monitor hat besondere Neigung und Drehring-stand-
	teilen.

	Sie können so instalieren, sich ihrem sichtbaren Winkel snzu-
	passen.

	Diose Neigung und Drehring-Standteilen wurden Besonders für
	diesen Monnnnnnnnngedacht und sind ein Einziges, das sie ver-
	wenden sollen.

	Verwenden sie irgendandere standteilen, dann koennen sich
	Unbestaendigkkkkkkkkkkkkund schaden ergeben.

	Um die Neigung und Drehring-Standteilen auf den Monitor zu
	instalieren, bitte folgen sie diesen Schritten:

	1. Stellen sie die Obenseite des Monitors nach unten und Bild-
	schirmseite nach links.

	2. Montieren sie die standteilen und den Monitor suf den P. C.

	   2-1. Stellen sie so das Stand-Oberteil auf den P. C dass
		sich die bossierte "FRONT" Schrift auf dem Stand-Obcr-
		teil "A" zu der vorderseite des P. C zu orientieren

	   2-2. Stellen sie den Stand-Stoepsel "B" auf den Stand-
		Oberteil

	   2-3. Binden sie den Stand-Stoepsel und P. C  durch Stand-
		Oberseite mit grosser Schraube "C" fest.

	3. Drehen sie die P. C-Montage um und setzen sie die vier
	   Stand-Anhänger in die vier schlitzen auf dem boden des
	   Kabinetts und schieben die P. C-Montage nach unten, Bis
	   das schnappen der Kabinett-Rueckseite die P. C-Montage
	   feststellen.

	4. Binden sie die P. C-Montage an den Winkelstuetze-Stand "E"
	   mit kleiner Schraube "D" fest.

	ANBEI: EINE ZEICHNUNG UeBER DIE OBEN GENANNTE FACHWORTE.


   Übersetzung der Anleitung eines Einhandtelefons:

	Das Gedachtnistelephon

	INSTALLIERUNG
	-------------

	1) fuer USA/kanadische Benutzer

	A) Mit regelmaessigem Steckkontakt

	   Schalten Sie einfach den Stecker in den Steckkontakt ein,
	   wie in der Zeichnung gezeigt ist.

	   < >  <<---------- FCC regelmaessiger Stecker
	    |
	   FCC regelmaessiger Steckkontakt

	B) Mit Regelmaessigem-zu-4-spitzen Zwischenstecker

	   Schalten Sie den Stecker in den Zwischenstecker und den
	   Zwischenstecker in den Steckkontakt ein.

	   +--------+
	   |  . .   |  --+++++ FCC Regelmaessiger Stecker
	   |  . .   |  --+++++
	   +--------+ 4-spitzen FCC Zwischenstecker

	2) fuer Benutzer draussen USA und KANADA

	   Verbinden Sie den roten und gruenen Leitungsdraht in die
	   Nummernanschlussdose.

	              +---------+
	    ----------|         |---------- Nummernanschluss Leitung
	              +---------+
	                    Nummernanschlussdose

	Die Elemente des Telefons

	   1. Der Hoerer
	   2. Das Zahlentastatur
	   3. Der Wiederwaehler
	   4. Der Lagerer
	   5. Der EIN/AUS Schalter des Klingers
	   6. Der Freigestellte Singweisengriffer
	   7. Der Wiederstzenkopf
	   8. Das Mik (rofon)
	   9. Der Klinger

	DIE WIRKUNG

	Der Singweisengriffer (Freigestellte)

	Stellen Sie die Gerte des Singweisengriffers zur EIN-Stellung.
	Eine nette Singweise wirde verbeugen den andern Teil auf denn
	Telephon von hoerender Threr geheimer Unterredung. Stellen Sie
	die Gerte des Singweisengriffers zurueck zur AUS-Stellung zu
	nehmen die Telephonunterredung zurueck.

	Der Klingereinheit

	Stellen Sie den EIN/AUS Schalter des Klingers zur EIN-Stellung
	wenn wollen Sie nicht zu werden gestoert werden von eintre-
	tender ednruefe.

	Normales Waehlen

	1. Nehmen Sie den Griff auf und hoeren Sie fuer den Wahlschei-
	   benton zu.
	2. Setzen Sie die Tasten in die Telephonnummer. Dieses Telephon
	   wird stehen die ziffern an so schnell wie koennen Sie die
	   Tasten setzen und waehlen Sie sie.

	Das Wiederwaehlen

	1. Nehmen Sie den Griff auf und hoeren Sie fuer den Waehl-
	   scheibenton zu.
	2. Druecken Sie die Taste von # zweimal. Die vorig-eintretende
	   Nummer wird wiedergewaehlt werden selbsttaetig.

	Der hemmendes Wiederwaehlen

	Die Wiederwaehlenwirksamkeit wird gehemmt koennen von druek-
	kende Taste von * zweimal nach normales gevervollstaendiges
	Waehlen. darum die andere Leute koennen treten ein nicht die
	Nummer, dafa Sie waehlten vorig.

	Entlassend Draht

	Haengen Sie und waehlen Sie andere Nummer und druecken Sie das
	Wiedersetzenkopf fuer 2 Sekunden wenigstens denn entlassem
	Sie sie.

	Das Lagerungswaehlen

	Dieses Telephon kann 18-Zifferntelephonnummern legern zwanzig
	in zwanzig Gedachtnisplaetze naemlich 00,01,...18,19.

	Das Einlagern

	1. Nehmen Sie den Griff auf und lassen Sie das Wiedersetzen-
	kopf niedergedrueckt.
	2. Druecken Sie die Taste von * einmal.
	3. Treten Sie die Nummer ein und lassen Sie sie eingelagert.
	4. Druecken Sie die Taste von * einmal wieder.
	5. Druecken Sie eine Gedaechtnisplatznummer.

	Das Gedaechtniswaehlen

	1. Nehmen Sie den Griff auf und hoeren Sie fuer den Waehl-
	   scheibenton zu.
	2. Druecken Sie die Taste von # einmal.
	3. Druecken Sie die Gedaechtnisplatznummer. Die Nummer dafa
	   lagerten Sie in jene besondere Platz, wird gewaehlt werden
	   selbsttaetog.

	Die Bemerkung

	Brauchen Sie nie abschabende, starke Reinigungsmittel oder
	Loesungsmittel zu reinigen irgend ein Teil das Telephons oder
	Drahts zu meiden den Schaden, Brauchen Sie ein dumpfes (nicht
	nasses) Tuch und sanftes abschaberloses Reinigungsmittel.
	Waehrend aufaerhalb dem Brauen, setzen Sie Thr Telephon auf
	einer platten Oberflaeche oder setzen Sie es zurueck in den
	Halter.

	DRUCKEN IN HONG KONG

@ENDNODE

@NODE ST0036 "Anrufbeantwortersprüche"
@TOC Witze.guide/Inhalt

	*Klick* Hier ist der automatische Beichstuhl von Pater X. Der
	Herr wird Dir vergeben. Sprich alle deine Sünden nach dem
	Piepton auf Band und bete drei Vaterunser und drei Ave Maria,
	wenn Du aufgelegt hast. Amen. *Piep*

	*Klick* X. [Pause] Ah, hallo! Schön, daß Du Dich auch mal
	wieder meldest! Was gibt's denn? [Pause] Ja? [Pause] Aha?
	Und? [Pause] Ahh, ja? [Pause] Ach so. Ähh, ist ja alles schön
	und gut, die Sache hat nur einen Haken: Ich bin gar nicht zu
	Hause. Du redest gerade mit einem Anrufdings, na Du weißt schon,
	so'n Anrufbeantworter. Also jetzt kommt gleich so'n Piepton,
	und dann erzählst Du mir alles nochmal. Tschüß! *Piep*

	*Klick*  Hier Erzbistum Paderborn, kirchliche Zentrale für
	Sündenerlaß. Unsere Beichtstühle sind zur Zeit alle belegt,
	bitte beichten Sie nach dem Pfeifton. *Piep*

	*Klick*  Hier ist das Zentrum des Wissens und der Macht. Es
	gibt nichts was wir nicht schon wüßten. Wenn Sie trotzdem etwas
	sagen wollen, dann hinterlassen Sie Ihre Nichttigkeiten nach
	dem Pfeifton *Piep*

	*Klick* Hallo, hier ist der Anschluss X. Bitte sprechen Sie
	*vor* dem Signalton! [2 bis 3 Sekunden Pause] *Piep*

	*Klick* "Guten Tag, Ramses Pyramidenverleih! Unser Büro ist
	zur Zeit leider nicht besetzt, Sie können Ihren Pyramidenwunsch
	jedoch auf Band sprechen, bitte warten Sie dazu den Signalton
	ab!" *Piep*

	*Klick* Guten Tag, hier spricht X. Ich bin gerade nicht da,
	weil ich nicht zu hause bin. Bitte hinterlassen sie... *Piep*

	*Klick* Städtisches Krematorium. Da wir gerade ein paar Öfen
	anheizen, kann niemand zum Telefon kommen. Bitte hinterlassen
	sie...

	*Klick* Katholische Männerbadeanstalt. Leider sind für heute
	keine Termine mehr frei. Bitte hinterlassen sie... *Piep*

	*Klick* Guten Tag, hier sind die Rathaustoiletten, 3. Kabine.
	Ich bin gerade auf einer etwas länger dauernden Sitzung be-
	schäftigt und kann daher nicht zum Telefon kommen. Bitte hin-
	terlassen sie keinere größeren Geschäfte nach dem Signalge-
	räusch. *Pfrrrzzzt*

	*Klick* Hallo. Here is your international operator. The number
	you dialed in Saudia Arabia is no longer active. Please ask
	your local consultant. *Piep*

	*Klick* Hier spricht Darth Vader. Bitte hinterlassen Sie Ihre
	Nachricht nach dem metallischen Keuchton. *Chchchch*

	*Klick* (gelangweilt) Hallo... hier ist Marvin. Richtig, der
	paranoide Androide. Ich bin zehn mal älter als das Universum,
	meine Datenbänkte wissen mehr, als Du Erdling Dir in 1000
	Jahren ausdenken könntest. Ich bin sicher, daß mich das, was
	Du mir erzählen willst, nicht interessiert, weil ich es sicher
	schon weiß. Wenn Du mich unbedingt langweilen willst, dann
	sprich nach dem Piepton. *Piep*

	*Klick* Ich bin nur ein einfacher Anrufbeantworter, Sie haben
	mich sehr glücklich gemacht, meine Nummer gewählt zu haben.
	Es war mir eine große Freude, meine Schaltkreise für Sie
	aktiviert zu haben. *Piep*

	*Klick* Hallo, hier ist der Anrufbeantworter von X. Ich bin
	mit Sicherheit zu Hause, aber es kann gut sein, daß ich den
	Anrufbeantworter unter einem Stapel Papier vergraben habe, so
	daß ich ihn ganz bestimmt nicht finden werde. Sie haben also
	zwei Möglichkeiten: Warten sie ein paar Minuten, damit sie
	ganz sicher sein können, daß ich entweder nicht da bin oder
	die Suche aufgegeben habe, oder sprechen sie direkt nach dem
	Piepton. *Piep*

	*Klick* Norddeutscher Unterhosenverleih, X am Apparat, Guten
	Tag...

	(Im Hintergrund 'Spiel mir das Lied von Tod', Text mit mexi-
	kanischem Akzent, also vor allem ein stark gerolltes 'r')
	*Klick* Sei gegrüßt, Fremder. Wir treffen uns morgen früh bei
	Sonnenaufgang an der alten Eiche. Solltest Du noch ein letztes
	Wort zu sagen haben, so tu dies nach dem langen Geierschrei!
	*Krääächz*

	(Im Hintergrund die Titelmusik von "Star Wars")
	*Klick* Hallo, hier spricht Obi Wan Bongartz. Leider kann ich
	nicht persönlich in Kommunikation treten, da ich einen Date
	mit Darth Vader habe. Sie können jedoch gerne eine Nachricht
	an R2D2 hinterlassen. *Piep*

	*Klick* Wenn Sie Anrufbeantworter hassen,legen Sie bitte so-
	fort auf und schreiben einen Brief. Andernfalls...

	*Klick* (Laut und zornig) Du Spinner,stinkendes Fischgesicht,
	Doofmannsgehilfe...
	(Mit normaler Stimme): Diese und noch viele andere schöne Be-
	leidigungen fand ich schon auf meinem Band. Bitte ergänzen
	Sie diese durch Ihre Lieblingsgrobheiten *Piep*

	*Klick* Sie haben das Recht, zu schweigen. Alles, was Sie sa-
	gen, kann und wird gegen Sie verwendet werden. Wenn sie sich
	keinen eigenen Anrufbeantworter leisten können, müssen sie
	sich einen kaufen. Wenn Sie jetzt doch was sagen wollen, tun
	Sie es jetzt, oder schweigen sie für immer... *Piep*

	(schwebende Stimme) *Klick* Hier ist der automatische Guru der
	Familie X. Meine Jünger sitzen gerade in der Ecke und medi-
	tieren. Wenn Du mit uns in spirituellen Kontakt treten willst,
	so verschmelze Dein Karma mit unserem mittels elektrischer
	Schwingungen. Erkenne Dich selbst, aber erst mal den transzen-
	denten Kontaktton. *Hare Krishna!*

	*Klick* Learning English Lesson 1 - speak after me. *Beep*

	*Klick* "Hier ist der automatische [und so weiter] Bitte spre-
	chen sie nach dem Signalton. *Piep* [Fake; Pause] Wenn es
	wichtig war, dann können sie es sicher nach dem echten Ton
	wiederholen! *Piep*

@ENDNODE

@NODE EndStor "Stories - Index"
@TOC Witze.guide/Inhalt
@NEXT EndStor

   @{b}Version 1.00:@{ub}

	@{" Atari-Witze                " link ST0008}	@{" Begriffe aus der Politik   " link ST0004}
	@{" Coladosen richtig öffnen   " link ST0005}	@{" Computerlexikon            " link ST0001}
	@{" Fanta (V)Fier...           " link ST0014}	@{" Radio FFN                  " link ST0003}
	@{" WinDOOF                    " link ST0006}	@{" Zitate                     " link ST0007}

   @{b}Version 1.01:@{ub}

	@{" Anleitung (I)              " link ST0020}	@{" DFÜ im Jahre 2011          " link ST0021}
	@{" Ende eines PC-Users        " link ST0015}	@{" Dornröschen                " link ST0016}
	@{" Neulich im Funkverkehr     " link ST0022}	@{" Schülergebet               " link ST0017}
	@{" Tagebuch eines Studenten   " link ST0018}	@{" Tagebuch eines Trinkers    " link ST0019}

   @{b}Version 1.02:@{ub}

	@{" Expeditionen ins Bierreich " link ST0024}	@{" Stilblüten aus Aufsätzen   " link ST0025}

   @{b}Version 1.03:@{ub}

	@{" Abkürzungen                " link ST0026}	@{" Anleitung (II)             " link ST0023}
	@{" Anleitung (III)            " link ST0032}	@{" Mensa-Umfrage              " link ST0027}

   @{b}Version 1.1:@{ub}

	@{" Anleitung (IV)             " link ST0035}	@{" Anrufbeantwortersprüche    " link ST0036}
	@{" Der Erlkönig               " link ST0031}	@{" Die Geschichte der DFÜ     " link ST0029}
	@{" Krötenlecken               " link ST0028}	@{" Namen, die keiner haben... " link ST0002}
	@{" Programmiersprachen        " link ST0033}	@{" Raumschiff Pfannekuchen    " link ST0030}
	@{" Star Trek Lost Episodes    " link ST0034}

@ENDNODE
