@database READ.ME
@author "Michael Simons"
@(c) "Copyright © 1994-95 CONSULTRON"

@node Main "CrossMAC"
                              CrossMAC
                    $VER: READ.ME 1.05 (13/11/95)
                           CIN: U0RO-KNFE

This  file  describes  any changes, highlights and special features
for this version and revision of CrossMAC.

PLEASE READ THIS FILE FOR IMPORTANT NEWS!

NOTE:  Please  log  down  the  Customer Identification Number (CIN)
listed  in  the  heading  above.  It's comprised of the numbers and
letters  listed  following the word `CIN:'. Place it in your manual
and  on  the  disk. It MUST be used to receive technical support or
to register.

********** TABLE OF CONTENTS *******************************
@{"Running CrossMAC from the Product Disk" link "Running CrossMAC from the Product Disk"}
@{"Installing CrossMAC" link "Installing CrossMAC"}
@{"Manual Corrections" link "Manual Corrections"}
@{"My screen blinks when reading or writing Mac 800K disks. What's happening?" link "Screen Blinks"}
@{"Renaming Files" link "Renaming Files"}
@{"Configuring a Mac Hard Drive" link "Configuring a Mac Hard Drive"}
@{"Configuring a CD-ROM Drive" link "Configuring_a_CD-ROM_Drive"}
@{"Formats Supported" link "Formats_Supported"}
@{"MacBinary Support" link "MacBinary Support"}
@{"Data Fork Only Mode" link "Data Fork Only Mode"}
@{"Setting the Default FileType" link "Setting the Default FileType"}
@{"Who Owns This Disk Anyway?" link "Who Owns This Disk Anyway?"}
@{"Troubleshooting" link "Troubleshooting"}
@{"Electronic Registration" link "Electronic Registration"}
@{"Technical Support" link "Technical Support"}
@{"Electronic Bulletin Board Service" link "Electronic Bulletin Board Service"}
@{"Copyrights, Disclaimers and Trademarks" link "Copyrights, Disclaimers and Trademarks"}
@ENDNODE

@NODE "Running CrossMAC from the Product Disk"
Double-Clicking  on  the  appropriate  icon can start CrossMAC from
the  product  disk  (particularly  if  you  are running on a floppy
based system).

To  start:  double-click  on  the "MAC0" icon. Your internal floppy
drive  will  now  be  configured  as  a  Mac  drive  with  the name
"MAC0:".  You  can  now  read  and  write the different Mac formats
which  your  System hardware will allow. For the different types of
formats  supported  and  the hardware requirements for some formats
please see @{"Formats Supported" link "Formats_Supported"}.

To  format  a  Mac  disk,  double-click  on  the @{b}Format@{ub} icon in the
@{i}System@{ui}  drawer.  Choose  the  device to format from the device list
and answer any of the questions and options given.

@ENDNODE


@NODE "Installing CrossMAC"
Simply  clicking  the  Install  icon  from Workbench will begin the
installation  of  the CrossMAC FileSystem. If you are installing to
a  hard  drive,  some  of  the  files must be copied to your System
partition.  Only  FileSystem  related  files  are  copied  to  your
System  partition,  you  may select the destination of the CrossMAC
utilities,   if   you   are   installing  them.  The  install  uses
Commodore's   Installer,   so   if   you   have   installed   other
applications  that  use  the  Installer,  the environment should be
familiar to you.

Once  installed,  you  can  use  most  features  immediately. A few
features  such  as  Mac  hard  disk  access  may require additional
operations  be  performed  before  use. For further information see
@{"Configuring a Mac Hard Drive" link "Configuring a Mac Hard Drive"}

@ENDNODE

@NODE "Manual Corrections"

@{b}Finder_Manager is now File_Type_Manager@{ub}

References  to  @{i}Finder_Manager@{ui}  in  the  manual  should be replaced
with  @{i}File_Type_Manager@{ui}.  We  realized  after  the  manual  went to
print   that   the   term  "Finder"  may  be  a  trademarked  name.
Consequently  we  have  changed  the  name  of the program to avoid
possible  legal  hassles.  Please remember this change of name when
reading the manual.

@{b}Our Email address has been modified@{ub}

Our primary email address is consultron@consultron.plymouth.mi.us

Our secondary address is cstron@m-net.arbornet.org
@ENDNODE

@NODE "Screen Blinks"
@{b}"My  screen  blinks  when reading or writing Mac 800K disks. What's
happening?"@{ub}

If  you  get  this phenomemon, don't panic. It's not fatal. Only if
you  have  EVERY  element  of  the following setup might the screen
blinks occur:

    · Amax II or AMax IV card
    · Reading/writing 800K Mac low density disks

Due  to  the design of the AMax cards, we need to temporarily
shut  down  the screen DMA hardware to reduce the chance of missing
data  from  the floppy controller onboard the AMax card. This means
screen  updates  will  be  shut down temporarily. We also recommend
that  you  you  don't  perform  any  high-speed  serial port access
during  those  times  either.  This  only applies when accessing an
800K Mac disk.
@ENDNODE

@NODE "Renaming Files"
Just  a  short  note  about  renaming  files  under this version of
CrossMAC:  Although  the Amiga treats the data and resource `forks'
as  separate  files  the  Mac  likes  to  keep  them together. As a
compromise, we've tried to do both.

If   you   rename  either  the  data  or  resource  file,  it  will
automatically rename the other.
@ENDNODE



@NODE "Configuring a Mac Hard Drive"
CrossMAC can support Mac formatted hard drives.

To   configure  a  Mac  Hard  Disk,  use  our  @{i}Install@{ui}  program  or
double-click  the  ConfigDisk.CrossMAC  icon  which  resides on the
product  disk  (if  you're trying to configure a CD-ROM, please see
@{"Configuring a CD-ROM Drive" link "Configuring_a_CD-ROM_Drive"}).    Once    the   program   starts,   a
configuration of one of three types of hard disks is available.

@{b}One:@{ub}  A  'true'  Mac  hard disk configured as the entire disk. This
type   is   useful  to  transfer  data  between  the  Amiga  and  a
stand-alone  Mac.  Examples  of  this  type of disk are SyQuest and
Bernoulli.  We  do  HIGHLY recommend that this type of hard disk be
formatted   on  the  Mac  first  then  brought  to  the  Amiga  for
configuring.
@{"Configure a 'true' Mac hard disk NOW!" SYSTEM "c/Configdisk Mac Disk POSTFIX=0 PREFIX=MHD BUFFERS=40"}

@{b}Two:@{ub}  An  'image'  of  an  Mac  hard disk within an Amiga hard disk
partition.  An  example  of  this  type  of disk is an AMax/EMPLANT
partition.
@{"Configure an 'image' of an Mac hard disk NOW!" SYSTEM "c/Configdisk Mac PARTITION POSTFIX=0 PREFIX=MHD BUFFERS=40"}

@{b}Three:@{ub}  An  'image'  of  an Mac hard disk within a file. An example
of this type of disk is an ShapeShifter or EMPLANT diskfile.
@{"Configure a Mac 'diskfile' NOW!" SYSTEM "c/Configdisk Mac FILE POSTFIX=0 PREFIX=MHD BUFFERS=40"}

@ENDNODE

@NODE "Configuring_a_CD-ROM_Drive"
To  configure  a  CD-ROM  Drive  to  read  Mac HFS CD-ROMS, use our
@{i}Install@{ui}   program  or  double-click  the  ConfigDisk.CrossMAC_CDROM
icon  which  resides  on  the  product disk. The controller must be
able to support SCSI direct commands with block sizes of 2048.
@{"Configure a Mac CD-ROM drive NOW!" SYSTEM "c/Configdisk Mac Disk POSTFIX=0 PREFIX=MCD BUFFERS=60 SCSI_DIRECT BLOCKSIZE=2048"}

@ENDNODE


@NODE "Formats_Supported"
CrossMAC  supports  a  variety  of  different  floppy disk formats.
Although  CrossMAC  can  read the standard Mac floppy formats given
the  proper  Amiga hardware (see below). CrossMAC can also read and
write  the  formats  created  by  some Mac emulators. The quasi-Mac
formats  supported  are  the  AMax  II  and Emplant disk format for
emulation of 800K floppies.

These  Mac  formats  require certain Amiga hardware before they can
work with CrossMAC.

    · Mac  800K  --  AMax  II cartridge with Mac 800K floppy drive,
      AMax II Plus card or AMax IV card.
    · Mac 1440K or 1.44M -- an Amiga high density floppy drive
    · AMax   or   Emplant   800K  -  standard  Amiga  drives  using
      low-density disks.
    · Mac 800K -- AMIA cartridge with Mac 800K floppy drive.

CrossMAC  can  also  be used on to read Mac hierarchical file
system  (HFS)  CD-ROMS.  Please  see @{"Configuring a CD-ROM Drive" link "Configuring_a_CD-ROM_Drive"} for
setting up a proper mountfile to use HFS CD-ROMS.

@ENDNODE

@NODE "MacBinary Support"
CrossMAC support MacBinary files in two ways.

First,  if  you  read  a  file  from a CrossMAC device and append a
`.bin'  to  the  end  of  the name, we'll automatically combine the
data  and  resource  forks into a MacBinary file (type II). Also if
you  move  a  MacBinary  file  to  a CrossMAC device and it has the
`.bin'  appended  to the end, we'll automatically separate the data
and resource forks.

Secondly,  we  support  the  MacBinary  explicitly  by  setting the
`MacBin  Only'  option  in the CrossMAC commodity for the specified
device. The default setting is `Both Forks'.
@ENDNODE

@NODE "Data Fork Only Mode"
CrossMAC  can  be  configured  to  display  data  forks  only. This
option  will  filter out the resource forks from directory listings
and  Workbench  windows. This is particularly useful to most people
since  the  data  in  the resource fork is rarely used. To activate
this  feature,  select  the  `Data  Fork'  option  in  the CrossMAC
commodity  for  the  specified device. The default setting is `Both
Forks'.

Although  the  resource  forks  do not appear in this mode they can
still  be  accessed.  Adding  the `.rs' to the end of the data name
will access the resource fork if it is present on the disk.
@ENDNODE

@NODE "Setting the Default FileType"
You,  our  customers,  have  described  a  need  to save files to a
CrossMAC   disk  with  filetypes  different  than  the  default  of
"TEXT".  In  addition,  some  programs  generating the files do not
allow  the  file  extension  to be user selectable (such as Toaster
framestores).  We  hopefully  addressed  these problems by allowing
the  user  to  set  the  default  filetype  (and  creator)  in  the
File_Type_Manager.

The  File_Type_Manager  now has two string fields where the default
filetype  and  creator can be user selectable. These values will be
used  if  a  file  is  written  to  the  CrossMAC disk and the file
extension  does  not  match  any  listed  in the filetype database.
Note:   The  default  filetype  and  creator  are  global  for  all
CrossMAC devices.
@ENDNODE

@NODE "Who Owns This Disk Anyway?"
Don't  worry,  this is not a rehash of the license agreement you've
already  read  on  the  front  of  the disk envelope. This concerns
people  who  are using MAC emulator products on the Amiga. Examples
of emulators are AMAX, EMPLANT or ShapeShifter.

If   you've   configured   a   Mac   disk   for  CrossMAC  that  is
simultaneously  configured  for  one  of the emulators, you may run
into a problem.

The  problem:  When more than one file system tries to write to the
same   physical   disk   volume/partition,  the  disk  may  end  up
corrupted.  Both  CrossMAC  and  the  emulators running Mac OSs are
file systems.

Let  me  draw  a  simple  analogy.  Let's say there is one checking
account  and  you have a set of checks and a friend has another set
of  checks  to the same account. If the both of you never cooperate
to  balance  the  account when checks are written, the account will
eventually be overdrawn.

Similarly,  file  systems  tend to cache small portions of the disk
so  as  to  speed  disk  access.  Let's  suppose  CrossMAC  and the
emulator  (running  Mac  OS)  just  happen  to  cache the same disk
information.  If  CrossMAC  modifies the information it has cached,
the  Mac  (the other file system) will not know the information was
changed.  Now,  CrossMAC  creates  a  new file and uses some blocks
not  previously  used. If the Mac wishes to create a file, it might
reuse  those  blocks  allocated  by CrossMAC. When this happens the
disk  is  most  likely  corrupted since neither file system has the
correct   information.  Both  have  also  modified  the  disk  with
out-of-sync information.

The  solution:  If  both  file systems would cooperate when writing
new  information  to  the  disk,  we'd have our problem solved. For
reasons  which  are  complicated,  that  solution  is not likely to
happen.

You  can  have  as  many  file  systems read the disk as long as no
writing  occurs.  However, if you must write, there are things that
can be done to significantly minimize disk corruption.
    · Create  two  partitions. One for CrossMAC to write to and the
      Mac  to  read  from and the the other for the Mac to write to
      and CrossMAC to read from.
    · Manually  prevent  multiple  file systems from simultaneously
      writing to the disk.
    · After  writing  the  disk  with  the Mac, first drop the disk
      into  the  Mac  trashcan. Next perform a @{b}DiskChg@{ub} (diskchange)
      for  the  CrossMAC  device.  This  action  will flush the Mac
      side and reread the disk from the Amiga side.
    · After  writing  the  disk with CrossMAC, pull the disk out of
      the  Mac  trashcan.  This action will reread the disk for the
      Mac side.

@ENDNODE

@NODE "Troubleshooting"
Here  are  some  ideas  to  help  you should you have trouble using
CrossMAC.

@{b}General@{ub}

    · Ensure  you  have  configured  the drive in which you wish to
      use   the  Mac  disk  by  Mount  ing  it.  The  device  names
      correspond  to  the  device  names  given  by  Commodore. For
      example,  MAC0:  is the Mac device name corresponding to DF0:
      and MAC1: is the Mac device name corresponding to DF1:.
    · Avoid file names longer than 25 characters.
    · Make  sure  you  do  not mix disk types and format types. For
      example,  do  not  do  a low density format on a high density
      disk  or  visa  versa.  Do  not  try  to  read a high density
      formatted disk in a low density drive.
    · Ensure  the  file  formats  you  want to use between both the
      Amiga  program  and  the  Mac  program  are  compatible.  For
      example,  an  Amiga Final Copy file is not readable by an Mac
      WordPerfect wordprocessor.
    · Should  you  exhibit  read  or  write errors with no specific
      pattern,  try  cleaning  the  floppy  drive heads of both the
      Amiga and Mac computers.
    · If  you  are  running  from  a copy of the product disk and a
      utility  appears  not  to run or run correctly, make sure the
      disk name is called ``CrossMAC''
    · The  easiest  way  to  check an Mac disk from the Amiga is to
      run   the   DiskChk   program  included  with  CrossMAC.  The
      following is a list of most of the CrossMAC error codes.
    · Some  directory  utilities  can  not  handle filenames longer
      than  30  characters.  The  directory utility may display the
      file  but  any  operation which tries to access the file will
      fail.  To  fix  the  problem rename the file within Workbench
      and reduce the number of filename characters.
    · Workbench  will  not  properly  display  icons  for Mac files
      with  filename  lengths greater than 25 characters. The icons
      displayed  are  the  Workbench  default  icon  instead of the
      CrossMAC generated icons.
    · Finder  information  is transferred by using the comment. For
      CLI,  the  COM  or  CLONE switch for the copy command must be
      used.  For  Dir Utility programs make sure that they copy the
      comment.
    · The  easiest  way  to  check an Mac disk from the Amiga is to
      run   the   DiskChk   program  included  with  CrossMAC.  The
      following is a list of most of the DiskChk error codes.


@{b}Error Messages@{ub}

@{u}No. Name Description@{uu}

-1  IOERR_OPENFAIL          device/unit failed to open
-2  IOERR_ABORTED           request aborted
-3  IOERR_NOCMD             command not supported
-4  IOERR_BADLENGTH         not a valid data length
20  TDERR_NotSpecified      general catch all error code
21  TDERR_NoSecHdr          couldn't find any sectors on track
22  TDERR_BadSecPreamble    bad sector header
23  TDERR_BadSecID          bad sector header
24  TDERR_BadHdrSum         sector header had incorrect CRC
25  TDERR_BadSecSum         data had incorrect CRC
26  TDERR_TooFewSecs        couldn't find enough sectors
27  TDERR_BadSecHdr bad     sector header
28  TDERR_WriteProt         can't write to a protected disk
29  TDERR_DiskChanged       no disk in the drive
30  TDERR_SeekError         couldn't find track 0
31  TDERR_NoMem             ran out of memory
32  TDERR_BadUnitNum        asked for a unit > 3
33  TDERR_BadDriveType      not a recognized drive
34  TDERR_DriveInUse        someone else allocated the drive
35  TDERR_PostReset         user hit reset; awaiting doom
36  MDERR_OutofTracks       out of physical tracks
37  MDERR_InvParam          invalid parameter (MD_SETPARMS)
38  MDERR_IndexNotSync      index signal not available
39  MDERR_WrongTrack        drive head on wrong physical track

@{b}Possible Problems and Solutions@{ub}

@{i}DF0:????@{ui}
     This  is  OK.  The task that handles the AmigaDOS device called
     DF0:  can't  recognize  foreign  disk  formats  such  as the Mac
     formatted disks.

@{i}Disk Ejected Too Soon.@{ui}
     Disk  removed  before  all  information  was written to it. Put
     the  disk  back  into  the drive and Retry might recover without
     corruption.  We  recommend  you wait at least 3 seconds from the
     last disk access before removing the disk.

@{i}Disk Full.@{ui}
     Exceeded  the  capacity  of the system disk. Remove unnecessary
     files from the disk.

@{i}Error=21.@{ui}
     Could  not  find  any  sectors on the specified track. Probably
     not  an  Mac  standard  density  formatted disk readable by your
     drive.

@{i}Error=22.@{ui}
     Sector  not  aligned  with  index signal from disk. Usually not
     disastrous. Retry might recover.

@{i}Error=23.@{ui}
     Sector not found. Disk might be corrupt. Retry might recover.

@{i}Error=24.@{ui}
     Sector   identification   information   corrupt.   Retry  might
     recover.

@{i}Error=25.@{ui}
     Sector data might be corrupt. Retry might recover.

@{i}Error=38.@{ui}
     Index  signal  from the drive not received. Amiga needs service
     to correct a hardware problem.

@{i}Not a DOS Disk.@{ui}
     Ensure  the  disk  is an Mac disk capable of being read by your
     drive.  Please  check  @{"Formats Supported" link "Formats_Supported"}  to  verify  that  your
     machine  is  capable  of  reading  the  format  of  the Mac disk
     inserted.  The  disk may be an AmigaDOS disk or Mac high density
     formatted disk in a low density drive.

@{i}Screen Blinks.@{ui}
     This  only  occurs  when reading an 800K Mac floppy. It's a bug
     in GARY chip. @{"My screen blinks" link "Screen Blinks"}

@{i}Renaming the data file and the resource file changes it name too.@{ui}
     Not a bug. It's a feature. @{"Renaming Files" link "Renaming Files"}

@{"Technical Support" link "Technical Support"}
@ENDNODE

@NODE "Electronic Registration"
We   suggest   that  you  immediately  register  the  product  you've
purchased.  This  will  allow  us  to  inform  you of new products or
upgrades   and  be  eligible  for  product  discounts.  Currently  we
provide  two  methods  of  registering  the  Customer  Identification
Number and address with us:

    · Email.  Send  the file s:Registration.data intact to either our
      Internet      account:     consultron@consultron.plymouth.mi.us
      (primary)  cstron@m-net.arbornet.org  (secondary)  or  logon to
      our BBS.

    · Paper.  Send  us  the paper output generated by or Registration
      program to the address listed in the output.

We  would  appreciate  if  you would use the Email method since
it help to eliminate typographical errors.
@{"Register NOW!" SYSTEM ":c/Registration :RegistrationInfo"}

@ENDNODE

@NODE "Technical Support"
If  you  purchased  our products as marketed by CONSULTRON, we'll try
to  give  you  the  best  technical support possible. You will notice
your  Customer  Identification Number is located in the third line of
the   READ.ME  file  and  will  automatically  be  entered  into  the
Registration  program.  Please  write this number on the disk, in the
manual  and  anywhere  convenient.  When you call for help, please be
ready  with  your  Customer Identification Number (CIN). We hope this
doesn't  inconvenience  you  much.  This  policy helps keep our costs
down and we can pass those savings on to you.

    @{b}(313) 459-7271@{ub} 10:00 AM to 5:00 PM Eastern Time

@ENDNODE


@NODE "Electronic Bulletin Board Service"
We've  provided  an electronic bulletin board service to better serve
you.  It  may  contain  update  patches  should  there  be any. Other
public  domain  or  shareware  files are available that may be useful
to  you.  We  also  have  demo  versions of most of our programs that
allow you to "try before you buy".

The telephone number of our BBS is:

    @{b}(313) 459-7271@{ub} 6:00 PM - 10:00 AM EST Weekdays
                  and all day on weekends and U.S. holidays

    Currently our service is 2400-14.4 baud 8N1

 Thank you.

@ENDNODE

@NODE "Copyrights, Disclaimers and Trademarks"
@{b}COPYRIGHTS@{ub}

CrossMACFileSystem,   mfm.device,   DiskChk,  DiskChg,  Registration,
ConfigDisk,    Install,    Dr_CrossMAC    (c)   Copyright   1988-1993
CONSULTRON. All Rights Reserved.

Mount,  DiskCopy,  Format,  Installer  and  Installer  project  icon,
AmigaGuide,     amigaguide.library,     (c)     Copyright     1991-93
Commodore-Amiga,   Inc.   All   Rights   Reserved.   Reproduced   and
distributed under license from Commodore.

@{b}DISCLAIMERS@{ub}

MOUNT,  FORMAT,  DISKCOPY,  INSTALLER  AND  AMIGAGUIDE  SOFTWARE  ARE
PROVIDED  "AS-IS"  AND SUBJECT TO CHANGE; NO WARRANTIES ARE MADE. ALL
USE IS AT YOUR OWN RISK. NO LIABILITY OR RESPONSIBILITY IS ASSUMED.

@{b}TRADEMARKS@{ub}

CrossMAC,   CrossDOS   and  CrossPC  are  trademarks  of  CONSULTRON.
AmigaGuide  is  a  trademark  of  Commodore-Amiga, Inc. Macintosh and
Finder are registered trademarks of Apple Computer, Inc.

Other  product  names  mentioned  in  this  file may be trademarks or
registered  trademarks  of  their respective companies and are hereby
acknowledged.

@ENDNODE
