@database READ.ME
@author "Leonard Poma"
@(c) "Copyright © 1993 CONSULTRON"
@$VER:  READ.ME 5.07 (21/7/93)
@smartwrap

@node Main "CrossDOS Plus"

                            CrossDOS Plus
                             Version 5.07
                             July 21 1993

This file describes any changes, highlights and special features for this
version and revision of CrossDOS Plus. 
PLEASE READ THIS FILE FOR IMPORTANT NEWS!

*******************************************
TABLE OF CONTENTS

@{"New features in this Release" link "New features in this Release"}
@{"Running CrossDOS or CrossPC from the Product Disk" link "Running CrossDOS or CrossPC from the Product Disk"}
@{"Installing CrossDOS or CrossPC" link "Installing CrossDOS or CrossPC"}
@{"Undocumented CrossPC Features" link "Undocumented CrossPC Features"}
@{"Configuring an MS-DOS Hard Drive" link "Configuring an MS-DOS Hard Drive"}
@{"Changes from Versions 3 and 4 of CrossDOS" link "Changes from Versions 3 and 4 of CrossDOS"}
@{"Notes for Floptical Users" link "Notes for Floptical Users"}
@{"Manual Corrections" link "Manual Corrections"}
@{"Troubleshooting - CrossDOS" link "Troubleshooting - CrossDOS"}
@{"Electronic Registration" link "Electronic Registration"}
@{"Technical Support" link "Technical Support"}
@{"Electronic Bulletin Board Service" link "Electronic Bulletin Board Service"}
@{"Copyrights, Disclaimers and Trademarks" link "Copyrights, Disclaimers and Trademarks"}

@ENDNODE

@NODE "New features in this Release"
@{"Improvements - CrossDOS" link "Improvements - CrossDOS"}
@{"Improvements - CrossPC" link "Improvements - CrossPC"}
@{"Improvements - Configure an MS-DOS Hard Drive" link "Improvements - Configure an MS-DOS Hard Drive"}
@{"Improvements - Dr_CrossDOS" link "Improvements - Dr_CrossDOS"}
@{"Improvements - Install" link "Improvements - Install"}
@{"Improvements - READ.ME" link "Improvements - READ.ME"}
@ENDNODE

@NODE "Improvements - CrossDOS"
CrossDOS now has its own disk icon!  When CrossDOS recognizes an MS-DOS
disk, a disk icon appears with "CrossDOS TM" on the label.  That's not all!
If you are using 2.0 or higher, opening the disk icon will display icons
for files and directories without needing to perform a @{b}Show/All Files@{ub}
first.

We now support disks formatted to 10 sectors per track used primarily on
Atari systems.

@ENDNODE

@NODE "Improvements - CrossPC"
We've significantly increased the speed of the serial port emulation.  Our
tests show the serial port to be reliable up to the baud rates on the
machines listed below.

    Machine  CPU Speed  CPU Type    Baud
    -------------------------------------
    A3000       25MHZ   68030       38.4K
    A500         7MHz   68000        4.8K

Your machine may exhibit higher or lower values depending on your
configuration.  The general rule-of-thumb to use is:  the more CPU power,
the faster the speed.

We've successfully used the following communication programs on CrossPC.
    Procomm
    Telix
    Compuserve Information Manager
    Prodigy
    Laplink

We now display the information in the CrossPC debug window on the PC screen
at boot time.

We've increased the MS-DOS hard drive speed by about 10%.

We've improved the mouse driver emulation to be compatible with more PC
applications.

@ENDNODE

@NODE "Improvements - Configure an MS-DOS Hard Drive"
We've improved the MS-DOS hard drive configuration program.  It now tries
to support drives that are non-RigidDiskBlock formatted.  It also displays
more information at each step for your peace of mind.

@ENDNODE

@NODE "Improvements - Dr_CrossDOS"
We've made @{b}Dr_CrossDOS@{ub} more intelligent in its diagnosis.  If
you're having difficulties, please use it before calling our technical
support line.

@ENDNODE

@NODE "Improvements - Install"
We now provide an @{b}Uninstall@{ub} option to try to remove as many files
associated with CrossDOS and CrossPC as we can find.  Use this option
sparingly.  There is NO need to do an uninstall before doing an install or
reinstall.  A reinstall will copy over the earlier releases of files with
later releases.

@ENDNODE

@NODE "Improvements - READ.ME"
We have converted our @{b}READ.ME@{ub} files into AmigaGuide® documents for
easier searches.

@ENDNODE

@NODE "Running CrossDOS or CrossPC from the Product Disk"
Both CrossDOS and CrossPC can be executed from this product disk
(particularly if you are running on a floppy based system).  Just
double-click on the appropriate icon.

To start:  double-click on the "PC0" icon.  Your internal floppy drive will
now be configured as an MS-DOS drive with the name "PC0:".  You can now
read and write preformatted MS-DOS disks.

If you need to format an MS-DOS disk, double-click on the @{b}Format@{ub}
icon in the @{i}system@{ui} drawer.  Choose the device to format from the
device list and answer any of the questions and options given.

Double-clicking on the CrossPC icon begins the PC-XT emulation.  Place an
MS-DOS 720K boot disk in your internal drive and it should boot up.
(Please note that 68000 users are only configured with 256K of PC memory in
the emulation.)

It's that simple.

@ENDNODE

@NODE "Installing CrossDOS or CrossPC"
You may choose to install both products using the @{b}Install@{ub} program
on the disk.  This is particularly efficient if you have a hard drive.  If
you do wish to install, DO NOT move the files over manually!  The
@{b}Install@{ub} program makes many intelligent choices depending on your
system configuration.

Once installed, you can use most features immediately.  A few features such
as MS-DOS hard disk access may require additional operations be performed
before you use it.  For further information see @{"Configuring an MS-DOS Hard Drive" link "Configuring an MS-DOS Hard Drive"}

@ENDNODE


@NODE "Undocumented CrossPC Features"
@{"New ToolTypes" link "New ToolTypes"}
@{"Obsolete ToolTypes" link "Obsolete ToolTypes"}
@{"Mouse Software" link "Mouse Software"}
@ENDNODE
  

@NODE "New ToolTypes"  
@{b}DISKSHARE@{ub}

Although CrossPC and CrossDOS can share data from the same MS-DOS disk,
there can be problems if it is accessed at the same time.  To reduce this
risk significantly, we implemented a 'lockout' feature as the default when
using CrossPC.  When CrossPC is running with a CrossDOS device (such as
PC0:  or PCC:) we disable access to it from the Amiga side.  When CrossPC
is rebooted (CTRL-ALT-DEL), it will free the CrossDOS devices to be used by
the Amiga.

If you wish to share the disks simultaneously between CrossPC and CrossDOS
you can set the DISKSHARE ToolType in the CrossPC icon.  CAUTION:  If the
proper precautions are not followed YOU WILL CORRUPT THE DISK.  See
@{b}Appendix@{ub} C in the manual called @{b}"Hard Drive Considerations"@{ub}
for an in-depth discussion about this problem.

It is recommended that you do not use DISKSHARE unless you are confident
you know what you are doing.  Since AmigaDOS and CrossPC both don't know
when the other is writing to the drive, it is possible to corrupt your
floppy or hard drive partition, losing some or all of your data.  If you do
need to use the partition from both AmigaDOS and CrossPC simultaneously,
remember that whenever you write to the disk, you must make the other
operating system aware that you have changed the disk.  Under AmigaDOS a
Diskchange command to the drive will work, under MS-DOS a CTRL-C or
executing @{b}CHKDSK@{ub} has a similar effect.

@{b}STARTPRI=xx@{ub}

The default priority of CrossPC is -10.  By specifying STARTPRI=xx in the
ToolTypes of the CrossPC icon, the priority of CrossPC is set to xx.  The
limits for this are -100 to 0.  CrossPC will ensure that the priority is
between these two limits.  Increasing the priority may not provide you any
more speed unless you are running other tasks.  You will probably never
need to use this ToolType.

@ENDNODE

@NODE "Obsolete ToolTypes"
@{b}CPU1 (Manual Edition 1 only)@{ub}

This is no longer used.  If it is present, it is ignored.  The only use for
the CPU1 ToolType was if you had an early GVP accelerator card.  Now
CrossPC automatically detects this, and executes the appropriate code.  If
you do have one of these GVP cards, CrossPC will state that it is using CPU
type 68010 instead of 68030.

@ENDNODE

@NODE "Mouse Software"
It is no longer necessary to use @{b}MOUSE.COM@{ub}.  The equivalent code
is executed whenever @{b}RightAmiga-Help@{ub} is pressed.  This makes it
easier to use the mouse if you haven't put MOUSE.COM onto an MS-DOS disk.
MOUSE.COM is still useful if you want the mouse to be enabled automatically
from the AUTOEXEC.BAT.

You can disable the mouse driver by pressing @{b}RightAmiga-Shift-Help@{ub}.
We recommend that you do not enable or
disable the mouse within an application.  This insures for proper
recognition of the mouse by applications.

@{b}NOTE:@{ub} PC applications that can use the mouse REQUIRE that the
mouse driver be active before executing the application.

@ENDNODE


@NODE "Configuring an MS-DOS Hard Drive"
CrossDOS and CrossPC now support MS-DOS formatted hard drives.  If the
drive you configure is already formatted, there are certain hard drive
formats that are not 'true' MS-DOS.  In this case, we do our best to
decipher the disk but 'all bets are off'.

We do require that you install both products using our @{b}Install@{ub}
program.  Also, select @{b}Configure MS-DOS Hard Disk for CrossDOS & CrossPC@{ub}
to have us try to create a proper mountfile to match.

You will be asked in the @{b}Install@{ub} program whether you want to
configure one of two types of hard disks.

@{b}One:@{ub} A 'true' MS-DOS hard disk configured as the entire disk.
This type is useful if you wish to transfer data between the Amiga and a
stand-alone PC.  We do HIGHLY recommend that this type of hard disk be
formatted on the PC first then brought to the Amiga for configuring.

@{b}Two:@{ub} An 'image' of an MS-DOS hard disk within an Amiga hard disk
partition.  This type is particularly useful with CrossPC.

Once the hard drive is configured, @{b}DO NOT use our Format@{ub} command
or the standard Amiga Format command to format it.  Instead, treat it like
an unformatted MS-DOS hard disk.  This means you must use the @{b}FDISK@{ub}
and @{b}FORMAT@{ub} commands provided by MS-DOS to partition and format the
hard disk respectively.  Failure to heed this warning may cause
unpredictable results.

For example, if the configured hard disk is to be used with CrossPC,
perform the following steps:
1. Execute CrossPC and boot off an MS-DOS boot floppy.
2. Run @{b}FDISK@{ub} to partition your configured hard drive. It will reset
    CrossPC after FDISK.
3. Execute CrossPC and boot off an MS-DOS boot floppy again.
4. Run "@{b}Format C: /s/v@{ub}" to format the C: partition and place system files on
    it.
5. Transfer other files from the MS-DOS boot floppy to the C: partition.
6. Reboot CrossPC you should be able to boot off your hard drive.

For further information refer to @{b}Appendix C@{ub} in the manual
(@{b}Hard Drive Considerations@{ub}) that discusses the different hard
drive types and special considerations.

@ENDNODE

@NODE "Changes from Versions 3 and 4 of CrossDOS"
This section is important for users who have an earlier version of
CrossDOS.

There have been changes to CrossDOS for a multitude of reasons.  These
reasons range from efficiency, speed, robustness and more.  We hope you
like the changes.  Most of the code is more efficient in both speed and
code size.  Those code pieces that are larger are due to feature additions.

The CrossDOS product has two versions of code for most of its programs.
One version is Amiga 1.3 and 2.0 compatible.  The other is 2.0 ONLY
compatible (identified by a ".2" on the end of the name).  The 1.3/2.0 code
is fatter, as you would guess, and generally has a few less features.  We
recommend that you install CrossDOS on the operating system version you
wish to run on.  If you wish to use it under both operating systems, you
should install it under 1.3.

@{"New CrossDOS Utilities" link "New CrossDOS Utilities"}
@{"We've Renamed the Default Floppy Devices" link "We've Renamed the Default Floppy Devices"}
@{"MountMF is Gone!" link "MountMF is Gone!"}
@{"MFORMAT, MDISKCOPY and Kill are History!" link "MFORMAT, MDISKCOPY and Kill are History!"}
@{"TxFilter and IntlTrans have been Combined!" link "TxFilter and IntlTrans have been Combined!"}
@{"TDPatch12 and TDPatch13" link "TDPATCH12 and TDPatch13"}
@ENDNODE

@NODE "New File System Name"
The file system code (the cornerstone of the CrossDOS product) has changed
name from @{b}MSDOSFILESYSTEM@{ub} to @{b}CrossDOSFileSystem@{ub}.  If you
install CrossDOS onto your system we will copy this new file system to your
L:  directory.  We also copy this same code to L:MSDOSFileSystem so that
your old configuration may still work.

@ENDNODE

@NODE "We've Renamed the Default Floppy Devices"
The old MS-DOS devices defaulted to the names DI0:  through DI3:.  We now
use PC0:  through PC3:.  If you like the old names better, all you have to
do is rename the mountfile from PC0 to DI0.  This rule applies to the other
devices too.  You can name the floppy mountfiles to virtually any name that
does not conflict with any other device name.

@ENDNODE

@NODE "New CrossDOS Utilities"
We include new utilities to support CrossDOS better as well as benefit the
entire Amiga system.  We have utilities such as @{b}Mount, Format and
DiskCopy@{ub} that are designed to replace the system utilities of the same
name.  They will operate on MS-DOS disks as well as Amiga disks.  They
operate just as the commands they are replacing but they have some
additional features to make life easier.

Although they are designed to replace the standard Amiga utilities, you can
elect to rename these utilities to CDMOUNT, CDFORMAT and CDDISKCOPY.  We
recommend that you replace your system commands to utilize these commands
to the fullest.

@ENDNODE

@NODE "MountMF is Gone!"
We've replaced this command with an advanced @{b}Mount@{ub} command that
uses mountfiles.  It can be used by either double-clicking on the mountfile
(such as PC0) or executing a mount of all the devices in a drawer at boot
time (we can do this in the Install program).

We do not encourage using @{b}MountMF@{ub} but we do have a new replacement
for it.  Our install program will try to find your old MountMF and replace
it.  This allows you to use it if it is already used in a boot script.

@ENDNODE

@NODE "MFORMAT, MDISKCOPY and Kill are History!"
@{b}MFormat and MDiskCopy@{ub} have been replaced with the full-featured
@{b}Format and DiskCopy@{ub} respectively.  Alternate floppy formats used
with MFormat have been replaced by special project icons located in the
@{i}:system/Alt_Formats@{ui} drawer.  We do not encourage using these
alternate formats unless you have to.  The @{b}Format@{ub} utility will
automatically sense the optimum disk format unless you override it by using
one of these alternate formats.  We also recommend it be used from the
product disk.  Refer to the @{b}READ.ME@{ub} file in that drawer for more
information.

The @{b}Kill@{ub} utility has been somewhat dangerous to use in the past
and it is now somewhat useless.  CrossDOS is now more efficient.  If there
is no MS-DOS disk in the drives, we try to deallocate all the memory we
can.  In fact, CrossDOS uses no CHIP memory unless it senses an MS-DOS
floppy disk in the drive.

Our @{b}Install@{ub} program will delete these files as well as the project
icons that are associated with them (such as Kill.DI0).

@ENDNODE

@NODE "TxFilter and IntlTrans have been Combined!"
We've combined the functions for setting the text filters and international
translation tables.  In fact, they should be even easier to use with more
features.  These functions have been combined into a @{b}commodity called
CrossDOS@{ub} located in your @{i}system@{ui} drawer.  Refer to the manual
in Chapter 4 for more details.

Our @{b}Install@{ub} program will delete TxFilter and IntlTrans as well as
the project icons that are associated with them.

@ENDNODE

@NODE "TDPatch12 and TDPatch13"
The trackdisk.device code resident in Kickstart code versions 1.2 and 1.3
has a couple bugs that need fixing as well as adding a new feature found in
version 2.0 of the trackdisk.device.  @{b}TDPatch12@{ub} and
@{b}TDPatch13@{ub} correct this problem for KickStart V1.2 and V1.3
respectively.  The installation program will detect the version of
KickStart you are running and transfer the proper patch version to your
@{i}C:@{ui} directory.  The mfm.device will automatically execute this file
for you if it is needed.

@{b}NOTE:@{ub} TDPatch will not work in conjunction with @{b}NOCLICK@{ub}
or @{b}TRACKSALVE@{ub} or the Applied Engineering device driver earlier
then Version 1.2.  we supply a small program called @{b}KillClick@{ub} (in
the @{i}diag@{ui} drawer) to stop the 'clicking' on the drive for KickStart
2.0 ONLY!

@ENDNODE


@NODE "Notes for Floptical Users"
CrossDOS and CrossPC now support floptical drives.  If you do not know if
you have a floptical drive you probably don't have one.  A floptical drive
can support the MS-DOS 720K, 1.44M and its own 20M floptical disk format.
It can also support an Amiga 20M hard drive format.

We do recommend that you install both products using our @{b}Install@{ub}
program.  Also, select the @{b}Configure MS-DOS Hard Disk for CrossDOS and
CrossPC@{ub} to allow us to attempt to create a proper mountfile.  When you
are configuring the floptical, make sure you have a preformatted MS-DOS
disk in the drive at the time.  Any MS-DOS disk should do (such as an 720K
disk).  This is needed to sense the proper information from the drive.

Formatting with the floptical drive is slightly different too.  This is
because the floptical cannot properly sense the size of the unformatted
disk in the drive.  There are two ways to format in the floptical drive.

One:  Insert a preformatted MS-DOS disk in the drive with the same
formatted size as you want to format.  If you want to format a 1.44M disk,
for example, insert a preformatted MS-DOS 1.44M disk in the drive first.
Then, execute the @{b}Format@{ub} program.  Proceed with the program until
you come the requester that says "Ok to format volume ...  " then insert
the actual disk to be formatted and proceed.

Two:  Double-click on the format project icon in the @{i}:system/Alt_Formats@{ui}
drawer that corresponds to the desired format.  For example, double-click
on the @{b}MSDOS_720K.Format@{ub} icon to 'force' the format of the disk to
720K.  Proceed through the format.

Choose the method that makes you comfortable.  Experimentation is your best
teacher.

@{b}NOTE:@{ub} At this time, GVP controllers will not permit a format of a
blank floppy using the @{b}Format@{ub} program.  In order to low-level
format a blank floppy you need to use their @{b}FAAASTPREP@{ub} program,
select "Manual Installation" then select "Low Level Format".  When completed,
exit @{b}FAAASTPREP@{ub} and perform a @{b}Format@{ub} with the "Quick Format"
option.

@ENDNODE

@NODE "Manual Corrections"
The following is a list of important manual corrections to editions 1 and
2.  Manual Edition 2 can be identified by the last line on the title page
(first page after the front cover).  Manual Edition 1 can be identified by
the lack of any edition text on the title page.

@{"Manual Edition 1" link "Manual Edition 1"}
@{"Manual Edition 2" link "Manual Edition 2"}
@ENDNODE

@NODE "Manual Edition 1"  
Chapter 1; Section @{b}Getting Started - CrossDOS@{ub}; Page 6; the Install
program cannot be run from the CLI.

Chapter 3; Section @{b}Using CrossDOS@{ub}; Page 10; The section about
showing icons on MS-DOS disks using the @{b}Show/All Files@{ub} of the
Windows menu is not necessary under 2.0.  Default icons are automatically
displayed.  See @{"Improvements - CrossDOS" link "Improvements - CrossDOS"} for further information.

Chapter 5; Section @{b}Troubleshooting - CrossDOS@{ub}; Page 29; the
heading to the fourth paragraph should read "DF0:BAD or DF0:????"

Chapter 7; Section @{b}Getting Started - CrossPC@{ub}; Page 36; the Install
program cannot be run from the CLI.

Chapter 9; Section @{b}Tech Notes - CrossPC@{ub}; Page 41; the last
paragraph, last sentence should read "For hard disks, DosType should be set
to 0x4D534800."

Chapter 9; Section @{b}Tech Notes - CrossPC@{ub}; Page 50; Item 5 should
read:  5.  Start CrossPC with an MS-DOS boot floppy.  Run FDISK.  After you
partition the disk, CrossPC will reboot.

Chapter 9; Section @{b}Tech Notes - CrossPC@{ub}; Page 50; Add the
following:  7.  You will need to format each partition you created with
FDISK.  To format the C:  partition to be bootable execute the following
command

  Format C: /s/v

8.  You can now reboot CrossPC and you should be able to boot off the C:
partition on your newly allocated hard drive.

@ENDNODE

@NODE "Manual Edition 2"
Chapter 3; Section @{b}Using CrossDOS@{ub}; Page 10; The section about
showing icons on MS-DOS disks using the @{b}Show/All Files@{ub} of the
Windows menu is not necessary under 2.0.  Default icons are automatically
displayed.  See @{"Improvements - CrossDOS" link "Improvements - CrossDOS"} for further information.

Chapter 8; Section @{b}Tech Notes - CrossPC@{ub}; Page 46; the second to
last paragraph second sentence should have the phrase @{b}LeftAmiga-Help@{ub}
changed to @{b}RightAmiga-Help@{ub}.

@ENDNODE


@NODE "Troubleshooting - CrossDOS"
Here are some ideas to help you should you have trouble using CrossDOS.


@{b}General@{ub}
  · Ensure you have configured the drive in which you wish to use the
    MS-DOS disk by Mounting it.  The device names correspond to the device
    names given by Commodore.  For example, PC0:  is the MS-DOS device name
    corresponding to DF0:  and PC1:  is the MS-DOS device name
    corresponding to DF1:.
  · Avoid file names longer than 8 characters. 
  · Avoid file extensions longer than 3 characters. 
  · Avoid space in file names or file extensions. 
  · Make sure you do not mix disk types and format types.  For example, do
    not do a low density format on a high density disk or visa versa.  Do
    not try to read a high density formatted disk in a low density drive.
  · When using Workbench, avoid transferring files with file extensions.
    Rename them first if necessary.
  · Ensure the file formats you want to use between both the Amiga program
    and the MS-DOS program are compatible.  For example, an Amiga FinalCopy
    file is not readable by an MS-DOS WordPerfect wordprocessor.
  · Should you exhibit read or write errors with no specific pattern, try
    cleaning the floppy drive heads of both the Amiga and MS-DOS computers.
  · The easiest way to check an MS-DOS disk from the Amiga is to run the
    DiskChk program included with CrossDOS.  The following is a list of
    most of the CrossDOS error codes.


@{b}Error Messages@{ub}

@{u}No.     Name                    Description@{uu}

-1  IOERR_OPENFAIL          device/unit failed to open
-2  IOERR_ABORTED           request aborted
-3  IOERR_NOCMD             command not supported
-4  IOERR_BADLENGTH         not a valid data length
20  TDERR_NotSpecified      general catchall error code
21  TDERR_NoSecHdr          couldn't find any sectors on track
22  TDERR_BadSecPreamble    bad sector header
23  TDERR_BadSecID          bad sector header
24  TDERR_BadHdrSum         sector header had incorrect CRC
25  TDERR_BadSecSum         data had incorrect CRC
26  TDERR_TooFewSecs        couldn't find enough sectors
27  TDERR_BadSecHdr bad     sector header
28  TDERR_WriteProt         can't write to a protected disk
29  TDERR_DiskChanged       no disk in the drive
30  TDERR_SeekError         couldn't find track 0
31  TDERR_NoMem             ran out of memory
32  TDERR_BadUnitNum        asked for a unit > 3
33  TDERR_BadDriveType      not a recognized drive
34  TDERR_DriveInUse        someone else allocated the drive
35  TDERR_PostReset         user hit reset; awaiting doom
36  MDERR_OutofTracks       out of physical tracks
37  MDERR_InvParam          invalid parameter (MD_SETPARMS)
38  MDERR_IndexNotSync      index signal not available
39  MDERR_WrongTrack        drive head on wrong physical track

@{b}Possible Problems and Solutions@{ub}

@{i}I changed the MS-DOS disk on the 5 1/4" drive and still get the old
directory from the previous disk.@{ui}
    The 5 1/4" drive doesn't support the disk change signal.  When you
    change disks, execute the CLI DiskChange command or our DiskChg command
    on the drive before your next access of the new disk.

@{i}I copied a file to an MS-DOS disk but can't find it when reading the
disk on my PC.@{ui}
    Avoid using spaces in file names.  The MS-DOS computer ignores
    everything after the space character.

@{i}I opened the MS-DOS disk from Workbench but I see none of the files
that I know are there.@{ui}
    MS-DOS files don't usually have icon files associated with each file.
    The Amiga uses these icon files to draw the icons in Workbench.  You
    can access the files by either selecting the Window/Show/All Files from
    the Workbench menu (not available under 1.3) or use any application
    file requester or directory utility.  @{"Improvements - CrossDOS" link "Improvements - CrossDOS"}

@{i}DF0:BAD. or DF0:????@{ui}
    This is OK.  The task that handles the AmigaDOS device called DF0:
    can't recognize foreign disk formats such as MS-DOS.

@{i}Disk Ejected Too Soon.@{ui}
    Disk removed before all information was written to it.  Put the disk
    back into the drive and Retry might recover without corruption.  We
    recommend you wait at least 3 seconds from the last disk access before
    removing the disk.

@{i}Disk Full.@{ui}
    Exceeded the capacity of the system disk.  Remove unnecessary files
    from the disk.

@{i}Error=-4.@{ui}
    TDPatch13 needs to be applied.  Ensure you aren't running NoClick or
    TrackSalve.  @{"TDPatch12 and TDPatch13" link "TDPATCH12 and TDPatch13"}

@{i}Error=21.@{ui}
    Could not find any sectors on the specified track.  Probably not an
    MS-DOS standard density formatted disk readable by your drive.

@{i}Error=22.@{ui}
    Sector not aligned with index signal from disk.  Usually not
    disastrous.  Retry might recover.

@{i}Error=23.@{ui}
    Sector not found.  Disk might be corrupt.  Retry might recover.

@{i}Error=24.@{ui}
    Sector identification information corrupt.  Retry might recover.

@{i}Error=25.@{ui}
    Sector data might be corrupt.  Retry might recover.

@{i}Error=38.@{ui}
    Index signal from the drive not received.  Amiga needs service to
    correct a hardware problem.

@{i}Not a DOS Disk.@{ui}
    Ensure the disk is an MS-DOS disk capable of being read by your drive.
    The disk may be an AmigaDOS disk or MS-DOS high density formatted disk
    in a low density drive.

@{"Technical Support" link "Technical Support"}
@ENDNODE

@NODE "Electronic Registration"
We would like you to help us in reducing the errors.  Errors are caused by
manually entering product registration information into our database.  This
occurs primarily because hand printing may be somewhat hard to decipher.

Our electronic registration is available through the install program or by
double-clicking on the Register icon.  Fill in the correct information
requested and print it off by selecting the "Print and Save" button.  Send
the printed registration sheet and the @{b}Proof-of-Purchase@{ub} card to
the address listed on the sheet.

@ENDNODE

@NODE "Technical Support"
Should you have any difficulties, double-click on the program @{b}Dr_CrossDOS@{ub}.
It will try to diagnose the problem.  If you are still having difficulties
you can contact us at:

CONSULTRON
8959 Ridge Rd
Plymouth, MI  48170-3213

@{b}(313) 459-7271@{ub}       10:00 AM - 5:00 PM EST     Weekdays

@{b}NOTE:@{ub} Make sure you send in your product registration with
@{b}Proof-of-Purchase@{ub} card.  We will send you a @{b}Product
Certificate@{ub} with a unique @{b}Customer Identification Number@{ub}.
You must use this number when calling or corresponding for technical
support.  No technical support will be given without this number.

@ENDNODE


@NODE "Electronic Bulletin Board Service"
We've provided an electronic bulletin board service to better serve you.
It may contain update patches should there be any.  Other public domain or
shareware files are available that may be useful to you.  We also have demo
versions of most of our programs that allow you to "try before you buy".

The telephone number of our BBS is:

@{b}(313) 459-7271@{ub}       6:00 PM - 10:00 AM EST     Weekdays
                  and all day on weekends and U.S. holidays

    Our service is 2400 baud 8N1

 Thank you.

@ENDNODE

@NODE "Copyrights, Disclaimers and Trademarks"
@{b}COPYRIGHTS@{ub}

CrossDOSFileSystem, mfm.device, MountMF, TDPatch12, TDPatch13, DiskChk,
DiskChg, Registration, ConfigDisk, Install, Dr_CrossDOS
(c) Copyright 1988-1993 CONSULTRON. All Rights Reserved.

CrossPC
(c) Copyright 1992-1993 IBeM Distributors. All Rights Reserved.
Reproduced and distributed under license from IBeM Distributors.

Mount, DiskCopy, Format, CrossDOS, Installer and Installer project icon,
AmigaGuide, amigaguide.library,
(c) Copyright 1991-93 Commodore-Amiga, Inc. All Rights Reserved.
Reproduced and distributed under license from Commodore.

gadtools13.library
(c) Copyright 1992 Dreamers Guild, Inc. All Rights Reserved.
Reproduced and distributed under license from Dreamers Guild, Inc.

@{b}DISCLAIMERS@{ub}

GADTOOLS13.LIBRARY, MOUNT, FORMAT, DISKCOPY, INSTALLER AND AMIGAGUIDE
SOFTWARE ARE PROVIDED "AS-IS" AND SUBJECT TO CHANGE; NO WARRANTIES ARE
MADE.  ALL USE IS AT YOUR OWN RISK.  NO LIABILITY OR RESPONSIBILITY IS
ASSUMED.

@{b}TRADEMARKS@{ub}

CrossDOS and CrossPC are trademarks of CONSULTRON.
AmigaGuide is a trademark of Commodore-Amiga, Inc.

@ENDNODE
