@database FlyinReadMe.guide
@author "Markus Pöllmann"
@$VER: ReadMe.guide 2.00 (04.11.98)
@wordwrap
@font xhelvetica.font 13
@node main "Flyin'High V1.2 - ReadMe"

 English

    @{u}A gfx-board compatible version of Flyin\'High@{uu}

    @{" General information " link general_e}
    @{" How to use it " link howtouse_e}


 Deutsch

    @{u}Eine Grafikkarten-Kompatible Version von Flyin\'High@{uu}

    @{" Allgemeine Informationen " link general_d}
    @{" Was für die Benutzung zu beachten ist " link howtouse_d}


 Italiano

    @{u}Una versione di Flyin'High compatibile con le schede grafiche@{uu}

    @{" Informazioni generali " link general_it}
    @{" Come usarla " link howtouse_it}


 © 1997/2005 by APC&TCP.
 All Rights Reserved.
http://www.apc-tcp.de

@endnode
@node general_e "Flyin'High V1.2 - General information"

A lot of people complained of the AGA-only version of Flyin'High. They were right, but when we designed Flyin'High we thought of a game that should make the best out of a "small" Amiga. Times have changed and my Amiga has too. When I got my gfx-board, I still wanted to play Flyin'High, but it seemed to be too difficult to make it run under CyberGfx or Picasso96.
Some time ago I started with "Phoenix", which was designed from the beginning to run on AGA, CyberGfx and Picasso96 - and on more powerful machines. I created lots of code and realized, that a lot of it would be usable for a more compatible version of Flyin'High. Well, here it is.

Who should use it? Everyone with a gfx-board and everyone who had problems getting Flyin'High started on his system. If you were satisfied with Flyin'High on your AGA-Amiga, you shouldn't install this version.

If you install this version, you should be aware, that
· you need more memory (8MB)
· you have to wait some time (~1.5 minutes) at the start of Flyin'High (to let him do necessary calculations)
· animations are more like a slide-show under Picasso96
compared to the original version of Flyin'High.

I expect you to run into problems when using a Picasso96-emulation on a CyberGfx-system.



Markus Pöllmann
@endnode
@node howtouse_e "Flyin'High V1.2 - How to use it"

The original version of Flyin'High has to be installed on your harddrive, that this version can be installed.

Flyin'High needs a screenmode with a width of 320 and a height of 256 with 256 colors. It is very likely, that your CyberGfx- or Picasso96-installation does not offer such a screenmode. If so, the Flyin'High screenmode-requester will show you only a PAL-mode. In this case, you have to create a screenmode on your own. For CyberGfx-systems the program for this purpose is called "CGXMode", for Picasso96-systems it's "Picasso96Mode". Please refer to their documentation to find out how to create your own screenmode.


Please remember, that the only accepted screenmode has to fit the following specifications:

width   320
height  256
colors  256, with a "look-up-table", no "high-color" or "true-color".

@endnode
@node general_d "Flyin'High V1.2 - Allgemeine Informationen"

Viele Leute habe sich darüber beschwert, daß Flyin'High nur auf AGA lief. Sie hatten recht, allerdings hatten wir bei der Programmierung von Flyin'High das Ziel, das Beste aus einem "kleinen" Amiga zu holen. Die Zeiten haben sich geändert, und mein Amiga auch.
Als ich meine Grafikkarte bekommen habe, wollte ich auch weiterhin Flyin'High spielen, allerdings schien die Umsetzung für CyberGfx oder Picasso96 zu umständlich und zeitraubend.
Vor einiger Zeit habe ich mit "Phoenix" begonnen, was von Anfang an für AGA, CyberGfx und Picasso96 ausgelegt war - und auch für schnellere Prozessoren. Ich habe viel Code geschrieben und es hat sich gezeigt, daß ich vieles davon für einen kompatiblere Version von Flyin'High einsetzen konnte. Nun gut, hier ist sie.

Wer sollte sie benutzen? Jeder mit einer Grafikkarte und jeder der Probleme bei der Benutzung von Flyin'High hatte. Wenn Sie mit Ihrer Flyin'High-Version auf Ihrem AGA-Amiga zufrieden sind, sollten Sie diese hier nicht installieren.

Wenn Sie diese Version installieren, sollten Sie sich bewusst sein, daß
· Sie mehr Speicher benötigen (8MB)
· Sie beim Start von Flyin'High einige Zeit (~1,5 Minuten) warten müssen (um ihn einige notwendig gewordene Berechnungen ausführen zu lassen)
· Animation unter Picasso96 mehr eine Dia-Schau sind
im Vergleich zur originalen Version von Flyin'High.

Sie könnten Probleme haben, wenn Sie eine Picasso96-Emulation auf einem CyberGfx-System installiert haben.



Markus Pöllmann
@endnode
@node howtouse_d "Flyin'High V1.2 - Was für die Benutzung zu beachten ist"

Die Originalversion von Flyin'High muß auf Ihrer Festplatte installiert sein, damit Sie diese Version installieren können.

Flyin'High benötigt einen Bildschirmmodus mit einer Breite von 320 und einer Höhe von 256 Pixeln, bei 256 Farben. Es ist recht wahrscheinlich, daß Ihre CyberGfx- oder Picasso96-Installation solch einen Bildschirmmodus noch nicht anbietet. In diesem Fall wird Ihnen der ScreenMode-Requester von Flyin'High nur den PAL-Modus zur Auswahl anbieten.
Dann müssen Sie sich solch einen Bildschirmmodus selbst erstellen. Auf CyberGfx-Systemen heißt das Programm für diesen Zweck "CGXMode", auf Picasso96-Systemen ist es "Picasso96Mode". Sie müssten in Ihrer Prefs-Schublade zu finden sein. Lesen Sie deren Dokumentation um herauszufinden, wie man seinen eigenen Bildschirmmodus erstellt.


Bitte merken Sie sich, das Flyin'High nur solche Bildschirmmodi akzeptieren wird, die folgenden Spezifikationen entsprechen:

Breite  320
Höhe    256
Farben  256, mit einem "look-up-table", kein "high-color" oder "true-color".

@endnode
@node general_it "Flyin'High V1.2 - Informazioni generali"

Molte persone si sono lamentate della disponibilità di Flyin'High solo per AGA. Avevano ragione, ma quando abbiamo progettato Flyin'High pensavamo a un gioco che sfruttasse al meglio gli Amiga "piccoli". Ora i tempi sono cambiati, e anche il mio Amiga. Quando ho comprato la mia scheda grafica volevo ancora giocare a Flyin'High, ma sembrava troppo difficile farlo funzionare su CyberGraphX o Picasso96.
Tempo fa ho iniziato a lavorare su "Phoenix", che era stato progettato sin dall'inizio per funzionare su AGA, CyberGraphX e Picasso96 - e su macchine più potenti. Ho scritto molto codice, e ho realizzato che gran parte di esso sarebbe stata utilizzabile per una versione di Flyin'High più compatibile. Bene, eccola qua.

A chi conviene usarla? A chiunque abbia una scheda grafica e a chiunque avesse problemi a far funzionare Flyin'High sul proprio sistema. Se eravate soddisfatti di Flyin'High sul vostro Amiga AGA, allora non dovreste installare questa versione.

Se installate questa versione dovete tener presente che, rispetto alla versione originale di Flyin'High:
· avete bisogno di più memoria (8 Mb)
· dovete aspettare un po' di tempo (cica 1 minuto e mezzo) all'avvio di Flyin'High (perché svolga alcuni calcoli necessari)
· le animazioni su Picasso96 somigliano più a uno slide-show.

Penso che si possano avere problemi usando l'emulazione Picasso96 su un sistema CyberGraphX.

Ringraziamo Marco De Vitis per la traduzione italiana.



Markus Pöllmann
@endnode
@node howtouse_it "Flyin'High V1.2 - Come usarla"

Perché questa versione possa essere installata, la versione originale di Flyin'High deve essere presente sul vostro disco rigido.

Flyin'High ha bisogno di uno schermo con una larghezza di 320 pixel e un'altezza di 256 pixel, a 256 colori. È molto probabile che la vostra installazione di CyberGraphX o Picasso96 non presenti un simile modo schermo. In questo caso la finestra di scelta del modo schermo di Flyin'High vi mostrerà solo un modo PAL. Se questo accade, dovrete creare voi stessi un modo schermo. Per i sistemi CyberGraphX il programma per fare ciò si chiama "CGXMode", per i sistemi Picasso96 è "Picasso96Mode". Siete pregati di fare riferimento alla loro documentazione per capire come creare un vostro modo schermo.


Ricordate che l'unico modo schermo consentito è quello che rispetta le seguenti specifiche:

Larghezza  320
Altezza    256
Colori     256, con una "look-up-table", non "high-color" né "true-color".

@endnode


