@DATABASE PGS.SUB
@(C) 1995 Soft-Logik Publishing Corporation
@INDEX PageStream3:Help/PGS.INA/MAIN



@remark *** SUBJECTS HELP FILE ***

@node ARTI "Articles"

@{FG Highlight}Articles@{FG Text}

Article is the term used to describe the text in a text frame, series of
frames, or frameless text object. When you choose the @{"Select All" link PageStream3:Help/pgs.edi/SELA} command,
all the text in an article will be selected.
@toc PageStream3:Help/PGS.HEL/MAIN
@endnode

@node ASRA "Aspect Ratio"

@{FG Highlight}Aspect Ratio@{FG Text}

This term is used to describe the ratio of the horizontal size of
something to its vertical size. For example, a box 2 inches wide and 1
inch high has an aspect ratio of 2:1.

The numerical aspect ratio is not usually of concern, but the ability to
maintain the aspect ratio of an object is important. For example, when
resizing a picture, you would not normally want to distort it by resizing
it proportionally more horizontally than vertically.

You can resize an object proportionally and maintain its aspect ratio
when resizing or pasting by holding down a Shift key while @{"dragging" link DRAG} the
mouse. If you do not hold down the Shift key, you will resize or paste
the object asymmetrically (anamorphically).

If you want to prevent an object from ever being resized asymmetrically,
you can toggle on the Proportional Scaling option for the object by
selecting it and choosing the @{"Edit" link PageStream3:Help/pgs.obj/EDIT} command.
@toc PageStream3:Help/PGS.HEL/MAIN
@endnode

@node ATTR "Text Attributes"

@{FG Highlight}Text Attributes@{FG Text}

All text entered in PageStream has attributes associated with it.
Attributes are the font, type style, size, color and formatting of the
text. PageStream has default text attributes when you start the program.
The default attributes become the current attributes, which you can
change at any time.

You can change the attributes for existing text by selecting the text and
then choosing any text attribute command from the @{"Type" link PageStream3:Help/pgs.typ/MAIN} menu. To change
all the attributes at once, choose the @{"Attributes" link PageStream3:Help/pgs.typ/ATTR} command.

You can change the attributes for new text by choosing any text attribute
command when text is not selected.
@toc PageStream3:Help/PGS.HEL/MAIN
@endnode

@node DRAG "Dragging the mouse"

@{FG Highlight}Drag@{FG Text}

Hold down the left mouse button, then move the mouse. Release the left
mouse button to stop dragging.

Dragging is commonly used to move, resize and manipulate objects, and to
select text.

If you hold down a Shift key while resizing an object or pasting a
graphic, its @{"aspect ratio" link ASRA} will be maintained.
@toc PageStream3:Help/PGS.HEL/MAIN
@endnode

@node PGSP "Page Spreads"

@{FG Highlight}Page Spreads@{FG Text}

Page Spreads are groups of pages which are linked together horizontally
or vertically to allow objects to lie across multiple pages.

Spreads are treated as single pages for viewing and printing. When you go
to a page, regardless of the page number you choose, the entire spread
including that page will be displayed if applicable. For example, if
pages 6, 7 and 8 are a page spread and you move to page 8, the page 6-7-8
spread will be displayed, although page 8 will be the current page.

The concept of a current page when all pages in a spread are visible and
editable is important, because each page in the spread can use a
different @{"master page" link PageStream3:Help/pgs.doc/MSPG}, grid and guides. Since each page in a spread can
have a different master page, a spread can be made up of pages of
different sizes.

Page spreads are created and broken up with the @{"Page palette" link PageStream3:Help/pgs.set/PAPA} command.
@toc PageStream3:Help/PGS.HEL/MAIN
@endnode

@node READ "Recommended Reading"

@{FG Highlight}Recommended Reading@{FG Text}

For information on subjects related to PageStream, the following sources
are recommended:
@{code}
@{FG Highlight}ARexx:@{FG Text}

Fast Guide to Arexx
  Vidia, 1992.
  A quick reference guide for ARexx.

The ARexx Cookbook
  by Merill Callaway. Whitestone, 1992. ISBN 0-9632773-0-8.
  A good tutorial guide to ARexx.

User's Guide--ARexx
  by Isabelle Vesey and Robert Stephenson Weird.
  Commodore Electronics Limited, 1992. P/N: 368759-01.
  A good reference to ARexx commands.


@{FG Highlight}Font Technology:@{FG Text}

Adobe Type 1 Font Format, Version 1.1
  by Adobe Systems Inc. Addison-Wesley Publishing Company, Inc., 1990.
  ISBN 0-201-57044-0.
  A technical description of the PostScript Type 1 font format.

PostScript Language Reference Manual, 2nd Edition
  by Adobe Systems Inc. Addison-Wesley Publishing Company, Inc., 1990.
  ISBN 0-201-18127-4.
  A technical description of the PostScript language.

Intellifont Scalable Typeface Format
  Agfa Corporation, 1991.
  A technical description of the Compugraphic Intellifont format.


@{FG Highlight}Design Tips@{FG Text}

Collier's Rules for Desktop Design and Typography
  by David Collier. DeCode Design, 1991. ISBN 0-201-54416-4.
  A good quick reference guide.

Desktop Publishing by Design
  by Ronnie Shushan & Dan Wright. Microsoft Press, 1989.
  ISBN 1-55615-134-9.
  If you only buy one book, buy this one.

Looking Good in Print
  by Roger C. Parker. Ventana Press Inc., 1988. ISBN 0-940087-05-7.
  A solid book for novices.

Roger C. Parker's One Minute Designer
  by Roger C. Parker. Que, 1993. ISBN 1-56529-216-2.
  Practical rules for page design.

The Complete Scanner Handbook for Desktop Publishing, PC Edition
  by David D. Busch. Dow Jones-Irwin, 1990. ISBN 1-55623-340-X.
  Everything you ever wanted to know about scanning.

The Desktop Publisher's Idea Book
  by Chuck Green. Bantam Books, 1993. ISBN 0-553-37173-8.
  How to design many types of documents.
@{body}
@{body}
@toc PageStream3:Help/PGS.HEL/MAIN
@endnode

@node REQR "System Requirements"

@{FG Highlight}System Requirements@{FG Text}
@{code}
To use PageStream 3.0, BME 2.0 and PageLiner 2.0, you must have at least:

Computer:  any Amiga model.

Memory:    3MB total RAM (at least 512K chip RAM),
           4MB RAM or more is highly recommended.

Drives:    hard drive with 3.6 to 12.4MB free space.

Workbench: AmigaDOS 2.04 or higher.

Printer (optional):
- Epson dot matrix/ink jet or compatible;
- Hewlett Packard DeskJet or compatible;
- Hewlett Packard LaserJet or compatible;
- Fargo Primera;
- PostScript laser printer, imagesetter or device;
- or any Preferences compatible printer.
@{body}
@{body}
@toc PageStream3:Help/PGS.HEL/MAIN
@endnode

@node MEMO "Hints for Saving Memory"

@{FG Highlight}Hints for Saving Memory@{FG Text}
@{code}
@{FG Highlight}If you don't need to load or save:@{FG Text}

·Pantone® colors*: delete SoftLogik:Colors/#?

·ProPage documents: delete SoftLogik:Filters/ProPage#?

·PageStream2® documents: delete SoftLogik:Filters/PageStream2#?

·MacPaint® pictures: delete SoftLogik:Filters/MacPaint.gfilter

·PCX pictures: delete SoftLogik:Filters/PCX.gfilter

·GIF pictures: delete SoftLogik:Filters/GIF.gfilter

·TIFF pictures: delete SoftLogik:Filters/TIFF.gfilter

·BMP pictures: delete SoftLogik:Filters/BMP.gfilter

·Art Expression® drawings: delete SoftLogik:Filters/ArtExpression.gfilter

·ProDraw drawings: delete SoftLogik:Filters/ProDraw.gfilter

·Freehand EPS drawings: delete SoftLogik:Filters/Freehand.gfilter

·Excellence® text: delete SoftLogik:Filters/Excellence.tfilter

·Final Writer® text: delete SoftLogik:Filters/FinalWriter.tfilter

·ProWrite text: delete SoftLogik:Filters/ProWrite.tfilter

·Microsoft® Word text: delete SoftLogik:Filters/Word.tfilter

·WordPerfect® text: delete SoftLogik:Filters/WordPerfect.tfilter

·Wordworth® text: delete SoftLogik:Filters/Wordworth.tfilter

@{FG Highlight}if you don't need to use:@{FG Text}

·ProPage text codes: delete SoftLogik:Engines/ProPage.codes

·PageMaker® text codes: delete SoftLogik:Engines/PageMaker.codes

·XPress® text codes: delete SoftLogik:Engines/XPress.codes

·French: delete SoftLogik:Engines/Fran#?

@{FG Highlight}If you don't have a:@{FG Text}

·Hewlett-Packard compatible laser or inkjet printer: delete SoftLogik:Printers/HP.printer

·Epson compatible printer: delete SoftLogik:Printers/Epson.printer

·PostScript printer**: delete SoftLogik:Printers/PostScript#?
@{body}
@{body}
*  Note: removing the Pantone® color libraries will save 100K of memory!

** Note: you can also delete the SoftLogik:Printers/PPD directory if you
don't have a PostScript printer, but this will only save you hard drive
space, not memory.
@endnode

@node MAIL "Mail MERGE"

@{FG Highlight}Mail Merge@{FG Text}

PageStream's mail merge feature allows you to personalize documents such
as letters so that each copy has customized names, addresses, phone
numbers, etc. You can use this information in the address block of a
letter, or anywhere within the text.

Mail merging has three steps: creating the data, inserting the data
variables, and merging the data with your document.

Data can be created in any text editor or database. The mail merge macro
included with PageStream3 assumes that the data was exported as ASCII
text from Datastore, but most databases and text editors can create
compatible files. The data must include a header on the first line of the
file that defines the field names. The fields must be tab delimited
(separated by a tab) and the records must be separated by a linefeed. The
following is an example of a three record data file: (tabs are
represented here with · characters.)
{code}
Address            City         Name          State  ZipCode
315 Consort Drive··St. Louis····Joe User······MO·····63011
7178 Sonoma Way····Los Angeles··Helen Hudson··CA·····95011
1234 Howe St.······Vancouver····Fred Stone····BC·····V9N 5N1
{body}
Once the data has been generated, create your document and then choose
the Mail Merge macro.* A file requester will open to select the ASCII
data file. Select the file and click on Ok. This will create user
variables for the document. You are now ready to insert your data
variables.

* Mail Merge will be in the Macros menu if you have the default
PageStream3.macros file loaded. If you have removed this macro, choose
Macros/Execute ARexx Macro and then select MailMerge.rexx from the file
requester. ARexx must be loaded prior to starting PageStream.

Variables are the data in your document which will be changed for each
record of data. To insert a variable into your document, choose the
@{"Insert Variable » User String" link PageStream3:Help/PGS.INSE} command. This will open a requester listing
the variables for your document. The variable names will match the field
names in your data file. Choose the variable to insert and click on
Insert. Repeat as required.

When you are ready to print your document, choose Mail Merge again from
the Macros menu. This will change the value of the variables to match the
first record and then will print the document. It will repeat this until
the document has been printed for each record.
@toc PageStream3:Help/PGS.HEL/MAIN
@endnode

