@DATABASE Befehle.inc
@NODE Befehle

Missionen
=========
Aus den folgenden Missionen muß sich der Mitspieler eine 
aussuchen. Diesen Charakter verkörpert er dann im Spiel.

Imperator
---------
Diese Mission ist einfach zu erklären. Friedliche und 
weniger friedliche Planeten werden erobert und unterworfen. Je 
größer das Reich, desto mächtiger der Imperator! Doch andere 
Sternenreiche und die Rebellen versuchen es Dir so schwer 
wie möglich zu machen.
Beispiel: Darth Vader


Heilsbringer
------------
Anfänglich sind sie ausgestattet mit einem einzelnen 
Raumschiff. Mit primitiven Tricks oder ähnlichen versuchen sie 
sich als Gott aufzuspielen. Fällt die Bevölkerung darauf 
hinein, kann der Heilsbringer hier herrschen ähnlich wie ein 
Diktator.
Beispiel: Der Jedimeister C´boath


Eroberer
--------
Diese Mission ist praktisch identisch mit der des Imperators. 
Der Hauptunterschied liegt in der Tatsache, daß der Imperator 
das alte Imperium wiedererrichten will und der Eroberer ein 
lokales Herrscher ist, der sein eigenes Sternenreich aufbauen 
will. Mit seiner Streitmacht, die aus einem zusammengewürfelten 
Haufen besteht, versucht er sich über das All auszubreiten. 
Eroberte Welten werden unterjocht und ausgebeutet.


Rebell
------
Sie kämpfen für Frieden und Gerechtigkeit innerhalb der 
Galaxis. Förderer finden sie bei den Reichen und Adligen auf 
den unterdrückten Planeten. Von ihrem Geld versucht der Rebell 
ein Streitmacht für das Gute zu Errichten. Mit ihrer Hilfe will 
er unterjochte Planeten befreien. 
Beispiel: Luke Skywalker


Mitglied in der Neuen Rebublik
------------------------------
Eine besondere Form der Diktatoren, man verfolgt ähnliche 
Ziele, Expansion. Doch die eroberten Planeten werden besser 
behandelt, als bei den Diktatoren. Man sieht sich mehr als 
Befreier von den alten Strukturen und läßt den Planeten eine 
größtmögliche Freiheit, das Einzige was man will sind Steuern. 
Die Mitglieder den Neuen Rebublik stehen sich im Ernstfall zur 
Seite und Unterstützen die Rebellen im Kampf gegen das Böse.
Beispiel: Mon Mothma


Sternengarde
------------
Eine mögliche Einrichtung der "Neuen Republik". Um sich noch 
besser vor Feinden zu schützen wurde die Sternengarde ins 
Leben gerufen. Alle Planeten der "Neuen Republik" bezahlen eine 
Art Steuer um diese Truppen zu finanzieren. Auch ist es 
denkbar, daß die Schiffe der Sternengarde von der "Neuen 
Republik"gestellt werden. Die Hauptaufgabe der Sternengarde 
ist der Schutz der "Neuen Republik" gegenüber Angreifern. So 
patroliert sie bei deren Planeten und hilft ggf. bei 
Angriffen. Ausgangssituation sind mehrere Jäger auf einem 
"Neuen Republik"-Planeten. Die Sternengarde kann von einem 
neuen Mitspieler übernommen werden oder nebenher von einem 
Mitglied gesteuert werden. Hauptsächlich wir die Sternengarde 
aber von einem ehemaligen Rebellen oder Söldner übernommen.
Einkommensberechnung: Steuer von "Neue Republik"-Planeten (liegt 
im Ermessen der Mitglieder), minus Kosten.


Syndikat
--------
Ein Zusammenschluß von Schmugglern, Kopfgeldjägern und Söldnern.
Das Syndikat verkauft alles was man woanders nicht kriegen 
kann, Informationen, Raumschiffe (vorzüglich ES-8-Typen), etc. 
Das Syndikat verfügt außerdem über Spione und viele 
Aufklärungsdroiden. Es wird mit jedem zusammengearbeitet der 
Geld hat.
Beispiel: Jabba the Hutt


Rassen
======
Allgemein kann man sagen, daß die Menschen die beherrschende 
Rasse im All ist, überall kann man sie treffen. "Your own 
Chapter"  unterscheidet daher nur zwischen Menschen und 
Ureinwohnern. Der Spieler kann sich selbst aber eine Rasse aus 
der Triologie aussuchen, z.B. Wookiees, Mon Calamari, ...


Befehle
=======
Hat der Spieler seine Ausgangssituation erhalten, kann er 
auch schon loslegen. Er schreibt seine Befehle an den Master. 
Wobei pro Runde für die Anzahl der Befehle keine obere Grenze 
gilt, außer der Spielleiter setzt eine solche fest.


Alarmstufen
-----------
Für verschiedene Situationen gibt es verschiedene Alarmstufen.

Befehl: "Alarmstufe B für Planet 3."


Aufklärung
----------
Um die Lage auf den einzelnen Planeten zu erforschen, ist es 
angebracht, zuerst einen Aufklärungsdroiden zu dem Planeten 
zu schicken. Diese funkt folgende Facts zu Deinem Hauptquartier: 
- Evolutionsstufe des Planeten
- Art des Planeten
- Anzahl der Raumschiffe
- Rasse der Bewohner
- eventuell den Herrscher
Beherbergt der Planet Kampfschiffe, so zerstören diese 
automatisch den Droiden, wenn man Glück hat, kann diese aber 
vorher noch ihre Daten senden. Sind keine Raumschiffe im 
Orbit, bleibt der Roboter automatisch im Orbit und wartet auf 
weitere Befehle.

Befehl: "Schicke Aufklärungsdroiden von Planet 2 zu Planet 3."

Anmerkung:Pro Runde kann man maximal 5 Probedroiden 
losschicken! Der Droid funkt nur einmal bei Erreichen des 
Planeten Infos zum Spieler, danach bleibt er im Orbit und 
wartet auf neue Befehle. Will der Spiel trotzdem später 
wieder Infos vom Droiden, so muß er ihn wieder ansprechen 
(Befehl: "Infos von PD auf Planet 3."). Außnahme ist, wenn der 
Planet angegriffen wird.


Aufklärungsdroiden eingraben
----------------------------
Zur besseren Tarnung des Droiden, besteht auch die Möglichkeit, 
daß dieser sich fast vollständig in die Planetenoberlfäche 
eingräbt, so daß nur noch ein kleiner Teil des Droiden zu 
sehen ist. Dies hat zur Folge, daß die Wahrscheinlich des 
Entdeckens minimiert wird.

Befehl: "Droid bei Planet 6 eingraben."

Anmerkung: Bevor der Droid wieder weitergeschickt werden kann, 
muß er sich natürlich erstmal wiederausgraben.

Befehl: "Droid bei Planet 6 ausgraben."


Deaktivierte Schiffe übernehmen (nur mit Raumschiffkatalog III)
-------------------------------
Es müssen sich neben den deaktivierten Schiffen mind. ein 
Schiff des Spielers mit einem Andocksystem oder 
Traktorstrahlprojektor befinden.

Befehl: "Deaktivierte Schiffe um Planet 3 übernehmen."


Forschen
--------
Hat man ein Labor auf einem ES7- oder ES8-Planeten, kann man 
hier forschen, um später einen besseren Tech-Level zu 
erreichen. Forschen kostet pro Runde 100CR.

Befehl: "Forschen."


Geld überweisen
---------------
Dies ist meistens bei Geschäften mit Söldnern oder dem Syndikat 
wichtig.

Befehl:"Überweise Darth Vader 120CR."


Information (allgemein)
-----------------------
Jeder Spieler verfügt über ein Computersystem. Über dieses kann er
wertvolle Informationen erlangen. Leider ist das Computersystem 
jedoch nicht so informativ wie das Spionagenetz des 
Galaktischen Syndikats.

Befehl: "Info über Imperator Zoar."


Informationen (für Galaktisches Syndikat)
-----------------------------------------
Das Galaktische Syndikat verfügt über ein weitreichendes 
Spionagenetz. Man kann deshalb versuchen über Spieler, 
Planeten, etc. Informationen herauszukriegen. Dies ist aber nur 
dem Syndikat möglich.

Befehl:"Info über Planet 12."

Befehl:"Info."

So gelangen allgemeine Gerüchte zu ihm.


Lobors abreissen
----------------
Hat man den maximalen Tech-Level 3 erreicht, werden die 
Labors nutzlos. Um Platz für z.B. eine weitere Fabrik zu 
schaffen kann man die Labors wieder abreißen. Dies kostet 50CR.

Befehl: "Labor abreissen."


Labors bauen
------------
Für die Verbesserung des Tech-Levels ist die Forschung in 
großen Laborkomplexen notwendig. Diese Labors kann man auf 
Planeten mit mindestens ES7 errichten. Sie brauchen den 
selben Platz wie eine Fabrikanlage und zählen deshalb auch zu 
dem 10-Fabriken-Limit. Kosten: 100CR.

Befehl: "Labor bauen."


Mission ändern
--------------
Man muß natürlich nicht immer bei seiner ursprünglich 
gewählten Mission bleiben. Es ist durchaus denkbar, daß ein 
Mitglied der Neuen Republik einen Verrat begeht und Eroberer 
wird, daß ein Rebell so mächtig wird, daß er sich der 
Republik anschließt oder das ein Imperator bekehrt wird und 
sich der guten Seite der Macht anschließt. Es gibt hier eine 
Fülle von Möglichkeiten. Wenn Du deine Mission ändern willst, 
setzte Dich mit dem Spielleiter in Verbindung. Näheres hierzu 
auch im Buch der Missionen. 


Mitteilungen schreiben
----------------------
Jeder Spieler besitzt die Möglichkeit, mit anderen Spielern 
Kontakt aufzunehmen. Dies ist aber nur möglich, wenn der a
ndere Spieler namentlich bekannt ist, z.B. durch Aufklärung 
oder Raumschlachten.
Die Nachricht erhält der andere Spieler in der Zugauswertung.

Befehl: "Schreibe an Darth Vader: Das Imperium wird vernichtet!"

Anmerkung:Bei längeren Mitteilung schreibt bitte die Message 
auf einen Extrazettel, den dann der entsprechende Mitspieler 
zugesandt kriegt.


Planeten bekehren
-----------------
Ein Heilsbringer befindet sich im Orbit des Planeten. Das 
Raumschiff klickt sich in das planetarische Kommunikationsnetz 
ein und versucht die Bevölkerung zu seinem Glauben zu bekehren.

Befehl: "Bekehre Planet 71."


Planeten besiedeln
------------------
Ähnlich der Kolonisation, aber das Besiedeln ist friedlich und geht
daher nur auf Planeten mit ES 0. Nach dem Befehl ist der Planet 
mit der eigenen Rasse bewohnt, er hat dann ES 1.

Befehl:"Besiedeln Planet Nr.3."

Anmerkung: Das Besiedelen von Gasplaneten ist menschlichen 
Rassen nur mit Hilfe einer Wolkenstadt möglich.


Planeten erobern
----------------
Man schickt die Raumschiffe wie oben erwähnt 
zu den ausgesuchten Planeten. Dem Befehl 
wird dann einfach der Zusatz des Eroberns 
drangehängt.

Befehl:"Schicke 20 X-Wings von Planet 2 zu              Planet 3 und erobere diesen."

Befinden sich Kriegsschiffe im Orbit 
eines freien Planeten, ohne daß sie den 
Befehl zum Erobern gekriegt haben, gilt der 
Planet weiterhin als frei. Die Schiffe 
befinden sich dann ganz friedlich im Orbit.
Sollen feindliche Schiffe nicht vernichtet, 
sondern nur deaktiviert werfen, so muß dies 
dem Befehl hinzugefügt werden, z.B. 
"Schicke 20X-Wing1 von 2 zu 3 und erobere 
diesen (nur deaktivieren)".
Wenn von einem eroberten Planeten die Schiffe wieder abgezogen 
werden, bleibt dieser trotzdem immernoch im Besitz des Spielers. 


Planeten kolonisieren
---------------------
Natürlich kann man auch die ursprüngliche Planetenbevölkerung 
auch durch die eigene Rasse ersetzen. Dafür muß der Planet erst 
auf ES 1 gescrapt werden. Danach wird der Planet kolonisiert.

Befehl: "Kolonisiere Planet 2."

Durch diesen Befehl werden die Ureinwohner vernichtet, deshalb 
wird das Kolonisieren geächtet und kann mit dem Auschluß aus 
der Neuen Rebublik und/oder weiteren Aktionen bestraft werden.


Planeten taufen
---------------
Bist Du der erste Spieler, der einen Planeten erobert, hast Du 
das Privileg, den Planeten zu taufen,

Befehl: "Taufe Planet 23 auf: Tantooine."


Planet unter Quarantäne stellen
--------------------------------
Im Laufe des Spiels kann man auf Planeten stoßen, in dessen 
Orbit man sich besser nicht befinden sollte. Durch eine Einigung, 
die noch aus der Zeit der alten Republik stammt, haben sich 
alle Spieler verpflichtet, solche Planeten unter Quarantäne 
stellen zu lassen. Dies macht man  mit einem kleinen Sender 
im Orbit.

Befehl: "Stelle Planet 77 unter Quarantäne wegen instabilem Orbit."


Planeten untersuchen
--------------------
Hat noch kein anderer Mitspieler den Planeten untersucht, kann 
der Spieler dies tun. Bevor der Planet in das Sternenreich 
eingegliedert wird, kann man mit Hilfe modernster Techniken 
untersuchen, ob sich irgendwelche Schätze hier verbergen.

Befehl: "Untersuche Planet 23."


Planet upgraden
---------------
Im Allgemeinfall gilt, je höher die ES eines Planeten, desto 
besser für seinen Besitzer, man verdient mehr Geld und kann auf 
dem Planeten Schiffe bauen. Hat man genug Geld, kann man seine 
Planeten auf die nächsthöhere ES upgraden, jedoch nur einmal
pro Spielrunde.
von  auf  Kosten
1    2    200
2    3    250
3    4    550
4    5    900
5    6    1100
6    7    2000
7    8    3000

Befehl: "Planet 3 upgraden."


Planet scrapen
--------------
Braucht man auf die Schnelle Geld, um z.B. seine Schulden zu 
Bezahlen oder Raumschiffe für eine Abwehrschlacht zu bauen, gibt 
es die Möglichkeit, Planeten zu scrapen. Dies ist der 
umgekehrte Vorgang vom Upgraden, auch dies ist nur einmal 
pro Spielrunde möglich.
von  auf  Ertrag
8    7    1500
7    6    1000
6    5    550
5    4    450
4    3    270
3    2    130
2    1    100

Befehl: "Planet 20 scrapen."


Raumflotte zurückziehen
-----------------------
Befindet sich eine Flotte im Anflug auf einen Planeten und 
man erfährt, daß dieser Planet eine überlegene Flotte besitzt, 
kann man der Flotte befehlen sofort bei Ankunft wieder 
zurückzukehren. Trotzdem wird die  Flotte eine Runde lang 
angegriffen."

Befehl: "Flotte im Anflug auf 3 zurückkehren."


Raumflug
--------
Die Raumflotte muß sich vorher im Orbit eines beliebigen Planeten 
befinden. Dann wird sie zu dem gewünschten Planeten geschickt.
Die Schiffe bewegen sich mit einer Geschw. von 10LJ/R.
  
Befehl: "Schicke 2 A-Wings, 4 B-Wings von Planet 10 zu Planet               17."
           
(Gehören beide Planeten (10,17) dem 
Mitspieler, so werden die Raumschiff nur 
auf einen anderen Planeten verlegt.)

Beachte: Raumjäger ohne Hyperdrive sind 
beim Raumflug auf die Begleitung eines 
Combat Starships angewiesen. Siehe 
Raumschiffbeschreibungen für die 
Jägerkapazitäten der einzelnen Kampfschiffe.


Raumschiffe bauen
-----------------
Die Raumschiffe sind sofort fertig und können daher in einer 
Runde gebaut und sogleich zugeschickt werden.

Befehl: "Baue 23 X-Wing auf Planet 55."

Anmerkung: Pro Runde können in einer Fabrik auf einem 
ES7-Planeten maximal 100Jäger oder 10Kampfschiffe gebaut 
werden. Auf einem ES8-Planeten sind es pro Runde und pro 
Fabrik 150Jäger, 15Kampfschiffe oder 1 ES8-Großkampfschiff. 
Es erspart dem Spielleiter übrigens eine Menge Zeit, wenn der 
Spieler noch die Gesamtkosten für den Raumschiffbau 
mitausrechnet. Nach vorheriger Absprache mit dem Mitspieler 
kann man Schiffe auch auf anderen Spielerplaneten bauen, z.B. 
ist dies innerhalb der Neuen Republik denkbar oder zwischen 
Eroberern und Syndikaten.


Raumschiffe stillegen
---------------------
Werden verschiedene Raumschiffe derzeit nicht mehr gebraucht, 
gibt es die Möglichkeit, diese vorübergehend stillzulegen. Dies 
hat den Vorteil, daß für diese Schiffe keine laufenden Kosten 
mehr gezahlt werden müssen.

Befehl: "10 X-Wing auf Planet 23 stillegen."


Raumschiffe verkaufen/kaufen
----------------------------
Sind sich 2 Spieler einig über Art, Anzahl und Preis fuer 
Raumschiffe können sie untereinander verkauft oder gekauft 
werden. Die Raumschiffe müssen sich im Orbit eines Planeten 
des Verkäufers oder eines neutralen Planeten befinden. Die 
beiden Spieler müssen in der gleichen Runde die Befehle 
geben. Danach fliegen die Schiffe zu einem Planeten des Käufers 
und das Geld wird transferiert.

Befehl des Verkäufers: "Verkaufe 10 X-Wing auf Planet 2 fuer                               Gesamtpreis von 90 Credits an EL SOLOS."


Raumschiffe vernichten
----------------------
Aus irgendwelchen Gründen will der Spieler seine Schiffe 
schnell loswerden. Dies kann man durch eine einfache 
Sprengung erreichen. Diese kostet 1CR pro Schiff.

Befehl: "Vernichte 2X-Wing bei Planet20."


Raumschiffe wieder in Betrieb nehmen
------------------------------------
Im Ernstfall können die stillgelegten Schiffe natürlich wieder in
Betrieb genommen werden. Allerdings braucht dies 2 Runden Zeit.
Werden in Runde 7 Schiffe wieder in Betrieb genommen, stehen 
diese dem Spieler erst wieder in Runde 9 zur Verfügung.

Befehl: "10 X-Wing auf 23 in Betrieb nehmen."


Raumschiffabrik abreissen
-------------------------
Da man pro Planet nur 10 Fabriken bauen kann, ist es manchmal 
auch nützlich, alte Fabriken abzureißen. Der Abriß kostet 100CR 
pro Werft.

Befehl: "X-Wing-Farbik auf Planet 65 abreissen."


Raumschiffabrik bauen
---------------------
Bevor man einen Raumschifftyp das erste Mal baut, muß man 
vorher die Fabrikanlage dafür errichten. Der Bau dauert eine 
Spielrunde und kosten ein Vielfaches des Preises des zu 
bauenden Raumschiffes.

Befehl:"Baue XW-Fabrik auf Planet 65."


Anmerkung: Diese Befehle sind meistens ausreichend für das Spiel,
doch wenn der Spieler irgendetwas ausgefallenes machen will, 
kann man natürlich auch dem Spielleiter freie Texte schreiben.



@ENDNODE

