@DATABASE Einleitung.inc
@NODE Einleitung


Star Wars - Your own Chapter
****************************

Einleitung
==========
Willkommen zu "Star Wars - Your own Chapter"! Diese Edition 
versetzt den Spieler in die phantastische Welt von George Lucas. 
Je nach belieben kann man auf Rebellenseite kämpfen oder auch 
sein eigenes Imperium aufbauen. Zeitlich ist dieses Spiel nach 
´The Return of the Jedi´ angesiedelt. Das große Imperium ist 
zerschlagen und die ´Neue Republik´ noch nicht wieder voll 
errichtet.
Aber was ist überhaupt ein Postspiel? Alles fing vor Jahren mit 
dem Fernschach an. Zwei Spieler konnten nicht zusammen an einem 
Ort sein, so waren sie gezwungen, ihre Spielzüge aufzuschreiben 
und sie sich gegenseitig zuzuschicken. "Star Wars - Your own 
Chapter" gehört der nächsten Generation von Postspielen an. 
Mehrere Spieler schicken gleichzeitig ihre Spielzüge an den 
Master (Spielleiter). Dieser wertet diese aus und schickt 
die Ergebnisse wieder an die Spieler. Eine Spielrunde dauert 
daher immer etwas, doch dafür wird man mit einem hohen 
Spielwert belohnt. Niemand kann genau wissen, welche Mission 
der andere Spieler verfolgt, welche Planeten er besitzt oder 
welche Allianzen er eingegangen ist. Der besondere Reiz liegt 
auch darin, daß man nicht die richtigen Namen der Mitspieler 
kennt, es existieren daher nur ein Darth Vader und nicht ein 
Fritz Müller! Das Spielgeschehen lebt und stirbt aber auch von 
der Phantasie des Masters. Er kann Mastercharaktere leiten, 
Fallen verstecken oder auch versteckte Informationen geben. Wie 
in einem Rollenspiel hat er fast allmächtige Macht, die er 
vorsichtig und weise benutzen sollte!

Spielstart
----------
Zum Spieleinstieg muß sich jeder neue Mitspieler einen 
Charakter aussuchen. Hierbei werden folgende Informationen 
benötigt: Name, Rasse, Mission. Danach erhält man vom Master 
die Ausgangssituation mit einer Sternenkarte und kann sofort 
mit seinen Befehlen loslegen.



@ENDNODE


