@DATABASE Info.inc
@NODE Info


Star Wars - Your own Chapter
****************************

Technisches:
- Missionen, die zur Auswahl stehen:
  - Imperator (Beispiel: Palpatine)
  - Eroberer
  - Heilsbringer (Beispiel: C´boath)
  - Rebell (Beispiel:Luke Skywalker)
  - Sternengarde
  - Neue Republik (Beispiel: Mon Mothma)
  - Syndikat (Beispiel:Jabba the Hutt)
  - Söldner (Beispiel: Boba Fett)
- Rassen: Alles was bei Star Wars so rummläuft!
- Befehle: ca.30, plus die Möglichkeit eigene Befehle zu kreieren!
- Raumschiffe: 12 Schiffe aus der Triologie (+weitere auf Wunsch)

Während des Spiels versucht man seine persönliche Mission zu 
erfüllen, da alle Spieler dies versuchen. Kommt es mit der Zeit 
zu Konflikten (z.B.: Rebellen, Imperium) oder aber es kommt zu 
Pakten, die öffentlich aber auch geheim sein können. Im Grunde 
sehen die Missionen wie in den Filmen aus, es geht um Freiheit, 
Macht, Geld oder alles zusammen.

Kosten: 
Der Spieleinstieg kostet DM10.-, dafür gibts die deutschsprachige 
Anleitung, die Sternkarte und drei Spielzüge gratis. Danach kostet 
jeder Spielzug DM2.50.- Bearbeitungsgebühr. Eine Spielrunde dauert 
3 Wochen . Jeder Spielzug wird mit Computer ausgewertet und der 
Spieler kriegt einen Bogen mit allen Infos über Planeten, 
Raumschiffe, Kapital und ähnlichem. 

Für DM 10.- kann man auch das komplette Spielsystem 
(Spieleranleitung, Masterbook, Sternkarte) erwerben.



Falls noch Fragen sind nur raus damit!

Patrick Henz    
Martinstr.15     
52062 Aachen
Germany

@ENDNODE


