@DATABASE Jedi.inc
@NODE Jedi


STAR WARS - Your own Chapter - The Jedi Academy
***********************************************
                     Copyright by Patrick  Henz


Einleitung
**********
Jeder Charakter hat die Möglichkeit Jedifähigkeiten zu 
erwerben. Mit diesen hat er dann im Spiel Vorteile gegenüber 
Charakteren ohne diese Fähigkeiten. 


Spielvorbereitung
*****************
Der Spielleiter legt einen Planeten in der Sternkarte fest, 
auf welcher sich die Jedi-Academy befinden soll. Dieser 
Planet sollte eine ES von kleiner 7 haben und unabhängig sein. 
Im Laufe der Zeit ist es aber auch durchaus möglich, daß der 
Planet von einem Spieler erobert werden kann. Dann liegt es an 
ihm, ob auch andere Spieler Zugang zu dieser Schule haben, oder 
ob es fortan eine Privatschule wird. 


Spiel
*****
Um Zugang zu der Academy zu Erlangen, muß sich mindestens 
ein Schiff des Spielers im Orbit befinden. 

Befehle
=======
Es ist ein langer und schwieriger Weg, ein ausgebildeter Jedi 
zu werden. Allerdings ist er für alle gleich, Geld ist hier 
kein Faktor. Es gibt drei Ausbildungsstufen:
1) Jedianfänger: Die ersten Fähigkeiten sind ausgebildet. 
Allerdings fehlt noch eine richtige Kontrolle über sie. 
(Beispiel: Luke Skywalker in "The Empire strikes back")
2) Fortgeschrittener Jedi: Viele Fähigkeiten stehen zur 
Verfügung, auch kann man sie jetzt gezielt einsetzen. 
(Beispiel: Luke Skywalker in "The Return of the Jedi")
3)Jedimeister: Die letzte Stufe der Perfektion. 
(Beispiel: Yoda in "The Empire strikes back")


Um die nächsthöhere Stufe zu erlangen gibt man einfach den 
Befehl "Lernen" an.

Befehl:"Academy: Lernen"

Bei Der Zugauswertung würfelt dann der Spielleiter mit einem W10:
-um die erste Stufe zu erreichen muß er mindestens eine 7 würfeln
-für die zweite Stufe ist dann mindestens eine 8 notwendig
-die dritte Stufe verlangt nach mindestens einer 9

Pro Runde kann man nur die nächsthöhere Stufe erreichen!


Vorteile
========

Handel
------
Ein Jedi hat größere Überzeugungskraft beim Handeln. Diese 
schlagen sich natürlich auch finanziell nieder:
-Jedi Stufe 1: man addiert 1 zu dem Tageswert hinzu
-Jedi Stufe 2: man addiert 2 zu dem Tageswert hinzu
-Jedi Stufe 3: man addiert 3 zu dem Tageswert hinzu


Raumkampf
---------
Ein Jedicharakter kann mit seinen Kräften seine Piloten 
positiv beeinflussen. Dadurch können sie übermenschliches 
leisten. Dieses erfordert jedoch einige Erfahrung, deshalb muß 
man schon ein Fortgeschrittener sein:
-Jedi Stufe 2: man addiert 1 zu der Trefferwahrscheinlichkeit hinzu
-Jedi Stufe 3: man addiert 1 zu der Trefferwahrscheinlichkeit 
hinzu, außerden addiert man 1 zu dem Angriffswert hinzu.


Spieler beeinflussen
--------------------
Dreimal kann ein Jedi einen anderen Mitspieler beinflussen. 
Statt der eigenen Befehle führt der andere Spieler dann die 
Befehle des Jedis aus. Dies gelingt aber nur, wenn dieser 
Spieler keine Jedi-Fähigkeiten besitzt. Ist er ein Jedi mit 
Stufe 1, so werden seine Befehle zwar nicht ausgeführt, aber 
auch die des Jedis nicht. Es hat dann die gleiche Folge, als ob 
der Spieler ein leeres Blatt abgegeben hätte. Voraussetzung für 
die Beeinflußung ist Stufe3.


Befehl:  "Beinfluße Spieler "Vla":
          Befehl1:Schicke 10 X-Wing1 von 18 zu 19.
          Befehl2: Taufe Pl.34 auf Goas.
          Befehl3:Schicke 1 AW von 17 zu 23.
          Befehl4:Schicke 1 AW von 18 zu 23.
          Befehl5:Mitteilung an Vader:Die Macht ist stark."     

Dies kann man maximal dreimal im Spiel machen. Hierzu 
zählen auch mißglückte Versuche.



THE FACES OF MARS
*****************
"Star Wars - your own Chapter" is a fan-produced game. 
The Faces of Mars do not want intend to infringe upon 
rights of any other copyright holder. All rights revert 
to the contributor upon publication.

FOM-Adresse:          Patrick Henz
                      Martinstr.15
                      52062 Aachen
                      Germany

@ENDNODE




