@DATABASE Master.inc
@NODE Master


STAR WARS - "Your own Chapter"
******************************
von Patrick Henz
******************************


1: Spielvorbereitungen des Masters 

Neben dem diesem Buch brauchst Du noch folgende Utensilien:
- Karteikarten
- Würfel (W6, W10, W20)
- Ordner


1.1: Entwerfen des Universums

Als Erstes sollte der Master eine galaktische Sternenkarte entwerfen, 
falls er nicht auf eine fertige zurückgreift. Als Maß sollte gelten:
"Anzahl der Planeten = Anzahl der Spieler * 10". Danach werden die
Entwicklungsstufen der Planeten mit einem W10 ausgewuerfelt:
- 1 bis  7: die Entwicklungsstufe
- 8 bis 10: neu wuerfeln.

Als Zweites geht es um die Planetenart, wieder mit einem W10:
1: Wuestenplanet
2: Meeresplanet
3: Wasserplanet
4: Vulkanplanet
5: Eisplanet
6: Kraterplanet
7: Dschungelplanet
8: Gasplanet
8-10: neu wuerfeln.

Drittens muessen die Bewohner ausgewuerfelt werden:
- Wüstenplanet (W20) (z.B.: Tantooine)
  - 1 bis 4 : Menschen
  - 5 bis 20: Ureinwohner

- Meeresplanet (W6):
  - nur Ureinwohner 

- Wasserplanet (W20) (z.B.: Erde):
  - 1 bis 10: Menschen 
  -11 bis 20: Ureinwohner 

- Vulkanplanet (W20):
  - 1 bis 5 : Menschen
  - 6 bis 20: Ureinwohner

- Eisplanet (W20) (z.B.: Hoth):
  - 1 bis 5 : Menschen
  - 6 bis 20: Ureinwohner

- Kraterplanet (W10):
  - 1 bis 4 : Menschen
  - 5 bis 10: Ureinwohner

- Dschungelplanet (W10):            - Gasplanet:
  (z.B.: Dagobah)                     - nur Ureinwohner
  - 1       : Menschen
  - 2 bis 10: Ureinwohner


Nach dem Würfeln sollte für jeden Planeten eine Karteikarte erstellt
werden, auf der folgende Daten festgehalten werden:
- ggf. Name
- Entwicklungsstufe
- Bewohner
- Art des Planeten
- ggf. Herrscher
- ggf. Fabrikanlagen


Extras der Sternkarte

Zusaetzlich zu den Planeten koennen auf der Sternkarte noch ein paar 
andere nette Ueberraschungen eingetragen werden, z.B.:
- Schwarze Loecher: Kreise, kreuzen die Raumschiffe in ihrer Flugbahn ein Schwarzes Loch, 
  verschwinden die Schiffe im Nichts
- Galaktischer Nebel: Flaeche, in der die Angriffstaerke und die Panzerung 
  auf null absinkt
- Wurmlöcher: natuerliche Sternentore, schwenkt ein Schiff
  in den Orbit eines solchen Planeten ein, wird es automatisch woanders
  rematerialisieren
- Meteroitenstuerme: Es wird einmal pro Flug mit einem W10 gewuerfelt.
  Bei 1 geraet die Flotte einmal waehrend des Fluges in einen solchen
  Sturm. Es wird danch festgestellt wieviele Verluste es dadurch gab.
  Der Sturm hat die Angriffstaerke 10. Es wird wie in einer Schlacht
  auf die Panzerung gewuerfelt.
- Der Kommerzsektor: Die ideale Heimat für Syndikate. Der Kommerzsektor ist 
  eine dichte Ansiedlung von Planeten. Dadurch ist dieser Bereich sehr
  gut zum Handeln geeignet. Siehe auch das Handelsmodul!
- Das Harpanische Reich: Ebenfalls wie der Kommerzsektor eine dichte
  Ansiedlung von Planeten. Dieser Sternenhaufen ist allerdings am Rande der
  Sternkarte angesiedelt. Dies ist der Startpunkt einer Spielerin. Das
  Harpanische Reich wird behandelt wie die Neue Republik, allerdings 
  fehlen am Anfang noch die Kontakte zu der Republik. Siehe "Entführung
  nach Dathomir" von Dave Wolverton.


1.2: Spielerverwaltung

Die Spielerverwaltung kann leicht im Chaos enden, darum sollte man einen
Ordner mit den ganzen Infos erstellen. Als erstes braucht man eine 
Flugliste, wo die ganzen Raumschiffbewegungen festgehalten werden.
Diese sollte folgende Einteilungen enthalten: 
- Name des Spielers
- Startplanet
- Zielplanet
- Art und Anzahl der Schiffe
- Ankunft in Spielrunde

Außerdem sollte man für jeden Spieler einen Bogen entwerfen, dieser enthält:
- Wappen
- Art und Anzahl der Schiffe (Zur Berechnung der laufenden Kosten)
- Name, Rasse und Mission
- Art und Anzahl der Planeten (Zur Berechnung des Einkommens)


2 Spielstart

Jeder Spieler kriegt eine Kopie der Sternkarte, ansonsten werden die einzelnen Mis-
sionen unterschiedlich behandelt.

Imperator

Der Imperator hat ein Anfangskapital von 30CR. Der Heimatplanet hat die
Evolutionsstufe 7 und er startet mit 10 TIE-Fightern. 
Er sollte: Aufklärungsdroiden bauen und sie zu benachbarten Planeten senden, da-
nach diese mit Schiffen erobern.
beachte: Strenzerstörer sind erst ab ES 8 moeglich.
Sein Einkommen berechnet sich aus den Planeten minus den laufenden Kosten.

Rebell

Der Rebell startet mit mit einem Anfangskapital von 30CR und 10 Jaegern.
Sein Startpunkt ist ein beliebiger Gruppe 7 Planet. Sein Einkommen ist
50% der gesamten Einkommen der Imperatoren und Heilsbringer, so entsteht ein
relatives Gleichgewicht zwischen Gut und Boese. Werden Planeten angegriffen,
so senden sie automatisch einen Hilferuf an den oder die Rebellen. Der
Rebell ist verpflichtet diesen Planeten zu helfen, merkt der Master, daß
er dies nicht tut, verliert der Rebell langsam sein Einkommen, denn dieses
wird von reichen Adligen, Geschaeftsleuten, etc. auf den versklavten
Planeten bezahlt. Gehoeren die angegriffenen Planeten der gleichen Rasse an,
wie der Imperator, so sehen diese an Angriff nicht als Unterjochung an,
sondern als Befreiung, also senden sie auch keine Hilferufe! Werden
Planeten von einem Heilsbringer bekehrt, so senden sie auch keine 
Hilferufe!
Der Rebell kann Schiffe auf allen freien Gruppe 7 Planeten bauen. Sie 
sollten daher diese Planeten beschuetzen. Hat er Schiffe im Orbit, so kriegt er des-
halb trotzdem kein Einkommen für den Planeten, da der Rebell keine Planeten er-
obert(!).


Heilsbringer

Der Heilsbringer ist die komplizierteste Mission aus dem Basissystem.
Er startet mit einem Anfangskapital von 30CR und einem Zerstörer. Mit
diesem Schiff sollte er fremde Planeten anfliegen. Ist das Schiff dann
in einem Orbit, versucht der Heilsbringer den Planeten zu bekehren.
Im Klartext heißt das, daß der Master mit einem W10 würfeln muß.
Er muß die ES ueberwuerfeln, schafft er es ist der Planet bekehrt und zahlt
dem Spieler sein Einkommen, schafft er es nicht, kann er naechste Runde
nochmal wuerfeln. Ab Stufe 7 bauen die Planeten selbststaendig Schiffe,
diese stehen aber nicht unter der Kontrolle des Spielers, sie dienen nur
zur Verteidigung des Planeten gegen Fremde. Der Spieler kann wie der
Rebell Schiffe auf fremden Planeten bauen, diese Planeten werden ihm
bei Spielbeginn bekanntgegeben. Mit diesen Schiffen kann er bekehren oder
ganz normal kaempfen. Will er einen Planeten upgraden muß der Master
wieder mit einem W10 den neuen ES überwuerfeln, es kann naemlich passieren,
dass die Planetenbevoelkerung merkt, daß sie nur ausgenutzt wird. Schafft
der Master die Wuerfelprobe nicht, so ist der Planet wieder frei, der 
Spieler muß aber trotzdem das Geld für das Upgraden bezahlen.
Beachte: Bekehren geht natürlich nur, wenn sich keine andere Flotte in 
der Umlaufbahn des Planeten befindet, ansonsten entflammt wie gewoehnlich
eine Raumschlacht

Mitglieder der "Neuen Rebublik"

Startvoraussetzung wie bei dem Imperator, jediglich das Einkommen
berechnet sich anders: 50%des Planeteneinkommens minus laufende
Kosten. Dafuer kann er im Ernstfall Rebellen und andere Ligamitglieder
um Hilfe bitten. Im Spielverlauf kann er sich auch zu einem
gewoehnlichen Eroberer entwickeln, dann fallen die Besonderheiten weg.






Galaktisches Syndikat

Startpunkt ist ein ES8-Planet. Anfaenglich hat das Syndikat 20 Jaeger,
10 Aufklärungsdroiden und 30CR. Der Spieler sollte wie der Soeldner versuchen 
andere Mitspieler zu finden und denen Angebote zu machen, evt. kann
der Master bei der Suche etwas behilflich sein. Auch das Syndikat
kann ueber Planeten regieren oder diese scrapen. 


3: Spielauswertungen

Raumschlachten

SW-Kampfsystem

Sind zwei Raumflotten in einem Orbit, so beginnt automatisch eine 
Schlacht um die Herrschaft über den Planeten. Der Master macht sich am
besten eine schriftliche Gegenüberstellung der beiden Flotten. Pro Treffer,
den das Schiff einstecken kann, macht er ein Kreuz, z.B:

X X X X X X X X        X-Wing            X X X X
X X                    TIE-Interceptor   X X X X X X

Mit einer Münze entscheidet sich, welche Flotte zuerst angreift.
Es greifen sich zuerst immer die Schiffe gleichen Typs an, also hier die
acht X-Wing gegen die anderen 4. Die Kampfformel ist: 
      ANGRIFFSTÄRKE x W10 > PANZERUNG x W10.
Ist das Ergebnis größer, so ist ein Gegner getroffen und ein Kreuz kann
weggestrichen werden. Jetzt macht der Master das gleiche für die andere
Seite. Hat der Gegner keine Schiffe mehr vom gleichen Typ, werden die 
schwächsten anderen Schiffstypen angegriffen, hier: TIEs. Haben alle
Schiffe dfer einen Seite schon geschossen, schießt die andere Seite so
lange weiter, bis auch hier alle verbliebenen Schiffe schonmal geschossen
haben.
Beachte: Schiffe können vernichtet werden, ohne das sie einmal geschossen
haben.
Trifft eine dritte Flotte auf das Kampfgeschehen, muß sie sich entscheiden,
auf welcher Seite sie kämpfen will. Ist die andere Seite dann vernichtet,
wird entweder ein Waffenstillstand vereinbart oder die beiden Flotten
bekriegen sich jetzt. Dies gilt auch für mehr als drei Flotten.
Zusatzregel: Man kann zusätzlich noch den Faktor Trefferwahrscheinlickeit 
in das Spielgeschehen aufnehmen. Er berücksichtigt noch Größe und 
Geschwindigkeit der Schiffe. Mit einem W10 wird gewürfelt, ob der Schuß
auch das Ziel trifft. Der Wert muß überwürfelt werden.


Raumschiffe

Name               Treffer bis zur Vernichtung    Trefferwahrscheinlichkeit
---------------------------------------------------------------------------
A-Wing                                  1              8
B-Wing                                  2              4
X-Wing                                  1              7
Y-Wing                                  2              5
TIE Starfighter                         1              4
TIE Interceptor                         2              4
Corellian Corvette                      5              4
Escort Frigate                          5              5
Victory Class Destroyer                15              1
Imperial Star Destroyer                20              1
Mon Calamari St.Destroyer              20              2


Rebellionen

Auf den Planeten mit den ES 4-6 sind zeitweise Rebellionen möglich. Hierbei spielt 
die sich im Orbit befindene Flotte eine wichtige Rolle. Beachte: Hat die Planeten-
bevölkerung dieselbe Rasse wie der Herrscher wird sie nie rebellieren! Ebenfalls bei 
Heilsbringern, Ligamitgliedern und Religioesen Vereinigungen rebellieren sie nie-
mals.

Es befinden sich weniger als 10 Schiffe im Orbit

Es wird mit einem W10 gewürfelt: 1-3: Rebellion, es muß jetzt für jeden Raumschiff-
typ im Orbit ebenfalls mit einem W10 gewürfelt werden:
Aufklärungsdroid: Würfelergebnis entsrpicht den Prozent der
                  vernichteten PDs.
Starfighter: 1-6: Würfelergebnis entspricht den Prozent der
                  vernichteten Jägern.
Transporter: 1-8: Würfelergebnis entspricht den Prozent der
                  vernichteten Transporter.
Combat Starships: Würfelergebnis minus 5 entspricht den Prozent der
                  vernichteten Kampfschiffe

Es befinden sich zwischen 10 und 20 Schiffe im Orbit

Es wird mit einem W10 gewürfelt: 1-2: Rebellion, es muß jetzt für jeden Raumschiff-
typ im Orbit ebenfalls mit einem W10 gewürfelt werden:
Aufklärungsdroid: Würfelergebnis minus 1entsrpicht den Prozent der
                  vernichteten PDs.
Starfighter: 1-6: Würfelergebnis minus 2 entspricht den Prozent der
                  vernichteten Jägern.
Transporter: 1-8: Würfelergebnis minus 2 entspricht den Prozent der
                  vernichteten Transporter.
Combat Starships: Würfelergebnis minus 7 entspricht den Prozent der
                  vernichteten Kampfschiffe


Es befinden sich mehr als 20 Schiffe im Orbit

Es wird mit einem W10 gewürfelt: 1: Rebellion, es muß jetzt für jedes
Raumschiff im Orbit ebenfalls mit einem W10 gewürfelt werden:
Aufklärungsdroid: Würfelergebnis minus 3 entsrpicht den Prozent der
                  vernichteten PDs.
Starfighter: 1-6: Würfelergebnis minus 5 entspricht den Prozent der
                  vernichteten Jägern.
Transporter: 1-8: Würfelergebnis minus 4 entspricht den Prozent der
                  vernichteten Transporter.
Combat Starships: nicht vernichtbar


Raumflug

Am Besten mißt der Master mit einem Lineal die Entfernung zwischen den Planeten 
nach. Alle Raumschiffe bewegen sich mit 10LJ pro Runde vorwärts. 
Aufklärungsdroiden sind 20LJ schnell.


Raumschiffbau

Jeder Mitspieler sollte auf seinem Startplaneten eine paar Anlagen
zum Raumschiffbau haben. 


Mastercharaktere

Natürlich kann der Master auch eigene Mitspieler mitmachen lassen.


Hilferufe

Eroberte Planeten haben die Chance einen Hilferuf an die Rebellen
abzusetzen. Um dies zu schaffen muss der Master die ES des Planeten
unterwuerfeln. Gelingt dies erhalten die Rebellen den Hilferuf.
Ausgeschlossen sind hiervon Planeten der Heilsbringer und Planeten die die selbe 
Bevoelkerung haben wie der Imperator.
Bei Planeten von der Religioesen Vereinigung muss die ES zweimal
unterwuerfelt werden.




Planeten unter Quarantaene setzen

Der Master sollte auf seiner Sternenkarte den Planeten makieren, falls sich ein Spie-
ler dem Planeten nähert, wird er über die Quarantäne informiert.


Probleme

Ein Spieler hat alle seine     - Kurz bevor sein letzter Planet  
Planeten verloren.               verloren geht, flieht der Rest der
                                 Flotte auf einen freien Planeten.
                                 Sind schon alle Planeten besetzt,
                                 läßt der Master die Schiffe zu einem
                                 fernen Planeten fliegen. Die Mission
                                 der Spielers verändert sich von einem
                                 Republikmitglied in einen Rebellen 
                                 oder von einem Eroberer in einen 
                                 Söldner. Siehe Buch der Missionen.

Faces of Mars

"Star Wars - your own Chapter" is a fan-produced game. Faces of Mars do not want 
intend to infringe upon rights of any other copyright holder. All rights revert to the 
contributor upon publication.

FOM-Adresse: 
                      Patrick Henz
                      Martinstr.15
                      52062 Aachen
                      Germany


@ENDNODE




