@DATABASE Modul6.inc
@NODE Modul6


STARWARS - Your own Chapter - das Handelsmodul
**********************************************

Produktübersicht
================
Ware                     Durchschnittspreis (CR)
------------------------------------------------
Textilien                0.3          
Polymere Kunststoffe     0.7
Alkoholika               1
Holz                     0.1
Kristalle                2
Radioaktive Elemente   100
Stahl                    0.05
Kupfer                   0.2
Aluminium                0.1
Zinn                     0.9
Silber                   7
Speziallegierungen      20
Petrochemische Produkte  2
Getreide                 0.03
Fleisch                  0.15
Gewürze                  0.6
Obst                     0.1
Pharmazeutika           10
Edelsteine             100
Schußwaffen              3
Munition                 3
Klingenwaffen            1
Werkzeuge                1
Schutzkleidung           5
Elektronische Bauteile  10
Mechanische Bauteile     7
Kybernetische Bauteile  25
Computerbauteile        15
Werkzeugmaschinen       75
Raumanzüge              40


Wasserwelten

Ware                     Ankauf        Verkauf
----------------------------------------------
Textilien                -10%          -20%         
Polymere Kunststoffe     -10%          -20%
Alkoholika               -10%          -20%
Holz                     -20%          -40%
Kristalle                +20%          +10%
Radioaktive Elemente       0%          -10%
Stahl                    +20%          +10%
Kupfer                   +20%          +10%
Aluminium                +30%          +20%
Zinn                       0%          -10%
Silber                   +10%           0%
Speziallegierungen       +10%            0%
Petrochemische Produkte  -20%          -30%
Getreide                   0%          -10%
Fleisch                    0%          -10%
Gewürze                    0%          -10%
Obst                     -10%            0%
Pharmazeutika            -20%          -30%
Edelsteine               +20%          +10%
Schußwaffen                0%          -10%
Munition                   0%          -10%
Klingenwaffen            -10%          -20%
Werkzeuge                -20%          -30%
Schutzkleidung           -20%          -30%
Elektronische Bauteile   -20%          -30%
Mechanische Bauteile     -10%          -20%
Kybernetische Bauteile   -10%          -20%
Computerbauteile         -10%          -20%
Werkzeugmaschinen        -10%          -20%
Raumanzüge               -10%          -20% 


Meereswelten

Ware                     Ankauf        Verkauf
----------------------------------------------
Textilien                +20%          +10%         
Polymere Kunststoffe     +20%          +10%
Alkoholika               +10%            0%
Holz                     +30%          +20%
Kristalle                +20%          +10%
Radioaktive Elemente       0%          -10%
Stahl                    +30%          +20%
Kupfer                   +20%          +10%
Aluminium                +30%          +20%
Zinn                     +20%          +10%
Silber                   +10%           0%
Speziallegierungen       +30%          +20%
Petrochemische Produkte  +10%            0%
Getreide                 +20%          +10%
Fleisch                    0%          -10%
Gewürze                    0%          -10%
Obst                     +10%            0%
Pharmazeutika            -10%          -20%
Edelsteine               +20%          +10%
Schußwaffen              +20%          +10%
Munition                 +20%          -10%
Klingenwaffen            +30%          -40%
Werkzeuge                +10%            0%
Schutzkleidung           +20%          +10%
Elektronische Bauteile     0%          -10%
Mechanische Bauteile       0%          -10%
Kybernetische Bauteile     0%          -10%
Computerbauteile           0%          -10%
Werkzeugmaschinen          0%          -10%
Raumanzüge               -20%          +10% 







Dschungelwelten

Ware                     Ankauf        Verkauf
----------------------------------------------
Textilien                -40%          -30%         
Polymere Kunststoffe     +30%          +20%
Alkoholika               -20%          -10%
Holz                     -50%          -90%
Kristalle                -10%          -20%
Radioaktive Elemente     +20%          +30%
Stahl                    +20%          +10%
Kupfer                     0%          -10%
Aluminium                +20%          +10%
Zinn                       0%          -10%
Silber                   -10%         -200%
Speziallegierungen       +30%          -20%
Petrochemische Produkte  +20%          -10%
Getreide                 -30%          -70%
Fleisch                    0%          -10%
Gewürze                  -20%          -60%
Obst                     -20%          -40%
Pharmazeutika              0%          -10%
Edelsteine                 0%          -10%
Schußwaffen                0%          -10%
Munition                   0%          -10%
Klingenwaffen              0%          -10%
Werkzeuge                  0%          -10%
Schutzkleidung             0%          -10%
Elektronische Bauteile   +10%            0%
Mechanische Bauteile       0%          -10%
Kybernetische Bauteile   +10%            0%
Computerbauteile         +10%            0%
Werkzeugmaschinen        +10%            0%
Raumanzüge               +10%            0% 


Wüstenwelten

Ware                     Ankauf        Verkauf
----------------------------------------------
Textilien                +20%          +10%         
Polymere Kunststoffe     -20%          -10%
Alkoholika                 0%          -10%
Holz                     +40%          +30%
Kristalle                  0%          -10%
Radioaktive Elemente       0%          -10%
Stahl                    +10%            0%
Kupfer                     0%          -10%
Aluminium                  0%          -10%
Zinn                       0%          -10%
Silber                     0%         -10%
Speziallegierungen       +10%            0%
Petrochemische Produkte  -20%          -30%
Getreide                 +90%          +40%
Fleisch                  +90%          +40%
Gewürze                    0%          -10%
Obst                     +90%          +40%
Pharmazeutika            -20%          -30%
Edelsteine                 0%          -10%
Schußwaffen                0%          -10%
Munition                   0%          -10%
Klingenwaffen            -10%          -20%
Werkzeuge                -20%          -30%
Schutzkleidung           -20%          -30%
Elektronische Bauteile   -20%          -30%
Mechanische Bauteile     -10%          -20%
Kybernetische Bauteile   -10%          -20%
Computerbauteile         -10%          -20%
Werkzeugmaschinen        -10%          -20%
Raumanzüge                 0%          -10%


Vulkanwelten

Ware                     Ankauf        Verkauf
----------------------------------------------
Textilien                  0%          -10%         
Polymere Kunststoffe     -20%          -10%
Alkoholika               -20%          -10%
Holz                     +80%          +40%
Kristalle                -20%          -30%
Radioaktive Elemente       0%          -10%
Stahl                    -10%          -20%
Kupfer                     0%          -10%
Aluminium                  0%          -10%
Zinn                       0%          -10%
Silber                     0%         -10%
Speziallegierungen       -10%          -20%
Petrochemische Produkte  -20%          -30%
Getreide                 +50%          +40%
Fleisch                  +50%          +30%
Gewürze                    0%          -10%
Obst                     +70%          +40%
Pharmazeutika            -20%          -30%
Edelsteine                 0%          -10%
Schußwaffen                0%          -10%
Munition                   0%          -10%
Klingenwaffen            -10%          -20%
Werkzeuge                  0%          -10%
Schutzkleidung           +40%          +20%
Elektronische Bauteile     0%          -10%
Mechanische Bauteile       0%          -10%
Kybernetische Bauteile     0%          -10%
Computerbauteile           0%          -10%
Werkzeugmaschinen          0%          -10%
Raumanzüge               +10%            0% 
 









Eiswelten

Ware                     Ankauf        Verkauf
----------------------------------------------
Textilien                +30%          +20%         
Polymere Kunststoffe       0%          -10%
Alkoholika                 0%          -10%
Holz                       0%          -10%
Kristalle                -30%          -20%
Radioaktive Elemente       0%          -10%
Stahl                    +10%            0%
Kupfer                   +10%            0%
Aluminium                  0%          -10%
Zinn                       0%          -10%
Silber                   +10%           0%
Speziallegierungen       +10%            0%
Petrochemische Produkte  +10%            0%
Getreide                 +80%          +30%
Fleisch                  +80%          +30%
Gewürze                  +80%          +30%
Obst                     +80%          +30%
Pharmazeutika              0%          -10%
Edelsteine               -10%          -20%
Schußwaffen                0%          -10%
Munition                   0%          -10%
Klingenwaffen              0%          -10%
Werkzeuge                  0%          -20%
Schutzkleidung           +10%            0%
Elektronische Bauteile     0%          -10%
Mechanische Bauteile       0%          -10%
Kybernetische Bauteile   +10%            0%
Computerbauteile           0%          -10%
Werkzeugmaschinen          0%          -10%
Raumanzüge               +10%            0% 


Kraterwelten

Ware                     Ankauf        Verkauf
----------------------------------------------
Textilien                +20%          +10%         
Polymere Kunststoffe     -20%          -10%
Alkoholika                 0%          -10%
Holz                     +80%          +30%
Kristalle                  0%          -10%
Radioaktive Elemente     -20%          -30%
Stahl                      0%          -10%
Kupfer                     0%          -10%
Aluminium                +10%            0%
Zinn                     +10%            0%
Silber                   +10%           0%
Speziallegierungen       +20%          +10%
Petrochemische Produkte    0%          -10%
Getreide                 +70%          +40%
Fleisch                  +80%          +40%
Gewürze                  +90%          +40%
Obst                     +90%          +50%
Pharmazeutika            -20%          -30%
Edelsteine               +20%          +10%
Schußwaffen                0%          -10%
Munition                   0%          -10%
Klingenwaffen              0%          -10%
Werkzeuge                  0%          -10%
Schutzkleidung           +10%            0%
Elektronische Bauteile     0%          -10%
Mechanische Bauteile     -10%          -20%
Kybernetische Bauteile   -10%          -20%
Computerbauteile         -10%          -20%
Werkzeugmaschinen        -10%          -20%
Raumanzüge               +10%            0% 


Gasplanet

Ware                     Ankauf        Verkauf
----------------------------------------------
Textilien                +60%          +50%         
Polymere Kunststoffe     +40%          +30%
Alkoholika               +60%          +60%
Holz                     +90%          -70%
Kristalle                +20%          +10%
Radioaktive Elemente     +50%         +410%
Stahl                    +20%          +10%
Kupfer                   +20%          +10%
Aluminium                +30%          +20%
Zinn                     +20%          +10%
Silber                   +10%           0%
Speziallegierungen       +10%            0%
Petrochemische Produkte  +40%          +30%
Getreide                 +40%          +30%
Fleisch                  +40%          +30%
Gewürze                  +20%          +10%
Obst                     +40%          +30%
Pharmazeutika              0%          -10%
Edelsteine                 0%          -10%
Schußwaffen              +30%          +20%
Munition                 +30%          +20%
Klingenwaffen            +80%          -90%
Werkzeuge                  0%          -10%
Schutzkleidung           +80%          +40%
Elektronische Bauteile   +40%          +30%
Mechanische Bauteile     +30%          +20%
Kybernetische Bauteile   +30%          +20%
Computerbauteile         +30%          +20%
Werkzeugmaschinen          0%          -10%
Raumanzüge               +50%          +20% 










Evolutionsstufe 1-3

Ware                     Ankauf        Verkauf
----------------------------------------------
Textilien                -20%          -10%         
Polymere Kunststoffe     +50%          -10%
Alkoholika               -30%          -20%
Holz                     -60%          -80%
Kristalle                +40%          +30%
Radioaktive Elemente    +100%          -90%
Stahl                    +60%          -50%
Kupfer                     0%          -10%
Aluminium                +60%          -20%
Zinn                       0%          -10%
Silber                   +30%           0%
Speziallegierungen       +80%            0%
Petrochemische Produkte  +50%          -30%
Getreide                 -40%          -70%
Fleisch                  -10%          -30%
Gewürze                    0%          -10%
Obst                     -10%            0%
Pharmazeutika            +40%          +30%
Edelsteine               +20%          +10%
Schußwaffen              +80%          +50%
Munition                 +80%          +50%
Klingenwaffen            -10%          -20%
Werkzeuge                  0%          -10%
Schutzkleidung             0%          -10%
Elektronische Bauteile   +70%          -30%
Mechanische Bauteile     -10%          -20%
Kybernetische Bauteile   +90%          -20%
Computerbauteile         +90%          -20%
Werkzeugmaschinen          0%            0%
Raumanzüge               +90%          -50% 


Evolutionsstufe 4-6

Ware                     Ankauf        Verkauf
----------------------------------------------
Textilien                -20%          -10%         
Polymere Kunststoffe       0%          -10%
Alkoholika                 0%          -10%
Holz                       0%          -10%
Kristalle                  0%          -10%
Radioaktive Elemente     -20%          -30%
Stahl                      0%          -10%
Kupfer                     0%          -10%
Aluminium                +10%            0%
Zinn                       0%          -10%
Silber                   +20%         +10%
Speziallegierungen       +30%          +20%
Petrochemische Produkte    0%          -10%
Getreide                   0%          -10%
Fleisch                    0%          -10%
Gewürze                    0%          -10%
Obst                     +10%            0%
Pharmazeutika            +10%            0%
Edelsteine               +20%          +10%
Schußwaffen                0%          -10%
Munition                   0%          -10%
Klingenwaffen            -30%          -40%
Werkzeuge                  0%          -10%
Schutzkleidung             0%          -10%
Elektronische Bauteile   +10%            0%
Mechanische Bauteile     -20%          -30%
Kybernetische Bauteile   +20%          +10%
Computerbauteile         +10%            0%
Werkzeugmaschinen          0%          -10%
Raumanzüge               +30%          +20% 


Evolutionsstufen 7-8

Ware                     Ankauf        Verkauf
----------------------------------------------
Textilien                +10%            0%         
Polymere Kunststoffe     -20%          -10%
Alkoholika                 0%          -10%
Holz                     +40%          -10%
Kristalle                +20%          +10%
Radioaktive Elemente     -10%          -20%
Stahl                    -20%          -10%
Kupfer                   -10%            0%
Aluminium                -10%            0%
Zinn                       0%          -10%
Silber                   +10%           0%
Speziallegierungen       +20%          +10%
Petrochemische Produkte  -20%          -30%
Getreide                 +10%            0%
Fleisch                  +20%          +10%
Gewürze                    0%          -10%
Obst                     +20%          +10%
Pharmazeutika            -20%          -30%
Edelsteine               +20%          +10%
Schußwaffen                0%          -10%
Munition                   0%          -10%
Klingenwaffen            -50%          -60%
Werkzeuge                -20%          -30%
Schutzkleidung           -20%          -30%
Elektronische Bauteile   -20%          -30%
Mechanische Bauteile     -10%          -20%
Kybernetische Bauteile     0%          -10%
Computerbauteile           0%          -10%
Werkzeugmaschinen        -10%          -20%
Raumanzüge                 0%          -10% 










Transporter
===========

Space Barge (Incom X-23 StarWorker)
-----------
Angriff:           0
Panzerung:         3
ES:                7
Kosten:          440CR
lauf.Kosten:       2CR/R
Kapazität:      5000 metrische Tonnen
Geschw.:           1
Treffer:           2
Trefferw.:         2


Stock Light Freighter (Corellian YT-1300 Transport)
---------------------
Basismodell des "Millennium Falcon".

Angriff:           1 Laserkanone: 2
Panzerung:         4
ES:                7
Kosten:           40CR 
lauf.Kosten:       2CR/R
Kapazität:       100 metrische Tonnen
Geschw.:           2
Treffer:           2
Trefferw.:         4


Bulk Freighter (Corellian Action IVTransport)
--------------
Angriff:           0
Panzerung:         6
ES:                7
Kosten:        20000CR
lauf.Kosten:       4CR/R
Kapazität:     75000 metrische Tonnen
Geschw.:           1
Treffer:           5
Trefferw.:         1


Container Ship (Kuat Drive Yards Super Transport)
--------------
Angriff:           0
Panzerung:         6
ES:                8
Kosten:       200000CR
lauf.Kosten:      10CR/R
Kapazität:  25.000.000.000 metrische Tonnen
Geschw.:           1
Treffer:          10
Trefferw.:         1



Star Galleon (Imperial Star Galleon)
------------
Diese 300m langen Schiffe sind eine gefährliche Kombination 
von Transportern und Kampfschiffen.

Angriff:          10 Turbolaserbatterien: 4
Panzerung:         6
ES:                7
Kosten:          600CR  
lauf.Kosten:       5CR/R
Kapazität:     75000 metrische Tonnen  
Geschw.:           1
Treffer:           4
Trefferw.:         1


Kampfschiffe - Kapazitäten
==========================
Corellian Corvette:       3000 metrische Tonnen
Escort Frigate:           6000 metrische Tonnen
Imperial Star Destroyer: 36000 metrische Tonnen
Imp. Super Star Destr.: 360000 metrische Tonnen
Mon Calamari Star Cr.    20000 metrische Tonnen
Victory Class Destroyer:  8100 metrische Tonnen

Millenium Falcon:          100 metrische Tonnen

Nähere Angaben zu diesen Schiffen in dem Raumschiffkatalog.



Tageswert
=========

Wurf(W20)   Prozent des Grundwerts
----------------------------------
 1- 2       40%
    3       50%
    4       60%
    5       70%
    6       80%
    7       90%
 8-10      100%
   11      110%
   12      120%
   13      130%
   14      150%
   15      170%
   18      200%
19-20      300%


Befehle
=======

Warenkauf
---------
Voraussetzung hierfür ist, das sich der Transporter im Orbit 
des Planeten befindet. Beispiel: Händler X möchte für seine 
Space Barge Alkoholica auf einem Wasserplaneten (ES4) kaufen.
Berechnung (Kauf):
5000(Kapazität der Space Barge) mal 1CR(Durchschnittswert von 
Alkoholica)= 5000CR.
5000CR - 10%(Ankaufswert von Alkoholica auf Wasserwelten 
(-10%) + Ankaufswert auf ES4-Planeten (0%))) = 4500CR.
Würfelergebnis: 3 (Tageswert) = 2250CR(50% Tageswert).
Beachte: Man kann ein Raumschiff immer nur voll beladen und es 
kann nur ein Gut verwendet werden. Natürlich kann man auch 
gleichzeitig mehrere Schiffe beladen. Dann wird die Kapazität 
mal der Anzahl der Schiffe genommen (wenn es die gleichen 
Typen sind). Das Geld wird vom Spielerkonto abgezogen.
Berechnung (Verkauf der Alkoholica auf einem Gasplaneten mit ES6):
5000 (Kapazität der Space Barge) mal 1CR (Durchschnittswert 
von Alkoholica) = 5000CR.
5000CR + 50%(Verkaufswert von Alkoholica auf Gasplaneten 
(+60%) + Verkaufswert auf einem ES6-Planeten (-10%)) = 8000CR.
Würfelergebnis: 10 (Tageswert) = 8000CR (100%Tageswert).
Beachte: Der Planet kann noch eine Handelssteuer erheben. 
Die Berechnungen werden vom Spielleiter ausgeführt.

Befehl: "Kaufe für 10 Space Barges auf Planet 23 Alkoholica."
        "Verkaufe für 10 Space Barges auf Planet 24 Alkoholica."


Steuern
-------
Der Spieler kann für seine Planeten auch Handelssteuern erheben. 
Je höher sie sind, desto mehr verdient er an den Geschäften 
mit, aber Händler fliegen im allgemeinen lieber Planeten mit 
niedrigen Steuern an. Will der Charakter Steuern erheben, so 
muß der Spieler einen Bogen für den Planeten an den 
Spielleiter schicken.

Beispiel:

Planet 28 (Wasserplanet Terra)
Ware                     Steuern (CR pro Tonne)
------------------------------------------------
Textilien                0.1          
Polymere Kunststoffe     0.2
Alkoholika               0.5
Holz                     0.3
Kristalle                1
Radioaktive Elemente    50
Stahl                    0.01
Kupfer                   0.1
Aluminium                0.1
Zinn                     0.4
Silber                   2
Speziallegierungen       5
Petrochemische Produkte  1
Getreide                 0.03
Fleisch                  0
Gewürze                  0
Obst                     0
Pharmazeutika            1
Edelsteine              10
Schußwaffen              1
Munition                 0
Klingenwaffen            0
Werkzeuge                0
Schutzkleidung           1
Elektronische Bauteile   1
Mechanische Bauteile     1
Kybernetische Bauteile   5
Computerbauteile         5
Werkzeugmaschinen       34
Raumanzüge               3

Verbot für Händler Solo und Imperator Palpatine.

Wenn man will, kann man natürlich auch noch zwischen Ankauf 
und Verkauf in den Steuern unterscheiden. Bei Geschäften 
werden dann die Steuern automatisch dem Händler abgezogen und 
dem Planetenherrscher gutschrieben.


Handelsbeschränkungen
---------------------
Natürlich muß man nicht mit jedem Handeln, der kommt. Dies würde 
ja zur Folge haben, daß man seine politischen Gegener 
finanziell unterstützen würde. Man schreibt dann auf den Bogen 
mit den Steuern noch, mit wem man nicht handeln will, oder 
welche Waren auf dem Planeten illegal sind, z.B. Waffen. Man 
kann sogar soweit gehen, daß man Transporter von einem 
bestimmten Spieler direkt bei Ankunft angreift.      


Quellen:
- Star Wars 
- Frontier / Elite II      -Raumschiffsimulation 
- Traveller                -Rollenspiel

Thanks to Jörg Weissinger!

THE FACES OF MARS
*****************
"Star Wars - your own Chapter" is a fan-produced game. FOM do 
not want intend to infringe upon rights of any other copyright 
holder. All rights revert to the contributor upon publication.
 
@ENDNODE


