@DATABASE Modul1.inc
@NODE Modul1

Die Mos Eisley Cantina
**********************************************
                     Copyright by Patrick Henz

Einleitung
==========
Auf dem Wüstenplaneten Tatooine befindet sich die in der 
ganzen Galaxis berüchtigte Schmugglerbar "Mos Eisley". Hier 
treffen zwielichtige Gestalten von überall her aufeinander. 
Der ideale Ort um Bekanntschaften zu machen und Informationen 
zu sammeln. Daher kann es sehr lohnent sein, einen Abgesandten 
nach Tatooine zu schicken.        

        
Der Abgesandte
==============
Vor dem Aufsuchen der Bar, muß der Abgesandte bestimmt 
werden, d.h., daß Aussehen, Rasse, vielleicht noch 
Kleidung, Akzent, Charakter, etc. entworfen werden muß. Danach 
wird dieser mit einem
Schiff nach Tatooine geschickt.


Befehle
=======
Um die Möglichkeiten der Bar auszunutzen zu können muß sich 
mindestens ein Schiff des Spielers sich bei dem Planeten 
befinden! Dem Befehl sollte zur besseren Kenntnismachung 
des Masters "Mos Eisley:" vorausgehen.


Glücksspiele
------------
Eine Möglichkeit Geld zu verdienen ist das Sabacc-Spiel. Die 
Vor- und Nachteile dieser Methode sind wohl schon seit 
tausenden von Jahren bekannt.

Befehl: "Mos Eisley: Spiele mit 200CR."


Informationen
-------------
In der Bar befinden sich viele Gäste, ein paar von ihnen 
haben immer was Wissenswertes auf Lager. Eine Frage kann 
nichts schaden, oder etwa doch?        

Befehl: "Mos Eisley: Frage Crux nach Infos über Planet 34."


Kosten
------
Die Landegebühr auf Tatooine beträgt 10CR, danach fallen pro 
Spielrunde 2CR Liegegebühr an.

  
Faces of Mars
*************
"Star Wars - your own Chapter" and "The Mos Eisley-Cantina" 
are fan-produced games. The Faces of Mars do not want intend 
to infringe upon rights of any other copyright holder. All 
rights revert to the contributor upon publication.

FOM-Adresse:          Patrick Henz
                      Martinstr.15
                      52062 Aachen
                      Germany


@ENDNODE

