@DATABASE Modul5.inc
@NODE Modul5

Star Wars - Your own Chapter
****************************
      Das Buch der Missionen


Eroberer
========
Diese Mission ist praktisch identisch mit der des Imperators. 
Der Hauptunterschied liegt in der Tatsache, daß der Imperator 
das alte Imperium wiederaufbauen will und der Eroberer ein 
lokaler Herrscher ist, der sein eigenes Sternenreich aufbauen 
will. Mit seiner Streitmacht, die aus einem zusammengewürfelten 
Haufen besteht, versucht er sich über das All auszubreiten. 
Eroberte Welten werden unterjocht und ausgebeutet. 

Anfangstips
-----------
-Aufklärungsdroiden losschicken
-starke Verteidigungsflotte für den Heimatplaneten aufbauen
-möglichst einen zweiten Planeten auf ES7 upgraden und dort 
Fabriken bauen

Taktiktips
----------
-Wenn man Gegner nicht vernichten will, kann man auch 
versuchen diese zu erpressen, z.B.:"Zahle 200CR oder ich 
erobere deine Planeten."
-Ist es abzusehen, daß man einen Planeten an einen anderen 
Spieler verlieren wird, hat man immer noch die Möglichkeit, ihn 
so weit wie möglich zu scrapen. Man verdient so noch etwas Geld 
und außerdem kriegt der andere dann weniger Einkommen.
-Wengier Handelssteuern sind oftmals mehr! Ruhig auchmal 
Werbung bei den Händlern für seine Planeten machen. 

mögliche Veränderungen
----------------------
-zum Imperator: Der Spieler versucht sich in Mitteilungen auf 
die Wurzeln des Imperiums zu berufen.
-zum Mitglied in der "Neuen Republik": Grundsätzlich ist die 
"Neue Republik" neuen Mitgliedern immer aufgeschlossen. Es 
steht dem Erober also frei einen Antrag zu stellen. 
Voraussetzung ist allerdings, daß man mindestens ein 
Ligamitglied namentlich kennt.
-zum Rebell: Falls ein Gegner alle ES7 Planeten erobert hat 
oder diese zerstört, hat der Eroberer keine Möglichkeit mehr 
selbst Raumschiffe zu bauen. Entweder man kauft dann Schiffe 
von anderen, wie z.B. dem Syndikat oder man vollzieht einen 
Wechsel zum Guten und kämpft dann für die Unterdrückten.
-zum Händler: Wenn man alle Planeten verloren hat, kann man 
mit Transportern und Kriegsschiffen sich anderswo ansiedeln 
und sich fortan als Händler sein Geld verdienen.


Imperator (Beispiel:Imperator Palpatine)
=========
Diese Mission ist einfach erklärt. Das große Imperium ist 
zerschlagen und ehemalige Flottenteile versuchen es 
wiederzuvereinen. Dies geht natürlich so, daß man sich selbst 
zum neuen Imperator ausrufen läßt und versucht soviele Planeten 
wie möglich zu erobern. Je größer das Reich, desto mächtiger 
das neue Imperium. Doch andere Herrscher und vorallem die 
Rebellen wollen einem das Leben so schwer wie möglich machen. 
Seine Streitmacht besteht vorallem aus imperialen Schiffen.

Anfangstips
-----------
-Aufklärungsdroiden losschicken
-starke Verteidigungsflotte für den Heimatplaneten aufbauen
-möglichst einen zweiten Planeten auf ES7 upgraden und dort 
Fabriken bauen

Taktiktips
----------
-Wenn man Gegner nicht vernichten will, kann man auch 
versuchen diese zu erpressen, z.B.:"Zahle 200CR oder ich 
erobere deine Planeten."
-Ist es abzusehen, daß man einen Planeten an einen anderen 
Spieler verlieren wird, hat man immer noch die Möglichkeit, ihn 
so weit wie möglich zu scrapen. Man verdient so noch etwas Geld 
und außerdem kriegt der andere dann weniger Einkommen.
-Wengier Handelssteuern sind oftmals mehr! Ruhig auchmal 
Werbung bei den Händlern für seine Planeten machen. 

mögliche Veränderungen
----------------------
-zum Eroberer: Der Spieler versucht sich in Mitteilungen von 
dem Imperium loszusagen. Man beruft sich auf sich selber oder 
auf seinen Heimatplaneten.
-zum Mitglied in der "Neuen Republik": Grundsätzlich ist die 
"Neue Republik" neuen Mitgliedern immer aufgeschlossen. Es 
steht dem Erober also frei einen Antrag zu stellen. 
Voraussetzung ist allerdings, daß man mindestens ein 
Ligamitglied namentlich kennt.
-zum Rebell: Falls ein Gegner alle ES7 Planeten erobert hat 
oder diese zerstört, hat der Eroberer keine Möglichkeit mehr 
selbst Raumschiffe zu bauen. Entweder man kauft dann Schiffe 
von anderen, wie z.B. dem Syndikat oder man vollzieht einen 
Wechsel zum Guten und kämpft dann für die Unterdrückten.
-zum Händler: Wenn man alle Planeten verloren hat, kann man 
mit Transportern und Kriegsschiffen sich anderswo ansiedeln 
und sich fortan als Händler sein Geld verdienen.


Heilsbringer (Beispiel: C´boath)
============
Anfänglich ist der Heilsbringer mit einem einzelnen Raumschiff 
ausgestattet. Mit primitiven Tricks oder ähnlichem versucht er 
sich als Gott aufzuspielen. Fällt die Bevölkerung darauf 
hinein, kann der Heilsbringer hier herrschen ähnlich wie ein 
Imperator. Hat einer seiner Planeten eine ES von mindesten 7, 
fängt die Bevölkerung hier automatisch an, Raumschiffe zu 
bauen. Allerdings dienen sie nur zur Planetenverteidigung, 
der Heilsbringer hat keine Kontrolle über sie. Auf freien 
Planeten kann der Spieler Raumschiffe bauen. Gibt es keine 
davon, muß er sie bei Syndikaten kaufen.
Man kann nur mit einem Schiff pro Runde versuchen zu bekehren.

Anfangstips
-----------
-die nächsten Planeten ansteuern und versuchen diese unter die 
mentale Kontrolle zu bringen
-später vorsichtig versuchen seine Planeten auf eine mittlere ES 
zu bringen
-so schnell wie möglich Schiffe anschaffen, ansonsten kann 
es schnell passieren, daß das einzige Schiff vernichtet wird 
und der Spieler ist am Ende

Taktiktips
----------
-Versuchen Kontakte mit Eroberern oder Imperatoren zu knöpfen. 
Auf ihren Planeten kann man dann vielleicht billig Schiffe 
bauen.
-Sicherheitshalber sich es nicht mit den Syndikaten verderben.
-Mit dem Geld eine Raumschifflotte anschaffen. Mit dieser kann 
man dann ganz normal Planeten erobern.
-Versuchen einen Planeten auf eine ES von 7 upzugraden. Diese 
Planeten bauen dann zwar eine unkontrollierbare Flotte auf, 
aber andererseits kann der Heilsbringer natürlich gegen 
Credits hier auch Schiffe bauen.


mögliche Veränderungen
----------------------
-zum Eroberer: Man muß sich von der Macht lossagen und sich 
nur noch auf die Kraft der Raumflotte verlassen.
-zum Imperator: Auch Imperator Palpatine hatte die Fähigkeiten 
der Macht. Der Spieler kann sich auf ihn berufen und 
gleichzeitg Heilsbringer und Imperator sein.
-zum Mitglied in der "Neuen Republik": Hierfür muß der 
Heilsbringer einen Antrag an die "Neue Republik" stellen. Dafür 
muß er mindestens ein Mitglied namentlich kennen. Außerdem 
verzichtet er dann auf seine übernatürlichlichen Fähigkeiten. 
Die "Neue Republik" ist nicht gezwungen, den Antrag 
anzunehmen. Dies liegt im Ermessen der anderen Mitspieler.


Rebell (Beispiel:Luke Skywalker)
======
Kämpfer für Frieden und Gerechtigkeit innerhalb der Galaxis. 
Förderer finden sie bei den Reichen und Adligen auf den 
unterjochten Planeten. Von ihrem Geld versucht der Rebell 
eine Streitmacht für das Gute zu errichten. Mit ihrer Hilfe will 
er diese Planeten befreien.

Anfangstips
-----------
-Raumschiffe über mehrere Planeten verteilen, so daß man im 
Notfall schneller bei diversen Planeten ankommen kann. 
-Sobald man Mitglieder der "Neuen Republik" kennt, mit ihnen 
Kontakt aufnehmen, schließlich kämpfen beide auf der gleichen 
Seite. 

Taktiktips
----------
-Je mehr Spieler sich für die Mission des Rebelles 
entscheiden, desto kleiner ist das Einkommen des einzelnen 
Rebells. Es ist daher wichtig, sich mit anderen abzusprechen, 
so daß die Rebellen möglichst effizient arbeiten und ihre 
Kräfte schonen.

mögliche Veränderungen
----------------------
-zum Eroberer: Einmal befreite Planeten werden nicht mehr 
wieder verlassen, sondern nun vom Rebell unterjocht. Man muß 
dies dem Spielleiter dann mitteilen, da ein Rebell kein Geld 
für Planeten kriegt.
-zum Mitglied in der "Neuen Republik": Man fängt an, befreite 
Planeten weiter zu betreuen. Man unterweist sie in der Technik 
und läßt zum Schutz Schiff in ihrem Orbit. Auch hier muß der 
Master unterrichtet werden, damit einem später auch die Steuern 
von den Planeten gutgeschrieben werden. Danach wird ein Antrag 
an die "Neue Republik" gestellt. Dieser sollte für einen 
ehemaligen Rebellen eigentlich nur eine Formsache sein.
-zur Sternengarde: (siehe Sternengarde)


Syndikat (Beispiel:Jabba the Hutt, Talon Karrde)
========
Ein Zusammenschluß von Schmugglern,Kopfgeldjägern und 
Söldnern. Das Syndikat verkauft alles was man woanders nicht 
kriegen kann: Informationen, Raumschiffe (besonders ES8-Typen), 
etc. Außerdem verfügt man über Spione und viele 
Aufklärungsdroiden. Es wird mit jedem zusammengearbeitet der 
Geld hat.

Anfangstips
-----------
-"Mitteilung an alle": Steht zwar nicht in der Spieleranleitung 
ist aber wegen der vielen Spione auf den diversen Planeten 
logischerweise auch möglich. In den Mitteilungen sollte man 
schreiben, welche Dienste man anbieten kann.
-Die Mos Eisley-Cantina ist ein beliebter Treffpunkt für Spieler.

Taktiktips
----------
-Es ist zu prüfen, ob ein Spezialisierung, z.B.: als Söldner, 
sich lohnt.
-Wengier Handelssteuern sind oftmals mehr! Ruhig auchmal 
Werbung bei den Händlern für seine Planeten machen.
-Man kann ruhig auch mal falsche Gerüchte in die Welt setzen, 
um z.B. andere Spieler gegeneinander aufzuhetzen. 

mögliche Veränderungen
----------------------
-zum Eroberer: Nach einer Zeit, wenn die eigene Raumflotte 
ein gewisse Stärke erreicht hat, kann der Spieler vom Syndikat 
zum Eroberer wechseln. Dadurch verliert man allerdings seine 
guten Kontakte.
-zum Rebellen: Ist der Heimatplanet verloren, kann man sich 
eines besseren besinnen und fortan für das Gute kämpfen.
-zum Mitglied in der "Neuen Republik": Will man dort 
eintreten, kann man ja mal einen Antrag stellen. Voraussetzung 
ist allerdings, daß man ein Mitglied namentlich kennt. Ob 
der Antrag angenommen wird liegt an den Mitgliedern.
-zum Händler: Wenn man alle Planeten verloren hat, kann man 
mit Transportern und Kriegsschiffen sich anderswo ansiedeln 
und sich fortan als Händler sein Geld verdienen.


Mitglied in der "Neuen Republik" (Beispiel: Mon Mothma)
================================
Eine besondere Form der Eroberer, man verfolgt ähnliche Ziele, 
nämlich Expansion. Doch die eroberten Planeten werden besser 
behandelt, als bei den Eroberern. Man sieht sich mehr als 
Befreier von den alten Strukturen und läßt den Planeten eine 
größtmögliche Freiheit, das Einzige was man will sind Steuern. 
Die Mitglieder der "Neuen Republik" stehen sich im Ernstfall 
zur Seite und Unterstützen die Rebellen im Kampf gegen das Böse.

Anfangstips
-----------
-Aufklärungsdroiden losschicken
-starke Verteidigungsflotte für den Heimatplaneten aufbauen
-möglichst einen zweiten Planeten auf ES7 upgraden und dort 
Fabriken bauen
-frühzeitig Kontakte zu den anderen Mitgliedern und den 
Rebellen aufnehmen
-Abkommen über gegenseitige Hilfen abschließen.

Taktiktips
----------
-Der Spielleiter teilt in der 2.Spielrunde den Mitgliedern 
der "Neuen Republik" die Heimatwelten der anderen Mitglieder 
mit. Es hängt von jedem Spieler einzeln ab, ob er den anderen 
auch die eroberten Planeten mitteilt.
-Die Heimatplaneten können über diverse Schiffwerften verfügen. 
Man könnte daher Abkommen über gegenseitige Nutzung 
dieser abschließen, z.B.: Baut Mitglied "A" dann Raumschiffe 
auf dem Planeten von Mitglied "B".
-Kommt ein Ligamitglied den Abmachungen nicht nach, liegt es an 
den anderen ihn aus den "Neuen Republik" auszuschließen. Er 
entwickelt sich dann zum normalen Eroberer.
-2 Mitglieder unterschiedlichen Geschlechts können auch eine 
mehr oder weniger politische Heirat arangieren. Dies hat zur 
Folge, das beide Sternenreiche fast zu einem großen 
zusammenschmelzen. 
-Wengier Handelssteuern sind oftmals mehr! Ruhig auchmal 
Werbung bei den Händlern für seine Planeten machen. 

mögliche Veränderungen
----------------------
-zum Eroberer:Geld siegt über Menschlichkeit. Die eroberten 
Planeten werden nun unterjocht und ausgebeutet.
-zum Imperator: Das Ligamitglied läßt sich vom Imperium 
bestechen und verrät die anderen Republik-Welten.
-zum Rebellen: Verliert der Spieler alle ES7-Planeten, kann er 
z.B. in den Untergund gehen und wie ein Rebell seinen Kampf 
gegen das Imperium weiterführen.
-zum Händler: Wenn man alle Planeten verloren hat, kann man 
mit Transportern und Kriegsschiffen sich anderswo ansiedeln 
und sich fortan als Händler sein Geld verdienen.


Sternengarde
============
Eine mögliche Einrichtung der "Neuen Republik". Um sich noch 
besser vor Feinden zu schützen wurde die Sternengarde ins 
Leben gerufen. Alle Planeten der "Neuen Republik" bezahlen eine 
Art Steuer um diese Truppen zu finanzieren. Auch ist es 
denkbar, daß die Schiffe der Sternengarde von der 
"Neuen Republik"gestellt werden. Die Hauptaufgabe der 
Sternengarde ist der Schutz der "Neuen Republik" gegenüber 
Angreifern. So patroliert sie bei deren Planeten und hilft ggf. 
bei Angriffen. Ausgangssituation sind mehrere Jäger auf 
einem "Neuen Republik"-Planeten. Die Sternengarde kann von 
einem neuen Mitspieler übernommen werden oder nebenher von 
einem Mitglied gesteuert werden. Hauptsächlich wir die 
Sternengarde aber von einem ehemaligen Rebellen oder Söldner 
übernommen.
Einkommensberechnung: Steuer von "Neue Republik"-Planeten 
(liegt im Ermessen der Mitglieder), minus Kosten.

Anfangstips
-----------
-Raumschiffe über mehrere Planeten verteilen, so daß im 
Ernstfall überall schnell eingegriffen werden kann.

Taktiktips
----------
-wie auch das Syndikat verfügt die Sternengarde über viele 
gute Informanten. Also auch mal "Info" ausprobieren.

mögliche Veränderungen
-----------------------
-zum Eroberer: Man kann seine militärische Stärke ausnutzen, 
um selbst Planeten zu erobern.
-zum Syndikat: Da man viele Infoquellen hat, kann man auch ein 
Syndikat auchfmachen, wenn man anfängt Planeten zu erobern. 
-zum Rebellen: Bezahlt die "Neue Republik" nicht mehr genug 
oder kann sie nicht mehr genug bezahlen, ist die Sternengarde 
wieder aufsich gestellt. Man kann sich so zu einem Rebellen 
entwickeln.


Söldner
=======
Eine Spezialisierung eines ehemaligen Syndikats. Wenn die 
Raumschiffabriken und die galaktischen Kontakte 
verlorengegangen sind bleibt dem Spieler fast nichts anderes 
übrig, als sich fortan als Söldner durchzuschlagen. Es werden 
Eroberungs- oder Erforschungsmissionen für andere Spieler, 
vorzugsweise Eroberer und Imperatoren übernommen. Fängt ein 
ganz neuer Spieler als Söldner an, so startet er auf einem 
beliebigen Planeten mit diversen Schiffen und einem 
Anfangskapital von 50CR. Neue Raumschiffe muß er allerdings 
von Syndikaten oder anderen Quellen beziehen.

Anfangstips
-----------
-schnell Kontakte zu anderen Mitspielern aufnehmem und seine 
Dienste anbieten.
-ruhig auch mal selbstständig Planeten erobern, man kriegt 
zwar keine Einkommen für sie, kann aber sie an andere Spieler 
verkaufen
-Erpressung ist auch möglich

Taktiktips
----------
-Nie die Raumflotte auf einen Planeten konzentrieren!

mögliche Veränderungen
----------------------
-zum Eroberer: Hat man genug Schiffe kann man auch daran 
denken, selbst die Herrschaft über ein Sternenreich zu 
übernehmen. Es muß hierfür aber der Spielleiter kontaktiert werden.
-zum Rebell: Das Gewissen drückt und Du beschließt jetzt für 
das Gute zu kämpfen!
-zur Sternengarde: Der Söldner kriegt den Auftrag von der 
"Neuen Republik" die Sternengarde zu bilden.


Der Orden der Macht
===================
Vor tausenden von Jahren, als es die ersten Jedi-Ritter gab, 
entstand auch eine Sekte, die diese Jedis als Propheten 
verehrten. Die Jedis mochten diese Vergötterung nicht, da sie 
ganz im Widerspruch steht zu allem was mit Hilfe der Macht 
gelernt haben. Doch trotz vieler Versuche ihrerseits ließ sich 
die Sekte sich nicht von ihrem Glauben abbringen, im Gegenteil 
der Orden gewann schnell an Mitgliedern und politischer 
Macht. Einer ihrer Hautanliegen wurde die Konzentration auf 
die Propheten. Dabei beschrenkten sie sich nicht nur auf sich, 
sondern auf die ganze Bevölkerung. Mit militärischer Stärke 
wurden ganze Planeten bekehrt. Nach der Eroberung wird dann 
die moderne Technik zerstört, so daß alle ihre Planeten auf 
einer einheitlichen ES von 4 stehen, mit Außnahme der Heimat 
Alvo, hier war das spirituelle und militärische Zentrum der 
Sekte. Von einem Großteil der erbeuteten Vermögens wurde hier 
auch ein riesiger Tempel errichtet. 
Mit der Machtergreifung des Imperiums in der Galaxis wurden 
neben den Jedi-Rittern auch der "Orden der Macht" nahezu 
ausgelöscht und die Bauten auf dem Planeten Alvo zerstört. 
Heute erinnern nur noch Ruinen an diese Zeit. Doch einige 
wenige haben sich wieder als Ziel gesetzt, die Sekte wieder zu 
der Stärke zu führen, die sie früher mal inne gehabt hatte.
Anfänglich startet man mit einer Flotte von 10Jägern, einem 
Kampfschiff und 30CR auf dem Planeten Avlo.

Anfangstips
-----------
-Jäger auf mehrere Planeten verteilen
-starke Verteidigungsflotte für den Heimatplaneten aufbauen
-möglichst einen zweiten Planeten auf ES7 upgraden und dort 
Fabriken bauen

Taktiktips
----------
-Andere Planeten auf ES4 scrapen oder upgraden.
-Wenn man Gegner nicht vernichten will, kann man auch 
versuchen diese zu erpressen, z.B.:"Zahle 200CR oder ich 
erobere deine Planeten."
-Ist es abzusehen, daß man einen Planeten an einen anderen 
Spieler verlieren wird, hat man immer noch die Möglichkeit, ihn 
so weit wie möglich zu scrapen. Man verdient so noch etwas Geld 
und außerdem kriegt der andere dann weniger Einkommen.


Händler (benötigt Zusatzmoduel "Handel")
=======
Mit einer Flotte von Transportern startet man auf einem 
beliebigen Planeten (der Planet kann auch einem anderen 
Spieler gehören). Ziel ist es durch geschickten An-und 
Verkauf möglichst viel Geld zu verdienen.
Einkommensberechnung: Handelserlöse, minus Kosten.

Anfangstips
-----------
-gleich loslegen mit den Geschäften, aber vorher Infos über 
die Zielplaneten einholen
-Kontakte mit "Neuer Republik", Rebellen oder Syndikaten 
aufnehmen

Taktiktips
----------
-Später auch ruhig Kampfschiffe kaufen, sie dienen zur Eskorte 
der Transporter!

mögliche Veränderungen
----------------------
-zum Eroberer: Ist die Kampflotte groß genug, kann man auch 
anfangen Planeten zu erobern. Vorher ist es ratsam Kampfschiffe 
als Transporter einzusetzen. Diese können dann überraschend 
eine Raumschlacht anfangen.
-zumRebell: Neben den Geschäften kann man ja auch für das 
Gute kämpfen. (Siehe Han Solo!)
-zum Syndikat: Gute Kontakte haben auch die Händler. Warum 
also nicht die Geschäfte zum Syndikat ausbauen?






Spieldokumentation: Patrick Henz


Faces of Mars
*************
"Star Wars - your own Chapter" is a fan-produced game. 
The Faces of Mars do not want intend to infringe 
upon rights of any other copyright holder. All 
rights revert to the contributor upon publication.


@ENDNODE


