@DATABASE Preise.inc
@NODE Preise

Star Wars - Your own Chapter
****************************
Preisliste

Basisset (Masterbuch, Spieleranleitung, Sternkarte)      DM6.-

Zusatzmodule:

0) Spieleranleitung (2.Version)                          DM2.-
   Gründlich überarbeitet gibt es jetzt die neue
   Spieleranleitung. Enthält Tabellen, Anleitung,
   neue Befehle und das Zusatzmodul "Jedi Academy".

1) Die Mos Eisley Cantina auf Tatooine                   DM2.-
   (für Spielleiter)

2) Zusatzereignisse mit z.B.: Dagobah, Angriff der       DM2.-
   Ssi-ruuk, Die dunkle Macht, etc.
   (für Spielleiter)

3) Die Blobrennen auf Umgul                              DM2.-
   (für Spielleiter)

4) Raumschiffkatalog (3.Version)                         DM6.-
   viele neue Schiffe aus Filmen, Comics, Büchern
   auf knapp 40 Seiten gibt es 76 Raumschiffe und
   41 Abbildungen       
   (für alle)

5) Das Buch der Missionen: enthält insgesamt 9           DM4.-
   Missionen, dazu jede Menge Tips, Taktiken  
   zum Spielen und auch Verändern der Missionen. 
   Aufgelockert wird dies durch diverse Zeichnungen
   und Fotos.
   (für alle)

6) Handel: Endlich kann man wie Han Solo durch das       DM4.-
   All reisen. Dieses Modul enthält neben den
   vielen Tabellen und Übersichtstafeln auch noch
   einen Katalog der diversen Raumtransporter.
   (für alle)

7) Jedi-Academy
   Nun kann man im Spiel auch Jedi-Fähigkeiten          DM0.50.-
   erwerben.
   (für alle)

8)Die Amiga-Spielerdisk                                DM3.-
   Enthält die folgenden Spieleranleitungen:
   Allgemeine Befehle, Tabellen, Blobrennen,
   Mos Eisley-Cantina, Handel, Buch der Missionen.
   Zusammengefügt in einen Amigaguide.
   (für alle)

Bei Bestellung bitte DM4.- für Porto + Verpackung mitschicken.

Patrick Henz
Martinstr.15
52062 Aachen
Germany

@ENDNODE

