@DATABASE Katalog.inc
@NODE "Katalog"


Science Fiction-Themes 
by the
Faces of Mars


1) FOM210
-Battlestar Galactica
-Blade Runner
-The Faces of Mars
-Star Wars
-Terminator

2) FOM241
-Ghostbusters
-Odyssey
-Star Wars
-Terminator II

3) FOM273
-Star Trek
-The Black Hole
-Robocop
-Rambo

4) FOM299
-Airwolf
-Bat Man
-Future World
-Spacepatrol Orion

5) FOM349
-Dune (3 modules)

6) FOM361
-Airwolf II
-Alf (2 modules)
-Blade Runner
-Super Mario Bros.

7) FOM392
-A Journey to Mars
-Star Trek
-Star Wars



All disks are freeware.

@endnode

                

