@DATABASE Story2.inc
@NODE "Story2"

Boba Fett lebt!
***************

...Sein gepanzerter Leib rutschte an Lando vorbei und ohne
Zwischenhalt in das Maul des Sarlac...

Dunkelheit.

Der Gestank nahm ihm die Luft zum atmen, seine Augen brauchten
lange um sich an das difuse Licht zu gewöhnen. Benommen schüttelte
Boba Fett den Kopf, er richtete sich halb auf, Schleim bedeckte
seinen Körper, der Untergrund war weich und nachgebend. Gedanken
jagten durch sein Hirn:
-dieser verfluchter Jedi
-tausend Jahre allmählich verdaut werden
-Hans Kopgeld hab ich noch nicht ausgegeben

Eine Regung versetzte seine Sinne in Alarmzustand. Hatte sich der
Boden bewegt? Sinnestäuschung?

Boba Fett wartete angespannt, da war es wieder, ein kaum merkliches
Erzittern des Bodens, der Höhle. Der Sarlac bewegte sich. Ein
gigantischer Muskel, der irgendwo im Erdinneren endete.

Er entfernte sich von der Öffnung, das Grau wurde zu Schwarz.

"Er schluckt mich runter!"

Panik stieg in ihm auf, plötzlich wurde ihm klar, daß der Sarlac 
ihn bereits verdaute, mit dem Schleim.

"Ich will hier raus!"

Der Kopfgeldjäger begann auf allen vieren dem Maul entgegen zu
kriechen. Das Beben des Muskels wurde stärker, schneller. Boba
Fett rutschte ab und nahm ein Schleimbad, dort wo die Substanz 
seine Kleidung durchtränkt hatte, begann die Haut zu jucken, er 
wollte sich kratzen. "Dieser verfluchte Skywalker!", er sprach
den Satz laut aus, seine Panik war weg, seine Lage schrie nach
Rache.

"Rache an Skywalker, nein an der ganzen verdammte Allianz!"

Boba Fett ignorierte das Brennen auf seiner Haut, den Schleim, 
der von der Decke tropfte, den Sarlac, der sein Opfer behalten
wollte.

Grauer Lichtschimmer, Sand unter seinen Händen, Boba war am Maul
angekommen. Er zog sein Kampfmesser und jagte es tief in den
nachgiebigen Boden. Der Sarlac brüllte auf. Mit einer Hand hielt
er sich fest, um nicht wieder zurück zurutschen. Mit seiner freien
Hand nahm er seinen Raketenantrieb ab und tränkte den Schleim mit
dem Treibstoff. Zitternd suchte er mit seiner brennenden und auf
doppelte Größe geschwollenden Hand nach seinem Feuerzeug, über
und über mit Schleim bedeckt hielt er sich krampfhaft am Messer
fest, das die ständige Bewegung des Sarlac bereits gelockert
hatte. Seine tauben Finger umschlossen das Feuerzeug. Mit einer
Stichflamme entzündete sich der Schleim, der Rauch war ätzend und
brannte in der Lunge. Der Sarlac bäumte sich auf.

Boba Fett wurde ausgespuckt.

Der Aufprall war hart und schmerzhaft, er verlor das Bewußtsein.

Als Boba Fett zu sich kam standen die zwei Sonnen von Tatooine
drei handbreit im Westen über dem Horizont und tauchten die Wüste
in rotes, schnell schwindendes Licht.

Der Kopfgeldjäger stand auf, der Schleim war zu einer harten
Kruste getrocknet, das Brennen und Jucken hatte aufgehört. Um ihn
herum lagen verstreut die Reste von Jabbas Segelbarke und dem
Begleitsegler. Der Hinrichtungstag der Gefangenen war zu Jabbas
Todestag geworden.

"Kein Verlust!", sagte Boba zu sich selbst, während er einem Toten
seinen Umhang abnahm. "Mein Glückstag!", dachte Boba als er einen
noch funktionierenden Blaster fand. Im letzten schwindendem Licht 
sah er in der Nähe etwas blitzen. Eine Flasche Fussel, die 
Explosion hatte sie weggeschleudert, Der Schnaps brannte auf seinen
wunden Lippen und in seinem Hals, doch wenig später spürte er die
wohltuende Wärme, die sich in seinem Körper ausbreitete. Boba Fett
warf noch einen letzen Blick auf die Überbleibsel eines
gefürchteten Schurken und ging in die Wüste davon. Sein Ziel war
Anchorhead oder Mos Eisley, doch das Wichtigste war überleben. Nur
Überleben!

Die nächtliche Kälte weckte ihn auf, seit Tagen ging er nachts 
immer nach Osten, die Flasche Fussel war halb leer. Boba Fett
hatte gelernt Gekkos und Sandschlangen zu fangen und zu essen.
Während er einen Fuß vor den anderen setzte und Düne um Düne 
hinter sich ließ, waren seine Gedanken mit seiner Rache 
beschäftigt. Rache an Skywalker, Solo und der kleinen Prinzessin,
er stellte sich tausend Möglichkeiten vor, ihre Leben zu zerstören,
töten wäre zu einfach, leiden sollen sie!

Boba Fett lächelte unter seiner Panzermaske, ja, vielleicht würde
er sie dem Sarlac zum Fraß vorwerfen! Als der Morgen graute brach
er erschöpft zusammen, wickelte sich in den Mantel, grub sich in 
den Sand ein und verschmolz mit der Wüste. Vibrationen weckten ihn,
Boba Fett fuhr auf, glaubte sich doch wieder in dem Sarlac 
gefangen. Das grelle Lichte blendete seine Augen, als er wieder
klar sehen konnte, erkannte er unförmige Tiere mit rieseigen 
Hörnern, die von Reitern gelenkt wurden. Die Karawane bewegte
sich genau auf ihn zu. Banthas und Sandleute.

"Was machten die Tusken so weit in der Wüste?"

Egal, ihm bot sich eine einmalige Gelegenheit der Wüste zu 
entkommen, er würde sie nutzen. Entschlossen griff er nach dem
Blaster und grub sich wieder ein.

Langsam bewegte sich der Troß in seine Richtung, der Boden erbebte,
Sand rieselte auf den versteckten Kopfgeldjäger. Als die Tusken an
ihm vorbei waren, sprang Boba Fett auf und eröffnete das Feuer. Die
überraschten Sandleute konnten nicht reagieren, als der tödliche
Strahl sie traf.

Die Banthas waren stehengeblieben, Boba fand Wasser und 
Trockenfleisch, gierig stürzte er sich auf das Essen und schlang
große Bissen ungekaut hinunter. Dann bestieg er einen Bantha und
gab ihm die Zügel frei.

Das Tier kannte den Weg zum Wasser, zur Zivilisation. Boba Fett
war dem Wüstentod entkommen. Ein Lachen stieg tief aus ihm auf,
erst leise, dann lauthals lachte Boba Fett in den blauen Himmel.

Der Bantha schüttelte nur seine großen Ohren während er langsam
aber zielsicher der Jundlandwüste entgegen trabte.

                 
                   Copyright by Beate Richter   


  
  "The Boba Fett-Experience" is a fan-produced programm.  
  We do not want intend to infringe upon rights
  of any other copyright holder. All rights revert to the
  contributor upon publication.

@ENDNODE

